### ISSUE TITLE
Deleting a TestMethod throws and error until Text Explorer refreshes tests

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#661] opened 2023-10-27 19:29 UTC
Type: <b>Bug</b>

1. Add a test method
2. click 'Run tests' in the Testing pane
3. Delete the test method
4. click 'Run tests' in the Testing pane
5. test output shows "Method {MyProject.TestClass.TestMethod} does not exist".

Expected:
- don't error for tests that no longer exist
- remove deleted tests from Test pane

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.41GB free)|
|Process Argv|--crash-reporter-id 24452be9-7e87-49ef-aeb5-c1b3aefe6bde|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
24365598:30736109
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
copilotsettingc:30859502
synctok:30869157
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30871694
pythonregdiag2:30871582
pyreplss1:30865275
pythoncet0:30874138
h48ei257:30870396
pythontbext0:30864172

```

</details>

**Comment by burtonrodman** [comment] 2023-10-27 19:39
I often have to rebuild the project and/or restart VSCode multiple times before the list of tests refreshes in the Testing pane.

**Comment by AbhitejJohn** [comment] 2023-10-31 22:02
This is similar to #131 in that Source based discovery can help with scenarios like these. @peterwald , do we perform a build and hence a rediscovery before running tests in VSCode? That would ideally clear removed tests.

**Comment by peterwald** [comment] 2023-11-02 19:13
> This is similar to #131 in that Source based discovery can help with scenarios like these. @peterwald , do we perform a build and hence a rediscovery before running tests in VSCode? That would ideally clear removed tests.

We do perform a rebuild when run tests is activated. I cannot reproduce this with an xUnit test project. The tests do seem to be accurately updated.

**Comment by burtonrodman** [comment] 2023-11-02 19:44
I am using MSTest

**Comment by peterwald** [comment] 2023-11-02 19:56
Ah, thanks for the clarification. Strangely, I am seeing similar results in MSTest... Investigating.

**Comment by peterwald** [comment] 2023-11-03 17:03
It turns out that when running all tests, we don't get a list of projects to build and the logic that checks to see if the build made any changes is failing as a result. A fix is forthcoming.

**Comment by peterwald** [comment] 2023-11-04 22:42
Fixed in the next release

**Closed by peterwald** 2023-11-04 22:42 UTC
Labels: bug, area-test, fixed (release pending)

**Comment by burtonrodman** [comment] 2023-11-04 22:44
you rock!  I was starting to doubt vscode's test experience.  hope yall add MSTest to your testing matrix.  i _actually_ prefer xunit, but my day job has standardized on MSTest ;(

**Comment by peterwald** [comment] 2023-11-04 22:46
Thanks. I have no idea why I couldn't reproduce this with xUnit. After seeing what the fix was, it seems like it should have happened on all test frameworks.
