### ISSUE TITLE
[BUG] "Debug project associated with this file" results in "*.csproj does not support debugging. No launchable target found." while "Run & Debug" works like expected 

### ISSUE THREAD

**Issue by regetskcob** [microsoft/vscode-dotnettools#701] opened 2023-11-09 11:16 UTC
### Describe the Issue

I just created a freshly new MAUI .Net project on my mac, using Visual Studio for Mac which has been completly installed a few minutes before. Since Studio told me, that I'll have to ma a transistion to VSCode in 2024, I directly tried it out.

It seems like "Debug project associated with this file" (Button near the top right corner when a .cs file is opened) is working not as expected, while the "Run & Debug" section what I expected (running the app on the selected destination). The error I get using the "Debug project associated with this file"-Button is:

`'.../Projects/FirstSteps/FirstSteps/FirstSteps.csproj' does not support debugging. No launchable target found.`

I made a screen record of the issue and uploaded it to https://1drv.ms/v/s!AnJkH8YinVaQgeRM_g1758cZTSMc_g?e=XS2BFX
Additionally I have to tell, that Fn + F5 is working as well.

Hopefully someone can tell me, what to configure, so both buttons do the same (run & debug) :)

### Environment Information

- macOS 14.2 on an M1 MacBook Pro
- VS Code v1.84.1
- -> C# Dev Kit v1.0.14
- -> .Net MAUI v0.5.50

**Comment by WardenGnaw** [comment] 2023-11-09 16:41
This seems to be a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/653.

Feel free to re-open with comments if it is a different issue.

**Closed by WardenGnaw** 2023-11-09 16:41 UTC
Labels: bug, area-debugging, area-maui
