### ISSUE TITLE
[SUGGESTION] <C# dev kit specify SDK Version>

### ISSUE THREAD

**Issue by Edemilorhea** [microsoft/vscode-dotnettools#397] opened 2023-08-15 16:14 UTC
### Describe the feature you'd like

I develop two project of .Net 7 and .Net 8 preview at same time, But If I install .Net 8 preview then dev kit will use .Net 8 SDK on .Net 7 project.

I tried many time, isn't can nomally to develop .Net 7 project until to uninstall .Net 8 preview SDK then it working. 

So I think this problem isn't hard to provide, I glad to see this feature. 

Thanks a lot

**Comment by timheuer** [comment] 2023-08-16 21:27
@Edemilorhea It's unclear if you are indicating you are hitting issues like #318 here where the presence of .NET 8 Preview 7 may be causing an issue.  If that is the case, please take the latest pre-release version (> 0.4.5) of the C# Dev Kit which enables a fix for this via setting for now.

Otherwise, if you could expand on your issue of what is failing when you use .NET 8 SDK to build your NET7 app that would be great, it should not be blocking you unless you have some other configuration as Tom mentions like a `global.json` file specifying a required SDK.

**Comment by Edemilorhea** [comment] 2023-08-17 03:02
@timheuer @tmeschter Thank you guys, when I Use pre-release version of the C# Dev Kit and setting global.json, it is working, really thank you.

**Comment by timheuer** [comment] 2023-08-17 04:09
Okay, thank you @Edemilorhea I'll close this as a dupe of #318 for now.

**Closed by timheuer** 2023-08-17 04:09 UTC
Labels: enhancement, area-project, needs-more-info
