### ISSUE TITLE
[BUG] Error when starting debug: "Could not find the task 'maui: Build'."

### ISSUE THREAD

**Issue by MeestorX** [microsoft/vscode-dotnettools#885] opened 2024-01-25 19:54 UTC
### Describe the Issue

Was working fine until I updated to the latest .NET and maui workloads. Currently version 8.0.300-preview.24074
When clicking the debug (Play) icon, I receive a popup with the message "Could not find the task 'maui: Build'."

### Steps To Reproduce

Update .NET to 8.0.300-preview.24074
Try to debug a Maui app using the Maui Extension.

### Expected Behavior

Starts debugging as usual.

### Environment Information

macOS Sonoma
VSCode 1.85.2 (Universal)

**Comment by Cfun1** [comment] 2024-02-20 20:25
I have the same issue, plus there no menu in the status bar to select the platform (debug target).

**Comment by mauroa** [comment] 2024-03-19 18:03
Hi @MeestorX  and @Cfun1.
Could you please share the content of the .NET MAUI output pane? The debug target must be selected from the language status item at the bottom right of VS Code (you can find it clicking the '{}' icon), together with the startup project.
You can also try updating to latest VS Code MAUI pre-release version in order to see if it makes any difference.
Thanks

**Comment by mauroa** [comment] 2024-04-12 15:52
I'm closing this issue since we haven't received the requested information to the users. Please feel free to reopen it in case you still reproduce the issue and have the requested information.
Thanks for your feedback and help.

**Closed by mauroa** 2024-04-12 15:52 UTC
Labels: bug, needs-more-info, area-debugging, triaged, area-maui

**Comment by IoMarius** [comment] 2025-02-02 11:06
I do have the same issue on windows 11.
I am trying to run a maui blazor hybrid app.

here is my launch.json config:
`{
            "name": "consumer-mobileapp-samsungid",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build",
            "configuration": "Debug",
            "project": "${workspaceFolder}/src/PersonalCabinet.Consumer.MobileApp/PersonalCabinet.Consumer.MobileApp.csproj",
            "targetFramework": "net9.0-android",
            "device": "R38M20E9VNZ"
        },`
