### ISSUE TITLE
[BUG] Solution explorer failed to load with the error message as in the screenshot

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/vscode-dotnettools#409] opened 2023-08-18 13:56 UTC
### Describe the Issue

Created a .NET MAUI project from the default template (`dotnet new maui`) and then opened the folder VS Code with the .NET MAUI extension installed.

VS Code failed to load the solution explorer and was blocked from proceeding further.

_Note: Installed both .NET 7 and .NET 8 preview in my system._

<img width="960" alt="dotnetmaui-vs-code-soln-load-error" src="https://github.com/microsoft/vscode-dotnettools/assets/81947404/a1b0f72b-2138-49a2-a0e8-c12675d3a94b">

### Steps To Reproduce

1. Create a new .NET MAUI project `dotnet new maui`
2. Open the folder in VS Code with the .NET MAUI extension
3. Wait for the Solution Explorer to load
4. Fails to load  the solution

### Expected Behavior

Solution Explorer should load the project and allow to build and debug the .NET MAUI app.

### Environment Information

- OS (Windows 11 v10.0.22621.2134
- VS Code v1.81.1
- .NET MAUI Extension - v0.2.13

**Comment by egvijayanand** [comment] 2023-08-18 13:57
Let me know if any further info is needed.

**Comment by smitpatel** [comment] 2023-08-18 17:12
Duplicate of #318

**Closed by smitpatel** 2023-08-18 17:12 UTC
Labels: bug, area-solution
