### ISSUE TITLE
[BUG] Solution Explorer not opening after moving to the right side

### ISSUE THREAD

**Issue by karl-gardner** [microsoft/vscode-dotnettools#860] opened 2024-01-16 14:21 UTC
### Describe the Issue

Once the solution explorer is moved to the right side of the screen and vs code is closed it will not show up anywhere and I can't find where to open it again. Let me know if you are not able to recreate this. I have recreated it multiple times now.

### Steps To Reproduce

1. Download vscode and C# Dev Kit extension
2. Open existing C# projects/solution or create a new project with "dotnet new console" command.
3. Close vscode
4. Open folder containing c# project with vscode and notice the solution explorer pop up on the bottom left side (might need to sign in to microsoft to use c# dev kit):

![image](https://github.com/microsoft/vscode-dotnettools/assets/91646805/19bebcb2-24d5-48fe-8cde-cb1f9177e44d)

5. Drag the solution explorer over to the right side to be able to see it better instead of the bottom left side (outlined in red):

![image](https://github.com/microsoft/vscode-dotnettools/assets/91646805/db66b355-3505-42bb-9cb1-e1dc46abc7b0)

6. Close vscode. Open same folder or any other folder containing c# project (csproj files). Now solution explorer is missing:

![image](https://github.com/microsoft/vscode-dotnettools/assets/91646805/728873b7-c7c1-4a5b-a348-961779e40a25)

### Expected Behavior

The solution explorer is supposed to show up in vs code when opening a c# project containing a csproj file. Preferably it will show up in the same location that it was left at like on the right side of the screen.

### Environment Information

VS Code version:
Newest version available
C# Extension version:
Newest Version available

**Comment by timheuer** [comment] 2024-02-16 04:05
Closing as dupe of #864

**Closed by timheuer** 2024-02-16 04:05 UTC
Labels: bug, area-solution
