### ISSUE TITLE
[BUG] C# Dev Kit does not update files in ...User/Local/Temp/Metadataassource

### ISSUE THREAD

**Issue by IngmarPaetzold** [microsoft/vscode-dotnettools#683] opened 2023-11-03 16:38 UTC
### Describe the Issue

Installed Dev Kit today.

Example situation: in my code, there is an error with the type of a method call, for instance:
```
// a class method is defined as:
... Method( List<string> list ) { ...


// The app calls it with an int list:

List<int> mylist = new();
...
class.Method( mylist )         // <-- red squiggly because method takes List<string>
```

When I then change the method signature in the class to `... Method( List<int> list ) { ...`, the analyzer still shows the error, although method and call are OK now.
When I right click on the called method and "go to definition F3", not the original code is opened, but some "compiler generated" file in the said temp directory.

Turns out, that this file is still the old version.

`dotnet build` does not help. There is no compiler error any more, but the problem persists in VS Code's "PROBLEMS" view.
(Edit:) `dotnet clean` before does not help either.

The only thing that helps:

- Disable Dev Kit
- Restart VS Code
- Enable Dev Kit 

Very annoying.

1. Is there another way to update the files in the Temp directory?
2. Why is the cached and "compiler generated" file opened upon F3, and not the original file? That's what I really expect to see, and maybe want to continue working on.

### Steps To Reproduce

see above

### Expected Behavior

The code problem should be solved, no red squiggly any more.
The analyzer should recognize that the original used file has changed and update its cache accordingly.
Edit: I'd like to open my code file upon F3, not the cached one.

### Environment Information

Windows 10
VS Code 1.84.0
Dev Kit 1.0.14
C#

**Comment by dibarbet** [comment] 2023-11-09 20:10
@IngmarPaetzold - the class that defines `Method` - is that in a different project from where you're calling it?  If so, does the project that contains the definition a part of your solution file?

Can you share a screenshot of what the solution explorer shows for the class with the definition and the class where you're using it?

Thanks!

**Comment by IngmarPaetzold** [comment] 2023-11-23 18:19
Hi David,
yes, the file is in a shared sibling project. Nevertheless, it is referenced in the project's *.csproj as:
```
  <ItemGroup>
...
    <ProjectReference Include="..\..\Shared\Tools\Tools.csproj" />
  </ItemGroup>
```

Thus, it is not a problem for the _compiler_ to find it, and I was assuming that the analyzer would do so as well.

It was not yet in the Solution, therefore, a screenshot would not show it.

Now, I have manually added it to the solution
`dotnet sln add ..\Shared\Tools\Tools.csproj`
and it seems to work for now. So thanks for the hint with the solution.

Still, I am the opinion that the analyzer should not reference/display the file in the Temp directory (which it obviously _does_ find!), since that is confusing. I do not work with the Temp directory, actually do not want that anything copies files to there, and do not want that F3 jumps to there. I think that the project contains my code, and that is the (only!) source the tools should use.

**Comment by dibarbet** [comment] 2023-11-28 22:27
> It was not yet in the Solution, therefore, a screenshot would not show it.
> 
> Now, I have manually added it to the solution `dotnet sln add ..\Shared\Tools\Tools.csproj` and it seems to work for now. So thanks for the hint with the solution.

Yeah - currently the project will need to be in the solution for Roslyn to find the source for it - otherwise it will just show up as a metadata reference.

The project system or CPS would have to support loading project references outside of the solution and pass that information on to Roslyn for the scenario to work otherwise.  Moving over to the CPS side to decide if they want to support that feature.

**Comment by dibarbet** [comment] 2023-11-28 22:32
Looks we have multiple issues on this - closing this one as a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/474

**Closed by dibarbet** 2023-11-28 22:32 UTC
Labels: bug, area-project

**Comment by IngmarPaetzold** [comment] 2023-11-29 08:53
Thanks David for caring. Works for me so far, so I can enjoy DevKit's goodies ;-)
