### ISSUE TITLE
BUG: C# Dev Kit Extension (suddenly) requires work or school account

### ISSUE THREAD

**Issue by jrdodds** [microsoft/vscode-dotnettools#942] opened 2024-02-22 13:20 UTC
Type: <b>Bug</b>

Starting today (2/22/2024), VSCode began showing "Sign in Microsoft to use C# Dev Kit" although I already have a signed in Microsoft account.

![Screenshot 2024-02-22 082317](https://github.com/microsoft/vscode-dotnettools/assets/1728516/b154470e-533f-4300-8bfc-71755a91ad6f)

When I try to resolve the sign in issue, the sign in web page shows an error: "You can't sign in here with a personal account. Use your work or school account instead."

![Screenshot 2024-02-22 083253](https://github.com/microsoft/vscode-dotnettools/assets/1728516/1aca8a72-0428-4a5e-a8d7-69af540e579f)

The C# Dev Kit license allows for use by individuals. This is a serious defect for the license terms.

Extension version: 1.3.10
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700 (20 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (45.91GB free)|
|Process Argv|--crash-reporter-id 74de4b21-5429-47d6-9cca-78f54d6e104c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30968132
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
pydisww1:30959800
edj9j583:30969295
fegfb526:30961430
7j2b6412:30969109
bg6jg535:30958357
ccp2r3:30958157

```

</details>

I reproduced the issue on macOS 14

**Comment by Meryovi** [comment] 2024-02-22 16:13
I'm having the same issue in MacOS Sonoma 14.2.1 and Windows 11. Same extension and VS Code versions as OP.

**Comment by glen-84** [comment] 2024-02-22 17:39
I'm not sure if this is related:

> IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 401 and response ""'

**Comment by foontzoot** [comment] 2024-02-22 21:19
I have the same issue on Ubuntu 22.04.4 LTS
VS Code details:
```
Version: 1.86.2
Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
Date: 2024-02-13T19:41:37.860Z
Electron: 27.2.3
ElectronBuildId: 26908389
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-17-generic snap
```

**Comment by d-3-n** [comment] 2024-02-22 21:37
> I have the same issue on Ubuntu 22.04.4 LTS VS Code details:
> 
> ```
> Version: 1.86.2
> Commit: 903b1e9d8990623e3d7da1df3d33db3e42d80eda
> Date: 2024-02-13T19:41:37.860Z
> Electron: 27.2.3
> ElectronBuildId: 26908389
> Chromium: 118.0.5993.159
> Node.js: 18.17.1
> V8: 11.8.172.18-electron.0
> OS: Linux x64 6.5.0-17-generic snap
> ```
VS Code and extensions have always been a buggy mess. Usual 'fixes' one reloads the window, restarts an extension etc. In this case sign out of your outlook account, then sign in again. If that doesn't work reinstall the extension.

**Comment by HiMarioLopez** [comment] 2024-02-22 22:31
Same issue on Windows 11.

![image](https://github.com/microsoft/vscode-dotnettools/assets/23390842/d3a01a4b-ec75-435c-9ffc-4affa2b9ae48)

`IdeBenefitsSource: Failed to fetch entitlements. Error: 'Error: Request to https://api.subscriptions.visualstudio.microsoft.com/Me/Entitlements/IDEBenefits?api-version=2023-03-26&caller=vscode failed with status code: 401 and response ""'`

Device Specifications:

Device name	WindowsDesktop
Processor	AMD Ryzen 7 7800X3D 8-Core Processor              4.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	E1B04AB9-6EFD-4969-98AE-8351B2578077
Product ID	00330-80000-00000-AA081
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

VSCode Info:

Version: 1.87.0-insider (user setup)
Commit: a0b90ac5e04ea9a0733b68062253a469994e170e
Date: 2024-02-22T05:48:26.543Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.26058

**Comment by jrdodds** [comment] 2024-02-22 23:01
Per @d-3-n I tried the following:

### Sign out and sign back in

1. Sign out of the Microsoft account (which is used for Sync Setting and C# Dev Kit)
2. Sign in to Sync Settings - sign in is successful
3. Sign in to C# Dev Kit - sign in **fails**

The order matters:

1. Sign out of the Microsoft account (which is used for Sync Setting and C# Dev Kit)
2. Sign in to C# Dev Kit **first** - sign in is successful
3. Sign in to Sync Settings - sign in is successful

Problem is resolved for the session but restart VSCode and the C# Dev Kit needs a sign in again.

Tested and had the same results on Windows and macOS.

### Reinstall the Extension

1. Sign out of the Microsoft account (which is used for Sync Setting and C# Dev Kit)
2. Uninstall the ".NET MAUI" extension (which requires the C# Dev Kit)
3. Uninstall the "C# Dev Kit" extension
4. Close and restart VSCode
5. Install the ".NET MAUI" extension
6. Sign in to C# Dev Kit - sign in is successful
7. Sign in to Sync Settings - sign in is successful
8. Close and restart VSCode
9. C# Dev Kit needs a sign in again

Tested and had the same results on Windows and macOS.

**Comment by midkir** [comment] 2024-02-23 08:00
I'm having the same issue on WSL on Windows 10. 
Though it doesn't reproduce for another local (non-WSL) project on the same Windows 10 machine.
My user profile is the same for both environments.
![image](https://github.com/microsoft/vscode-dotnettools/assets/29122304/87a7ce4f-cc29-47a0-8a42-69ec6dc3eb81)

**Comment by jrdodds** [comment] 2024-02-23 15:50
I tested using "Install Another Version..." and "Switch to Pre-Release Version" (v1.4.6 (pre-release)) to downgrade and upgrade the extension to different versions (v1.2.7 and v1.4.6 (pre-release), respectively) to see if the behavior changed. It didn't.

**Comment by timheuer** [comment] 2024-02-23 16:33
Closing as a dupe of #697 which is where we are tracking -- see last comment https://github.com/microsoft/vscode-dotnettools/issues/697#issuecomment-1960343360 FYI @AndreyTretyak

**Closed by timheuer** 2024-02-23 16:33 UTC
Labels: bug, area-identity
