### ISSUE TITLE
[BUG] VSCode cannot import namespaces

### ISSUE THREAD

**Issue by taiphanvan2k3** [microsoft/vscode-dotnettools#1272] opened 2024-07-10 02:48 UTC
### Describe the Issue

- I cannot use "Ctrl ." to import a namespace
- Namespaces that I imported ago do not appear dark blue but are faint
![image](https://github.com/microsoft/vscode-dotnettools/assets/108993284/01f422f7-77c2-452a-9ada-1ee318bcb2a2)
+ .Common, .Common.Schemas are faint

### Steps To Reproduce

- Turn off VSCode
- Then turn it on again
- Open a file C#, then I see the above bug:
   + Cannot go to reference and import namespace 
   + Cannot use **Ctrl .** to import namespace

### Environment Information

- OS: Windows 11
- Installed extensions: C# Dev Kit, C#

**Comment by dibarbet** [comment] 2024-07-10 23:42
Likely duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1269

**Closed by dibarbet** 2024-07-10 23:42 UTC
Labels: bug, area-roslyn
