### ISSUE TITLE
[BUG] Project system ran into an unexpected problem, please report it to the product team

### ISSUE THREAD

**Issue by mwkcoding** [microsoft/vscode-dotnettools#1520] opened 2024-10-10 07:23 UTC
### Describe the Issue

Possibly related to #1470. Still getting the notification but now the log from C# extension is different

Log file:
[ProjectSystemServerFault_4ec43309-fbb1-4a70-841e-8b7b2f3e18d2.failure.txt](https://github.com/user-attachments/files/17323845/ProjectSystemServerFault_4ec43309-fbb1-4a70-841e-8b7b2f3e18d2.failure.txt)

C# Extension output:
```
Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
waiting for named pipe information from server...
[stdout] {"pipeName":"\\\\.\\pipe\\dc0f7466"}
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 9:08:37 AM] [Program] Language server initialized
[Info  - 9:08:42 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.Utilities\NAMESPACE.Webjobs.Utilities.csproj loaded by C# Dev Kit
[Info  - 9:08:42 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:42 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.ScriptRunner\NAMESPACE.Webjobs.ScriptRunner.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\TestClient.Core\TestClient.Core.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Std.Domain\NAMESPACE.Domain.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.REDACTED\NAMESPACE.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.API\NAMESPACE.Functions.API.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.REDACTED\NAMESPACE.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.V3.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Std.Security\NAMESPACE.Security.csproj loaded by C# Dev Kit
[Info  - 9:08:43 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Std.Data\NAMESPACE.Data.csproj loaded by C# Dev Kit
[Info  - 9:08:45 AM] [RazorWorkspaceListener] No razor documents for (ProjectId, #5397c37b-6ac8-4107-88ea-d4d9346bb4d9 - NAMESPACE.REDACTED)
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.DevOps\NAMESPACE.Functions.DevOps.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\Tests\Tests.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.V3.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Std.Utilities\NAMESPACE.Utilities.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.V3.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Core.REDACTED\NAMESPACE.Core.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.V3.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Core.API\NAMESPACE.Core.API.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.V3.Utilities\NAMESPACE.Functions.Utilities.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Std.Content\NAMESPACE.Content.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Functions.REDACTED\NAMESPACE.Functions.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Webjobs.Core.REDACTED\NAMESPACE.Webjobs.REDACTED.csproj loaded by C# Dev Kit
[Info  - 9:09:18 AM] [WorkspaceProjectFactoryService] Project C:\Users\USERNAME\code\REPOSITORY\NAMESPACE.Core.REDACTED\NAMESPACE.Core.REDACTED.csproj loaded by C# Dev Kit
[Warn  - 9:09:18 AM] [LanguageServerHost] Text for virtualcsharp-razor:///c:/Users/USERNAME/code/REPOSITORY/NAMESPACE.Core.REDACTED/Pages/REDACTED/Login.cshtml__virtual.cs did not match document text (DocumentId, #0068351f-fc93-4e48-9d35-637b3ff2cc11 - virtualcsharp-razor:///c:/Users/USERNAME/code/REPOSITORY/NAMESPACE.Core.Apps/Pages/REDACTED/Login.cshtml__virtual.cs) in workspace's Host current solution
```

### Steps To Reproduce

Once again, I don't know. Just opened my solution and it happens.

### Expected Behavior

Just.. work? 😄 

### Environment Information

Version: 1.94.1 (system setup)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

C# Extension version: v2.50.25
C# Dev Kit Extension version: v1.11.14

**Comment by smitpatel** [comment] 2024-10-10 21:37
Duplicate of #636

**Closed** 2024-10-14 21:33 UTC
Labels: bug, area-project
