### ISSUE TITLE
Package manager in C# dev kit vs code

### ISSUE THREAD

**Issue by MarshalOfficial** [microsoft/vscode-dotnettools#297] opened 2023-07-29 10:41 UTC
### Describe the feature you'd like

It's an essential need to have a package manager in C# dev kit extension in vs code

### Environment Information

- VS Code version 1.80.2
- C# dev kit v0.2.100

**Comment by timheuer** [comment] 2023-07-31 15:49
Thanks @MarshalOfficial I'm closing this marking as a duplicate of #62

**Closed by timheuer** 2023-07-31 15:49 UTC
Labels: enhancement, area-solution
