### ISSUE TITLE
Predefined type 'System.Int32'

### ISSUE THREAD

**Issue by stasnocap** [microsoft/vscode-dotnettools#195] opened 2023-06-22 13:18 UTC
Type: <b>Bug</b>

I have 3 git repositories, 3 vscode workspaces, and 1 solution which contains others 2 repos. Seems, some class libs dont see usings 
Errors:
Predefined type 'System.Int32' is not defined or imported
Predefined type 'System.Void' is not defined or imported ... etc

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.80GB free)|
|Process Argv|C:\\Users\\КапитанС\\Desktop\\BudRev.code-workspace --crash-reporter-id c12828a2-41de-494d-88aa-bfeda1c6f723|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30773603
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30766890
pythongtdpath:30769146
bgfeh915:30769767
e440d664:30770001
pythonidxptcf:30772540
pythondjangots:30772535

```

</details>

**Comment by ProTip** [comment] 2023-06-22 20:10
Potential duplicate of #150

**Comment by arkalyanms** [comment] 2023-06-26 20:43
yes dup of https://github.com/microsoft/vscode-dotnettools/issues/150

**Closed by arkalyanms** 2023-06-26 20:43 UTC
Labels: area-roslyn
