### ISSUE TITLE
Unable to debug MAUI

### ISSUE THREAD

**Issue by williambuchanan2** [microsoft/vscode-dotnettools#921] opened 2024-02-15 01:04 UTC
Type: <b>Bug</b>

Just wonder if anyone is looking at these problems which have been reported for a while with VS Code on Mac. 

Unable to open solution unless it is in the same folder.
Reporting "Android SDK: Install required" despite having already done this.
Reporting ".NET MAUI SDK: Not found" despite it being installed.
Reporting "Failed to restore solution" as soon as VS Code loads

Basically, it just doesn't seem to work, and now VS For Mac is not working as well so literally no way to debug iOS now.

Extension version: 1.3.10
VS Code version: Code 1.86.1 (Universal) (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:09:01.236Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|19, 17, 8|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id b9566a76-2b0f-495e-a772-549d05ca4538|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
vscrp:30673768
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
b5d27386:30958190
a89i1917:30961429
3ef8e399:30964150

```

</details>

**Comment by williambuchanan2** [comment] 2024-02-15 01:06
![Screenshot 2024-02-15 at 11 59 51 am](https://github.com/microsoft/vscode-dotnettools/assets/32165641/0e5963e8-fe0a-4efd-bed5-df62771fd695)

![Screenshot 2024-02-15 at 12 06 01 pm](https://github.com/microsoft/vscode-dotnettools/assets/32165641/3bb50533-96b2-49e0-96fb-d4dcd1a94fcf)

![Screenshot 2024-02-15 at 12 06 24 pm](https://github.com/microsoft/vscode-dotnettools/assets/32165641/4819ca04-6a38-499e-8145-8dab2565ed59)

**Comment by lifengl** [comment] 2024-02-24 23:15
Make sure that you have installed latest SDKs from https://dotnet.microsoft.com/en-us/download, and you might need reboot your machine after that.  The VSCode extension is a developer tool, which doesn't carry or install SDKs for you. If SDK hasn't been installed on the machine, the extension would not work.

**Comment by lifengl** [comment] 2024-02-24 23:19
Make sure the SDK installed can be located by PATH environment. You can try to execute dotnet --info in a terminal window to check whether the SDK can be located.  Also, make sure to install the ARM version SDK for the M2 machine, the extension doesn't support the X64 target SDK.

if you still run into problem, can you provide the logging data from the extension, which may help to understand what might be wrong.

**Comment by williambuchanan2** [comment] 2024-02-26 00:10
The SDK is installed and I added it to the path - this fixed the issue with the errors popping up (strange how Android Studio just seemed to work without having to do this). 

However I still can't open the solution. I understand it should load when I do a File ->Open Folder? I have multiple solutions in the same folder but nothing happens when I open the folder.

**Comment by lifengl** [comment] 2024-03-06 21:17
can you open the solution manually? when there are multiple solutions, the extension doesn't choose one. It shows a notification when you open the workspace first time.  If you expand the solution explorer, it shows a button to open the solution as well.

**Comment by williambuchanan2** [comment] 2024-03-06 21:46
> can you open the solution manually? when there are multiple solutions, the extension doesn't choose one. It shows a notification when you open the workspace first time. If you expand the solution explorer, it shows a button to open the solution as well.

If I try and open the solution manually it just opens it as text.

I know that it 'should' show a notification when there are multiple solutions in the folder, but it most certainly doesn't. I have uploaded movies of this in the past but nothing seems to have happened to address this. See the 2 movie files I have uploaded here:

https://github.com/microsoft/vscode-dotnettools/issues/776

Both methods of opening the folder do nothing.

This is a new macbook - I had the same problem on my old macbook, and the same happens to everyone else in the team, so it's not an isolated problem.

**Comment by lifengl** [comment] 2024-03-12 06:41
I saw your earlier video.  The C# extension is only activated when there is at least one .csproj in the workspace. It would not work if you only have .sln file, but no .csproj file.  In the other video, if the workspace has a single .sln file with .csproj files. "Open solution" would open it, can you expand the solution explorer window to see whether anything there.  I saw the output window mentioned the .csproj inside the workspace.

**Comment by williambuchanan2** [comment] 2024-03-13 00:05
The folder setup is as follows:
\
  \_solutions
    - solution1.sln
    - solution2.sln
    - solution3.sln
  \projects
     \project1
       - project1.csproj
     \project2
       - project2.csproj
     \project3
       - project3.csproj
     
So the csproj files are not in the same folder as the solutions (which is a common situation).

**Comment by mauroa** [comment] 2024-03-19 18:38
Removing the "area-maui" project since the SDK related issues have been solved as per @lifengl suggestions, so the remaining issue looks C# DevKit/CPS related.

**Comment by williambuchanan2** [comment] 2024-03-22 03:32
Looks like I spoke too soon.

Once again I am getting the "Android SDK install required" error in VS Code. dotnet --info lists all the versions of the sdk and everything else, so it all appears to be there.

This issue of not being able to find various bits of dotnet seems to be a real problem for a few different applications. So far the only solution I have found is to leave it a few days and then it magically works for a day or 2.

**Comment by williambuchanan2** [comment] 2024-03-22 04:58
Figured out the Android SDK issue. It looks like the .NET Maui extension has a setting for the Android SDK and Java SDK. These are both blank. It turns out when they are blank the extension uses an old SDK which was part of Xamarin. This then causes the cascade of problems with SDK components not being found.

**Comment by williambuchanan2** [comment] 2024-03-22 05:11
Ok finally found out more information on the problems.

It looks like the extension needs the files and folders to be in a certain place. I copied my solution into the root of the repository and updated the paths to the projects, and that seems to now work when I open that folder (possibly related to it being the only sln file in that folder as well). Either way, it looks like there is some kind of bug related to opening solutions if the files and folders aren't in the location it expects.

I also had a lot of issue configuring the debug options - mainly how to select the right iOS simulator. The instructions said to click on the curly braces at the bottom of the screen, but this didn't work for me. What the instructions fail to mention is that you need to open the Maui csproj file first - then clicking the braces shows the debug options. It shouldn't be that hard, and it's really clunky. Also, this doesn't always work - in fact I can't get the debug options to show again. Clicking the braces just opens the menu now, but at least I have it working now.

I finally got it to run on an iPhone 14 simulator - it turns out there is a problem with this latest .NET version where it won't run on iPhone 15. Not sure how to work it out because I just get a binary dump with no useful information.

Feels like i'm working with a student project rather than the next Microsoft platform...

**Comment by Michael-Eng** [comment] 2024-04-29 06:02
Hi @williambuchanan2 - Thank you for the additional information.

When you open a folder, if there is a single sln file at that location, we will load the solution. If there are multiple solutions we will prompt you to choose the sln file to open. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/18017073/0fd7c099-3824-4401-a170-03078af9578d)

Once you open a solution, C# Dev Kit will show the contents of your solution in the solution explorer (not folder view). You can close the solution by right clicking the solution node in solution explorer and selecting Close Solution. At that point you can click the Open Solution button which will prompt you for a solution file.

**Comment by williambuchanan2** [comment] 2024-04-29 06:05
> When you open a folder, if there is a single sln file at that location, we will load the solution. If there are multiple solutions we will prompt you to choose the sln file to open.

That's the problem - that isn't happening! I am not being prompted to choose the sln. Nothing happens.

**Comment by Michael-Eng** [comment] 2024-04-29 06:14
What do you see in the solution explorer? Do you see the Open Solution button?

**Comment by williambuchanan2** [comment] 2024-04-29 06:29
> What do you see in the solution explorer? Do you see the Open Solution button?
> 

See attached. From what I can see it seems to have selected one of the solutions - however I can't run it. If I try to run it I get prompted to choose the debugger and when I do nothing happens.

However, first problem is that I don't have the ability to choose which solution to open...


![Screenshot 2024-04-29 at 4 27 17 PM](https://github.com/microsoft/vscode-dotnettools/assets/32165641/f0ce9087-4427-4b69-a05a-e900137a0153)

**Comment by williambuchanan2** [comment] 2024-04-29 06:45
Uh ok yes that works (although it's not exactly user friendly).

Same problem again with running it though. If I try to select .NET Maui as the debugger nothing happens:

![Screenshot 2024-04-29 at 4 43 54 PM](https://github.com/microsoft/vscode-dotnettools/assets/32165641/0aee26ac-a65d-4f03-990f-5f19ba57b4d1)

**Comment by Michael-Eng** [comment] 2024-04-29 06:47
Reactivating the issue, changing the title and moving to the MAUI area path.

**Comment by mauroa** [comment] 2024-04-29 16:11
@williambuchanan2 can you share the content of the .NET MAUI output pane? Also the C# DevKit output pane content.
What device do you have selected in the debug target list? (clicking on the '{}' at the bottom right when you open a .cs or .xaml file)
Thanks

**Comment by mauroa** [comment] 2024-04-30 21:37
@williambuchanan2 thanks for the confirmation. That's how language status items work by design in VS Code, however we are currently working on improving the overall debugging experience so it's more user friendly and easy to use. Thanks for your help and feedback.

**Closed by mauroa** 2024-04-30 21:37 UTC
Labels: bug, triaged, area-maui, high-priority

**Comment by williambuchanan2** [comment] 2024-04-30 22:55
Ok thanks for the update. I'm pretty negative in general with how this works because VS for Mac is being retired and VS code is being forced on us as it's replacement. From what I can see it's got a long way to go. It just looks like a bug ridden bunch of hacky workarounds to get something working, rather than a usable IDE. However, looks like I don't really have any choice at the moment than to use this...
