### ISSUE TITLE
[BUG] error MSB4057: The target "Target_Name" does not exist in the project.

### ISSUE THREAD

**Issue by AndresGMD** [microsoft/vscode-dotnettools#1200] opened 2024-06-14 12:14 UTC
### Describe the Issue

I am getting the following error in debugging when executing the task: (This happens with any project)

```PS
 *  Executing task: dotnet: build c:\Users\User\Project\Path\Solution.Folder\Project.Api\Project.Api.csproj 

dotnet build C:\Users\User\Project\Path\Solution.Folder\Solution.Folder.sln /target:Project_Api /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
  Determining projects to restore...
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Client\Project.Client.csproj (in 673 ms).
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Service\Project.Service.csproj (in 1.04 sec).
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Background\Project.Background.csproj (in 1.04 sec).
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Api\Project.Api.csproj (in 1.04 sec).
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Job.Unit.Tests\Project.Job.Unit.Tests.csproj (in 1.05 sec).
  Restored C:\Users\User\Project\Path\Solution.Folder\Project.Api.Unit.Tests\Project.Api.Unit.Tests.csproj (in 1.05 sec).
  1 of 7 projects are up-to-date for restore.
C:\Users\User\Project\Path\Solution.Folder\Project.Background\Project.Background.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Client\Project.Client.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Shared\Project.Shared.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Service\Project.Service.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Job.Unit.Tests\Project.Job.Unit.Tests.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Api.Unit.Tests\Project.Api.Unit.Tests.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
C:\Users\User\Project\Path\Solution.Folder\Project.Api\Project.Api.csproj : error MSB4057: The target "Project_Api" does not exist in the project.
```

### Steps To Reproduce

1. Run and Debug (Ctrl+Shift+D)

### Environment Information

- OS: Windows 11
- VS Code Version: 1.90.1 (user setup)
- Extension Version: 1.7.25

**Comment by WardenGnaw** [comment] 2024-06-14 18:09
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1195

**Closed by WardenGnaw** 2024-06-14 18:09 UTC
Labels: bug, area-project, area-dotnet-debugging, area-project-cps, area-restore
