### ISSUE TITLE
[SUGGESTION] Controller based API/Web Projects is missing. Support for creating Function Apps

### ISSUE THREAD

**Issue by amitdixit** [microsoft/vscode-dotnettools#207] opened 2023-06-29 06:37 UTC
### Describe the feature you'd like

Controller based API/Web Projects is missing. Support for creating Function Apps

**Comment by smitpatel** [comment] 2023-06-29 23:10
Duplicate of #115

**Closed by smitpatel** 2023-06-29 23:10 UTC
Labels: enhancement, area-project
