### ISSUE TITLE
Missing checkForDevCert setting

### ISSUE THREAD

**Issue by junalmeida** [microsoft/vscode-dotnettools#820] opened 2023-12-20 16:01 UTC
Type: <b>Bug</b>

## Issue Description ##
Missing `checkForDevCert` setting in `launch.json` when using `"type": "dotnet"`.

## Steps to Reproduce ##
Open launch.json
Add a ".NET: Launch C# Project"
Try set `"checkForDevCert": false`

## Expected Behavior ##
Accept `checkForDevCert` setting and do not check if false.

## Actual Behavior ##
Setting is ignored, vscode warns it is not available.

### C# log ###
<details>Post the output from Output-->C# here</details>

### C# LSP Trace Logs ###
<details>Post the output from Output-->C# LSP Trace Logs here.  Requires `dotnet.server.trace` to be set to `Trace`</details>

## Environment information ##

**VSCode version**: 1.85.1
**C# Extension**: 2.14.8
**Using OmniSharp**: false

<details><summary>Dotnet Information</summary>
.NET SDK:
 Version:   7.0.308
 Commit:    f6a2f50f2d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.308/

Host:
  Version:      7.0.11
  Architecture: x64
  Commit:       ecb34f85ec

.NET SDKs installed:
  3.1.426 [/usr/local/share/dotnet/sdk]
  6.0.405 [/usr/local/share/dotnet/sdk]
  6.0.406 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.410 [/usr/local/share/dotnet/sdk]
  6.0.412 [/usr/local/share/dotnet/sdk]
  6.0.414 [/usr/local/share/dotnet/sdk]
  7.0.102 [/usr/local/share/dotnet/sdk]
  7.0.103 [/usr/local/share/dotnet/sdk]
  7.0.200 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]
  7.0.304 [/usr/local/share/dotnet/sdk]
  7.0.306 [/usr/local/share/dotnet/sdk]
  7.0.308 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.22 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
</details>
<details><summary>Visual Studio Code Extensions</summary>

|Extension|Author|Version|Folder Name|
|---|---|---|---|
|atlascode|atlassian|3.0.9|atlassian.atlascode-3.0.9|
|azure-account|ms-vscode|0.11.6|ms-vscode.azure-account-0.11.6|
|bash-debug|rogalmic|0.3.9|rogalmic.bash-debug-0.3.9|
|csdevkit|ms-dotnettools|1.1.16|ms-dotnettools.csdevkit-1.1.16-darwin-x64|
|csharp|ms-dotnettools|2.14.8|ms-dotnettools.csharp-2.14.8-darwin-x64|
|durablefunctionsmonitor|DurableFunctionsMonitor|6.3.0|durablefunctionsmonitor.durablefunctionsmonitor-6.3.0|
|EditorConfig|EditorConfig|0.16.4|editorconfig.editorconfig-0.16.4|
|explorer-exclude|PeterSchmalfeldt|1.3.2|peterschmalfeldt.explorer-exclude-1.3.2|
|file-icons|file-icons|1.1.0|file-icons.file-icons-1.1.0|
|gitlens|eamodio|14.6.1|eamodio.gitlens-14.6.1|
|hexeditor|ms-vscode|1.9.12|ms-vscode.hexeditor-1.9.12|
|icons|tal7aouy|3.7.0|tal7aouy.icons-3.7.0|
|ilspy-vscode|icsharpcode|0.17.0|icsharpcode.ilspy-vscode-0.17.0|
|live-server|ms-vscode|0.4.13|ms-vscode.live-server-0.4.13|
|macos-modern-theme|davidbwaters|2.3.19|davidbwaters.macos-modern-theme-2.3.19|
|material-product-icons|PKief|1.7.0|pkief.material-product-icons-1.7.0|
|mono-debug|ms-vscode|0.16.3|ms-vscode.mono-debug-0.16.3|
|nasc-touchbar|felipe|1.12.0|felipe.nasc-touchbar-1.12.0|
|npm|idered|1.7.4|idered.npm-1.7.4|
|pipenv-scripts|FedericoVarela|1.0.3|federicovarela.pipenv-scripts-1.0.3|
|powershell|ms-vscode|2023.8.0|ms-vscode.powershell-2023.8.0|
|python|ms-python|2023.22.1|ms-python.python-2023.22.1|
|python-environment-manager|donjayamanne|1.2.4|donjayamanne.python-environment-manager-1.2.4|
|rainbow-csv|mechatroner|3.9.0|mechatroner.rainbow-csv-3.9.0|
|remote-containers|ms-vscode-remote|0.327.0|ms-vscode-remote.remote-containers-0.327.0|
|remote-explorer|ms-vscode|0.5.2023121309|ms-vscode.remote-explorer-0.5.2023121309|
|remote-repositories|ms-vscode|0.40.0|ms-vscode.remote-repositories-0.40.0|
|remote-ssh|ms-vscode-remote|0.108.2023112915|ms-vscode-remote.remote-ssh-0.108.2023112915|
|remotehub|GitHub|0.62.0|github.remotehub-0.62.0|
|scriban|xoofx|1.2.1|xoofx.scriban-1.2.1|
|test-adapter-converter|ms-vscode|0.1.8|ms-vscode.test-adapter-converter-0.1.8|
|tsl-problem-matcher|amodio|0.6.2|amodio.tsl-problem-matcher-0.6.2|
|vsc-material-theme-icons|equinusocio|3.3.1|equinusocio.vsc-material-theme-icons-3.3.1|
|vscode-azureappservice|ms-azuretools|0.25.1|ms-azuretools.vscode-azureappservice-0.25.1|
|vscode-azurefunctions|ms-azuretools|1.13.1|ms-azuretools.vscode-azurefunctions-1.13.1|
|vscode-azureresourcegroups|ms-azuretools|0.8.3|ms-azuretools.vscode-azureresourcegroups-0.8.3|
|vscode-azurestorage|ms-azuretools|0.15.3|ms-azuretools.vscode-azurestorage-0.15.3|
|vscode-coverage-gutters|ryanluker|2.11.1|ryanluker.vscode-coverage-gutters-2.11.1|
|vscode-dotnet-runtime|ms-dotnettools|2.0.0|ms-dotnettools.vscode-dotnet-runtime-2.0.0|
|vscode-edge-devtools|ms-edgedevtools|2.1.3|ms-edgedevtools.vscode-edge-devtools-2.1.3|
|vscode-eslint|dbaeumer|2.4.2|dbaeumer.vscode-eslint-2.4.2|
|vscode-github-actions|github|0.26.2|github.vscode-github-actions-0.26.2|
|vscode-icons|vscode-icons-team|12.6.0|vscode-icons-team.vscode-icons-12.6.0|
|vscode-jest|Orta|5.2.3|orta.vscode-jest-5.2.3|
|vscode-nuget-gallery|patcx|0.0.24|patcx.vscode-nuget-gallery-0.0.24|
|vscode-pull-request-github|GitHub|0.78.1|github.vscode-pull-request-github-0.78.1|
|vscode-pylance|ms-python|2023.12.1|ms-python.vscode-pylance-2023.12.1|
|vscode-react-native|msjsdiag|1.12.2|msjsdiag.vscode-react-native-1.12.2|
|vscode-scss-formatter|sibiraj-s|3.0.0|sibiraj-s.vscode-scss-formatter-3.0.0|
|vscode-taskexplorer|spmeesseman|2.13.2|spmeesseman.vscode-taskexplorer-2.13.2|
|vscode-test-explorer|hbenl|2.21.1|hbenl.vscode-test-explorer-2.21.1|
|vscode-thunder-client|rangav|2.16.3|rangav.vscode-thunder-client-2.16.3|
|vscode-xml|redhat|0.26.1|redhat.vscode-xml-0.26.1-darwin-x64|
|vscode-yaml|redhat|1.14.0|redhat.vscode-yaml-1.14.0|
|vscode-yarn|gamunu|2.1.0|gamunu.vscode-yarn-2.1.0|
|vscodeintellicode-csharp|ms-dotnettools|0.1.26|ms-dotnettools.vscodeintellicode-csharp-0.1.26-darwin-x64|
|yarn-task-provider|dkneeland|0.2.2|dkneeland.yarn-task-provider-0.2.2|;

</details>

Extension version: 1.1.16
VS Code version: Code 1.85.1 (Universal) (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:48:06.308Z)
OS version: Darwin x64 23.1.0
Modes:
Connection to 'SSH: windows' could not be established 
Connection to 'ssh-remote+windows' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|9, 24, 24|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id d86b36da-14f9-422b-8173-94de5e9844ae|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: windows' could not be established 

Connection to 'ssh-remote+windows' could not be established
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30899288
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
0bi6i642:30917235
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementsc:30887149
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232
cp7184t:30925682

```

</details>

**Comment by WardenGnaw** [comment] 2023-12-20 18:24
Duplicate of #774.

@junalmeida `checkForDevCert` will be set for dotnet configurations if the `launchSettings.json` configuration has `useSSL: true`

**Comment by junalmeida** [comment] 2023-12-20 18:58
@WardenGnaw Thanks for pointing that out. I believe, as a suggestion, that the notification of certificate could suggest this change is required to not show the alert.

**Closed** 2023-12-20 18:58 UTC
Labels: duplicate, area-debugging

**Comment by WardenGnaw** [comment] 2023-12-20 21:23
@junalmeida Was there a specific dialog or error message that you would like to see that suggestion on?

**Comment by junalmeida** [comment] 2023-12-20 22:13
@WardenGnaw 
![image](https://github.com/microsoft/vscode-dotnettools/assets/991675/6d9bebe9-0a70-4ed4-8a5a-55b1c28935cc)
This dialog I believe should suggest on how to not check if certificate is trusted in case you manage it manually.
