### ISSUE TITLE
Intellisense doesn't work on Unity method like Update(), OnTriggerEnter().

### ISSUE THREAD

**Issue by iouzzrj** [microsoft/vscode-dotnettools#1056] opened 2024-04-10 12:33 UTC
Type: <b>Bug</b>

IntelliSense's auto complete feature does work most of the time, but it doesn't work on some Unity method like Update(), OnTriggerEnter().

This is a snapshot from Visual Studio in which IntelliSense works for the OnTriggerEnter method:
![屏幕截图 2024-04-10 202600](https://github.com/microsoft/vscode-dotnettools/assets/43952332/b0170276-3a2e-4770-bc0d-cf017912c052)

On Visual Studio Code however, the auto complete doesn't work:
![屏幕截图 2024-04-10 203148](https://github.com/microsoft/vscode-dotnettools/assets/43952332/45dd84b2-ffbe-41df-8316-dbcaab617567)

Extension version: 1.0.1
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (113.72GB free)|
|Process Argv|C:\\Users\\iouzz\\Documents\\Unity Projects\\My project (2) -g C:\\Users\\iouzz\\Documents\\Unity Projects\\My project (2)\\Assets\\Scripts\\OutOfBounds.cs:1:0|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by iouzzrj** [comment] 2024-04-10 12:39
I just learned the C# chapter on classes and haven't learned about inheritance yet. But seems these methods are inherited from MonoBehaviour. So the auto complete doesn't work on inherited method?

**Comment by iouzzrj** [comment] 2024-04-10 12:41
Sorry, I clicked the wrong button. Reopen this issue now.

**Comment by sailro** [comment] 2024-04-10 19:03
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1020

**Closed by sailro** 2024-04-10 19:03 UTC
Labels: duplicate, area-unity
