### ISSUE TITLE
Command args not wrapped in quotes

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-dotnettools#237] opened 2023-07-07 20:46 UTC
Type: <b>Bug</b>

When I try to build/clean my C# project by right-clicking it in the <b>Solution Explorer</b>, I get an error `MSB1008`. My Windows user folder contains a space. When running the `dotnet build/clean` commands, the extension does not wrap the path to the project file in quotation marks, which I think it should.

Extension version: 0.2.99
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (9.51GB free)|
|Process Argv|--crash-reporter-id 7bccedbc-48b9-48dd-8a6c-c536d01ad5f2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
bgfeh915:30780428
pythonnosm12tcf:30779713
pythonidxpt:30784022
pythonnocebcf:30776496

```

</details>

**Comment by Michael-Eng** [comment] 2023-07-10 20:31
I think this is a dup of #24. Please try using the prerelease version of the extension since it's fixed in that version to see if it fixes it for you too?

**Comment by Michael-Eng** [comment] 2023-07-10 21:28
@Jxwoon can you take a look?

@HiddenDot can you share more details about the command that's not getting quoted?

**Comment by adrianvmsft** [comment] 2023-07-12 01:57
I was able to reproduce the issue on my side, it seems to be a limitation in a VS Code feature that the extension uses. I opened an issue on the vs-code side to see what the right solution should be.

Thank you for reporting this issue,
Adrian

**Closed as completed** 2023-07-12 03:15 UTC
Labels: bug, area-project-cps
