### ISSUE TITLE
[BUG] Deployed app is corrupted when iOS Action Extension projects are included as a project reference in the .CSPROJ file

### ISSUE THREAD

**Issue by austinbaccus** [microsoft/vscode-dotnettools#852] opened 2024-01-12 20:07 UTC
### Describe the Issue

We have an iOS app for iPhone. We also have an iOS Action Extension project that goes along with it. The app is build using MAUI for VS Code (Mac).

When I try to build the main iOS app and deploy it to my iPhone for debugging, it builds and deploys to my iPhone. However, it seems like the app is corrupted and cannot be launched:

1. The app name is not {app name}. Instead, it's a random string of letters (usually something like "bjhdfjvhdsjhfvhjgdf").
2. The app icon is not our app icon. Instead, it's the default iOS app icon.
3. The app cannot actually be launched ore debugged. An error is thrown when you try to launch the app on the phone.

The fix is to remove the Action Extension project reference within the main app's .CSPROJ file.

### Steps To Reproduce

1. Create iOS mobile project
2. Create iOS Action Extension project
3. Reference the Action Extension project within the mobile project's .CSPROJ file
4. Deploy to device
5. Observe weird app properties and inability to launch on device

### Expected Behavior

Main app is deployed to device with the correct name, the correct icon, and is launchable even if the Action Extension project is referenced.

### Environment Information

- OS: macOS Sonoma 14.2
- Chip: Apple M1
- Xcode: 15.2
- C# Dev Kit: 1.2.7
- VS Code: 1.85.1
| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1999747">1999747</a>

**Comment by tmeschter** [comment] 2024-01-18 19:48
@austinbaccus Is your iPhone app built using MAUI?

**Comment by austinbaccus** [comment] 2024-01-19 21:35
@tmeschter Yes.

**Comment by tmeschter** [comment] 2024-01-25 19:43
Moving to "area-maui" as this seems specific to MAUI app deployment.

**Comment by mauroa** [comment] 2024-04-09 19:41
Hi @austinbaccus. 
There's no default template for .NET iOS App Extensions, so I assume you adapted your .csproj to be SDK Style and also to target net8-ios, is that assumption, correct?

That said, are you getting a successful build if you build from command line? (dotnet build). If you can try that and share a binlog of the resulting build (passing -bl the command line build), I could see what is going on.

Finally, if by any chance you can share you solution, that would be helpful as well.
Thanks

**Comment by mauroa** [comment] 2024-04-12 14:22
Just as an update after some investigation, iOS Extensions for VS Code is not fully supported, so we need to convert this into a feature request. We'll work on it and provide updates when the support is ready. Thanks for your help and patience.

**Comment by mauroa** [comment] 2024-04-12 15:35
Closing as a duplicate of this other one: https://github.com/microsoft/vscode-dotnettools/issues/548

You can follow up status and progress directly in that ticket

**Closed by mauroa** 2024-04-12 15:35 UTC
Labels: bug, duplicate, enhancement, triaged, area-maui, vs-sync, mac, vs-syncd
