### ISSUE TITLE
C# Intellisense not working

### ISSUE THREAD

**Issue by codeveer85** [microsoft/vscode-dotnettools#905] opened 2024-02-09 02:36 UTC
Type: <b>Bug</b>

Install vs code on Mac
Install the C# dev kit extension
Create a dotnet project using C#
Intellisense does not work

Extension version: 1.3.10
VS Code version: Code 1.86.1 (31c37ee8f63491495ac49e43b8544550fbae4533, 2024-02-07T09:08:57.920Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id d02e1bf9-8c87-405e-a2cd-2ec042e9392a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
3ef8e399:30949928
bg6jg535:30958357
ccp1r3:30958155

```

</details>

**Comment by jefflomax** [comment] 2024-02-10 02:40
same with C# Dev Kit v1.3.10 VS Code Version: 1.86.0 Windows 22H2
No Intellisense

**Comment by ravitejaavv** [comment] 2024-02-13 11:53
is there any update on this issue?

**Comment by ArjunNair** [comment] 2024-04-02 07:07
Ditto. I'm trying to use it with Unity and without intellisense, it's pretty hard.

**Comment by ArjunNair** [comment] 2024-04-05 05:32
Well it has magically started working for me after restarting the Mac. :-| Maybe all it needed was a restart of Unity or VS Code or both or an actual restart of the Mac. Who knows anymore how things even work? *shrug*

**Comment by AbhitejJohn** [comment] 2024-04-29 18:36
@jebriede : Would you have any additional thoughts on how restore might have caused this to happen? It seems like this is suddenly working for a couple of folks but it isn't very clear what caused it in the first place.

**Comment by webreidi** [comment] 2024-05-13 16:25
Closing this issue as everything is working now. Please reopen if you experience the issue again.

**Comment by tomasszabo** [comment] 2024-05-13 17:00
@webreidi it is still not working, in logs is only following:

```
received named pipe information from server
attempting to connect client to server...
client has connected to server
[Info  - 18:54:56] [Program] Language server initialized
```

but the last line never appears:

```
[Info  - 18:55:08] [WorkspaceProjectFactoryService] Project /.../Microsoft/Demo/DemoAPI/DemoAPI.csproj loaded by C# Dev Kit
```

C# Dev Kit: v1.5.20
VS Code: Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:14:32.757Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin arm64 23.4.0

Need to use VS Code - Insiders (from where I copied the last line from logs), in standard VS Code Intellisense is not working. Please reopen.

**Comment by codeveer85** [comment] 2024-05-16 02:03
I resolved this issue by using older version of Dotnet Core- 7.0.405. It is still not working with latest version for me.

**Comment by lifengl** [comment] 2024-05-16 22:24
> @jebriede : Would you have any additional thoughts on how restore might have caused this to happen? It seems like this is suddenly working for a couple of folks but it isn't very clear what caused it in the first place.

C# Dev Kit need find the location where SDK is installed from the PATH environmental variable (and it also runs dotnet command, which need to be resolved in this way.)  However, some time, vscode session starts earlier will capture the environmental variables so it will not see changes after installing packages later. Often this is reset after rebooting the machine, which might explain what we saw here.

**Comment by lifengl** [comment] 2024-05-16 22:42
For developers who still cannot get this to work after closing vscode process completely (or better, reboot the machine), we need see what is in the log to find a clue.

A most basic log would be the "C# Dev Kit" tab in the output window. More detailed log files can be found by opening vscode extension folder (vscode command), and dig into ms-dotnettools.csdevkit folder. Some log files in the ServiceHub folder would help.

Interesting one include:

*-hubController-*-*-1.log
*-Microsoft.VisualStudio.ProjectSystem.CompositionService-*-*-1.log

If you can share some content of the log file, it will help us to look for the reason behind this issue.

**Comment by tomasszabo** [comment] 2024-05-17 07:42
Rebooting VS Code or the complete system did not helped.

C# Dev Kit output:

```
Starting Spawn .NET server...
Using preinstalled .NET runtime at "/usr/local/share/dotnet/dotnet"
.NET server started and IPC established in 15483ms
Completed Spawn .NET server (17498ms)
```

There are no log files in extension folder (see [extension_files.txt](https://github.com/microsoft/vscode-dotnettools/files/15345324/extension_files.txt))

**Comment by lifengl** [comment] 2024-05-17 19:56
@tomasszabo , thanks to follow up on this,

The output window tells us the C# Dev Kit did start, but the log should be longer, containing information like starting NuGet restore, or open a solution. Missing that information means maybe we didn't open any solution file in the workspace.

That might be a problem leading confusions, because the extension would automatically open a solution, if there is a single solution file in the workspace, otherwise, it pops up a notification to ask developers to select/open one. However, the notification might not be noticeable, and it only happens when you open the workspace first time on the machine. (-- well, many developers hate to see a repeated message, or to see a message at all).  I wonder whether you run into this.

In the vscode 'explore' tab, you might see a 'solution explorer' view (if it is not dragged to somewhere else), check whether anything is opened, or it has a button to open a solution.  If not, you can also use '.NET: Open Solution' command in vscode to ensure we open a solution.

If this doesn't resolve your problem, we should take another look the output window & the extension log.

BTW, to get to the extension log, you need use vscode command 'Developer: Open Extensions Logs Folder', which will find the folder for you.  The folder is not in the location where the extension is installed, but in a temporary folder, so they can be cleaned up later.

**Comment by tomasszabo** [comment] 2024-05-20 19:51
I agree, output should be longer, but it is not. But I do have a project open:

<img width="1113" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/6609558/3f5723ec-7990-473d-809a-45acaaefecec">

Logs requested:

[EEDB5B4F-Microsoft.VisualStudio.ProjectSystem.CompositionService (0.1)-RemoteServiceBroker-2327-pmvljk0y-1.log](https://github.com/microsoft/vscode-dotnettools/files/15381258/EEDB5B4F-Microsoft.VisualStudio.ProjectSystem.CompositionService.0.1.-RemoteServiceBroker-2327-pmvljk0y-1.log)
[EEDB5B4F-Microsoft.VisualStudio.ProjectSystem.CompositionService-2390-erxrmezo-1.log](https://github.com/microsoft/vscode-dotnettools/files/15381259/EEDB5B4F-Microsoft.VisualStudio.ProjectSystem.CompositionService-2390-erxrmezo-1.log)
[EEDB5B4F-hubController-2370-lvi32u3u-1.log](https://github.com/microsoft/vscode-dotnettools/files/15381261/EEDB5B4F-hubController-2370-lvi32u3u-1.log)

**Comment by lifengl** [comment] 2024-05-20 19:57
@tomasszabo : the log shows the project system is warmed up, but nothing loaded. (The warming up logic is triggered earlier to cut JIT overhead in the critical loading path.

One way to see what has been opened is to expand the 'Solution explorer' below the file system tree. It is an user experience problem in the extension to make it less clear what has been opened, which need be improved.

**Comment by tomasszabo** [comment] 2024-05-20 20:08
Here you go:

<img width="1113" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/6609558/0ec37425-3a3d-4441-8929-12ef67c11cc2">

**Comment by lifengl** [comment] 2024-05-25 00:40
Yes, @tomasszabo , thank a lot for the screen shot. You can click the "open solution" button to open a solution file, and check whether it resolves your problem.

**Comment by tomasszabo** [comment] 2024-05-26 19:13
Yes, clicking on `Open Solution` button solves the problem. But shouldn't the solution be opened automatically?

**Comment by lifengl** [comment] 2024-06-07 17:55
do you have multiple solution files in the workspace? In which case, the extension pops up a notification to ask the developer to make a choice, however, that notification window is easily missed. 

the experience can definitely be improved here, which is being considered now...

**Comment by tomasszabo** [comment] 2024-06-10 07:26
@lifengl there is no solution file in the workspace, only `csproj` (see screenshot above). However, if I open the exact same project in `VS Code - Insiders` then it works as expected (automatically), no need to do something manually. 

Therefore, in my opinion, it is a bug of `C# DevKit + VS Code` combination, because in `C# DevKit + VS Code - Insiders` it is working as expected. And the version of `C# Dev Kit` is the same in both distribution of VS Code - v1.6.8.

**Comment by lifengl** [comment] 2024-06-12 02:41
if there is no solution file, the extension would generate a .sln file, and open it, which would be the experience you saw in the Insider version. If the solution is closed, the state would be persisted, and it would not be opened in the next session forever, until it is manually opened again. Because the insider/normal vscode saves the workspace state in different location, I guess this might be a state preserved long time ago. Of course, It is hard to say whether there is a bug a while ago in the extension. Because the state is persisted in the old workspace, it will keep the state even the extension is updated.  The only way to tell is to create a completely new workspace in a copy of your repo in a new location to try it.  

now, after you open the solution once, and do you see the problem again?

**Comment by tomasszabo** [comment] 2024-06-12 07:38
@lifengl I need to open the solution manually each time I open the workspace or restart VS Code, so if there should be some state preserved, it doesn't look like it's happening. I've also created a new fresh test project (with `dotnet new webapi --use-controllers` command), but the behavior is the same as in old workspace - need to open solution manually each time.

However, I'm experiencing an exception from `C# Dev Kit` when opening the solution:

```
12/06/2024 09:14:30
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
```

It looks like it happens when I've multiple workspaces open and then try to open solution in one of them (doesn't matter which one is first).

**Comment by lifengl** [comment] 2024-06-12 19:50
Hey, @tomasszabo : thanks, that definitely sounds a bug to me. Let me try to see whether I can reproduce it. -- it is interesting, because I don't think the extension is different for vscode & vscode insiders build (the insiders build is more a preview for vscode itself).

The exception appears to tell there is a piece of bad code in the extension TypeScript code, which assumes some execution order which does not hold. Although itself should not cause the issue you mentioned, but maybe some initialization code is skipped, which leads both of them?

**Comment by lifengl** [comment] 2024-06-12 20:57
@tomasszabo : the exception you saw is the same issue as #1175. It appears to be a race condition in some TypeScript code, and I loop it to developers in that area. It should not affect the workspace state to be saved. I will let that part to be tracked in the other bug.

**Comment by lifengl** [comment] 2024-06-12 21:58
@tomasszabo, just to make sure I understand the scenario, I wonder whether you turned off this setting in the vscode:

![image](https://github.com/microsoft/vscode-dotnettools/assets/11638466/6813759b-312f-478c-a59a-b585b5e8e44a)

**Comment by tomasszabo** [comment] 2024-06-13 07:17
@lifengl I'm sorry, I had these properties disabled due to problems when running VS Code workspace with multiple projects: 

<img width="1136" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/6609558/9b44547b-7674-464c-9983-513eb671e082">

As far as I remember, there were some issues with Azure Functions extension and multiple projects in workspace, therefore I disabled solution generation.

However, when it is enabled, it works fine if I have only one project in VS Code open. If I have multiple projects in one workspace (see screenshot above) then solution is generated only for the first one and `C# Dev Kit` is not working in the second one (and there is no option to load another solution in `Solution Explorer`).

**Comment by lifengl** [comment] 2024-07-18 17:54
@tomasszabo ,
 you can change those options on workspace level, instead of the entire user level, which could help you to address some of those conflicting needs.  
 
If it is a newly generated solution file, it should include all .csproj in the workspace. But the generated .sln was not maintained automatically, so when new projects are added later, it might become stale. It is a known problem being investigated.  If you ran into it, your workaround for now is to delete the older generated .sln file, or adds new projects manually into it (there is a context menu to do it in the solution root node inside the solution explorer.

There is also an option to keep the generated .sln file outside of the workspace folder. It is not on by default, because it doesn't support workspaces with special global.json files. It might work for you, if your workspace doesn't use a global.json file.

**Comment by lifengl** [comment] 2024-07-18 18:02
This thread has been drifted to discuss issues related to generated .sln file, instead of the original problem. 

so far, the intellisense issue seems to be addressed by restarting the Mac machine (usually force vscode to pick up updated PATH environment from earlier new installation of the SDK, or ensure a solution is opened in the workspace.

We are updating our experience to give warning or indication when there is no solution opened or the current file is not covered by the current solution file in the status bar, which will hopefully reduce some of the confusion here. There are pending work to maintain generated .sln file up to date, and experience around the generated .sln file.

At this point, I will close this issue. Please let us know you still have intellisense issues further, or open new issues for any problem due to generated solution files.

**Closed by lifengl** 2024-07-18 18:02 UTC
Labels: bug, area-project-cps, high-priority, mac
