### ISSUE TITLE
[BUG] Blazor Components are seen a unknown

### ISSUE THREAD

**Issue by DevTard** [microsoft/vscode-dotnettools#49] opened 2023-06-07 14:45 UTC
### Describe the Issue

When using the extension to program a Blazor project any custom components are not identified and are underlined as a warning  

"Found markup element with unexpected name 'xxxxx'. If this is intended to be a component, add a @using directive for its namespace.Razor(RZ10012)"

This is for components that are referenced via usings and was not an issue prior to installing this extension.

### Environment Information

- OS - MacOS
- VSCODE - 1.78.2 (Universal)
- Extension 
    - C# - v2.0.206
    - C# Dev Kit - v0.1.83
    - IntelliCode for C# Dev Kit - v0.1.9

**Comment by artyomszasa** [comment] 2023-06-27 07:18
Installing C# Dev kit completly breaks all blazor projects for me (even the simpliest ones).
![Képernyőkép erről: 2023-06-27 09-07-54](https://github.com/microsoft/vscode-dotnettools/assets/843989/6bdac79b-39ee-49a2-8218-decd8f085493)

Solution is open, yet not a single blazor tag is recognized at all.

Uninstalling C# dev kit extension does not resolve this issue, downgrading the Omnisharp extension back to "release version" does. Issue is reproducible even without C# dev kit extension --> switching Omnisharp to "pre-release" version instantly breaks all razor files, switching back fixes that...

**Comment by ryzngard** [comment] 2023-08-17 23:13
> Installing C# Dev kit completly breaks all blazor projects for me (even the simpliest ones). ![Képernyőkép erről: 2023-06-27 09-07-54](https://user-images.githubusercontent.com/843989/249067072-6bdac79b-39ee-49a2-8218-decd8f085493.png)
> 
> Solution is open, yet not a single blazor tag is recognized at all.
> 
> Uninstalling C# dev kit extension does not resolve this issue, downgrading the Omnisharp extension back to "release version" does. Issue is reproducible even without C# dev kit extension --> switching Omnisharp to "pre-release" version instantly breaks all razor files, switching back fixes that...

I'm sorry to hear that. Unfortunately I was unable to reproduce this issue with 

C# `v2.0.376`
DevKit `v0.4.5`

If you are still hitting this issue can you please provide a copy of the logs for `Razor Logs`. Similar to instructions about reporting an issue https://github.com/dotnet/vscode-csharp#found-a-bug

**Comment by stefffdev** [comment] 2023-08-18 04:46
For the problem still exists, happened right now with the C# and DevKit Versions you mentioned.
Razor Logs are attached.
[Razor.log](https://github.com/microsoft/vscode-dotnettools/files/12375404/Razor.log)

**Comment by ryzngard** [comment] 2023-10-02 21:59
> The problem seems to still exist, happened right now with the C# and DevKit Versions you mentioned. Razor Logs are attached. [Razor.log](https://github.com/microsoft/vscode-dotnettools/files/12375404/Razor.log)

Thanks for providing logs. We're still unable to find a repro on M1 Mac with versions tested. If possible, do you have a repro project for this?

**Comment by stefffdev** [comment] 2023-10-07 18:57
I think I was able to create a small project to reproduce the issue but I would rather not make it public, can I email it instead?

**Comment by ryzngard** [comment] 2023-10-09 21:05
Yup! Just send it to andrha@microsoft.com

**Comment by garrettlondon1** [comment] 2023-10-19 03:45
![image](https://github.com/microsoft/vscode-dotnettools/assets/3959577/538ba30f-b6db-42ba-b01d-2dea13ddce20)

Same on my project, the Button component is even open in the tab above

**Comment by mikes-gh** [comment] 2023-11-05 22:45
I have this issue.
I am one f the maintainers of https://github.com/MudBlazor/MudBlazor however I am the only vscode mac user.
If you open this project in vscode you will get thousands of RZ10012.
This didn't happen when I was using omnisharp.

**Comment by mikes-gh** [comment] 2023-11-18 11:32
It seems to me that RZ10012 is shown for components in a referenced Blazor component library that don't have a code behind file.  Ones with a code behind are resolved.  Devkit seems to have a problem discovering components without a code behind.

**Comment by garrettlondon1** [comment] 2023-11-19 05:51
For me as well, Visual Studio & VS Code experience is broken in latest versions with RZ10012 errors everywhere..

**Comment by mikes-gh** [comment] 2023-11-19 22:47
@jaredpar could this be related to https://github.com/dotnet/razor/issues/8718? Is it possible C# Devkit is using an old version of the razor compiler for its design time compilation? Without the code there's no way for us to tell.

**Comment by ryzngard** [comment] 2023-11-20 19:40
https://github.com/dotnet/razor/issues/9600 may be related as well, if you're updating to .NET 8 (or have changed targeting in some other way)

**Comment by garrettlondon1** [comment] 2023-11-20 19:50
@ryzngard it looks like I'm having a similar issue

**Comment by dawchelstowski** [comment] 2023-11-21 17:04
I've got this issue as well, but in the latest pre-release build only workaround is when you open not recognised component, it seems that loading this file helps for IDE to find out it actually exists, maybe there is a way to load entire set of files in the solution? I think it could solve the issue

**Comment by ryzngard** [comment] 2023-11-27 21:40
@davidwengier I saw that https://github.com/dotnet/razor/pull/9601 is for VS windows only. Do we have a similar issue in our VS Code handling?

Either way, this issue specifically was Mac/Linux related. @stefffdev sent me the repro project and I was able to reproduce the issue. Unfortunately I don't know the root cause yet.

**Comment by garrettlondon1** [comment] 2023-11-27 21:45
I can confirm both on VS Code & Visual Studio Windows I'm seeing the same. Both latest version of C# extension (no dev kit), as well as latest version of VS2022

**Comment by ryzngard** [comment] 2023-11-27 21:46
@garrettlondon1 please file feedback through VS and record a repro :) It will get directed to our team with extra diagnostics attached.

**Comment by davidwengier** [comment] 2023-11-30 11:15
> @davidwengier I saw that [dotnet/razor#9601](https://github.com/dotnet/razor/pull/9601) is for VS windows only. Do we have a similar issue in our VS Code handling?

I can do you better than an issue, we have PRs: https://github.com/dotnet/roslyn/pull/70913 and https://github.com/dotnet/vscode-csharp/pull/6688

**Comment by sion-corn** [comment] 2023-12-16 03:11
I am seeing the same issue in Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.3
Running on Win 10.

**Comment by parko65** [comment] 2023-12-16 14:45
Same here VS2022 17.8.3 Win 11.

**Comment by parko65** [comment] 2023-12-16 14:58
> It seems to me that `RZ10012` is shown for components in a referenced Blazor component library that don't have a code behind file. Components with a code behind are resolved. Devkit seems to have a problem discovering components without a code behind.

@mikes-gh Issue happens even if code behind is present also.

**Comment by parko65** [comment] 2023-12-16 15:28
Close VS 2022, delete bin and obj folders, reopen project and issue is gone.

**Comment by mikes-gh** [comment] 2023-12-16 17:11
> > It seems to me that `RZ10012` is shown for components in a referenced Blazor component library that don't have a code behind file. Components with a code behind are resolved. Devkit seems to have a problem discovering components without a code behind.
> 
> @mikes-gh Issue happens even if code behind is present also.

@parko65 Yes you are right.  I confirm this is not a pattern.

**Comment by mikes-gh** [comment] 2023-12-16 17:12
> Close VS 2022, delete bin and obj folders, reopen project and issue is gone.

For vscode on macOS this doesn't seem to make any difference

**Comment by sion-corn** [comment] 2023-12-16 18:38
> > Close VS 2022, delete bin and obj folders, reopen project and issue is gone.
> 
> For vscode on macOS this doesn't seem to make any difference

Deleting bin and obj folders don't make any difference for me in **Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.3** (Win10)

BUT I am not seeing this issue when opening the same solution in **Microsoft Visual Studio Community 2022 (64-bit) - Preview
Version 17.9.0 Preview 2.0** (Win10)

**Comment by parko65** [comment] 2023-12-16 19:04
Damn it, worked for me.
So this is not VS version dependent.

@mikes-gh I do apologise, I'm not testing on Code for Mac at the moment as I had the issue with VS2022 windows.

**Comment by sion-corn** [comment] 2023-12-16 19:22
> Damn it, worked for me. So this is not VS version dependent.
> 
> @mikes-gh I do apologise, I'm not testing on Code for Mac at the moment as I had the issue with VS2022 windows.
> 
> @sion-corn You're win10 with 17.8.3. I can't see any reason why 17.9.0 preview would make a difference.
> 
> Ill try the same scenario on Win10.

Beats me, but it does make a difference for me.

**Comment by davidwengier** [comment] 2023-12-16 23:25
> I can't see any reason why 17.9.0 preview would make a difference.

The fix for the bug was in 17.9 Preview 2.

**Comment by ryzngard** [comment] 2023-12-18 19:11
This bug should be used for tracking VSCode issues, so it should be independent of VS version. The right place for VS bugs is  https://github.com/dotnet/razor . 

For those experiencing this issue in VS, 17.9 P2 is the expected fix as @davidwengier  pointed out

**Comment by ryzngard** [comment] 2024-02-08 18:53
I'm not sure why this is vscode-dotnettools, but I believe the fix is going into dotnet/vscode-csharp. @davidwengier can you confirm?

**Comment by davidwengier** [comment] 2024-02-08 22:11
No news on when the change might go in. I would also caution against pinning all of your hopes and dreams on it. There are a number of reasons why RZ10012 might be shown, having old files in an `obj` folder is just one of the issues.

**Comment by daveHylde** [comment] 2024-03-07 14:58
I'm also facing this issue in vscode on windows 11. It works fine in Rider, but in vscode I get lots of errors and warnings as described in this issue. Another annoying part is that the razor LSP goes crazy and constantly finds new problems before it removes them again. It never reaches a finite analysis state.
It's the same behaviour in WSL and non-WSL.

**Comment by daveHylde** [comment] 2024-04-03 07:57
Can this be re-opened?

**Comment by ryzngard** [comment] 2024-04-03 21:23
Yup, this is still on my list for investigation. We've made various improvements but there's still definitely an issue. Some vacation and other work related things meant I missed that this got closed. Happy to reopen

**Comment by BenBurge** [comment] 2024-04-17 21:57
I'm a Windows 11 user.

In my case I have 4 components in the same namespace. One of the four components is detected properly while the other 3 give me the error about adding a using statement.

I've tried some of the mentioned fixes like removing the obj folder. None of those options seem to fix the issue.

![image](https://github.com/microsoft/vscode-dotnettools/assets/13814339/926377b5-dc26-4f58-93e6-b4ca0113a419)

![image](https://github.com/microsoft/vscode-dotnettools/assets/13814339/7644aecc-7498-488f-a5d3-c41231e4af93)
![image](https://github.com/microsoft/vscode-dotnettools/assets/13814339/660cbd98-c51b-46b3-a2f7-1a2e619727dc)

**Comment by garrettlondon1** [comment] 2024-04-17 22:11
Too many basic functions broken

go to definition
Component references
Using statements..

these are basic features that arent a nice to have, they are reuired to always be functional for developers to work

**Comment by ryzngard** [comment] 2024-04-17 22:18
@BenBurge can you please file separate feedback through VS Code? There is a `Razor: Report Razor Issue` command that should attach relavent logs.

**Comment by BenBurge** [comment] 2024-04-18 15:10
> @BenBurge can you please file separate feedback through VS Code? There is a `Razor: Report Razor Issue` command that should attach relevant logs.

Of course! I've posted the logs through the VC Code Report a razor issue.

https://github.com/dotnet/razor/issues/10275

**Comment by AaronBeaudoin** [comment] 2024-05-03 15:33
To summarize what I'm experiencing (Windows 11, VS Code 1.89.0, C# Extension 2.23.15, C# Dev Kit Extension 1.4.29):

- When loading the solution, the error/warning count in the status bar goes nuts, zipping up and down between dozens of warnings and hundreds of warnings as the LSP looks through the solution in the background.
- When the LSP finally "calms down", it still hasn't got everything figured out.
  - Opening a code behind file reveals errors such as:
    - `'MyComponent.OnInitializedAsync()': no suitable method found to override (CS0115)`
    - `The name 'StateHasChanged' does not exist in the current context (CS0103)`
  - When opening the component's `.razor` file, the errors go away, so it seems like the LSP couldn't find the "code in front" of the component that goes with the "code behind" file without me manually opening it in an editor.
  - However, the `MyComponent.razor` file still has errors from missing references (RZ10012 errors as described above). As others have discovered, these seem to be coming from components that _don't_ have code behind files and just have the code inline with `@code`. Similarly to above, opening the components in editors causes them to be found.
- But annoyingly, every time I open a new file in an editor, the LSP seems to go through it's whole "discovery loop?" again and the warning count in my status bar goes nuts for another 10-30 seconds.

I really want to fully move to VS Code from VS 2022 for all my C# projects, but for Blazor right now this is not possible because of these issues. I'm also trying to encourage my coworkers to give VS Code a try, but stuff like this is working against my case.

Is there anything we can do to help get this resolved soon so VS Code becomes a viable editor for Blazor projects?

**Comment by AaronBeaudoin** [comment] 2024-05-07 16:01
Can we remove the "mac" label from this issue? This problem is definitely present on other platforms as well.

**Comment by ryzngard** [comment] 2024-05-08 22:21
If opening fixes the issue, likely it's related to https://github.com/dotnet/vscode-csharp/issues/6852 

While the errors may be the same, root cause is different. It's easier for us to track specific details to make sure when we fix an issue we're not asserting all other related are fixed. This is to track mac specific issues for unknown components

**Comment by burtonrodman** [comment] 2024-06-07 18:54
> Too many basic functions broken
> 
> go to definition Component references Using statements..
> 
> these are basic features that arent a nice to have, they are reuired to always be functional for developers to work

HEAR, HEAR!!  vscode/C# Dev Kit is almost unusable atm -- especially for Razor/Blazor:
- false positive errors/warnings ABOUND
- intellisense almost always picks the wrong thing (ex:  @ushort instead of @using)
- go to definition is broken (literally) 90% of the time
- parameter intellisense is broken (literally) 90% of the time
- formatting is always wrong and doesn't respect my .editorconfig settings
- no WebAssembly debugging
- 1 missing/misplaced semicolon/curly and you end up with 100 errors -- impossible to find

sorry for the rant, but it's been building up... i promise i'll do my best to report actionable bugs on all of this as they come up again (today).

**Comment by burtonrodman** [comment] 2024-06-07 19:06
btw, additional information related to this actual bug...
 
 The warnings I'm getting are for components in the same folder -- which to my understanding should be in the same namespace and therefore not require an @using statement in the consuming component or _Imports.razor

![image](https://github.com/microsoft/vscode-dotnettools/assets/7658657/4f27e814-2dcd-42e6-8009-971eed598ce9)

**Comment by bpsc-wkubis** [comment] 2024-06-08 06:44
> > Too many basic functions broken
> > go to definition Component references Using statements..
> > these are basic features that arent a nice to have, they are reuired to always be functional for developers to work
> 
> HEAR, HEAR!! vscode/C# Dev Kit is almost unusable atm -- especially for Razor/Blazor:
> 
> * false positive errors/warnings ABOUND
> * intellisense almost always picks the wrong thing (ex:  @ushort instead of @using)
> * go to definition is broken (literally) 90% of the time
> * parameter intellisense is broken (literally) 90% of the time
> * formatting is always wrong and doesn't respect my .editorconfig settings
> * no WebAssembly debugging
> * 1 missing/misplaced semicolon/curly and you end up with 100 errors -- impossible to find
> 
> sorry for the rant, but it's been building up... i promise i'll do my best to report actionable bugs on all of this as they come up again (today).

I totally get what you're saying. VS Code is really tough to use right now. I'm hitting the same problems you are. Most of the time, IntelliSense doesn't work at all, and I have to keep running 'dotnet build' to check my code. It's a mess.

**Comment by armanfellowmind** [comment] 2024-06-13 13:42
> To summarize what I'm experiencing (Windows 11, VS Code 1.89.0, C# Extension 2.23.15, C# Dev Kit Extension 1.4.29):
> 
> * When loading the solution, the error/warning count in the status bar goes nuts, zipping up and down between dozens of warnings and hundreds of warnings as the LSP looks through the solution in the background.
> * When the LSP finally "calms down", it still hasn't got everything figured out.
>   
>   * Opening a code behind file reveals errors such as:
>     
>     * `'MyComponent.OnInitializedAsync()': no suitable method found to override (CS0115)`
>     * `The name 'StateHasChanged' does not exist in the current context (CS0103)`
>   * When opening the component's `.razor` file, the errors go away, so it seems like the LSP couldn't find the "code in front" of the component that goes with the "code behind" file without me manually opening it in an editor.
>   * However, the `MyComponent.razor` file still has errors from missing references (RZ10012 errors as described above). As others have discovered, these seem to be coming from components that _don't_ have code behind files and just have the code inline with `@code`. Similarly to above, opening the components in editors causes them to be found.
> * But annoyingly, every time I open a new file in an editor, the LSP seems to go through it's whole "discovery loop?" again and the warning count in my status bar goes nuts for another 10-30 seconds.
> 
> I really want to fully move to VS Code from VS 2022 for all my C# projects, but for Blazor right now this is not possible because of these issues. I'm also trying to encourage my coworkers to give VS Code a try, but stuff like this is working against my case.
> 
> Is there anything we can do to help get this resolved soon so VS Code becomes a viable editor for Blazor projects?

This perfectly encapsulates my issues. I ended up disabling C# devkit and reenabling omnisharp. That fixed it for me.

**Comment by wizcas** [comment] 2024-06-15 08:55
My team is considering starting a new project using .NET core with Blazor. Some team members work on Mac so VS is not an option. VS for Mac is about to stop maintenance. Rider is expensive. Now even VS Code cannot provide a reasonable support. All ways to .NET seems to be blocked for devs who are not working on Windows.
I don't see how this would help .NET community grow.

**Comment by joe-mills** [comment] 2024-06-15 09:19
[like]  Joseph Mills reacted to your message:
________________________________

**Comment by mikes-gh** [comment] 2024-06-15 14:43
@wizcas Totally agree.  I am on macOS with vscode using OmniSharp.  I don't know how resources for the C# devkit are allocated internally.  Maybe it's the VS team?  Currently it's not working as can be seen by the age of these issues.  I am still not able to user C# dev since it was conceived a year ago.

**Comment by marcos-prins** [comment] 2024-06-16 22:26
The error still persist

![Screenshot from 2024-06-16 17-13-27](https://github.com/microsoft/vscode-dotnettools/assets/52753267/326806c3-0b82-4efd-ac23-0637d4a14823)

**Comment by ryzngard** [comment] 2024-06-17 20:40
GH isn't a great place to discuss the internals, nor will I talk about company resources: 

1. We are working hard on this. The majority of the work being done is in dotnet/roslyn and dotnet/razor. DevKit sometimes is the root cause here, but less so than just the complexity of how things work. 
2. If you're ever curious the C# discord is a great place to discuss the ins and outs here and why this is a hard problem to solve, but also what we are doing about it both in the short term and long term. 

Moral of the story: we hear you, are working to improve this, and always appreciate you continuing to test and let us know if you're still hitting issues or if new ones arise.

**Comment by mikes-gh** [comment] 2024-06-17 21:15
@ryzngard I understand your comments.  Thing is this is closed source, so we have no real way of knowing or appreciating the problems. Would you have a thread from the C# discord server that shed some light on what's going on.

**Comment by ryzngard** [comment] 2024-06-17 22:54
@mikes-gh the close source portion isn't the issue. AFAICT this isn't necessarily a devkit issue at all. We have seen multiple issues (like https://github.com/dotnet/razor/issues/5901 ) 

The short answer is that getting component and symbol information is tricky. Razor can't be a statically parsed language because of the mix of html/csharp. Context of the file isn't the only important portion, context in the project and available symbols is also very important. VS Code and VS4W work differently here.

In VS 4 windows this system is just heavier tested, runs in the same process, and in general has at least been isolated to only having to work on windows. The communication on MacOS and Linux was tested, but it's now going through the growing pains of our inability to test everything. 

Synchronizing the project information is almost always the crux of the issue. The overall architecture changes we're hoping to make on the dotnet/razor team is following this issue https://github.com/dotnet/razor/issues/9519 (and pretty much others like it). 

That is a large effort to greatly improve the architecture here and get us having the same source of truth without trying to synchronize across different processes. 

In the meantime, targeted fixes like https://github.com/dotnet/razor/pull/10480 are being done to help reliability, and I'm currently still doing more work here. 

I'm always happy to have more detailed discussion. I don't have a thread in discord but am happy to respond there to help facilitate a conversation that is less delayed than GH issues.

**Comment by joe-mills** [comment] 2024-06-21 07:08
> @ryzngard thanks for the update. transparency is key when we have a critical mass of very frustrating issues that seem to be going unanswered.

I also appreciate the explanation but I'm still not clear if we should expect to be able to develop Blazor on vscode at all.

If I follow the latest docs from MS for starting a Blazor Server project in VS code it gives you step by step instructions using c# Dev Kit and you end up with broken intelligence and tooling (dotnet -- version 8.0.302)

[https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=vsc](https://learn.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=vsc)

**Comment by garrettlondon1** [comment] 2024-06-21 13:04
We just need to find a way to slap AI on this and then it will get prioritized :)

**Comment by joe-mills** [comment] 2024-06-21 13:09
> We just need to find a way to slap AI on this and then it will get prioritized :)

Maybe it works on the new copilot pc's.  I think they do AI.. ;)

**Comment by marcos-prins** [comment] 2024-06-21 13:13
> We just need to find a way to slap AI on this and then it will get prioritized :)

I was thinking exactly the same, because it looks like IA is the only one priority for Microsoft right now

**Comment by afallingstone** [comment] 2024-07-10 14:05
It sucks because this has been broken for a while... But, here is a work around that seems to work for me. 

1. After opening the solution. Add a blank _Imports.razor inside a folder (not root). Wait till the tab at the top turns green, then delete it. 
3. Open any components referenced in the razor file you want to work in and view them until they are fully loaded. 
4. Re-open the razor file you want to work in, and the component references should work until you restart VS Code, then you have to do this again.
5. This works for both .razor and .cs files.

Here is an example:

Before
![code1](https://github.com/microsoft/vscode-dotnettools/assets/82959136/d8f5de25-65d3-4a5c-a3a2-79ed78b40435)

After
![code2](https://github.com/microsoft/vscode-dotnettools/assets/82959136/f42d2664-f557-4885-8ceb-3bfd81efe604)

**Comment by ryzngard** [comment] 2024-07-10 20:17
@afallingstone hopefully we've found a fix for this with a recent merge https://github.com/dotnet/vscode-csharp/pull/7273 

It's expected to go out in the next prerelease of the extension. This (and a slew of similar bugs) will be re-verified if they are reproducing still

**Comment by ryzngard** [comment] 2024-07-17 20:42
This should be available now with `v2.39.28 (pre-release)`

**Comment by marcel2215** [comment] 2024-07-18 12:26
Even after updating to C# `2.39.28 (pre-release)` and C# Dev Kit `v1.9.8 (pre-release)` I am still having this issue.

![screenshot1](https://github.com/user-attachments/assets/60265855-1b66-4b8b-9d33-0777c491d7c8)

In my case I have a solution containing two projects: `DopamineUI.csproj` and `DopamineUIPreview.csproj`. The former contains the code of all components.

![screenshot2](https://github.com/user-attachments/assets/4fa20bdb-7d6c-4f28-8ba6-706969680087)

When I launch Visual Studio Code, I open the entire `dopamine-ui` folder in one window so I can access both source and preview at the same time. Everything compiles and runs fine, but working with 400+ ghost warnings/errors is not a pleasant experience.

A workaround is to open both projects (`src` and `preview` subfolders) in separate windows, but doing so creates unwanted `src/src.sln` and `preview/preview.sln` files. Both projects are already referenced in `DopamineUI.sln`.

![screenshot3](https://github.com/user-attachments/assets/7bf323df-add0-49c0-853f-17a7e7a417e8)

Moreover, the existence of the `preview.sln` file is preventing me from using `dotnet watch` command. This is likely because it detects both `DopamineUI.sln` and `preview/preview.sln`. I am limited to launching via `FN + F5` or `dotnet run` as these are unaffected. I have tried running `dotnet watch --project DopamineUIPreview.csproj` but got the same MSB1011 error. However, this is a problem with the `dotnet` itself and not the extension.

![screenshot34](https://github.com/user-attachments/assets/564e613d-5a50-4799-a1b5-b73c547194eb)

Deleting `preview.sln` solves the `dotnet watch` problem but it causes these 400+ warnings to reappear as components are not detected again.

**Details**
OS: `macOS Sonoma 14.5`
VS Code: `1.91.1`
C# Extension: `v2.39.28 (pre-release)`
C# Dev Kit: `v1.9.8 (pre-release)`
.NET: `8.0`

The project I am working on is open-source and pinned on my GitHub profile. Feel free to use it to investigate/reproduce the issue.

**Comment by marcel2215** [comment] 2024-07-18 13:12
I have now tested it on my Windows PC and everything is exactly the same - so the problem is not related to just macOS.

**Comment by ryzngard** [comment] 2024-07-18 22:02
Thanks @marcel2215 , reopening

**Comment by bpsc-wkubis** [comment] 2024-07-19 05:31
Bumping up, got still same issues as @marcel2215

**Comment by dawidkacprzak** [comment] 2024-07-19 18:42
Hi, for me the 'solution (if we can name that..) is to just add using to namespace. 
I don't know how does it work in more complex solutions - probably pain in the ... but it works for me.

Just add usings on the top of the file.

It looks like the _Imports.razor is not working as should be for IDE extension. (For build it's ok)

Attached screenshot before and after using.

What's more interesting after additional using i can remove it after and IDE looks fixed for all other usings...

![image](https://github.com/user-attachments/assets/58104ad7-7528-4acf-8254-232359637f4d)
![image](https://github.com/user-attachments/assets/f1291fbd-840a-4cc6-a6f1-aa6da66887cb)

**Comment by ryzngard** [comment] 2024-07-19 20:17
> Hi, for me the 'solution (if we can name that..) is to just add using to namespace. I don't know how does it work in more complex solutions - probably pain in the ... but it works for me.
> 
> Just add usings on the top of the file.
> 
> It looks like the _Imports.razor is not working as should be for IDE extension. (For build it's ok)
> 
> Attached screenshot before and after using.
> 
> What's more interesting after additional using i can remove it after build and IDE looks fixed for all other usings... really weird
> 
> ![image](https://private-user-images.githubusercontent.com/10233135/350520937-58104ad7-7528-4acf-8254-232359637f4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjAyNDgsIm5iZiI6MTcyMTQxOTk0OCwicGF0aCI6Ii8xMDIzMzEzNS8zNTA1MjA5MzctNTgxMDRhZDctNzUyOC00YWNmLTgyNTQtMjMyMzU5NjM3ZjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGM3OTUwYTFhZWVjZDczMWIwNTA1ZjgzZDVkNDY5N2UxMjhjOWNiMzlkNmEzNWJkZjE4YTBjMGQ1N2JmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFRSOqKhLPzafQZPSkCQCKVPQLutDiYAwLvQTLeGMyQ) ![image](https://private-user-images.githubusercontent.com/10233135/350521012-f1291fbd-840a-4cc6-a6f1-aa6da66887cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjAyNDgsIm5iZiI6MTcyMTQxOTk0OCwicGF0aCI6Ii8xMDIzMzEzNS8zNTA1MjEwMTItZjEyOTFmYmQtODQwYS00Y2M2LWE2ZjEtYWE2ZGE2Njg4N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjA4M2IxMDI1M2JjNGNlOGM2YWZmMWE0ZWI5YzU1NDY5YzAzMGNhNzExM2Y3OWRkNzY0ODdjMmQ0ZjIwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DMF8dKARes6hVNlvXwD1CGDd1iqfDHWVoghcbKqY-38)

This _sounds_ like what should be fixed in pre-release. I'm investigating the repro with `DopamineUI` today

**Comment by dawidkacprzak** [comment] 2024-07-19 20:20
> > Hi, for me the 'solution (if we can name that..) is to just add using to namespace. I don't know how does it work in more complex solutions - probably pain in the ... but it works for me.
> > Just add usings on the top of the file.
> > It looks like the _Imports.razor is not working as should be for IDE extension. (For build it's ok)
> > Attached screenshot before and after using.
> > What's more interesting after additional using i can remove it after build and IDE looks fixed for all other usings... really weird
> > ![image](https://private-user-images.githubusercontent.com/10233135/350520937-58104ad7-7528-4acf-8254-232359637f4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjAyNDgsIm5iZiI6MTcyMTQxOTk0OCwicGF0aCI6Ii8xMDIzMzEzNS8zNTA1MjA5MzctNTgxMDRhZDctNzUyOC00YWNmLTgyNTQtMjMyMzU5NjM3ZjRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MGM3OTUwYTFhZWVjZDczMWIwNTA1ZjgzZDVkNDY5N2UxMjhjOWNiMzlkNmEzNWJkZjE4YTBjMGQ1N2JmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eFRSOqKhLPzafQZPSkCQCKVPQLutDiYAwLvQTLeGMyQ) ![image](https://private-user-images.githubusercontent.com/10233135/350521012-f1291fbd-840a-4cc6-a6f1-aa6da66887cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MjAyNDgsIm5iZiI6MTcyMTQxOTk0OCwicGF0aCI6Ii8xMDIzMzEzNS8zNTA1MjEwMTItZjEyOTFmYmQtODQwYS00Y2M2LWE2ZjEtYWE2ZGE2Njg4N2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDIwMTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwZjA4M2IxMDI1M2JjNGNlOGM2YWZmMWE0ZWI5YzU1NDY5YzAzMGNhNzExM2Y3OWRkNzY0ODdjMmQ0ZjIwZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DMF8dKARes6hVNlvXwD1CGDd1iqfDHWVoghcbKqY-38)
> 
> This _sounds_ like what should be fixed in pre-release. I'm investigating the repro with `DopamineUI` today

Ah, i did not mentioned. I was reproducing that on newest pre-release version of C# extension and latest release as well - same result

**Comment by ryzngard** [comment] 2024-07-19 21:00
Alright, I've got a repro of `DopamineUI`. I will see about testing on `OpenSuse tumbleweed`. 

I filed https://github.com/dotnet/razor/issues/10654 to better track the `DopamineUI` issue. 
I filed https://github.com/dotnet/razor/issues/10655 for the `OpenSuse tumbleweed` issue. 

This issue as originally filed is fixed. I'll see if I can root cause the two new issues, but this issue is "resolved" in the sense that "Component discovery is not completely broken on MacOS anymore". 

Thank you for the detailed information @marcel2215  and @dawchelstowski

**Closed by ryzngard** 2024-07-19 21:00 UTC
Labels: bug, area-razor, triaged, area-vscode
