### ISSUE TITLE
[BUG] .NET MAUI extension always starts with the device target first available on the list no matter what the user selection is

### ISSUE THREAD

**Issue by egvijayanand** [microsoft/vscode-dotnettools#250] opened 2023-07-12 21:36 UTC
### Describe the Issue

Have installed the .NET MAUI extension.

Opened a .NET MAUI project (`dotnet new maui`).

Have selected Windows Subsystem for Android (WSA) as the target device.

Though Android is the opted target platform, it always builds and launches the Windows platform as it's the first device target available on the list.

### Steps To Reproduce

1. Install the .NET MAUI extension
2. Open a .NET MAUI project
3. Select a device target that is not at the top of the device target list
4. Try to build and launch the project

### Expected Behavior

Expected to build the project and launch in the opted device target.

### Environment Information

OS: **Windows 11 (v10.0.22621.1928)**
VS Code: **v1.80.0**
.NET MAUI extension: **v0.1.34**

**Comment by maddymontaquila** [comment] 2023-07-13 18:42
Hi @egvijayanand ! If you try an Android emulator or physical does that work? I'm wondering if this is a WSA issue. When you launch a WSA app it looks just like a Windows app - if you build and deploy for Windows is the app the exact same?

**Comment by egvijayanand** [comment] 2023-07-13 18:47
@maddymontaquila, have validated the build command that is running in the background. Building it for the Windows platform only (`-f net8.0-windows10.0.19041.0`).

Will try to connect a physical Android device and update the outcome.

**Comment by egvijayanand** [comment] 2023-07-13 19:10
Here's the command from the VS Terminal (_username alone removed to protect privacy_):

Executing task: dotnet build -t:Build -p:Configuration=Debug **-f net8.0-windows10.0.19041.0 -r win10-x64** -p:WindowsPackageType=None -p:CustomAfterMicrosoftCSharpTargets="c:\Users\<username>\.vscode\extensions\ms-dotnettools.dotnet-maui-0.1.34-win32-x64\dist\resources\maui\MauiVSCodeWindows.targets" -p:_DeletePriConfigXml=True e:\MAUI\NET_8\Preview_6\MauiApp1\MauiApp1.csproj 

MSBuild version 17.7.0+5785ed5c2 for .NET
  Determining projects to restore...
  Restored e:\MAUI\NET_8\Preview_6\MauiApp1\MauiApp1.csproj (in 724 ms).
C:\Program Files\dotnet\sdk\8.0.100-preview.6.23330.14\Sdks\Microsoft.NET.Sdk\targets\Microsoft
.NET.RuntimeIdentifierInference.targets(314,5): message NETSDK1057: You are using a preview ver
sion of .NET. See: https://aka.ms/dotnet-support-policy [e:\MAUI\NET_8\Preview_6\MauiApp1\MauiA
pp1.csproj::TargetFramework=net8.0-windows10.0.19041.0]
  MauiApp1 -> e:\MAUI\NET_8\Preview_6\MauiApp1\bin\Debug\net8.0-windows10.0.19041.0\win10-x64\M
  auiApp1.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

**Comment by egvijayanand** [comment] 2023-07-13 22:26
@maddymontaquila Have tried with a physical Android device as the target device. But no change in the output. It always builds for the Windows platform and launches it as an unpackaged app. The terminal command is same as in the earlier comment.

Since the local machine (Windows) is available as the first target, it automatically picks that one, or is it by design to work only with the Windows target in this preview release of the extension?

![image](https://github.com/microsoft/vscode-dotnettools/assets/81947404/27ff46ef-b0a3-49bb-bfe9-5a1ce4e5417a)

**Comment by egvijayanand** [comment] 2023-07-13 22:37
And found another issue, **Selective targeting is not supported.**

To narrow down the cause, tried to selectively target Android alone by removing all other target platforms from the project file. Which is practically a very valid scenario. So, kindly plan to support this as well.

The extension reported it with an error message stating **.NET MAUI SDK not found**. Refer to the below screenshot.

![image](https://github.com/microsoft/vscode-dotnettools/assets/81947404/82eba80b-cffc-47ef-8d41-ed2926608766)

**Comment by egvijayanand** [comment] 2023-07-13 23:55
Found another issue, terminal commands using single quote char as a delimiter for the `AndroidSdkDirectory` property in anticipation of space in the path is causing trouble. The build command is failing. Kindly use double quotes.

A reference to the issue logged: https://github.com/dotnet/maui/issues/16091

**Comment by maddymontaquila** [comment] 2023-07-14 18:05
Ooooooh interesting. @egvijayanand  if you run `dotnet workload list` does it show maui, maui-android, etc? Then if you run `dotnet workload install maui` does that succeed? It should be able to target Android without issue. It looks to me like since it can't find the MAUI SDK its just building Windows instead of erroring correctly.

**Comment by egvijayanand** [comment] 2023-07-14 18:11
Yes, @maddymontaquila, have installed the .NET MAUI workload and it's getting listed as well.

Facing this Android build issue in CLI outside of VS Code as well. Seems like the Android SDK directory location delimited by the single quote is creating issues all around. Rather it should be delimited by double quotes which is working fine.

**Comment by egvijayanand** [comment] 2023-07-14 18:12
![image](https://github.com/microsoft/vscode-dotnettools/assets/81947404/cbf8e554-2d72-4ca8-b848-05acb6da7f72)

**Comment by maddymontaquila** [comment] 2023-07-14 18:13
It's weird that maui-android isnt listed - could you try `dotnet workload install maui-android` and see if that works?

**Comment by egvijayanand** [comment] 2023-07-14 18:17
> It's weird that maui-android isnt listed - could you try `dotnet workload install maui-android` and see if that works?

It's there, I clipped the screenshot. It's installed with VS update itself.

Only the MAUI workload is installed manually and Tizen is via VS extension.

![image](https://github.com/microsoft/vscode-dotnettools/assets/81947404/35a85706-33dd-4950-90a9-453800298ed5)

**Comment by maddymontaquila** [comment] 2023-07-14 18:22
Ahhhh ok sorry! I'm wondering if theres an issue because the workloads are all installed via VS, except for maui. Sometimes they randomly conflict even if it looks "ok". @mcumming will look more when he's back from time off - thank you for reporting!!!!

**Comment by egvijayanand** [comment] 2023-07-14 18:25
A good point to start the troubleshooting would be the scenario where **Android SDK** is installed in a location that is not the default Program Files folder, as it is here shared with Android Studio as well.

**Comment by egvijayanand** [comment] 2023-07-14 18:53
Hi @maddymontaquila, have resolved the Android build issue by editing the **extension.js** file made available in the folder %UserProfile%\\.vscode\extensions\ms-dotnettools.dotnet-maui-0.1.34-win32-x64\dist\.

At a particular location, where the MSBuild properties are collected, for the `AndroidSdkDirectory` property, Single quotes are replaced by Double quotes as delimiter.

Before:
```js
n.push(`-p:AndroidSdkDirectory='${o.path}'`)
```
After:
```js
n.push(`-p:AndroidSdkDirectory="${o.path}"`)
```

Kindly formalize the fix and provide a solution for Selective Targeting, which can be simulated just by commenting on other TFMs.

**Comment by mcumming** [comment] 2023-07-18 15:06
Hi @egvijayanand,
To get back to the original problem in the description. I am mostly interested in Step 3 of your steps to reproduce. Can you describe in more detail how you switched the target platform? Providing screenshots would be very helpful.

Additionally, do you have either the [Meteor](https://marketplace.visualstudio.com/items?itemName=nromanov.dotnet-meteor) or [Comet](https://marketplace.visualstudio.com/items?itemName=Clancey.comet-debug) extension installed? If so, try disabling them for the current workspace to see if there are possible conflicts occurring.

**Comment by mauroa** [comment] 2024-03-19 16:53
There's a fix available for this issue that will be published in the next VS Code MAUI pre-release version. We'll proceed to close this issue once that version is available to install.

**Comment by mauroa** [comment] 2024-04-12 16:20
Closing as fixed on latest .NET MAUI pre release

**Closed by mauroa** 2024-04-12 16:20 UTC
Labels: triaged, area-maui, fixed-pending-release
