### ISSUE TITLE
[QUESTION] Storyboard Support

### ISSUE THREAD

**Issue by andrews4s** [microsoft/vscode-dotnettools#571] opened 2023-09-28 05:36 UTC
In VS4Mac, opening a iOS/MacOS storyboard generated an XCode project as a bridge between the dotnet project and XCode IB. With VS4Mac support ending, are any plans to support similar functionality in C# Dev Kit?

> VS bug [#1895861](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1895861)

**Comment by maddymontaquila** [comment] 2023-10-03 19:42
Hi there! This, along with all the other "Xcode sync" type capabilities, are something we'd like to support in the future as part of the .NET MAUI extension but not currently in development. I'm keeping this issue open so we can provide updates here when we pick up this work!

**Comment by stefan89** [comment] 2023-11-13 18:54
@maddymontaquila any update on this? VS Code is not an alternative for 'VS for Mac' as long as these basic functionalities are not supported.

**Comment by maddymontaquila** [comment] 2023-11-27 22:08
> > @maddymontaquila any update on this? VS Code is not an alternative for 'VS for Mac' as long as these basic functionalities are not supported.
> 
> Agreed. How are we support to target iOS17 when VS for Mac doesn't support .NET 8 SDK and VS Code doesn't support Xcode sync.... I can't believe a 3rd party app like Rider already supports this.
> 
> Unless Microsoft is trying really hard to force everyone to use MAUI, I really don't understand their reasoning for getting rid of VS for Mac and not offering any viable alternatives.

Just had a conversation about this today with some on our engineering team. There's a proposal in the works. We were pretty heads down getting .NET 8 out last month so we're picking these things back up now (might get quiet again for the holidays, but this is top of my list for early next year!)

**Comment by jkavanaghrdm** [comment] 2024-01-31 14:47
Hi @maddymontaquila. We're currently blocked on new .Net Mobile development until we have storyboard and other xcode sync functions available. Would you be able to provide a timeline for those features to be available?

**Comment by projectgoav** [comment] 2024-03-11 11:08
We're now almost 6months since this was raised and raipdly approaching less than 6months until VS4Mac is to be retired and so far all we know is that you have had one conversation about this feature?

No proposal, no timescales or even any idea (or hope) that this feature will be supported at all, let alone before VS4Mac is retired. This is all incredibly disappointing.

**Comment by projectgoav** [comment] 2024-03-11 11:26
Agreed about Rider.

My company picked up some licenses to evaluate Rider shortly after VS4Mac sunset was announced. Has been working great since day one and had all the features we needed out of the box. It's very likely we'll be moving over to that instead of whatever VSCode solution is provided.... Assuming there is a VSCode solution at all.

**Comment by joeisapro** [comment] 2024-03-11 19:02
Anyone from Microsoft care to comment on this?  @maddymontaquila @timheuer ?

Apple will stop accepting AppStore submissions built with the iOS 16 SDK on April 29th.  VS4Mac doesn't support iOS SDK 17 (requires .NET 8) so we won't be able to update our apps soon.

Please tell us clearly what the plan is.  Maybe you should reconsider EOLing VS4Mac and give it .NET 8 support until another solution is available.

But, to be honest, this is the last time we are taken hostage like this and will most likely move to other technologies for newer apps.  Very unfortunate.

**Comment by lbulegato** [comment] 2024-03-13 08:16
What is shocking is that it seems there is no plan whatsoever from Microsoft. It's not feasible to communicate the end of life of a product (VS4MAC) and offer an unusable alternative (VSCODE). It would be more honest to say: use Rider, professionalism is lacking.
I'm not debating the plans, if Microsoft wants to discontinue the development of an IDE for Mac, it's their right. What I find incorrect is the lack of clarity.

**Comment by MateuszLas421** [comment] 2024-04-03 08:52
@microsoftopensource  @maddymontaquila  @timheuer  Any update?

**Comment by jkapsouras** [comment] 2024-04-24 08:27
I also use rider to address this problem. I opened vscode today to check if anything was changed but still no luck.

**Comment by johnconners** [comment] 2024-04-30 20:43
I'm assuming if you're developing a macOS .NET desktop app (like I do) then C# dev kit will not be a viable alternative if .xib support is not even in development? I have zero interest in MAUI btw. We're not far from VS for Mac's end of life date now. I'm assuming this comment from @maddymontaquila was more wishful thinking at the time of the announcement to soften the blow:

https://devblogs.microsoft.com/visualstudio/visual-studio-for-mac-retirement-announcement/#comment-29496

**Comment by andres-gimenez** [comment] 2024-05-05 08:37
Since MAUI came out, Microsoft has forgotten about Xamarin Native, so I think support for editing xib and Storyboard is going to take time to come out.

With the MAUI extension we will have the compilation and debugging solved. What we're not going to have is the editing of the xib, storyboard and plist. Visual Studio for Mac doesn't do that either because it delegates it to Xcode.

Would it be too complicated to develop a plugin to integrate dotnet core projects with XCode, as Visual Studio for MAC does? The creation of the designer.cs can be done with Roslyn (I know how to do it). What I'm not sure about is how to create the auxiliary project for XCode or how to open the plists.

**Comment by lbulegato** [comment] 2024-05-06 07:52
We only need to know the plans by Microsoft.
I am using Rider and it works fine, because vscode is unsuitable for real working.
But I'd like to understand plans for Xamarin native or as they call it now .NET IOS/Android.
They stopped porting base iOS/Android package like Firebase or google maps.

I have no idea if you can use a MAUI package for a native project for instance, we can try of course but it is the lack of information that is unrespectful.

**Comment by andres-gimenez** [comment] 2024-05-06 08:06
> We only need to know the plans by Microsoft. I am using Rider and it works fine, because vscode is unsuitable for real working. But I'd like to understand plans for Xamarin native or as they call it now .NET IOS/Android. They stopped porting base iOS/Android package like Firebase or google maps.
> 
> I have no idea if you can use a MAUI package for a native project for instance, we can try of course but it is the lack of information that is unrespectful.


The plans are that there are no plans. You only have to see how in https://github.com/dotnet/maui-samples the native example, it has been relegated and difficult to find, without any modification since its creation.

**Comment by acespedes451** [comment] 2024-05-14 19:58
Any updates for this? or are you Microsoft pretending us to migrate all our native Android and iOS projects to MAUI? because this is NOT going to happen.

**Comment by maddymontaquila** [comment] 2024-05-15 20:37
Hi everyone! I know it's been a minute since I've updated this issue - just want to let you know that this work is currently under development as part of the .NET iOS SDK, and once that's done it will be able to be used via the command line. As soon as the SDK work is done we will also hook it up through VS Code - likely through the command palette, or just automatically. Thank you all for your patience - hopefully we have some updates soon!

**Comment by partyalarm** [comment] 2024-05-17 01:10
If this can be done, prototyping of MAUI libraries for IOS and android can be progressed.

**Comment by viswanath-pamarthi** [comment] 2024-05-30 14:43
> Hi everyone! I know it's been a minute since I've updated this issue - just want to let you know that this work is currently under development as part of the .NET iOS SDK, and once that's done it will be able to be used via the command line. As soon as the SDK work is done we will also hook it up through VS Code - likely through the command palette, or just automatically. Thank you all for your patience - hopefully we have some updates soon!

@maddymontaquila  Thanks for the update, as everyone on the thread mentioned. Instead a timeline would certainly help and provide clear direction. We have been facing the same issues mentioned in this thread with new and existing development which need Xcode sync for UI editing.

**Comment by projectgoav** [comment] 2024-08-14 09:46
> Hi everyone! I know it's been a minute since I've updated this issue - just want to let you know that this work is currently under development as part of the .NET iOS SDK, and once that's done it will be able to be used via the command line. As soon as the SDK work is done we will also hook it up through VS Code - likely through the command palette, or just automatically. Thank you all for your patience - hopefully we have some updates soon!

Gentle reminder that VS4Mac is discountined 17days and we are still no further forward with this issue 🙃

**Comment by entdark** [comment] 2024-08-14 09:53
@projectgoav we are actually!
They just released a preview with that feature: https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/dotnetmaui.md#xcode-sync-for-cli-and-visual-studio-code

**Comment by projectgoav** [comment] 2024-08-14 09:57
I stand corrected. We're 50% of the way there. Cutting it fine mind you...

**Comment by andrews4s** [comment] 2024-08-15 01:44
> @projectgoav we are actually! They just released a preview with that feature: https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/dotnetmaui.md#xcode-sync-for-cli-and-visual-studio-code

This is great news. The implementation should work well with VS Code tasks. I'm having some bugs with it (some of which can be worked around) and will report once I have minimal repro test projects.

**Comment by dimysa** [comment] 2024-09-02 10:10
I tried the new xcsync functionality, and it works, but it does not generate `*.h` files for xib and storyboard, so I cannot create outlets for UI components.

**Comment by mcumming** [comment] 2024-09-04 16:48
> I tried the new xcsync functionality, and it works, but it does not generate `*.h` files for xib and storyboard, so I cannot create outlets for UI components.

Please let us know what your issues are here for the time being. We will have a better location for issue tracking in the coming months.

**Comment by mcumming** [comment] 2024-09-04 16:49
> I tried the new xcsync functionality, and it works, but it does not generate `*.h` files for xib and storyboard, so I cannot create outlets for UI components.

@dimysa Is this something that you frequently do? Does adding the outlet to a ViewController.h/.m work for you?

**Comment by andrews4s** [comment] 2024-09-05 06:22
> > I tried the new xcsync functionality, and it works, but it does not generate `*.h` files for xib and storyboard, so I cannot create outlets for UI components.
> 
> @dimysa Is this something that you frequently do? Does adding the outlet to a ViewController.h/.m work for you?

I generated a fresh macOS project and ran into this as well.
Steps:
mkdir mactest2
cd mactest2
dotnet new macos
dotnet build mactest2.csproj /t:xcsync-generate

Xcode launches the generated project, but the Assistant view has no results...
<img width="1512" alt="Screenshot 2024-09-05 at 2 17 58 AM" src="https://github.com/user-attachments/assets/574d615a-2f64-42ff-b3af-891863009bad">

Project sources show blank items...
<img width="1512" alt="Screenshot 2024-09-05 at 2 18 11 AM" src="https://github.com/user-attachments/assets/ac6f846f-15dd-4155-9085-c0d304eb13fd">

Deleting the blanks and adding all .m files fixes the project an the assistant view works again.
<img width="1397" alt="Screenshot 2024-09-05 at 2 19 04 AM" src="https://github.com/user-attachments/assets/b772b074-5923-4c5d-934c-86d6df29afa5">

**Comment by dimysa** [comment] 2024-09-05 11:24
@mcumming I'd say quite often since we have the entire UI for iOS done with Storyboard or XIB.
I tried to add ViewController and Storyboard to a simple project.
Using `xcsync-generate` in this case, created `h/m` files, but creating outlets and synchronizing via `xcsync-sync` didn't pull anything up in the .net project.
Also the `xcSyncVerbosity` property seems to do nothing because the Detailed value gives the same output in the terminal as `Normal`

**Comment by mcumming** [comment] 2024-09-05 11:40
> > > I tried the new xcsync functionality, and it works, but it does not generate `*.h` files for xib and storyboard, so I cannot create outlets for UI components.
> > 
> > 
> > @dimysa Is this something that you frequently do? Does adding the outlet to a ViewController.h/.m work for you?
> 
> I generated a fresh macOS project and ran into this as well. Steps: mkdir mactest2 cd mactest2 dotnet new macos dotnet build mactest2.csproj /t:xcsync-generate
> 
> Xcode launches the generated project, but the Assistant view has no results... <img alt="Screenshot 2024-09-05 at 2 17 58 AM" width="1512" src="https://private-user-images.githubusercontent.com/15205112/364648137-574d615a-2f64-42ff-b3af-891863009bad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzYxMjYsIm5iZiI6MTcyNTUzNTgyNiwicGF0aCI6Ii8xNTIwNTExMi8zNjQ2NDgxMzctNTc0ZDYxNWEtMmY2NC00MmZmLWIzYWYtODkxODYzMDA5YmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMmRhMTc1M2RiNTViYzQ3YTg2Zjk3NzFiNTU5YzkyZDE5ZWQzNzRkZTYzYzg4ZjQ0YzlkMGMzMzk2NDVlOTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.j2ZMesDLyRYhMgzo04rlj8uPITPeYAzeuJiKPwIdKgQ">
> 
> Project sources show blank items... <img alt="Screenshot 2024-09-05 at 2 18 11 AM" width="1512" src="https://private-user-images.githubusercontent.com/15205112/364648437-ac6f846f-15dd-4155-9085-c0d304eb13fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzYxMjYsIm5iZiI6MTcyNTUzNTgyNiwicGF0aCI6Ii8xNTIwNTExMi8zNjQ2NDg0MzctYWM2Zjg0NmYtMTVkZC00MTU1LTkwODUtYzBkMzA0ZWIxM2ZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTBjMTcyY2JhMGYzNWVmOTllYWQ5ZDBiMDlmMzg3ODdlNGQ3NzcxNzc1NGY2ZGY3MWQwNmE5MTY1MDIwN2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tqc2umhD8nuR6dW5R4r_kJ0EJ-PFfIkTBOG_59IOPC0">
> 
> Deleting the blanks and adding all .m files fixes the project an the assistant view works again.
> 
> <img alt="Screenshot 2024-09-05 at 2 23 34 AM" width="1512" src="https://private-user-images.githubusercontent.com/15205112/364649391-29521af5-5c5f-4f78-ae3d-535396b933ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzYxMjYsIm5iZiI6MTcyNTUzNTgyNiwicGF0aCI6Ii8xNTIwNTExMi8zNjQ2NDkzOTEtMjk1MjFhZjUtNWM1Zi00Zjc4LWFlM2QtNTM1Mzk2YjkzM2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkOTllODM1Y2FkNmYzNjk3MGE0NzZlMDVkY2ZkNDk3NWFjZTA0NjAzMWVlOWY0ZTE3NGRhYzNiNWUxOTJhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y6SoZqa9TbPKEUK0RTN4-6tX0fH7VpPtlCqP7E37rpo"> <img alt="Screenshot 2024-09-05 at 2 19 04 AM" width="1397" src="https://private-user-images.githubusercontent.com/15205112/364648854-b772b074-5923-4c5d-934c-86d6df29afa5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzYxMjYsIm5iZiI6MTcyNTUzNTgyNiwicGF0aCI6Ii8xNTIwNTExMi8zNjQ2NDg4NTQtYjc3MmIwNzQtNTkyMy00YzVkLTkzNGMtODZkNmRmMjlhZmE1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDExMzAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiZjk0MTcwYWFiMjIwMzYzYjU1ZjM5MTE2MzRlODM4YTkzODdjZTk2ZDVjMzA3ZmU1YjBkNzQ4ZmY5ZTNkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xCrPEHtLwX_x6lF5pQp09x4jDyz_kDsd2bLp4htgNhk">

@andrews4s, thanks for the detailed explanation. I see from the screenshots that the ViewController.h and ViewController.m files are generated correctly and present in the project but aren't registered correctly as compile items. We will investigate this. Once you manually fixed the project, can you create the Actions/Outlets and then use the `dotnet build mactest2.csproj /t:xcsync-generate` to have the changes synced back to the dotnet project?

**Comment by mcumming** [comment] 2024-09-05 11:45
> @mcumming I'd say quite often since we have the entire UI for iOS done with Storyboard or XIB. I tried to add ViewController and Storyboard to a simple project. Using `xcsync-generate` in this case, created `h/m` files, but creating outlets and synchronizing via `xcsync-sync` didn't pull anything up in the .net project. Also the `xcSyncVerbosity` property seems to do nothing because the Detailed value gives the same output in the terminal as `Normal`

@dimysa, Thanks for the reply, given @andrews4s's post from above, would you expect that there would be a `Main.h` file to correspond to the `Main.storyboard`? As for `/t:xcsync-sync` not syncing back to the .NET project, what project type did you start with so I can try to reproduce this issue? The default verbosity level is `Detailed` right now when executed through the `dotnet build` command. To get more detail you would have to use the `Diagnostic` level.

**Comment by andrews4s** [comment] 2024-09-05 15:21
> @andrews4s, thanks for the detailed explanation. I see from the screenshots that the ViewController.h and ViewController.m files are generated correctly and present in the project but aren't registered correctly as compile items. We will investigate this. Once you manually fixed the project, can you create the Actions/Outlets and then use the `dotnet build mactest2.csproj /t:xcsync-generate` to have the changes synced back to the dotnet project?

I tried adding a button and outlet to it. Everything works as expected in Xcode, but no .cs files changed and no error messages when I tried syncing back.
dotnet build mactest2.csproj /t:xcsync-sync /p:xcSyncVerbosity=Diagnostic
>Restore complete (0.9s)
>
>Build succeeded in 15.8s

**Comment by mcumming** [comment] 2024-09-10 20:59
@andrews4s We have internal tests that validate the `/t:xcsync-sync` command is working as expected. Can you send me a diff of the changes you made to the project before you tried to run  the sync command? I'd would like to reproduce your experience so I can provide a fix. Either a gist or pasted here is fine.

**Comment by andrews4s** [comment] 2024-09-10 21:34
> @andrews4s We have internal tests that validate the `/t:xcsync-sync` command is working as we expect it to. Can you send me a diff of the changes you made to the project before you tried to run the sync command? I'd would like to reproduce your experience so I can provide a fix. Either a gist or pasted here is fine.

Diff of the xcode project from the initial generation to after fixing the compile sources and adding an outlet.
https://gist.github.com/andrews4s/b70dc6bc73943d409034174a5c18aa7e

Attached the project if needed.
[mactest2.zip](https://github.com/user-attachments/files/16955138/mactest2.zip)

**Comment by andrews4s** [comment] 2024-09-11 06:06
@mcumming It looks like Xcode minified the pbxproj and messed up the diff of that file. I regenerated the project again with xcsync and diffed that after manually fixing it to get a more clear view of those changes.
https://gist.github.com/andrews4s/7a0bd60e7012d98da160efac26f5d931

**Comment by mcumming** [comment] 2024-09-11 16:55
Thanks @andrews4s, I will look into it.

**Comment by FreakyAli** [comment] 2024-09-19 13:22
@maddymontaquila  @mcumming  Any updates yet guys? VSM is already been retired for almost a month now, and VS for MAC itself did not support this...

**Comment by songsofwingspan** [comment] 2024-09-21 11:57
and what about regular VS 22 for Windows? This is also a proposed option after the sundown of VS4M (https://learn.microsoft.com/en-us/visualstudio/releases/2022/what-happened-to-vs-for-mac).

I am able to open storyboard files out of VS 22 on my paired Mac but no syncing in the background. even the temporary Xcode project is not created (with the corresponding .h and .m files for creating IB outlets)

**Comment by mcumming** [comment] 2024-09-24 14:23
> @maddymontaquila @mcumming Any updates yet guys? VSM is already been retired for almost a month now, and VS for MAC itself did not support this...

Hi @FreakyAli This is the latest update we have at this moment: https://github.com/dotnet/core/blob/main/release-notes/9.0/preview/preview7/dotnetmaui.md#xcode-sync-for-cli-and-visual-studio-code, was there something specific you are interested in knowing about?

**Comment by mcumming** [comment] 2024-09-24 14:29
> and what about regular VS 22 for Windows? This is also a proposed option after the sundown of VS4M (https://learn.microsoft.com/en-us/visualstudio/releases/2022/what-happened-to-vs-for-mac).
> 
> I am able to open storyboard files out of VS 22 on my paired Mac but no syncing in the background. even the temporary Xcode project is not created (with the corresponding .h and .m files for creating IB outlets)

Hi @songsofwingspan,
Since editing storyboard files (adding/removing IBOutlets and IBActions) requires Xcode, our focus is on improving that experience on a Mac machine first. We are investigating options for editing Xcode specific files from a Windows machine, but there are no concrete plans for changing the current experience.

**Comment by mcumming** [comment] 2024-10-17 18:34
Hello,
Wanted to provide an update for everyone here. We have a [new location for filing issues](https://github.com/dotnet/xcsync/issues) for the new `xcsync` tool. I am going to close this issue soon in favor of the new location. 

With the new location comes a few more changes. 
1. The `xcsync` tool is now open source licensed under the MIT license.
2. It is now a .NET Global Tool so you don't have to execute it through the cumbersome `dotnet build /T:XXX` command.

**Comment by ggbtvs** [comment] 2024-11-01 15:03
> Hello, Wanted to provide an update for everyone here. We have a [new location for filing issues](https://github.com/dotnet/xcsync/issues) for the new `xcsync` tool. I am going to close this issue soon in favor of the new location.
> 
> With the new location comes a few more changes.
> 
> 1. The `xcsync` tool is now open source licensed under the MIT license.
> 2. It is now a .NET Global Tool so you don't have to execute it through the cumbersome `dotnet build /T:XXX` command.

where is the source code for the xcsync?

**Comment by mcumming** [comment] 2024-11-07 03:54
> > Hello, Wanted to provide an update for everyone here. We have a [new location for filing issues](https://github.com/dotnet/xcsync/issues) for the new `xcsync` tool. I am going to close this issue soon in favor of the new location.
> > With the new location comes a few more changes.
> > 
> > 1. The `xcsync` tool is now open source licensed under the MIT license.
> > 2. It is now a .NET Global Tool so you don't have to execute it through the cumbersome `dotnet build /T:XXX` command.
> 
> where is the source code for the xcsync?
Hi @ggbtvs ,
The source for xcsync is in the same repository I linked for filing issues: https://github.com/dotnet/xcsync/

**Closed by mcumming** 2024-11-07 03:54 UTC
Labels: enhancement, triaged, area-maui, vs-sync, vs-syncd
