### ISSUE TITLE
[SUGGESTION] make it more user friendly

### ISSUE THREAD

**Issue by Nemonek** [microsoft/vscode-dotnettools#243] opened 2023-07-11 21:31 UTC
### Describe the feature you'd like

I'd like doing '_dotnet run_' like I do for console apps to run a maui app, but right now it doesn't work; for this solution explorer thing, please, add the option '_add reference_' because it's not user friendly at all; the run without debug done on a solution start the program in the debug console, and it's completely unusable cause it's read only.
Last, please, add something more easy to understand that having to install tons of ectensions.

**Comment by webreidi** [comment] 2023-07-11 23:20
Add reference request is a dup of https://github.com/microsoft/vscode-dotnettools/issues/47 and https://github.com/microsoft/vscode-dotnettools/issues/62.

**Comment by maddymontaquila** [comment] 2023-07-13 18:53
`dotnet run` instead of `dotnet build -t:Run` is a feature request for the SDK itself - I believe it is similar or a dupe of https://github.com/dotnet/sdk/issues/31253

**Comment by mauroa** [comment] 2024-03-19 16:48
Closing since there are already issues/tickets opened on other repos (and linked here) about the suggestions made in this issue description, so this is in fact a duplicate of all those other issues. There's no action item to do on the VS Code MAUI extension side for now around this.

**Closed by mauroa** 2024-03-19 16:48 UTC
Labels: duplicate, enhancement, area-maui
