### ISSUE TITLE
F12 Goto Definition goes to a compiled view not the source

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode-dotnettools#41] opened 2023-06-07 13:21 UTC
Type: <b>Bug</b>

Before I upgraded to the C# Dev Kit I would F12 Goto Definition on a class and it would take me to the source using the normal omnisharp c# extension. Since the upgrade I now get a decompiled view of the file 

So I see this: 

```cs
#region Assembly core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null 

// /Users/solrevdev/Projects/solution/src/Core/obj/Debug/net7.0/ref/core.dll
```

And not the actual source file. This has started happening since I upgraded to Dev Kit

Extension version: 0.1.83
VS Code version: Code - Insiders 1.79.0-insider (aee52551e25d98391f9064996196cd83a9fc8669, 2023-06-06T15:02:30.317Z)
OS version: Darwin arm64 22.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 4833a52a-ed11-4d5d-b549-6ace2400b2b2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyind779:30611226
pythonsymbol12:30651887
a9j8j154:30646983
showlangstatbar:30737417
pythonms35:30671666
03d35959:30757351
7ij38806:30687742
pythonfmttext:30716741
pythoncmvfstr:30726892
fixhidewlkth:30724384
showsbindicator:30724477
pythongtdpath:30726887
pythonnosmt12:30757129

```

</details>

**Comment by DanHorrocksBurgess** [comment] 2023-06-07 13:56
I also experience the same problem as @solrevdev - when using F12 / Go to definition I don't navigate to the actual source file rather a Decompiled Metadata version of the file.

**Comment by timheuer** [comment] 2023-06-07 14:22
Closing as dupe of #40 -- let's use that to track

**Closed by timheuer** 2023-06-07 14:22 UTC
