### ISSUE TITLE
Go to Definition does not work within package references

### ISSUE THREAD

**Issue by jesperkristensen** [microsoft/vscode-dotnettools#256] opened 2023-07-14 06:54 UTC
Type: <b>Bug</b>

1. Create a new web project and solution
2. Open Program.cs
3. Select WebApplication and press F12
3. An editor opens with metadata for WebApplication
4. Select IHost or any other type in the editor and press F12
5. Expected result: An editor with metadata for IHost should open
6. Actual result: Message "No definition found for 'IHost'" is displayed

This worked with only the C# extension installed, but stopped working when I installed the C# Dev Kit extension

![image](https://github.com/microsoft/vscode-dotnettools/assets/548890/a1c41fa4-068e-41e9-a1a0-9dd80d8d0524)

Extension version: 0.3.2
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Windows_NT x64 10.0.20348

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|47.67GB (13.46GB free)|
|Process Argv|--file-uri vscode-remote://ssh-remote%2BREDACTED/c%3A/rcc.code-workspace --crash-reporter-id e1474425-8a00-4ec8-8364-fe51656c778f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: REDACTED|
|OS|Windows_NT x64 10.0.20348|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (6 x 2688)|
|Memory (System)|19.53GB (9.14GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30789497
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30785052
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
h7j2d465:30786200
dsvsc013cf:30789518

```

</details>

**Comment by arkalyanms** [comment] 2023-08-17 21:23
> This worked with only the C# extension installed, but stopped working when I installed the C# Dev Kit extension

Fyi

**Comment by tmeschter** [comment] 2023-08-21 20:34
@jesperkristensen Are you still seeing this issue on newer versions of the C# Dev Kit extension? If so, can you provide the contents of the "Project" output window?

**Comment by jesperkristensen** [comment] 2023-08-22 16:59
@tmeschter I still see it with C# Dev Kit v0.4.5 and C# 2.0.376.

"Projects" output is this:

```
2023-08-18 13:01:09.104 [info] Project system initialization finished. 11 project(s) are loaded, and 0 failed to load.
2023-08-22 15:26:48.662 [info] Project system initialization finished. 12 project(s) are loaded, and 0 failed to load.
2023-08-22 18:15:36.776 [info] Project system initialization finished. 1 project(s) are loaded, and 0 failed to load.
```

**Comment by NickReinlein** [comment] 2023-08-25 14:11
+1 I have this same error. Latest version on Linux Mint 21 5.4.12
Both the normal release of C# dev kit v0.3.21 and the pre-release version of v0.4.6 both have the same issue. Restarting the language server does not help. Relaunching vscode and re-opening the project doesn't help.

Let me know if you want me to include any logs

---------
Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.2.0-26-generic

**Comment by tmeschter** [comment] 2023-08-28 16:32
Oh, I somehow missed that this was "Go to Definition" _from_ a metadata-as-source view.

**Comment by tmeschter** [comment] 2023-08-28 17:12
Moving to area-roslyn per a conversation with @dibarbet.

**Comment by dibarbet** [comment] 2023-09-19 18:39
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5787

**Closed by dibarbet** 2023-09-19 18:39 UTC
Labels: bug, triaged, area-roslyn
