### ISSUE TITLE
iOS Provisioning Support

### ISSUE THREAD

**Issue by jingliancui** [microsoft/vscode-dotnettools#1589] opened 2024-11-07 12:17 UTC
### Describe the feature you'd like

https://learn.microsoft.com/en-us/dotnet/maui/ios/device-provisioning/automatic-provisioning?view=net-maui-8.0
https://learn.microsoft.com/en-us/dotnet/maui/ios/device-provisioning/manual-provisioning?view=net-maui-8.0

As a VS code user, I want it can support iOS provisioning.
So that I can:
1. Debug the app in real iOS device on Mac with VS Code.
2. Without depend on Windows' Visual Studio.

### Environment Information

macOS

**Comment by keylime-unicorn** [comment] 2024-11-07 20:21
Closing as duplicate of [#1539](https://github.com/microsoft/vscode-dotnettools/issues/1539).

**Closed by keylime-unicorn** 2024-11-07 20:21 UTC
Labels: enhancement, area-maui
