### ISSUE TITLE
The type or namespace name 'App' could not be found

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#1184] opened 2024-06-08 01:33 UTC
Type: <b>Bug</b>

1. open a Blazor project (of any description)
2. randomly, you will receive the titled Error in the Problems window
3. the project compiles, runs and debugs fine.
4. it will eventually go away (especially after restarting vscode) -- but it always comes back.

Extension version: 1.6.8
VS Code version: Code 1.90.0 (89de5a8d4d6205e5b11647eb6a74844ca23d2573, 2024-06-04T19:33:54.889Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.38GB free)|
|Process Argv|--folder-uri file:///d%3A/source/2010solutions/VisitingAngels/VisitingAngelsAdmin --crash-reporter-id c8e3650d-a133-42e9-901c-3aa8e8465629|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelc:31048052
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
pythonprt:31056678
dwnewjupyter:31046869
26j00206:31048877

```

</details>

**Comment by burtonrodman** [comment] 2024-06-08 01:35
before you even ask... no I can't provide a project that reproduces the issue... it happens in EVERY project at some point without any discernable pattern.  screenshot:

![image](https://github.com/microsoft/vscode-dotnettools/assets/7658657/1b0a0465-c277-4302-a4a8-b2120b79f685)

**Comment by Octanoz** [comment] 2024-07-22 14:07
Any updates / root cause found / work-arounds? I'm finding that this week dotnet watch can't run with this error present anymore, dotnet build fails and, so far, restarting VS Code hasn't made it go *poof* either

**Comment by ryzngard** [comment] 2024-08-12 16:43
This should be resolved with `v2.39.29`. Depending on project size you may hit https://github.com/dotnet/razor/issues/10600 , but once things "settle" they shouldn't stop working. 

Let me know if you're still hitting this issue and thanks for reporting!

**Closed by ryzngard** 2024-08-12 16:43 UTC
Labels: bug, area-razor
