### ISSUE TITLE
Maui - iOS project with extensions pushes/runs extension instead of appt

### ISSUE THREAD

**Issue by b12kab** [microsoft/vscode-dotnettools#1681] opened 2024-12-11 13:32 UTC
Type: <b>Bug</b>

**Describe the Issue**
Incorrect launch/run of app with extensions to iOS simulator using VS Code.

**Expected Behavior:**
When an app with extensions is launched/run that the app is pushed to the device, and the app runs.

**Actual:**
When project with extensions is launched/run from Rider with a destination of iOS simulator, it pushes the app to the simulator and when app is run it runs without issue.

When project with extensions is launched/run from VC to a iOS simulator, it publishes the extension to the simulator and when extension is run, it crashes.

As this runs in Rider properly, this appears to be an issue with VS Code extension.

**Steps To Reproduce**
Repro project: https://github.com/b12kab/vc_ios_exception_exception
Create Debug Identifiers & Profiles.
Click run.
App builds, extension (instead of app) is deployed to simulator.
Extension is launched and crashes on simulator.
[In case it helps, debug console window contents](https://github.com/user-attachments/files/18096292/vc_debug_console_window_output.txt)
[Also in case it helps, Maui Workload used .net 8 SR5](https://github.com/user-attachments/files/18096320/workload.8.0.40.SR5.json)

Extension version: 1.6.16
VS Code version: Code 1.95.3 (Universal) (f1a4fb101478ce6ec82fe9627c43efbf9e98c813, 2024-11-13T14:50:04.152Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (11 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|36.00GB (0.80GB free)|
|Process Argv|--crash-reporter-id ce471525-5abd-4b6c-a424-32f4f48194fc|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by emaf** [comment] 2024-12-11 20:24
Closing as duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1403.

**Closed by emaf** 2024-12-11 20:24 UTC
Labels: area-maui
