### ISSUE TITLE
[SUGGESTION] Sync with active document

### ISSUE THREAD

**Issue by anvar-ramazanov** [microsoft/vscode-dotnettools#263] opened 2023-07-14 13:10 UTC
### Describe the feature you'd like

When you are working in VS22 there is a function `Sync with active document`:

<img width="359" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5313099/bcec24d0-9a84-4a7c-8043-caf3de4fcf44">

For vscode there is `Reveal in explorer view`: 

<img width="200" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5313099/4ea8ba75-c591-43d0-90c1-1ce80d326295">

But I didn't find how to synchronize active tab in Solution Explorer in C# DevKit Extension. 

 Could we consider to add such functionality? 

### Alternatives considered

When you are working in VS22 there is a function `Sync with active document`:

<img width="359" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5313099/bcec24d0-9a84-4a7c-8043-caf3de4fcf44">

For vscode there is `Reveal in explorer view`: 

<img width="200" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5313099/4ea8ba75-c591-43d0-90c1-1ce80d326295">

But I didn't find how to synchronize active file in Solution Explorer in C# DevKit Extension.

**Comment by smitpatel** [comment] 2023-07-14 17:43
duplicate of #180

**Comment by timheuer** [comment] 2023-07-14 18:35
Closing as dupe of #51 and #180

**Closed by timheuer** 2023-07-14 18:35 UTC
Labels: duplicate, enhancement
