### ISSUE TITLE
On Create New Project Continuously Opening Select Folder

### ISSUE THREAD

**Issue by devraj102** [microsoft/vscode-dotnettools#216] opened 2023-07-01 03:40 UTC
Type: <b>Bug</b>

When I am creating a new project in vs code using the C# dev kit and selecting a project template then it asks for a select folder and after specifying a folder it again opens the select folder pop up and that is happening in a loop unit I didn't click on cancel.

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by smitpatel** [comment] 2023-07-05 22:18
Duplicate of #42

**Closed** 2023-07-06 23:20 UTC
Labels: area-templates
