### ISSUE TITLE
[BUG] This extension uses embedded .net runtime instead of system-wide

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode-dotnettools#20] opened 2023-06-06 21:42 UTC
### Describe the Issue

I have a .NET runtime (6.0 and 7.0) installed system-wide using dotnet-install.sh script into /usr/share/dotnet directory which is also added to PATH, but this extension still downloads a separate .NET runtime to /home/user/.config/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.5/dotnet and uses it onstead of system-wide one.

### Steps To Reproduce

1. Install Visual Studio Code on Arch Linux
2. Install .NET SDK using `dotnet-install.sh` to /usr/shart/dotnet and add it to PATH
3. Install pre-release version of C# extension
4. Open any .NET project and see that a separate version of runtime is downloading

### Expected Behavior

Extension uses system-wide installed version of .NET runtime

### Environment Information

- OS: Arch Linux
- VScode version: 1.78.2
- .Net version:
  ```
  dotnet --list-sdks
  6.0.408 [/usr/share/dotnet/sdk]
  7.0.302 [/usr/share/dotnet/sdk]
  ```
- Extension version: v2.0.206

**Comment by Igorgro** [comment] 2023-06-06 22:03
I also tried this advice https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md#manually-installing-net, but it didn't help

**Comment by AArnott** [comment] 2023-06-08 22:41
This is by design as far as C# Dev Kit is concerned. We rely on the .NET Runtime Acquisition VS Code extension to get the runtime that our .NET processes require. Where it gets the runtime from or installs it to is out of scope for this particular repo. I see you've already found the repo that hosts that extension, so this is fair feedback to send their way.

Thank you for using our new extension and sending feedback!

**Closed by AArnott** 2023-06-08 22:41 UTC
Labels: bug, triaged, area-sdk
