### ISSUE TITLE
 Project system data flow 'Source: 50160389' closed because of an exception

### ISSUE THREAD

**Issue by mamamiawhatacode** [microsoft/vscode-dotnettools#167] opened 2023-06-19 11:22 UTC
Type: <b>Bug</b>

=====================
6/19/2023 1:09:37 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Source: 50160389' closed because of an exception.
missingBuildCount >= 0 (missingBuildCount >= 0)
---> (Inner Exception #0) Microsoft.Assumes+InternalErrorException: missingBuildCount >= 0
   at Microsoft.Assumes.Fail(String message)
   at Microsoft.Assumes.True(Boolean condition, String message)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__PopulateMissingBuildData|5(<>c__DisplayClass5_1&)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__ComposeItemUpdates|2()
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.<TryUpdate>g__ProcessAddsAndUpdates|0()
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.TryUpdate(IProjectChangeDescription evaluationProjectChange, IProjectChangeDescription buildProjectChange, String projectFullPath, Nullable`1& dependencies)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>g__Transform|6_1(IProjectSubscriptionUpdate update)
   at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue`1 projectVersionedValue, Func`2 transform)
   at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>b__6_0(IProjectVersionedValue`1 u)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformBlockSlimSync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 
===================

Extension version: 0.1.103
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (21.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kvenkatrajan** [comment] 2023-06-20 17:13
Thanks for your feedback. The root cause is a Duplicate of #22 and a fix is underway and being tested.

**Comment by smitpatel** [comment] 2023-06-28 17:10
The fix is available in v0.2.99

**Closed by smitpatel** 2023-06-28 17:10 UTC
Labels: bug, area-project, fixed (release pending)
