### ISSUE TITLE
[BUG] MSTest test project isn't detected

### ISSUE THREAD

**Issue by aaronpowell** [microsoft/vscode-dotnettools#70] opened 2023-06-08 05:18 UTC
### Describe the Issue

I'm trying to add a devcontainer to https://github.com/Azure/data-api-builder so I created a basic .NET container (branch here: https://github.com/Azure/data-api-builder/tree/aaronpowell/devcontainers).
When opening in the devcontainer C# Dev Kit fails to display the tests in the solution, with the following log error:

```
Created Test Controller
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/6.0.408].
Initialized Test Explorer Server [3030]
Test Store Folder: /home/vscode/.vscode-server-insiders/data/User/workspaceStorage/6736c141923b9b9715f8214c4605830e/ms-dotnettools.csdevkit
Test data store opened in 0.016 sec.
Initialized project system provider.
1 projects added, 0 changed, 0 removed.
========== Starting test discovery ==========
========== Test discovery finished: 2421 Tests found in 2.5 sec ==========
2421 tests discovered from /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll in 2459.3669 ms
Tests changed, running test discovery: /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll
========== Starting test discovery ==========
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.StringEx' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
No test is available in /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 487.7 ms ==========
0 tests discovered from /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll in 487.7309 ms
```

### Environment Information

- OS: Windows 11, but using WSL2 + Remote Containers
- VS Code:

```
Version: 1.79.0-insider (user setup)
Commit: b380da4ef1ee00e224a15c1d4d9793e27c2b6302
Date: 2023-06-07T14:26:54.152Z
Electron: 22.5.5
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
```

Here's the .NET SDK and runtime info:

```
vscode ➜ /workspaces/data-api-builder/src (aaronpowell/devcontainers) $ dotnet --list-sdks
6.0.408 [/usr/share/dotnet/sdk]
vscode ➜ /workspaces/data-api-builder/src (aaronpowell/devcontainers) $ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by timheuer** [comment] 2023-06-08 23:40
I think a dupe of #28 -- @aaronpowell do you have your build output going in a specific outdir? /cc @peterwald

**Comment by aaronpowell** [comment] 2023-06-09 00:36
> I think a dupe of #28 -- @aaronpowell do you have your build output going in a specific outdir? /cc @peterwald

Ah, I tried to search for possible dupes!

Yes, the output goes to a custom directory - https://github.com/Azure/data-api-builder/blob/aaronpowell/devcontainers/src/Cli.Tests/Cli.Tests.csproj#L8

**Comment by timheuer** [comment] 2023-06-09 22:10
Closing as dupe of #28

**Closed by timheuer** 2023-06-09 22:10 UTC
Labels: bug, duplicate, area-test

**Comment by peterwald** [comment] 2023-06-12 14:09
@aaronpowell I believe the problem is that the dotnet 7 SDK (or newer) needs to be installed for this to work.

**Comment by timheuer** [comment] 2023-06-12 14:11
> @aaronpowell I believe the problem is that the dotnet 7 SDK (or newer) needs to be installed for this to work.

Ah if this is the case, this is another indicator of how a remote isn't getting the acquisition of the right bits for us (the host here where VSCode is installed starts fine, but the devcontainer doesn't have the right runtime needed).  @aaronpowell would be a quick validation to change the devcontainer to a 7.0SDK base and see.

**Comment by aaronpowell** [comment] 2023-06-12 23:59
@peterwald  Just added the .NET 7 SDK to the devcontainer:

```
vscode ➜ /workspaces/data-api-builder (aaronpowell/devcontainers) $ dotnet --list-sdks
6.0.408 [/usr/share/dotnet/sdk]
7.0.302 [/usr/share/dotnet/sdk]
vscode ➜ /workspaces/data-api-builder (aaronpowell/devcontainers) $ dotnet --list-runtimes
Microsoft.AspNetCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.16 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

Then restarted VS Code and still nothing:

```
Created Test Controller
Using vstest from dotnet sdk in [/usr/share/dotnet/sdk/7.0.302].
Initialized Test Explorer Server [1166]
Test Store Folder: /home/vscode/.vscode-server-insiders/data/User/workspaceStorage/6736c141923b9b9715f8214c4605830e/ms-dotnettools.csdevkit
Test data store opened in 0.166 sec.
Initialized project system provider.
2 projects added, 0 changed, 0 removed.
========== Starting test discovery ==========
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.StringEx' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
No test is available in /workspaces/data-api-builder/src/out/tests/net6.0/Cli.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
An exception occurred while test discoverer 'MSTestDiscoverer' was loading tests. Exception: Could not load type 'Microsoft.VisualStudio.TestTools.UnitTesting.StringEx' from assembly 'Microsoft.VisualStudio.TestPlatform.TestFramework, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
No test is available in /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
========== Test discovery finished: 0 Tests found in 719.7 ms ==========
0 tests discovered from /workspaces/data-api-builder/src/out/tests/net6.0/Azure.DataApiBuilder.Service.Tests.dll;/workspaces/data-api-builder/src/out/tests/net6.0/Cli.Tests.dll in 719.678 ms
```

**Comment by aaronpowell** [comment] 2023-06-13 00:02
Scratch that - did a `dotnet clean` and removed the `out` folder (the custom build output location) then `dotnet build` and the tests are picked up again.

I assume that it needs something from the .NET 7 SDK that comes in the build phase? We have a `global.json` that pins to .NET 6, so I would've expected that to take priority.
