### ISSUE TITLE
[BUG] All local and 3rd party components in blazer app razor files are red with no editor support after update.

### ISSUE THREAD

**Issue by Asdfg75** [microsoft/vscode-dotnettools#990] opened 2024-03-13 16:00 UTC
### Describe the Issue

Just updated to:
C# v2.22.3
C# Dev Kit v1.4.29

All components in razor files are now red.
Looks like all razor support is broken.

Was working before update with the exception that I had to open every dependent razor component for them to be recognized in parent file.

### Environment Information

About VSCode:
Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:21:31.043Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin x64 23.4.0

**Comment by rizchaerul** [comment] 2024-03-13 16:08
same here

**Comment by Asdfg75** [comment] 2024-03-13 16:39
I rolled back to C# v2.15.30 and red issue went away.

Problem is present on C# v2.22.3 and previous version C# Dev Kit. This may be an issue with C# v2.15.30.

I reported there a few minutes ago.

**Comment by purple-zz** [comment] 2024-03-13 21:14
I get this on Windows, but everything works on my Mac. Had to downgrade C# extension to get everything working on Windows, but my Mac has 2.22.3 version and it works just fine. I even tried the preview version of vs code which uses its own directories for settings and so on but that was as broken with the latest versions as the regular one.

**Comment by ryzngard** [comment] 2024-03-15 00:55
Confirmed with a local project on windows. Investigating

![image](https://github.com/microsoft/vscode-dotnettools/assets/475144/ab52e038-10a9-42c7-a925-dfbdb14f468e)

**Comment by ryzngard** [comment] 2024-03-15 02:43
This looks like https://github.com/dotnet/razor/issues/10007 , which is fixed and will be in the next release. To verify, I used a new fluent ui app for blazor. Manually adding the namespace to each page fixes this issue for me locally. 

Please let me know if that fix does not resolve the issue for you. We hope to have it available soon

**Closed by ryzngard** 2024-03-15 02:43 UTC
Labels: bug, area-razor
