### ISSUE TITLE
Xcode sync designer.cs files to VS Code

### ISSUE THREAD

**Issue by JDELAOKELLER** [microsoft/vscode-dotnettools#681] opened 2023-11-02 19:07 UTC
### Describe the feature you'd like

Currently for Xamarin.IOS Visual Studio generates automatically a project in xcode while opening a XIB or storyboard file when a property is changed in Xcode automatically the designers files are updated in Visual Studio for Mac, this feature I've not seen in VSCode with Maui, C# Dev Kit or any .net Extension.

### Alternatives considered

Other alternatives is using Rider but its license will represent an additional cost for my company where developers already have their MSN subscriptions to Visual Studio.

### Environment Information

MACOS Sonoma
XCode 14
Visual Studio Code
.NET MAUI
C# Dev Kit

**Comment by mcumming** [comment] 2023-11-28 13:00
Duplicate of #571

**Closed by mcumming** 2023-11-28 13:00 UTC
Labels: enhancement, area-maui, mac
