### ISSUE TITLE
[SUGGESTION] Add NuGet package reference management to C# Dev Kit, too

### ISSUE THREAD

**Issue by DaRosenberg** [microsoft/vscode-dotnettools#62] opened 2023-06-07 22:01 UTC
### Describe the feature you'd like

Now that we have Solution Explorer and Test Explorer (ish), the one remaining key missing component is a NuGet package reference management in VS Code.

Minimum functionality:

- List installed packages at solution or project level
- List outdated packages at solution or project level, and bulk upgrade
- Browse for packages and add package references at project level

**Comment by arkalyanms** [comment] 2023-06-07 23:33
cc: @kartheekp-ms as well.

**Comment by JonDouglas** [comment] 2023-06-08 12:11
Thank you for filing an issue!

We have **four main concepts** for this area. Here are some mockups that we would love community feedback on. I won't go into too many details, but there would potential to share the first two options across VS products(Think having the same experience in VS, VS Code, etc). The latter two options are VS-code specific.

1. List WebView 👍:

![image](https://github.com/microsoft/vscode-dotnettools/assets/1288848/02ee3df3-f10f-4451-a13a-d9e6797fda62)

2. Tabs WebView ❤️:

![image](https://github.com/microsoft/vscode-dotnettools/assets/1288848/6abe8c3c-73de-4985-978b-e57cdf73005f)

3. Extensions View 🚀:

![image](https://github.com/microsoft/vscode-dotnettools/assets/1288848/b0b28c0e-1d32-4d7b-b4c7-238f4d5d154e)

4. Tree View 🎉:

![image](https://github.com/microsoft/vscode-dotnettools/assets/1288848/dcb1c2a7-c0be-4762-a272-495d2206f958)

Help us vote by using the appropriate reaction to this comment! (1.👍, 2.❤️, 3.🚀, 4.🎉)

**Comment by DaRosenberg** [comment] 2023-06-08 15:16
Much better @JonDouglas - thanks.

While I am generally partial to platform fidelity (and therefore in theory like the idea of using native VS Code UI paradigms wherever possible) in this case I must say I really prefer the first two because they just seem less constrained, a lot more functionally rich and generally much more usable.

In terms of list vs. tabs, **tabs is the clear winner IMO** and gets my vote.

Rarely (ever?) is there any value in seeing all those categories of dependencies in the same list simultaneously IMO. Separating these categories into tabs makes for a clearer overview, better progressive reveal, and also gives you more flexibility to vary the rest of the UI based on which tab is currently selected. For example, in the "updates" tab you could show a checkbox on each dependency and an action to update all selected ones.

But - either would be a huge step up from what we have today! 😁 

The separation of direct vs. transitive is awesome btw — not even in VS do we have that! 👍🏻

**Comment by JonDouglas** [comment] 2023-06-20 15:11
Thanks @DaRosenberg.

We have heard plenty of feedback regarding tabs vs. lists. We will also look into the feasibility of enabling different view-modes based on user preferences. We do know that our VS users love the tabs approach commonly found in many VS package/extension/etc management experiences, but we also want to keep our ears and eyes open for approaches used by the industry as a whole.

For what it is worth the separation of direct vs. transitive has been an experiment that finalized recently and will be enabled for all next Visual Studio release. We sadly ran into some significant performance regressions that needed to be resolved before we rolled it out to all.

https://devblogs.microsoft.com/nuget/introducing-transitive-dependencies-in-visual-studio/

**Comment by mamamiawhatacode** [comment] 2023-06-21 12:35
That would be awesome, IMO List WebView and Tabs WebView are beatiful. Looking forward to this in vscode.

**Comment by kblok** [comment] 2023-08-30 18:25
`Extensions View` looks beautiful but I'm concern about how would that look if you have to manager many different projects. Tabs view is quite close to what VS offers.

**Comment by Leonardo-Ferreira** [comment] 2023-10-10 20:30
one thing the could be VERY useful is the organization of VS for MAC:
![image](https://github.com/microsoft/vscode-dotnettools/assets/5585339/21259e71-43f5-4a9c-8889-2689f7a46dc2)

I absolutely love that green "arrow up" which indicates that there is a update to that nuget package

**Comment by tmeschter** [comment] 2023-11-16 19:13
Removing area-project as this will be driven from the NuGet side.

**Comment by TanvirArjel** [comment] 2023-12-22 16:18
Any update on this? This is the most wanted feature for C# Dev Kit.

**Comment by TanvirArjel** [comment] 2024-01-11 00:00
@JonDouglas You took the survey 7 months ago but still no update on progress!

**Comment by JonDouglas** [comment] 2024-02-01 20:56
We're working on an initial Visual Studio Code NuGet package management experience including command palette flows and integration with C# Dev Kit. It covers the initial experiences for adding, removing, and updating a NuGet package. 

To provide your feedback, please go to: https://github.com/NuGet/Home/pull/13208

**Comment by TanvirArjel** [comment] 2024-02-01 23:07
This means the following view is not happening anytime soon: ☹️

![image](https://github.com/microsoft/vscode-dotnettools/assets/14342773/2c7070e1-570c-4ee7-b7f2-5911894a95fa)

**Comment by JonDouglas** [comment] 2024-02-02 00:20
@TanvirArjel The team is working towards an initial NuGet experience. Please be sure to provide your feedback.

**Comment by Meligy** [comment] 2024-02-08 21:39
@JonDouglas 
Option 2 is the best IMO
![image](https://github.com/microsoft/vscode-dotnettools/assets/171637/83a33194-b91f-4c21-9831-40e74ecd5e0e)

One thing that classic VS uniquely excels at is consolidation. I'd love to see this in VS Code (and SDK if possible, but VS Code is more important as I use it on Mac, etc.).

**Comment by TanvirArjel** [comment] 2024-03-13 21:49
@JonDouglas Hi, I noticed that the merge request https://github.com/NuGet/Home/pull/13208 has been merged, but the functionality is still not available. Could you please provide an update on when it will be available? Thank you.

**Comment by michael-hawker** [comment] 2024-03-13 23:39
Really like the prototypes that show the consolidated lists (list, tree, extensions).

That's my biggest gripe with the existing Visual Studio view is that I have to already be changing context to view different pieces vs. getting the general overview. Especially when I go to search for a package to add and then I don't see anything because I'm in my 'installed' tab vs. 'browse'.

Would love to see a new experience tried here to get something fresh and compare against the 'classic' VS design here.

**Comment by kazo0** [comment] 2024-03-28 11:32
Love, **Love**, **_LOVE_** the ability to handle NuGet packages through the command palette now thanks to https://github.com/NuGet/Home/pull/13208. Not sure where the best place is for feedback but the only thing I would like to see through the command palette experience is some way to select multiple projects that a NuGet package should be added to. Unless I have missed this and it's already possible

Thank you!

**Comment by arkalyanms** [comment] 2024-03-28 15:49
@jebriede fyi

**Comment by evgenyvalavin** [comment] 2024-05-08 08:39
I'm not sure where to link this
https://github.com/NuGet/Home/issues/13429

**Comment by webreidi** [comment] 2024-09-04 22:43
Closing this initial experience issue. See https://github.com/microsoft/vscode-dotnettools/issues/1137 to follow the next steps for NuGet in C# Dev Kit.

**Closed by webreidi** 2024-09-04 22:43 UTC
Labels: enhancement, triaged, area-nuget, fixed-pending-release

**Comment by JonDouglas** [comment] 2024-09-05 19:29
here is a specific issue for GUI support & I jotted down some ideas on what it could be based on previous concepts:

https://github.com/microsoft/vscode-dotnettools/issues/1435
