### ISSUE TITLE
[BUG] Razor Language Server does not recognize default components and namespaces when using ÅÄÖ somewhere in the projects directory-path

### ISSUE THREAD

**Issue by 88jonhan** [microsoft/vscode-dotnettools#980] opened 2024-03-08 09:50 UTC
### Describe the Issue

When using special characters somewhere in the directory path (in my testcase a folder called TestÅÄÖ), the razor languages server stops recognizing default components in VS Code.
![bild](https://github.com/microsoft/vscode-dotnettools/assets/145433598/39544a76-bebd-4620-8160-6f783697dd4f)
![bild](https://github.com/microsoft/vscode-dotnettools/assets/145433598/fd0e9e93-9056-4f41-8938-f509c3aab4f9)
![bild](https://github.com/microsoft/vscode-dotnettools/assets/145433598/580739af-fbdd-481f-989b-de6fbc7cb906)

The project builds without error. 

Razor logfile:
[razorlog.txt](https://github.com/microsoft/vscode-dotnettools/files/14536397/razorlog.txt)

Works fine when the path does not contain special characters.
One small detail that might or might not matter: the "project.razor.vscode.bin" file that the language server creates is 2kb smaller in the project that contains special characters in its path.

### Steps To Reproduce

1. Create folder with special characters (eg. å, ä or ö) in the name
2. Open CLI in said folder
3. dotnet new blazor -o BlazorTest
4. Open VS Code in BlazorTest-folder
6. Wait until "project.razor.vscode.bin" is created in "/obj/Debug/net8.0/"

VS Code wont recognize BlazorTest.Components-namespace in Program.cs.
Components in .razor-files wont be recognized.

### Expected Behavior

I expected VS Code to recognize the default Components-namespace, as it does when I do the same steps in a directory-path not containing special characters. 
As åäö are frequently used in other languages I expected the Razor Language Server not care wether I used it or not

### Environment Information

-OS: 
Windows 11 Pro, 23H2. Version 22631.3155. 
Windows Feature Experience Pack 1000.22684.1000.0

-VS Code Version:
1.87.1 (system setup) (but same errors with users version)
Fresh install

-Extension Version:
v1.3.10

**Comment by ryzngard** [comment] 2024-03-20 21:00
This seems to be resolved with `v2.22.5` 

The error log shows 

```
[Info  - 10:39:50 AM] [LSP][LanguageServer.ProjectSystem.DefaultRazorProjectService] Opening document 'c:/Users/skron/Documents/Systemutveckling/Skolan/YH-SUVNET/OOP2/TestÅÄÖ/BlazorTest/Components/Routes.razor' in project 'ProjectKey { Id = C:/Users/skron/AppData/Local/Temp/2cf2484aa8964c96994a864bee527516/__MISC_RAZOR_PROJECT__/ }'.
[Client - 10:39:51 AM] (Warning) razor.provideDynamicFileInfo failed with CodeExpectedError: cannot open file:///file%3A/C%3A/Users/skron/Documents/Systemutveckling/Skolan/YH-SUVNET/OOP2/Test%25C3%2585%25C3%2584%25C3%2596/BlazorTest/Components/Pages/Weather.razor
```

Locally I can see that the path is no longer encoded with `v2.22.5`

```
[Info  - 1:51:08 PM] [CLaSP] [StartContext] textDocument/didOpen
[LSP][LanguageServer.ProjectSystem.SnapshotResolver] Looking for c:/Users/andrha/source/TestÅÄÖ/Pages/Counter.razor.
[LSP][LanguageServer.ProjectSystem.SnapshotResolver] Found c:/Users/andrha/source/TestÅÄÖ/Pages/Counter.razor in C:/Users/andrha/source/TestÅÄÖ/TestÅÄÖ.csproj
[Info  - 1:51:08 PM] [LSP][LanguageServer.ProjectSystem.RazorProjectService] Opening document 'c:/Users/andrha/source/TestÅÄÖ/Pages/Counter.razor' in project 'ProjectKey { Id = c:/Users/andrha/source/TestÅÄÖ/obj/Debug/net7.0/ }'.
```

With `v2.22.3` I was able to reproduce 

``` 
Client - 1:59:21 PM] Notifying document '\file:\\\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\Error.cshtml' changed 'added'
[Client - 1:59:21 PM] (Warning) razor.provideDynamicFileInfo failed with CodeExpectedError: cannot open file:///file%3A/c%3A/Users/andrha/source/Test%25C3%2585%25C3%2584%25C3%2596/Pages/Error.cshtml. Detail: Unable to read file '\file:\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\Error.cshtml' (Error: Unable to resolve nonexistent file '\file:\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\Error.cshtml')
[Client - 1:59:21 PM] File '\file:\\\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\_Host.cshtml' didn't exist in the Razor document list. This is likely because it's from outside the workspace.
[Client - 1:59:21 PM] Notifying document '\file:\\\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\_Host.cshtml' changed 'added'
[Client - 1:59:21 PM] (Warning) razor.provideDynamicFileInfo failed with CodeExpectedError: cannot open file:///file%3A/c%3A/Users/andrha/source/Test%25C3%2585%25C3%2584%25C3%2596/Pages/_Host.cshtml. Detail: Unable to read file '\file:\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\_Host.cshtml' (Error: Unable to resolve nonexistent file '\file:\c:\Users\andrha\source\Test%C3%85%C3%84%C3%96\Pages\_Host.cshtml')
```

**Closed by ryzngard** 2024-03-20 21:00 UTC
Labels: bug, area-razor
