### ISSUE TITLE
[BUG] Project references aren't being recognised

### ISSUE THREAD

**Issue by lostcoda** [microsoft/vscode-dotnettools#93] opened 2023-06-09 11:37 UTC
### Describe the Issue

I created two projects `Common` and `FileSender` and made a reference to `Common` inside `FileSender`, but couldn't access anything from `Common` as it doesn't get recognised at all.

`Error: The type or namespace name 'Common' could not be found (are you missing a using directive or an assembly reference?)`

### Steps To Reproduce

1. Create two console projects and make a reference of one project into the other. 
2. Create variables/methods inside the referenced project to be used inside the other project. 
3. Import the referenced project. 
4. Namespace won't be recognised; prompted for missing references. 

### Expected Behavior

Imported references are recognised. 

### Environment Information

OS: MacOS 12.6.5
VSCode: v1.79
C# Extension: v2.0.206
.NET 6

**Comment by timheuer** [comment] 2023-06-09 14:30
Thanks for the report @lostcoda! -- I had some initial flakiness but my solution works.
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/5fee8e8a-37a8-47bc-9a08-2354c18fa526)

Wonder if you can try this test solution https://github.com/timheuer/TestSolution and see in the TestConsole app you see the TestClassLib methods/property?

**Comment by lostcoda** [comment] 2023-06-10 06:56
The solution project you linked has a class library referenced into a console project, and it's working just fine as expected. But referencing a console project into another doesn't.

**Comment by tmeschter** [comment] 2023-08-21 20:20
@lostcoda Are you still seeing this issue on the most recent releases of the C# and C# Dev Kit extensions? I am unable to reproduce the behavior using two console apps, one with a reference to the other.

**Comment by tmeschter** [comment] 2023-09-05 18:19
@lostcoda I'm going to go ahead and close this as we can't make further progress on it based on the information we have. Please let us know if you have a chance to try a newer version of C# Dev Kit and you're still seeing issues.

**Closed by tmeschter** 2023-09-05 18:19 UTC
Labels: bug, area-project, needs-more-info, triaged, mac
