### ISSUE TITLE
Error when using extract to code behind action on a Blazor component (.razor)

### ISSUE THREAD

**Issue by danroth27** [microsoft/vscode-dotnettools#569] opened 2023-09-27 23:01 UTC
Type: <b>Bug</b>

Create a Blazor Web App with .NET 8. Try to extract the Counter component code block to a code behind file using the code action. When I try to do this I get an error notification.

Extension version: 0.5.119-g9e97a3cc15
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (41.03GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/daroth/Desktop/BlazorWebAssemblyHostedApp --crash-reporter-id 4f9325b6-0f0b-4512-95c8-0e78b95da0c9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
962ge761:30841074
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingt:30839829
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448

```

</details>

**Comment by danroth27** [comment] 2023-09-27 23:01
@phil-allen-msft

**Comment by phil-allen-msft** [comment] 2023-10-05 21:44
@danroth27 , this may have been fixed by a recent change; do you have the content of the error notification so that we can determine if the fix matches this error?

**Comment by phil-allen-msft** [comment] 2023-10-05 21:46
Offline feedback, the issue is now fixed.

**Closed by phil-allen-msft** 2023-10-05 21:46 UTC
Labels: area-razor
