### ISSUE TITLE
[BUG] Test Explorer not updating when test fails and not consistent with C# Dev Kit - Test Explorer output

### ISSUE THREAD

**Issue by cicorias** [microsoft/vscode-dotnettools#927] opened 2024-02-17 13:00 UTC
### Describe the Issue

>NOTE: i've verified this on Windows 11 WSL2 as well -- so not OS specific.
>NOTE: also verifed on direct Windows 11 PowerShell.   -- last gif
>NOTE: also happens in dev container.
>NOTE: additionally the test explorer doesn't always pick up tests on fresh "clone->build" -- second to last gif

Test Explorer AND Code pane Debug status do not show the failed status of tests and is not in sync with actual test failure. 

Test Explorer shows test “may” have passed 

Code View shows test “may” have passed 

Output windows “output-> c# Test Explorer” shows failure 

This occurs with xUnit, NUnit, MSTest project types 

### Steps To Reproduce

Using a MacBook m2 arm64 with Sonoma 14.3.1 (23D60) 

Clone repo and branch https://github.com/cicorias/dotnet-worker-example-mqtt/tree/macos-arm-fix  

Ensure you swithc to branch “macos-arm-fix" 

Install VS code – both stable or insiders – or create new profile 

Install ONLY the C# Dev Kit 

Build project – either from Terminal -> Build – or dotnet build 

Run tests – ensure they pass 

Modify code to make test fail 

Run the test from either Test Explorer or Code view Run Test – see that they show green 

Switch to Output view and look at the “c# dev kit – test explorer” -- here you see that it CORRECTLY reports a test failure 

Switch to the “Test Results view” -- see that the test seems “unfinished” --  

From terminal run “dotnet test” 

NOTE: an odd observation is that “sometimes” it picks up and reports correctly. I’ve tried rebuild; clean, rebuild, etc. And have not figured out the proper sequence to make it recover and show proper status in Test Explorer/Test Results/Code view 

### Expected Behavior

Test Explorer and Code view run test should show proper status of failed test 

Test Results window should show completed test run 

## macos sononma m2 arm64
```
.NET SDK:
 Version:           8.0.101
 Commit:            6eceda187b
 Workload version:  8.0.100-manifests.5638171e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.3
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.101/

.NET workloads installed:
 Workload version: 8.0.100-manifests.5638171e
 [maui-desktop]
   Installation Source: SDK 8.0.100
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.6/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.1
  Architecture: arm64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.302 [/usr/local/share/dotnet/sdk]
  6.0.400 [/usr/local/share/dotnet/sdk]
  6.0.404 [/usr/local/share/dotnet/sdk]
  6.0.407 [/usr/local/share/dotnet/sdk]
  6.0.408 [/usr/local/share/dotnet/sdk]
  6.0.413 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.202 [/usr/local/share/dotnet/sdk]
  7.0.302 [/usr/local/share/dotnet/sdk]
  7.0.307 [/usr/local/share/dotnet/sdk]
  8.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.16 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  x64   [/usr/local/share/dotnet/x64]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

# windows 11 with wsl2

```
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.014977a5

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.200/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.419 [/usr/share/dotnet/sdk]
  7.0.406 [/usr/share/dotnet/sdk]
  8.0.200 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
➜  dotnet-worker-example-mqtt git:(macos-arm-fix) ✗ 
```

# direct windows 11 
```
C:\g\temp\dotnet-worker-example-mqtt [macos-arm-fix ≡ +0 ~1 -0 !]> dotnet --info     
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
 [maui-windows]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    8.0.6/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maui\8.0.6\WorkloadManifest.json
   Install Type:        FileBased

 [ios]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.ios\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

 [maccatalyst]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    17.2.8004/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.maccatalyst\17.2.8004\WorkloadManifest.json
   Install Type:        FileBased

 [android]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    34.0.52/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.android\34.0.52\WorkloadManifest.json
   Install Type:        FileBased

 [wasm-tools]
   Installation Source: VS 17.9.34607.119
   Manifest Version:    8.0.2/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.workload.mono.toolchain.current\8.0.2\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

.NET SDKs installed:
  6.0.419 [C:\Program Files\dotnet\sdk]
  7.0.406 [C:\Program Files\dotnet\sdk]
  8.0.200 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
C:\g\temp\dotnet-worker-example-mqtt [macos-arm-fix ≡ +0 ~1 -0 !]>
```
# first showing passing OK -- "berfore" making test change to force failure

![2024-02-17 07 48 00 2](https://github.com/microsoft/vscode-dotnettools/assets/1080406/740c7b91-aa0c-4714-8636-987c29425137)

# showing failure after making change to the unit test to force failure
https://github.com/microsoft/vscode-dotnettools/assets/1080406/eb7d1beb-a6c1-45e4-bc8c-2885c50e3e14

![csharp (1)](https://github.com/microsoft/vscode-dotnettools/assets/1080406/e4c0550e-7cf9-4637-9c7d-109b667c8b38)

![csharpwindows](https://github.com/microsoft/vscode-dotnettools/assets/1080406/0e13fb88-1cad-4aa6-883d-a750519f898d)

# running and not working in dev container

![image](https://github.com/microsoft/vscode-dotnettools/assets/1080406/fd944164-b677-49c0-a593-ce53045a0ea0)

**Comment by FairlieAgile** [comment] 2024-02-20 22:29
I am also experiencing this issue. Selecting to re-run all tests from the top menu works as expected. So the problem appears to be restricted to running individual or specific groups of tests.

**Comment by jmfennell** [comment] 2024-02-23 08:55
I'm also experiencing this. If I run the tests from the test explorer they report as passed, even if they have failed. Running them from within the file works as expected.

**Comment by BAAZKonqi** [comment] 2024-02-23 10:39
I have the same problems:
C# Dev Kit - Test Explorer: test results are not updated
test result tab: test results are not updated
output tab -> C# Dev Kit - Test Explorer: Correct results are shown

The Problem is, that there is no way to see the actual reason the test failed, as this would normally be shown in the test result tab.

VSCode: 1.86.2
C# Dev Kit: 1.3.10

**Comment by peterwald** [comment] 2024-02-23 20:22
Thanks for the detailed report @cicorias. 

This is caused by a race condition that can happen if the test run is marked as complete before all of the results come in. The results that lose the race are discarded. Unfortunately, I don't have a workaround other than to note that if you run many tests, then the results from only the last result notification would likely be lost (although there can be multiple test results in each result notification). I do have a fix going in, and it should make the next pre-release hopefully.

**Comment by DavidMartynWood** [comment] 2024-03-06 22:46
Verified with latest pre-release and fixes the issue for me.

**Closed** 2024-03-21 10:51 UTC
Labels: bug, area-test, fixed (release pending), mac
