### ISSUE TITLE
[BUG] C# Dev Kit commands not found

### ISSUE THREAD

**Issue by ccalvarez** [microsoft/vscode-dotnettools#225] opened 2023-07-04 16:02 UTC
### Describe the Issue

I have installed the C# Dev Kit for VS Code extension.  

When I open a folder containing a Visual Studio Solution, the expected Solution Explorer is not showing up.

Besides, when I try to run any command from the Command Palette, I got errors saying the command is not found:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/a5bc5069-2124-454d-8fa4-9bdd6a5c8779)

### Steps To Reproduce

1. In this environment:
 Operating System:  Windows 10
 Version:  22H2
 Compilation SO:  19045.2965

2. Run Visual Studio Code
![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/54219c9d-f78a-4743-ba33-49c10dbb8cf9)

3. With C# Dev Kit extension installed, press CTRL-SHIFT-P to open the Command Palette

4, Find/choose:  .NET: New Project...
![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/e086ff22-c155-4dba-ac06-6588654f4931)

### Expected Behavior

The expected behavior is to execute the command selected, instead of showing "command not found".

### Environment Information

1. OS: Windows 10
 Version:  22H2
 Compilation SO:  19045.2965

2. VS Code:
![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/c78eeedc-9b67-4ffd-9605-b1ab9de32e84)

3. Extension version:
![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/cb5ce6b0-8ed6-489d-b839-620a88da0db5)

**Comment by claudiaregio** [comment] 2023-07-05 23:27
I'm also running into this issue

**Comment by webreidi** [comment] 2023-07-05 23:50
@ccalvarez Can you look at the C# extension? In order for C# Dev Kit to work, it requires the prerelease version (>2.0). You can get that version by clicking the "Switch to prerelease" button at the top of the C# extension page.

Please let me know if that fixes this issue and if you are able to create a new project after that.

**Comment by ccalvarez** [comment] 2023-07-06 15:44
@webreidi thank you!  I have switched to the prerelase version of the C# Extension, and now the C# Dev Kit works as expected.

Thanks!

![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/08f2c3ee-fa79-4b98-a43f-ca82cfed152a)

and

![image](https://github.com/microsoft/vscode-dotnettools/assets/2665104/6d8bbf5d-a870-42c0-919e-864b2a0ce5d5)

**Comment by JotaRata** [comment] 2023-07-14 02:21
The issue came back with the latest update

**Comment by jhgorse** [comment] 2023-11-10 22:35
I see this on macOS for both available releases.

**Comment by webreidi** [comment] 2023-11-13 16:43
@jhgorse Can you give a bit more details about what you were trying to do and which versions of C# Dev Kit and the C# extension you are using, please?

**Comment by exhuma** [comment] 2023-11-17 07:43
I'm running into the same issue. Here are the versions that I have installed.

nb: I'm using these inside a dev-container based on the image `mcr.microsoft.com/devcontainers/dotnet:7.0`

```
Name: C#
Id: ms-dotnettools.csharp
Description: Base language support for C#
Version: 2.10.28
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csharp
```

```
Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 1.0.14
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit
```

**Comment by yonog1** [comment] 2023-11-17 08:19
ive been getting the same error message "csdevkit not found" in the new version of vscode and vscode insiders unless i revert the c# extension to version 2.1.2.
i tried installing vscode again thinking maybe some of its files are corrupt but that didnt fix anything.
the only weird thing is i ran the vscode 1.80.0 installer and everything seemed to work fine, but then when vscode requested an update and i reloaded it went back to the current faulty state

**Comment by mike-reilly-bg** [comment] 2023-11-28 18:21
Hello, I have just run into this myself, and I am currently not able to resolve it.

Steps to reproduce:
1. Open VS Code
2. Ctrl + shift + p to open command pallet, ".NET: New Project..."
3. Error popup: "command 'csdevkit.addNewProject' not found"

I have tried all the permutations of the current and prerelease versions for the MS C# and C# Dev Kit extensions, with the necessary window reloads:
* C# 2.10.28 / 2.12.4
* C# Dev Kit 1.0.14 / 1.1.12

![image](https://github.com/microsoft/vscode-dotnettools/assets/83244726/143c5337-3d89-4d93-9fea-fa0cf5369ee7)

**Comment by mike-reilly-bg** [comment] 2023-11-28 18:33
RESOLVED (not a bug)

For future readers, the issue was a necessary extension setting, which was warned in a popup that I blew by =/

To fix:
1. ctrl + shift + p, "Preferences: Open User Settings (JSON)
3. Add this setting to the file, before the final '}':  "dotnet.preferCSharpExtension": false

![image](https://github.com/microsoft/vscode-dotnettools/assets/83244726/1628a292-ca4b-4e12-bead-fbb876738815)

**Comment by aspirio187** [comment] 2023-12-01 08:47
I tried @mike-reilly-bg's solution and @ccalvarez's one.

Adding the line in the `settings,json` file doesn't seem to have any effect.

Neither does passing the C# and C# Dev Kit to preview. By the way, C# extensions doesn't have a preview version on my side. Is it possible that since the message was posted, there has been an update?

**Comment by jimwheeler** [comment] 2023-12-02 20:53
Also having this issue.  Adding line in settings.json did not help.  Pretty disappointed that we're told to switch to this since Visual Studio for Mac is going end of life and then it just breaks.  I hope there is going to be better and more robust quality control very soon because I no one can afford to have their tools just suddenly stop working.  I am on M1 Mac.  Latest VS Code.  Tried both CSDevKit 1.0.14 and the Pre-Release version.

**Comment by timheuer** [comment] 2023-12-15 23:49
@aspirio187 and @jimwheeler are you still experiencing this?

**Comment by jmoralesv** [comment] 2023-12-22 02:46
I'm suffering the same issue with my Surface Pro 8, Windows 11, .NET 8 SDK and the latest versions of both C# and C# Dev Kit extensions. Opening a C# project doesn't trigger IntelliSense, I can't run or debug the project. This doesn't happen in my laptop. 

Uninstalling and installing the extensions again doesn't help at all. I guess it has something to do with either the settings or my configuration.

The previous workarounds didn't work either.

Is this a way to force us to install the massive Visual Studio 2022? It's a terrible experience for newcomers, I understand now the ratings in the marketplace for these extensions.

**Comment by aspirio187** [comment] 2023-12-23 22:13
> @aspirio187 and @jimwheeler are you still experiencing this?

I cannot confirm 100% since I didn't reuse it on the laptop having this issue. On the other laptops, with the same configuration, no issue.

**Comment by jmoralesv** [comment] 2023-12-26 17:25
Just wanted to add an update: the issues with the C# and C# Dev Kit extensions are gone after:
* Uninstalling the extensions from VS Code
* Removing the folders for the extensions in C:\Users\{user_name}\.vscode\Extensions

The second step is the one it resolved my issues, I think. Even after restarting VS Code the extensions folders were already there. I guess reinstalling the extensions was not fixing the issues because the folders already existed.

Anyway, now I can use IntelliSense, run and debug my .NET projects in my Surface Pro device.

**Comment by Kaoticz** [comment] 2024-01-03 07:03
I'm writing to confirm that I have also encountered this bug and none of the solutions mentioned here worked for me, not even removing the extensions' folders.

**Comment by poisson-fish** [comment] 2024-01-03 08:02
I can confirm this issue on both release and pre-release....

**Comment by webreidi** [comment] 2024-01-13 00:03
@Kaoticz and @poisson-fish can you please look at the C# extension settings and make sure that you do not have Dotnet: Prefer C# Extension checked?

Also, can you provide which version of C# Dev Kit and C# extension you are using?

**Comment by Kaoticz** [comment] 2024-01-14 20:38
> @Kaoticz and @poisson-fish can you please look at the C# extension settings and make sure that you do not have Dotnet: Prefer C# Extension checked?
> 
> Also, can you provide which version of C# Dev Kit and C# extension you are using?

Here are the extensions I have:
`C# Dev Kit` - v1.3.2
`C#` - v2.15.30
`Intellicode for C# Dev Kit` - v0.1.26
`.NET Install Tool` - v2.0.0

`Prefer C# Extension` is also **unchecked**.
![image](https://github.com/microsoft/vscode-dotnettools/assets/1812311/8eee849d-33cb-4495-a377-feeb8b63eb13)

Possibly a relevant detail, but I'm using NixOS. Everything is installed in `/nix/store`, which is read-only. Do the C# extensions require write permissions in their folders in order to work?
On a side-note, I haven't had issues with the C/C++ and Python extensions (also from Microsoft), they worked flawlessly without tinkering. The C# extensions not working caught me by surprise.

**Comment by shackcrack007** [comment] 2024-01-17 12:48
same issue for me, completely new win 10 completely updated, with new vscode and the extensions by the book

**Comment by Michael-Eng** [comment] 2024-01-18 17:00
> > @Kaoticz and @poisson-fish can you please look at the C# extension settings and make sure that you do not have Dotnet: Prefer C# Extension checked?
> > Also, can you provide which version of C# Dev Kit and C# extension you are using?
> 
> Here are the extensions I have: `C# Dev Kit` - v1.3.2 `C#` - v2.15.30 `Intellicode for C# Dev Kit` - v0.1.26 `.NET Install Tool` - v2.0.0
> 
> `Prefer C# Extension` is also **unchecked**. ![image](https://private-user-images.githubusercontent.com/1812311/296615240-8eee849d-33cb-4495-a377-feeb8b63eb13.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1OTczODYsIm5iZiI6MTcwNTU5NzA4NiwicGF0aCI6Ii8xODEyMzExLzI5NjYxNTI0MC04ZWVlODQ5ZC0zM2NiLTQ0OTUtYTM3Ny1mZWViOGI2M2ViMTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMTY1ODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdjNzIxNzhlZTYzYjRmNTlhYjhiMzY2YzlhMTllNmFmMDJjN2NkZTVhZjMxYzk0YzFjOGY1YzI4YzY2YjJmNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h6jnEr7ZsbtGXK4IhPlp1QbSbsG6qQ4Fa3g8vgZYP9o)
> 
> Possibly a relevant detail, but I'm using NixOS. Everything is installed in `/nix/store`, which is read-only. Do the C# extensions require write permissions in their folders in order to work? On a side-note, I haven't had issues with the C/C++ and Python extensions (also from Microsoft), they worked flawlessly without tinkering. The C# extensions not working caught me by surprise.

Yes we do require write permissions to copy files and build up some internal MEF components.

**Comment by Beldarak** [comment] 2024-01-18 17:53
Same issue here since the last version (2.15.30) with my Unity project.

I've reverted to 2.14.18 and eveything's working fine on this version.

I'm using .Net install Tool (v2.0.0), C# Dev Kit (v1.3.2 pre-release), IntelliCode for C# Dev Kit (v0.1.26 preview), Unity (Unity for Visual Studio Code) (v0.9.4 preview)

Hope that helps :)

**Comment by Kaoticz** [comment] 2024-01-18 18:24
> Yes we do require write permissions to copy files and build up some internal MEF components.

Oh, it could be it then. I guess it can't be helped then.
Thanks for the support.

**Comment by Andrukas8** [comment] 2024-03-20 08:08
I'm having the same issue on Win10... Have tried every remedy I could find, but nothing works.

**Comment by webreidi** [comment] 2024-04-04 15:07
@jbevain  did you see the comment on Jan 18 about it working in 2.14.18, but not in 2.15.30 of Unity, and reverting the Unity version made it work. Is this a known issue with Unity?

It seems the original issue with NixOS is something we can't resolve due to no access to write to the necessary directory. If there is nothing else on the Unity issue we can close this ticket.

**Comment by akaloshych84** [comment] 2024-04-23 05:26
Same problem, macOS, VSCode connected to linux VM via remote SSH.

**Comment by jbevain** [comment] 2024-04-26 20:07
@arkalyanms @webreidi there's nothing in here specific to Unity. They're talking about reverting the C# extension version. 2.15.30 is not a Unity version.

**Comment by smitpatel** [comment] 2024-05-01 21:53
Moved the area. The issue occurs when C# dev kit fails to activate fully. Possible causes include C# extension not present or older version or preferring C# extension via settings. Readonly OS. We should summarize set of requirements for C# dev kit activation.

**Comment by webreidi** [comment] 2024-05-01 23:53
@Beldarak can you verify that you do not have dotnet.preferCSharpExtension set to true for the workspace?

**Comment by arkalyanms** [comment] 2024-05-02 00:33
@smitpatel could we add a check to that effect before activation and throw up an error and/or disable if prereq was not met?

**Comment by smitpatel** [comment] 2024-05-02 19:32
Looking at code, we do log messages when prereq is not met. We also show prompt for upgrade if C# extension is old.

Looking at commands in command palette, we should hide some of the commands which doesn't make sense to show in empty workspace like rebuild solution. We should only show them once solution is open. Certain commands like add new project are supposed to activate the extension. If possible we should show error message if user selected command which activated extension but it failed. (contrast to case where extension activate because of csproj file where user may not want to use the extension).

Tagging @AArnott if he has more insights on how we can improve experience here.

**Comment by smitpatel** [comment] 2024-05-29 19:33
We have added some common issue when extension fails to activate or commands are not found in our FAQ https://code.visualstudio.com/docs/csharp/cs-dev-kit-faq#_why-isnt-c-dev-kit-activating-c-dev-kit-commands-are-not-found
If all those are correct setting and still extension is not working then please file a new issue with details.

**Closed by smitpatel** 2024-05-29 19:33 UTC
Labels: bug, area-extensionmanagement, high-priority

**Comment by jooyeonroh** [comment] 2024-07-07 15:43
I solved this issue by just deleting a folder named `.vscode` in current project directory.

**Comment by RDistinct** [comment] 2024-08-07 06:35
@jooyeonroh same!

**Comment by vinicius-stutz** [comment] 2025-03-18 04:28
> I solved this issue by just deleting a folder named `.vscode` in current project directory. And reload vscode window.

Thank you!

**Comment by babluusa15** [comment] 2025-05-29 17:48
> I solved this issue by just deleting a folder named `.vscode` in current project directory. And reload vscode window.

Thank You. 
I opened up that .vscode file and changed the True to False for the following and then it started working. 
{
    "dotnet.preferCSharpExtension": false
}

When i looked for the same "dotnet.preferCSharpExtension" setting thru VS Code Settings search option, it was unchecked, but yet did not work. Then following your clue, found redundant code/ settings. Setting it to false now works.

**Comment by lucasbaizer2** [comment] 2025-06-04 22:35
Updating my very old VSCode (1.87.2) to latest (1.100.3) fixed this for me.

**Comment by nepgya2803** [comment] 2025-06-26 03:11
The issue happens again. Reinstalling does not help.
```
Name: C#
Id: ms-dotnettools.csharp
Description: Base language support for C#
Version: 2.80.16
Publisher: Microsoft
```
```
Name: C# Dev Kit
Id: ms-dotnettools.csdevkit
Description: Official C# extension from Microsoft
Version: 1.20.35
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-dotnettools.csdevkit
```

**Comment by nepgya2803** [comment] 2025-06-27 07:54
Hi @webreidi 
The current VS code version is 
```
Version: 1.101.2 (user setup)
Commit: 2901c5ac6db8a986a5666c3af51ff804d05af0d4
Date: 2025-06-24T20:27:15.391Z
Electron: 35.5.1
ElectronBuildId: 11727614
Chromium: 134.0.6998.205
Node.js: 22.15.1
V8: 13.4.114.21-electron.0
OS: Windows_NT x64 10.0.26100
```
`"dotnet.preferCSharpExtension": false` fixed the issue, but I have to reinstall the extension. Simply reloading the window cannot reactivate it.  
Thank you for your support!
