### ISSUE TITLE
[BUG] Unable to build WinUI for debugging

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/vscode-dotnettools#98] opened 2023-06-09 17:36 UTC
### Describe the Issue

When F5ing a WinUI Project, it fails when building the project.

> The platform 'AnyCPU' is not supported for Self Cotnained mode.

### Steps To Reproduce

1. Create a WinUI project
2. Hit F5

### Expected Behavior

WinUI builds and starts debugging

**Comment by WardenGnaw** [comment] 2023-06-09 17:51
@arkalyanms I believe this should go to `area-project` because the blocker is building the project.

**Comment by tmeschter** [comment] 2023-06-15 17:40
@WardenGnaw How are you creating the WinUI project?

**Comment by Licantrop0** [comment] 2023-06-16 00:36
I created it in Visual Studio 2022 using the [WinUI Template Studio](https://marketplace.visualstudio.com/items?itemName=TemplateStudio.TemplateStudioForWinUICs)

**Comment by tmeschter** [comment] 2023-07-10 23:14
Unfortunately I can't get the WinUI Template Studio extension to install. If a repro project can be uploaded, I'll take a look.

**Comment by smitpatel** [comment] 2024-10-14 21:20
Closing as we are not able to reproduce the issue.

**Closed by smitpatel** 2024-10-14 21:20 UTC
Labels: bug, area-project, triaged
