### ISSUE TITLE
C# Intellisense stops working mid-session

### ISSUE THREAD

**Issue by davidortinau** [microsoft/vscode-dotnettools#1448] opened 2024-09-09 22:21 UTC
Type: <b>Bug</b>

In this extension version I have to reload the window many times in a session because C# intellisense stops working. It seems like the whole extension fails for some reason.

My typical loop is make a code change, debug to iOS or Mac Catalyst, hit a breakpoint, make a change, restart the debug session by clicking the restart icon. 

At some point in the span of only about 5-10 minutes the intellisense will cease to present options. I also notice the parameter hints disappear from the C# editor. Then I reload the window and all of these features return.

The project I'm working on is using .NET 9 Preview 7.

Extension version: 1.11.4
VS Code version: Code - Insiders 1.93.0-insider (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:13:15.344Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id fc80353a-ef2a-479f-83ff-be5b061d3542|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vsc_aacf:30263846
vscod805:30301674
vsaa593:30376534
py29gd2263:31024238
c4g48928:30535728
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
9c06g630:31013171
a69g1124:31018687
dvdeprecation:31040973
dwnewjupytercf:31046870
nb_pkg_only:31057982
nativerepl1:31104042
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31125599
cf971741:31111988
jh802675:31132134
e80f6927:31120813
ei213698:31121563

```

</details>

**Comment by SirWernich** [comment] 2024-09-10 04:02
i've been having similar issues on my machine (m2 pro), with the c# output in vscode showing a LocalRpcException multiple times:

`[Error - 05:57:45] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-09-10T03:57:43.1143140Z-10006-0' does not match current version '2024-09-10T03:57:45.4559270Z-10085-0'
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`1.StartRequestAsync[TRequest,TResponse](TRequest request, TRequestContext context, IMethodHandler handler, String language, CancellationToken cancellationToken) in /_/src/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 187
`

when i saw that, error above, especially the datetime stuff, i enabled my "set time and date automatically" in the system settings. last week i was doing some timezone-related stuff, so i disabled that so i could be in aruba. :) turns out my clock jumped ahead a few seconds and that seems to make the c# extensions unhappy. after restarting vscode it seems ok (only just did it now). i disabled the auto time setting again and restarted vscode and the exceptions came back.

not sure if that will fix your issue, but the disappearing intellisense etc is what i was experiencing too.

**Comment by ivanreyes30** [comment] 2024-09-10 09:43
https://github.com/microsoft/vscode-dotnettools/issues/1451#issuecomment-2340175632

**Comment by cgdallas** [comment] 2024-09-10 16:09
I am also experiencing this issue on the latest version and after having downgraded to 1.9.55, the issue goes away.

**Comment by newFort4** [comment] 2024-09-11 13:17
> I am also experiencing this issue on the latest version and after having downgraded to 1.9.55, the issue goes away.

+1

**Comment by dibarbet** [comment] 2024-09-11 18:00
> [LanguageServerHost] System.ArgumentException: '<Document5d7ca9a4-084c-4ddf-b0a9-d07241c0f0c6>' is not part of the workspace. at Microsoft.CodeAnalysis.Workspace.<>c.<OnDocumentClosedEx>b__213_0(Solution oldSolution, ValueTuple4 data) in //src/Workspaces/Core/Portable/Workspace/Workspace_Editor.cs:line 662

This is the likely cause of the issues (will cause the server to crash) and is a duplicate of https://github.com/dotnet/vscode-csharp/issues/7514
We should be releasing a fix in the C# extension soon.

> [Error - 05:57:45] [LanguageServerHost] StreamJsonRpc.LocalRpcException: Resolve version '2024-09-10T03:57:43.1143140Z-10006-0' does not match current version '2024-09-10T03:57:45.4559270Z-10085-0' at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeLens.CodeLensResolveHandler.HandleRequestAsync(CodeLens request, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeLens/CodeLensResolveHandler.cs:line 55 at 

This error is innocuous and won't cause any failures

**Closed by dibarbet** 2024-09-11 18:00 UTC
Labels: area-roslyn
