### ISSUE TITLE
[BUG] Failed test count not updated when clearing all results

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#628] opened 2023-10-17 13:47 UTC
### Describe the Issue

When you clear all test results in the testing view, the count of failed tests is not cleared at all:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/1aa5c3a8-2675-4198-8dfc-dbcbb3c4c040)

### Steps To Reproduce

1. Create an xunit project 
2. Add some code to the default test class so that the test method always fails
3. Run the test
4. The failure count on the Test View icon shows 1
5. Open the Test View and on the 3 dots on top right click on "Clear All Results"
6. The failure count on the Test View icon remains at 1

### Expected Behavior

The failure count should go back to zero or just show no number since no test has been run.

### Environment Information

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621

**Comment by webreidi** [comment] 2023-10-17 17:30
@peterwald I just tested this with VS Code version 1.84.0 (Insiders) and I couldn't reproduce this. Do you have a VS Code stable build to test to see if it is happening there? This may just need to wait on an update of VS Code.

**Comment by peterwald** [comment] 2023-10-23 17:46
Fixed in current Insiders release of VS Code. Fix will be available in the stable build of VS Code after the next release.

**Closed by peterwald** 2023-10-23 17:46 UTC
Labels: bug, area-test, area-vscode
