### ISSUE TITLE
Autocomplete and code intelligence not working in VS Code 

### ISSUE THREAD

**Issue by khagesh-medtronic** [microsoft/vscode-dotnettools#802] opened 2023-12-13 11:05 UTC
Type: <b>Bug</b>

Autocomplete and code intelligence not working in VS Code. 

Extension version: 0.5.50
VS Code version: Code 1.85.0 (Universal) (af28b32d7e553898b2a91af498b1fb666fdebe0c, 2023-12-06T18:18:04.614Z)
OS version: Darwin x64 22.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|13, 15, 10|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 8e6b30c0-86ba-47ee-89f9-d8a456ed9c5c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263:30899288
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2e4cg342:30602488
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
welcomedialog:30910333
pythonnosmt12:30797651
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
dsvsc013:30795093
dsvsc014:30804076
dsvsc015:30845448
pythontestfixt:30902429
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:30885898
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by AbhitejJohn** [comment] 2023-12-13 22:46
@khagesh-medtronic : Thanks for taking the time to let us know. Could you give us a little more context on your scenario/repro please? Do you see any log messages in the Output pane for "C#" and "C# Dev Kit" categories that you could share?

**Comment by khagesh-medtronic** [comment] 2023-12-14 03:44
It's very much frustrating that very basis things are not working in VS code and on the other hand Microsoft showing notification Visual Studio Mac to use VS code because VS Mac is going to retire. I don't understand how can we use VS Code where very basics things are not working. 

Steps to reproduce : 

1. Create new Maui App in VS code. 
2. try to Edit/Add some code in any xaml file. 
3. No autocomplete feature works, No code intelligence works. you have to type everything by your own. 

I feel this very basic feature for any IDE/Editor which not working in VS code. If this basic things are not working how can Microsoft release it.

**Comment by timheuer** [comment] 2023-12-14 03:54
@khagesh-medtronic I'm going to close this as a duplicate of #565 -- I know that says closed but I'm asking why it was closed as it's being worked on (as noted by the dev team in that issue).

**Closed by timheuer** 2023-12-14 03:54 UTC
Labels: area-maui

**Comment by khagesh-medtronic** [comment] 2023-12-14 05:52
@timheuer  if #565 is closed then why these features are not working? 
why is #565 marked closed?

**Comment by timheuer** [comment] 2023-12-14 07:13
> but I'm asking why it was closed as it's being worked on (as noted by the dev team in that issue).

Yes, see my comment above "but I'm asking why it was closed as it's being worked on (as noted by the dev team in that issue)." 
I think it is incorrectly closed as I can confirm we haven't shipped it yet of course.

and my comment over there (https://github.com/microsoft/vscode-dotnettools/issues/565#issuecomment-1855085880) -- will confirm with dev team...might just be a syncing issue as I saw the sync tool auto-closed it, but the internal backing bug is still open and as Marco notes on that issue, the team is working to bring the lang service (https://github.com/microsoft/vscode-dotnettools/issues/565#issuecomment-1741342564)

**Comment by scriptBoris** [comment] 2024-03-15 19:31
Any update? It is base functional
