### ISSUE TITLE
[BUG] InternalsVisibleTo won't get rid of red squiggles

### ISSUE THREAD

**Issue by julioct** [microsoft/vscode-dotnettools#603] opened 2023-10-11 21:09 UTC
### Describe the Issue

When a class in ProjectA tries to access internal types on ProjectB, it will present red squiggles complaining about the visibility of the types, as expected.

If you then apply **InternalsVisibleTo** to ProjectB, specifying ProjectA, then ProjectA will successfully compile, but red squiggles won't go away.

Only way to go around this is to completely close and reopen VS Code. Even restarting the language server won't do it.

### Steps To Reproduce

1. Create a class library and an xUnit project
2. Reference the class library from the xUnit project
3. Add an internal class in the class library and add internal method.
4. Add a unit test to the xUnit project that tries to invoke the internal method in the class library
5. Notice the red squiggles when trying to access the class or the internal method:

![image](https://github.com/microsoft/vscode-dotnettools/assets/2374270/bea8c90e-4694-4579-b62b-2a741711390a)

7. Add this to the class library project:

```xml
  <ItemGroup>
    <InternalsVisibleTo Include="ThexUnitProject" />
  </ItemGroup>
```

...where ThexUnitProject is the name of the xUnit project.

8. Notice the red squiggles won't go away.

### Expected Behavior

The red squiggles should go away.

### Environment Information

Extension version: 0.5.150
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621

**Comment by tmeschter** [comment] 2023-10-12 18:11
Moving to "area-roslyn" as this concerns live diagnostics.

**Comment by dibarbet** [comment] 2024-12-05 01:16
Closing this issue - we've made a number of changes to the extensions since this issue was file and I am unable to reproduce the issue.  ![Image](https://github.com/user-attachments/assets/02d85864-3ffe-4e06-a702-985d71977f4b)

Please try out the latest versions and re-open if you're still encountering issues.

**Closed by dibarbet** 2024-12-05 01:16 UTC
Labels: bug, triaged, area-roslyn
