### ISSUE TITLE
[SUGGESTION / QUESTION] Public API to access currently set Solution file

### ISSUE THREAD

**Issue by ReeceHumphreys** [microsoft/vscode-dotnettools#785] opened 2023-12-05 14:37 UTC
### Describe the feature you'd like

Some form of public API for other extensions to use so that they can access the currently set solution file and be notified when it changes.

**Comment by spouliot** [comment] 2023-12-05 22:07
This has been requested a few times already. See https://github.com/dotnet/vscode-csharp/issues/5805 and linked issues for more details.

**Comment by timheuer** [comment] 2023-12-06 01:28
As noted, closing as dupe of https://github.com/dotnet/vscode-csharp/issues/5805

**Closed by timheuer** 2023-12-06 01:28 UTC
Labels: enhancement, area-solution
