### ISSUE TITLE
[SUGGESTION] Support for changing Active Build Configuration for better code editing experience

### ISSUE THREAD

**Issue by niguiecandy** [microsoft/vscode-dotnettools#1037] opened 2024-03-29 04:07 UTC
### Describe the feature you'd like

AFAIK, unlike Visual Studio or Rider, VS Code doesn't have 'Build Configuration Indicator' UI or anything that does the similar function.

If you have a C# solution with multiple build configurations, and if some of them contains a preprocessor symbols, it becomes a nightmare:  you can't change the editor's ACTIVE build configurations to work with those preprocessed code paths. You have to manually edit the .csproj file to make it work.

C# Dev Kit should support for changing active build configuration in the editor.

*** If there is a way to do this, please let me know.

### Alternatives considered

I have to manually edit .csproj files so that a Debug configuration contains the required preprocessor symbols when editing. I have to comment it out when building.

### Environment Information

WIn 10, VS Code 1.87.2

**Comment by jbevain** [comment] 2024-03-29 16:39
Duplicate of #67.

**Comment by jvcdk** [comment] 2024-05-14 10:12
+1: I need this as well :)

**Comment by lifengl** [comment] 2024-07-31 05:19
this feature has been built in C# Dev Kit. The active configuration is showing in the status bar, and click it would bring up the process to change it. The workspace has to be reloaded as a limitation at this point of time.

**Closed by lifengl** 2024-07-31 05:19 UTC
Labels: enhancement, area-project-cps

**Comment by niguiecandy** [comment] 2024-07-31 05:52
Finally!! Thanks for the good work!
