### ISSUE TITLE
[SUGGESTION] Add NuGet integration

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-dotnettools#753] opened 2023-11-24 18:09 UTC
### Describe the feature you'd like

I'm trying to wean myself away from Visual Studio Mac, so I'd like NuGet integration. There doesn't seem to be any at this point in time. 

### Alternatives considered

Figuring out how to do NuGet management from the command line, which is what I'll end up doing, but to make this more user friendly I'd still like to see a menu or command palette driven approach.

### Environment Information

macOS
Visual Studio Code 1.84.2
.NET MAUI 0.5.50
C# Dev Kit 1.0.14

**Comment by timheuer** [comment] 2023-11-28 18:54
Closing as Dupe of #62

**Closed** 2023-11-30 01:53 UTC
Labels: enhancement, area-nuget
