### ISSUE TITLE
System.AggregateException: Project system data flow 'Source: 50160389' closed because of an exception

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#184] opened 2023-06-20 19:46 UTC
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/5831

```
=====================
6/19/2023 1:09:37 PM
LimitedFunctionality
System.AggregateException: Project system data flow 'Source: 50160389' closed because of an exception.
missingBuildCount >= 0 (missingBuildCount >= 0)
---> (Inner Exception #0) Microsoft.Assumes+InternalErrorException: missingBuildCount >= 0
at Microsoft.Assumes.Fail(String message)
at Microsoft.Assumes.True(Boolean condition, String message)
at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.g__PopulateMissingBuildData|5(<>c__DisplayClass5_1&)
at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.g__ComposeItemUpdates|2()
at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.<>c__DisplayClass5_0.g__ProcessAddsAndUpdates|0()
at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencies.MSBuildDependencyCollection.TryUpdate(IProjectChangeDescription evaluationProjectChange, IProjectChangeDescription buildProjectChange, String projectFullPath, Nullable1& dependencies) at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>g__Transform|6_1(IProjectSubscriptionUpdate update) at Microsoft.VisualStudio.ProjectSystem.CommonProjectSystemTools.Derive[T,TOut](IProjectVersionedValue1 projectVersionedValue, Func2 transform) at Microsoft.VisualStudio.ProjectSystem.Tree.Dependencies.Subscriptions.MSBuildDependencySubscriber.Source.<LinkExternalInput>b__6_0(IProjectVersionedValue1 u)
at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim2.TransformBlockSlimSync.ProcessInputAsync(TInput input) at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0)
```

And all project start looking red

### Steps To Reproduce

Appearing after project starts with dotnet run or 'Run without debugging'

**Comment by smitpatel** [comment] 2023-06-20 19:57
Duplicate of #22

**Closed** 2023-06-28 17:11 UTC
Labels: bug, area-project
