### ISSUE TITLE
Autocompletion is deleting code I have already written

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#171] opened 2023-06-19 16:53 UTC
### Describe the Issue

Autocompletion is deleting code I have already written

### Steps To Reproduce

_Sorry the quality of the gif is bad_ 

1. Create constructor, omit use of 'this' 
2. Go back to put 'this' 
3. Adding period after 'this' deletes the X and Y I have already written

![code_deleted](https://github.com/microsoft/vscode-dotnettools/assets/19276747/eac6f282-8a2b-4bc8-b5ff-546a3680643d)

### Expected Behavior

For the code I already wrote to not be deleted 

### Environment Information

Apple M2 Pro
OS: Ventura 13.2.1
C# Dev Kit: v0.1.103
C#: v1.25.9
Intellicode for C# Dev: v0.1.9

**Comment by timheuer** [comment] 2023-06-19 20:04
Dupe of https://github.com/dotnet/vscode-csharp/issues/5777

**Comment by arkalyanms** [comment] 2023-08-17 22:42
Indeed, was fixed.

**Closed by arkalyanms** 2023-08-17 22:42 UTC
Labels: bug, area-editing
