### ISSUE TITLE
[BUG] Debug command => Incorrect target type with _ in the project name

### ISSUE THREAD

**Issue by gautam-goudar** [microsoft/vscode-dotnettools#1197] opened 2024-06-13 23:18 UTC
### Describe the Issue

Incorrect target type is specified

The name of the project in the solution is  "MyProjectA" and not "My_Project_A".  I am not sure from where the incorrect name is being fetched and added to the below command when I click on the project (MyProjectA)  and select Debug=>Start New Instance (from Solution Explorer).  It happens to all the C# solutions that I have. 

```
dotnet build /path/to/MySolution.sln /target:My_Project_A /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary /p:Configuration=Debug /p:Platform="Any CPU" 
```

Tis happened all of a sudden when the extension was updated in VS Code couple days back.

### Steps To Reproduce

In the Solution Explorer
1.  Click on the project that one wants to run
2. Select Debug=>Start New Instance

### Expected Behavior

Project should build and start in the Debug mode.

### Environment Information

OS: Mac Sonama 14.5
VS Code: 1.90.1
C# Dev Kit Extension: v1.8.2 (pre-release) and also in v1.7.25

**Comment by WardenGnaw** [comment] 2024-06-13 23:48
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1195

**Closed by WardenGnaw** 2024-06-13 23:48 UTC
Labels: bug
