### ISSUE TITLE
[BUG] C# extension doesn't syntax highlight .csproj files

### ISSUE THREAD

**Issue by DavidZidar** [microsoft/vscode-dotnettools#191] opened 2023-06-21 21:11 UTC
### Describe the Issue

When I edit .csproj files I no longer see any syntax highlighting because they open as ".NET Project" instead of "XML".

### Steps To Reproduce

Edit any .csproj file.

### Expected Behavior

Either add syntax highlighting to ".NET Project" or use "XML" instead like before.

### Environment Information

- OS: Windows 11
- VS Code version: v1.79.2
- C# extension version: v2.0.238

**Comment by tav9122** [comment] 2023-06-22 17:25
get the same issue here

**Comment by tav9122** [comment] 2023-06-22 17:42
> ### Describe the Issue
> When I edit .csproj files I no longer see any syntax highlighting because they open as ".NET Project" instead of "XML".
> 
> ### Steps To Reproduce
> Edit any .csproj file.
> 
> ### Expected Behavior
> Either add syntax highlighting to ".NET Project" or use "XML" instead like before.
> 
> ### Environment Information
> * OS: Windows 11
> * VS Code version: v1.79.2
> * C# extension version: v2.0.238

check if omnisharp is running in the bottom left

**Comment by guppie70** [comment] 2023-06-22 18:02
Same here (MacOS, VS Code) after installing C# Dev Kit extension. Indeed OmniSharp isn't running anymore. 
C# log shows this:
`Dotnet path: /Users/jthijs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.7/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...`
How do I fix this?

**Comment by tav9122** [comment] 2023-06-22 18:26
> Same here (MacOS, VS Code) after installing C# Dev Kit extension. Indeed OmniSharp isn't running anymore. C# log shows this: `Dotnet path: /Users/jthijs/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.7/dotnet Activating C# + C# Dev Kit + C# IntelliCode... info: LanguageServerHost[0] Starting server...` How do I fix this?

 the Language Server Protocol (LSP) needs the sln file to function, once you install the extension it will generate a sln file if the current project doesn't have one, did you delete that file?

**Comment by guppie70** [comment] 2023-06-22 18:33
Ow - did not know that installing the C# Dev Kit would disable OmniSharp. No problem of course, then we need to look somewhere else.
All my DotNet projects have an *.sln file in the root folder. For one project, I also see a *.sln.DotSettings.user file. But none of my DotNet project have syntax highlighting enabled for the *.csproj files.

**Comment by senketsu03** [comment] 2023-06-23 00:42
The `Directory.Build.props` highlighting still works btw

**Comment by UPIMMUNITY** [comment] 2023-06-25 13:32
As far as I know, C# extension does not support syntax highlighting for `*.csproj` even in the time of Omnisharp. I use extension [`tintoy.msbuild-project-tools`](https://marketplace.visualstudio.com/items?itemName=tintoy.msbuild-project-tools) to get such feature.

**Comment by timheuer** [comment] 2023-06-26 20:05
> Ow - did not know that installing the C# Dev Kit would disable OmniSharp. No problem of course, then we need to look somewhere else. All my DotNet projects have an *.sln file in the root folder. For one project, I also see a *.sln.DotSettings.user file. But none of my DotNet project have syntax highlighting enabled for the *.csproj files.

You can choose to get to Omnisharp again -- would like to see if you do that if you get the experience you want -- paste some screenshots?

**Comment by guppie70** [comment] 2023-06-27 20:13
I think there is some sort of conflict between the default C# extension and the C# Dev Kit extension.
In the extensions pane of my VS Code, I noticed that the C# extension was switched to the “prerelease” version. After I clicked on the button to switch to the normal release, the syntax highlighting in the csproj files seemed to be working again.
My VS Code windows however now display this warning:
￼
I liked the additional functionality od the C# Dev Kit extension, but it had some pretty serious issues. Not only did the syntax highlighting in the csproj files break, also the references indicators above the methods all displayed “0 references” and it also seemed as if code problem indications were not as good as before...

**Comment by timheuer** [comment] 2023-06-27 22:40
Yes if you have Dev Kit installed you'll need to be using the pre-release of the base language support.  If you drop down to v1 of the base language support and still have Dev Kit installed you'll continue to see that warning.  For the time being if you need to stay on v1 of the base language support (C# extension) I'd recommend disabling Dev Kit.

I do also now see this behavior as well on the csproj syntax so let's keep this bug open for resolution there.

**Comment by timheuer** [comment] 2023-06-27 22:51
Found the change at https://github.com/dotnet/vscode-csharp/commit/173be18fd37ee88b53214a13b4b574507cc6ec34 that casues this -- association is not with XML any longer (which gave you the default highlighting).  Will check with the team on if this specific language association is needed in this way.  We could just change language id to XML and probably be back fine, but want to understand other implications. /cc @arkalyanms as this is in base -- not sure if this is needed specifically in debugger relationship.

**Comment by DavidZidar** [comment] 2023-06-27 23:16
@timheuer Thanks for tip! It's just annoying to have to change language every time, I'd rather it would just work out of the box. 😄

**Comment by timheuer** [comment] 2023-06-27 23:27
> @timheuer Thanks for tip! It's just annoying to have to change language every time, I'd rather it would just work out of the box. 😄

We'll get it fixed -- but you can also change the association one-time using this method and not each time.

**Comment by arkalyanms** [comment] 2023-06-28 00:23
Yes we are tracking it with https://github.com/dotnet/vscode-csharp/issues/5860 and will check with the debugger team to see what will break without it.

**Comment by timheuer** [comment] 2023-06-28 02:56
Closing then as dupe of https://github.com/dotnet/vscode-csharp/issues/5860

**Closed by timheuer** 2023-06-28 02:56 UTC
Labels: bug, area-project

**Comment by guppie70** [comment] 2023-06-28 05:50
Thanks for your swift response and action!
