### ISSUE TITLE
[BUG] Request nominateProject failed

### ISSUE THREAD

**Issue by gdl-reif** [microsoft/vscode-dotnettools#1175] opened 2024-06-06 06:27 UTC
### Describe the Issue

When opening a .NET8 project in a DevContainer, I receive the following log file and message to report it to the dev team:

```
=====================
6/6/2024 6:20:23 AM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
===================

```

### Steps To Reproduce

1. Open previously created project in VSCode
2. Add .devcontainer config using template dotnet-mssql
3. When VSCode switches to the devcontainer and loads the project, the above error message is reported

### Environment Information

OS: Windows 11 22631, Docker Desktop 4.28, VSCode 1.90.0, C# DevKit v1.6.8

**Comment by lifengl** [comment] 2024-06-12 20:53
This is a bug in the NuGet restore service TypeScript code. It appears to have a race condition in the implementation & design.

**Comment by jeffkl** [comment] 2024-06-13 18:19
Team Triage: @kartheekp-ms can you please take a look?

**Comment by jeffkl** [comment] 2024-06-13 18:21
Possible duplicate of https://github.com/microsoft/vscode-dotnettools/issues/849 and/or https://github.com/microsoft/vscode-dotnettools/issues/1138

**Comment by kartheekp-ms** [comment] 2024-06-20 02:55
@tmeschter I think this issue is same as discussed in https://github.com/microsoft/vscode-dotnettools/issues/636#issuecomment-1792787521.

**Comment by glen-84** [comment] 2024-08-19 17:36
Duplicate of #567.

**Closed** 2024-10-09 18:36 UTC
Labels: bug, area-project, high-priority
