### ISSUE TITLE
[BUG] Go to definition does not work with generated sources

### ISSUE THREAD

**Issue by megasuperlexa** [microsoft/vscode-dotnettools#1434] opened 2024-09-05 15:00 UTC
### Describe the Issue

With any generated sources, "Goto definition" produce error "The editor could not be opened due to an unexpected error: Unable to resolve resource source-generated:/Microsoft.Extensions.Logging.Generators/Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator/LoggerMessage.g.cs"

### Steps To Reproduce

1.  For example, let's use `Microsoft.Extensions.Logging`
2. Create partial method 
```csharp
public static partial class LoggingExtensions
{

    [LoggerMessage(LogLevel.Warning, "Validation errors occurred: {Message}",
        EventName = "ValidationError")]
    public static partial void LogValidationError(this ILogger logger, string message);
}
```
4. "Go to Definition" on `LogValidationError()` method

### Expected Behavior

Generated source should open, like in JetBrains Rider IDE, path is `/var/folders/92/xd1482x54_g7xbxg1lw5x4wm0000gn/T/SourceGeneratedDocuments/65B88BF58EF724012A34D5C9/Microsoft.Extensions.Logging.Generators/Microsoft.Extensions.Logging.Generators.LoggerMessageGenerator/LoggerMessage.g.cs`

### Environment Information

- VsCode Version: 1.92.2
- OS: Darwin arm64 23.5.0
- C# Dev Kit: v1.9.55

**Comment by dibarbet** [comment] 2024-09-05 18:36
dupe of https://github.com/dotnet/vscode-csharp/issues/6426

**Closed by dibarbet** 2024-09-05 18:36 UTC
Labels: bug, area-roslyn
