### ISSUE TITLE
No Launchable projects found.

### ISSUE THREAD

**Issue by dellis1972** [microsoft/vscode-dotnettools#1430] opened 2024-09-04 10:32 UTC
Type: <b>Bug</b>

When trying debug or run any maui or .net android app in vscode using the automatic configurations I get a "No launchable projects found" error. 

Steps to reproduce

1. create a new dotnet maui app 'dotnet new maui`
2. open it with VSCode
3. try to use the automatic configurations to debug 

Expected Results

I should see the maui project listed as a valid Launch configuration

actual results

You get a blank drop down. And later an error popup is reported "No Launchable projects found"

This used to work some of the projects I opened used to be able to use this feature. I can't see anything in the logs from C# DevKit which would hint at why its happening. 

Note for reference. The error message is not actionable. If the user gets this there is no information on what they can do to help themselves. The result is a very poor user experience. Even a link to docs which tells people to report an issue would be better than the current experience. 

Extension version: 1.9.55
VS Code version: Code 1.92.2 (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Max (12 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|2, 10, 12|
|Memory (System)|32.00GB (7.14GB free)|
|Process Argv|/Users/dean/OneDrive/Documents/moviesandtv.md --crash-reporter-id 921906d4-a2aa-4b9c-beb4-9fc5586f83b0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
newcmakeconfigv2:31071590
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flighttreat:31119336
wkspc-onlycs-c:31111717
wkspc-ranged-t:31125599
fje88620:31121564
aajjf12562:31125793

```

</details>

**Comment by dellis1972** [comment] 2024-09-04 10:36
installing the latest preview seems to fix it.

**Comment by ben-dean** [comment] 2024-09-06 13:30
Having the same problem on current release (1.10.16) and pre-release (1.11.4). Had to roll back to v1.9.55 to make it work again.

**Comment by emaf** [comment] 2024-09-06 15:58
Closing as duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1412

**Closed by emaf** 2024-09-06 15:58 UTC
Labels: bug, area-dotnet-debugging, triaged, area-maui

**Comment by cjrvdev** [comment] 2024-09-19 11:14
Hello @emaf I just switchted to devkit (1.8.10 PRE) and maui 1.3.29 and the issue is still there. Still getting "No launchable projects found" with automatic configuration. Created a new MAUI from the editor itself to test it and Im getting the exact same behavior.

**Comment by cjrvdev** [comment] 2024-09-19 11:33
Nevermind, I updated VSCode itself and now its fixed.. I dont understand the relationship between these but fine I guess
