### ISSUE TITLE
issues in creating .net new project

### ISSUE THREAD

**Issue by brianGathuka** [microsoft/vscode-dotnettools#1317] opened 2024-07-27 11:25 UTC
### Describe the Issue

when trying to run it shows  .new project ..resulted in an error t is not iterable

### Environment Information

OS(ubuntu)

**Comment by smitpatel** [comment] 2024-07-29 15:06
Can you share full repro steps? if possible a recording of what you are seeing.

**Comment by smitpatel** [comment] 2024-09-16 18:45
Closing as we are unable to reproduce the issue.

**Closed by smitpatel** 2024-09-16 18:45 UTC
Labels: bug, area-templates, needs-more-info
