### ISSUE TITLE
[BUG] Solution wide errors

### ISSUE THREAD

**Issue by andrewmd5** [microsoft/vscode-dotnettools#54] opened 2023-06-07 18:37 UTC
### Describe the Issue

I restarted VSCode and now the extension (Roslyn) reports that I lack a reference to System and every project has errors.

Oddly enough, creating a new project, it has no errors, but the previous one still does. Eventually after flipping back and forth between VSCode windows it gets stuck reporting errors too.

### Steps To Reproduce

- Create a new project
- Switch VSCode to another folder
- Switch back to the project you created

### Environment Information

macOS (M1), .NET 8

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
   
     <RootNamespace>Root</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="bebop" Version="2.7.1" />
  </ItemGroup>

</Project>
```

**Comment by AndrewMD5** [comment] 2023-06-07 18:40
Attempting to restart the language server yields: `command 'roslyn.changeRazorCSharp' already exists`

**Comment by timheuer** [comment] 2023-06-07 19:41
Might be related to #15

**Comment by AndrewMD5** [comment] 2023-06-07 20:06
> Might be related to #15

I switched to .NET 7 and the issue persists

**Comment by kant2002** [comment] 2023-06-08 05:52
Try following
1. Add global.json and set SDK to 7.0.105
2. remove bin,obj
3. restart language server using Ctrl+Shift+P
4. remove .vs folder

Either step 3 or step 4 fixed it for me.

**Comment by kant2002** [comment] 2023-06-08 06:10
I suspect you would see an issue if .NET 6 SDK would be pinned too (I try with pinned 6.0.408) 
![image](https://github.com/microsoft/vscode-dotnettools/assets/4257079/8e4279cd-caee-4864-9843-a3a1ef5fe006)

If I pin to 7.0.400-preview.23225.8 instead of 7.0.105 issue seems to be not present too.

**Comment by phil-allen-msft** [comment] 2023-06-15 21:57
the `command 'roslyn.changeRazorCSharp' already exists` is a dupe of https://github.com/dotnet/vscode-csharp/issues/5779, which should not impact solution restore/compile/SDK.

**Comment by kieranbenton** [comment] 2023-06-21 09:47
I have this exact same problem which effectively makes the preview version completely unusable right now.

<img width="612" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/39090/bb0ffeb3-501e-48eb-822d-fdd511910aa1">

Large closed source solution so I can't unfortunately provide a repro, have tried creating a simple two project solution from scratch and I can't reproduce it.

Can I have instructions on how to get more logging to help you guys diagnose this? 

Right now in the logs panes all I have in logs currently is:

* C#
```
Dotnet path: /Users/kieranbenton/Library/Application Support/Code/User/globalStorage/ms-dotnettools.vscode-dotnet-runtime/.dotnet/7.0.7/dotnet
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
```

* C# Dev Kit
```
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
.NET server started and IPC established in 706ms
Completed Spawn .NET server (710ms)
Completed Clear environment (917ms)
Completed Open a solution with environment service (1064ms)
Starting Restore solution...
Completed Open a solution (1080ms)
Completed Restore solution (1053ms)
```

There are no obvious issues (one or two info lines) in any of the other devkit related logs.

**Comment by kieranbenton** [comment] 2023-06-21 09:48
Previously this WAS working before the latest preview release (but I was suffering from the major issue there that was resolved to do with cross project references not working).

**Comment by arkalyanms** [comment] 2023-06-30 16:31
The roslyn language server portion of the issue on M1 mac is also tracked at https://github.com/dotnet/vscode-csharp/issues/5873.

**Comment by arkalyanms** [comment] 2023-07-05 17:28
This one predates https://github.com/microsoft/vscode-dotnettools/issues/210 although both are the same. We have been using https://github.com/microsoft/vscode-dotnettools/issues/210 as the primary one to discuss, so duping this to that, although this is newer since https://github.com/microsoft/vscode-dotnettools/issues/210 has more context.

**Closed by arkalyanms** 2023-07-05 17:28 UTC
Labels: bug, area-roslyn
