### ISSUE TITLE
[BUG] Solution Explorer build fails, but F5 succeeds

### ISSUE THREAD

**Issue by AllenD-MSFT** [microsoft/vscode-dotnettools#790] opened 2023-12-07 21:24 UTC
### Describe the Issue
When I right-click on the Solution Explorer project node and select build I see errors related to Android SDK discovery, but F5 works.

Note: I'm testing an internal process so this bug might be manipulated via a flow as part of testing.

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1938521">1938521</a>

**Comment by tondat** [comment] 2024-01-24 17:13
Closed because is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/717

**Closed by tondat** 2024-01-24 17:13 UTC
Labels: bug, triaged, area-maui, vs-sync, vs-syncd
