### ISSUE TITLE
C#/devkit/MAUI - F5 sets Working Directory to extension folder instead of project root [BUG] <title>

### ISSUE THREAD

**Issue by mroz7** [microsoft/vscode-dotnettools#630] opened 2023-10-17 19:28 UTC
### Describe the Issue

On Windows when you hit F5 to start debugging MAUI project that targeting unpackaged Windows the working directory is set to extension folder from where debugger starts. Working/Current directory should be set on project root.
Haven't checked non-MAUI C# project.

### Steps To Reproduce

1. Install C# DevKit
2. Install MAUI extension
3. create MAUI template project
4. Select Windows Unpackaged target (net-7.0)
5. Hit F5 to debug app
6. observe working directory (ie. in Process Explorer) it is set to "(...)\.vscode\extensions\ms-dotnettools.csharp-2.6.24-win32-x64\.debugger\x86_64\"

### Expected Behavior

Working directory should be set to project root or to launched exe directory

### Environment Information

-OS: Windows 10 22H2 (OS Build: 19045.3570)
-VSCode: 1.83.0
-C# extension: v2.6.24
-C# DevKit extension: v0.5.150
-MAUI extension: v0.4.9

**Comment by mauroa** [comment] 2023-10-27 15:38
Assigning to @srdjanjovcic for initial investigation/interaction since it's related to unpackaged Windows

**Comment by mauroa** [comment] 2024-04-12 18:48
Hi @mroz7, we are going through old and unattended issues to see if they are still reproducible on latest .NET MAUI pre-release, in order to define an action item for them.
Could you please confirm if this is still an issue for you?

Thanks for your help and patience.

**Comment by mauroa** [comment] 2024-07-02 14:18
We are unable to continue the investigation without the required information.
Feel free to request a reopening if you still experience any issue after updating to latest C#, C# DevKit and .NET MAUI versions and also please provide the information requested above.
Thanks for your help and feedback.

**Closed by mauroa** 2024-07-02 14:18 UTC
Labels: bug, needs-more-info, triaged, area-maui
