### ISSUE TITLE
[BUG] Unable to work with existing Unity project.

### ISSUE THREAD

**Issue by juanvaquero** [microsoft/vscode-dotnettools#335] opened 2023-08-05 19:42 UTC
### Describe the Issue

Since yesterday August 3, 2023, I upgraded to the new Visual Studio Editor package in Unity, and installed the new Unity extension released on the same day. I do not see the references in the variables of the scripts, but I do see those of the classes and methods. I can also "access" the reference menu of a variable if I double click on it holding control/(Command in Mac).

Could you give me a solution to be able to have the references working in the variables too?

Thank you very much in advance.

![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/b1964b6d-e43a-44b6-a0bf-e7c55403837b)

I don't know if this is part of the problem, but it appears every time I open vscode.

![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/cf78041b-5ca5-4588-91a6-adae95b0eebf)

### Steps To Reproduce

I have these versions of extensions related to the problem:

![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/acaa2370-33c7-4497-9c8e-0a1cb5e7fce0)
![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/2749bbc4-1749-487a-af5d-da6b945b2364)
![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/52aec37d-693a-430a-8611-4487533a8583)
![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/5ced8f87-0827-4f50-bf1a-9e1974c2770e)
![image](https://github.com/microsoft/vscode-dotnettools/assets/14598192/a3cb0657-924b-4946-9317-694b168fc3b1)

### Expected Behavior

I was hoping to see the number of variable references.

### Environment Information

Extension version: 1.6.0
VS Code version: Code 1.81.0 (Universal) (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:40:02.782Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|--crash-reporter-id 9a37cff7-e87a-4abc-bec7-dc4de918911b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30803845
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
vsctsb:30748421
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by AzuStar** [comment] 2023-08-06 11:53
I feel you. Have the same trouble, except my Unity projects refuse to load altogether.
Tried pretty much everything, all that's left is to fallback to C# v1 in the meantime. Uninstall all extensions relating C#. In Unity, in the asset/packages go to manifest.json and edit version visual studio tools from .20 to .18, this will restore resolution of types.

**Comment by timheuer** [comment] 2023-08-06 21:32
@jbevain

**Comment by cacheflowe** [comment] 2023-08-06 21:48
This seems like a duplicate of #329

**Comment by 976047167** [comment] 2023-08-07 02:53
you need to update unity package "Visual studio Editor"(not "Visual studio Code Editor") And regenerate proj files.

**Comment by jbevain** [comment] 2023-08-07 11:49
Given that the error is `The project file '/Users/egogames_unity/Documents/GitHub/SuperSnake/Assembly-CSharp.csproj'isin
unsupported format (for example, a traditional Net Framework project). It need be converted to new SDK style to work in C# Dev Kit`, I think this might be a case where something went wrong in your setup.

* In Unity's Package Manager (Windows -> Package Manager), make sure the `Visual Studio Editor` is updated to the version `2.0.20`. This is the version of the package that knows how to work with Visual Studio Code (the old `Visual Studio Code Editor` package is published by Unity and they stopped supporting it).
* In Unity's Preferences -> External Tools, make sure Visual Studio Code is selected as the External Editor, and do “Regenerate project files”. This will generate csproj files that the C# Dev Kit understands.

**Comment by jbevain** [comment] 2023-08-09 13:27
@juanvaquero did the above help address the issue?

**Comment by UA-Shane** [comment] 2023-08-09 13:40
@jbevain The same steps solved a similar issue for me, thank you

**Comment by jbevain** [comment] 2023-08-09 14:07
@UA-Shane good to hear, thanks for confirming!

**Comment by jbevain** [comment] 2023-08-12 13:56
Closing this as we haven't heard back. Let me know if you're still hitting issues. Thanks!

**Closed by jbevain** 2023-08-12 13:56 UTC
Labels: bug, area-unity
