### ISSUE TITLE
[BUG] couldn't create connection to server

### ISSUE THREAD

**Issue by alonprince** [microsoft/vscode-dotnettools#1285] opened 2024-07-15 10:10 UTC
### Describe the Issue

Using dotnet configured on PATH
Dotnet path: C:\Program Files\dotnet\dotnet.exe
Activating C# + C# Dev Kit...
[Error - 18:09:03] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
SyntaxError: Unexpected token ''... is not valid JSON
	at JSON.parse (<anonymous>)
	at f (c:\Users\admin\.vscode\extensions\ms-dotnettools.csdevkit-1.8.14-win32-x64\dist\extension.js:2:1436048)

![image](https://github.com/user-attachments/assets/a35f7388-c4ba-4087-9bd7-48c8e5e0833b)

Starting Clear environment...
Using preinstalled .NET runtime at "C:\Program Files\dotnet\dotnet.exe"
.NET server STDERR: Unhandled exception. 
.NET server STDERR: System.ArgumentNullException: Value cannot be null. (Parameter 'filePath')
   at Microsoft.VisualStudio.Telemetry.CommonProperty.CommonPropertyParserFactory.GetCommonPropertyParser(TelemetrySessionInternalBase session)
   at Microsoft.VisualStudio.Telemetry.TelemetrySessionInternalBase.LoadCommonProperties()
   at Microsoft.VisualStudio.ManagedTelemetry.VSCodeTelemetry.CreateAndStartDefaultSession(String sessionSettings)
   at Microsoft.VisualStudio.ManagedTelemetry.VSCodeTelemetry.StartTelemetrySessionAndCollector(String vsCodeTelemetryLevel, String customSessionId)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.<>c.<<BuildCommandLine>b__7_1>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<CancelOnProcessTermination>b__1_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.InvocationPipeline.InvokeAsync(IConsole console)
   at System.CommandLine.Parsing.ParseResultExtensions.InvokeAsync(ParseResult parseResult, IConsole console)
   at System.CommandLine.Parsing.ParserExtensions.InvokeAsync(Parser parser, String[] args, IConsole console)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.Main(String[] args)
   at Microsoft.VisualStudio.Server.ServiceBroker.Program.<Main>(String[] args)

Error occurred in launchDotNetServer: Error: Stream terminated before required bytes were read.
Failed at 'Spawn .NET server' (6035ms) with error: Error: Stream terminated before required bytes were read.
Failed at 'Clear environment' (6018ms) with error: Error: Stream terminated before required bytes were read.
Failed at 'handling solution file "c:\Users\admin\Documents\workspace\xxx\xxx.sln" in Dev Kit server' (6018ms) with error: Error: Stream terminated before required bytes were read.
.NET server exited with 3762504530

### Expected Behavior

Microsoft.CodeAnalysis.LanguageServer is not working

### Environment Information

vscode:
version: 1.91.1 (user setup)
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Windows_NT x64 10.0.22631

C# Dev Kit:
v1.8.14

**Comment by mattywarr** [comment] 2024-07-17 11:31
This is the same issue as the one I reported here: https://github.com/microsoft/vscode-dotnettools/issues/1256

**Comment by alonprince** [comment] 2024-07-19 04:25
> This is the same issue as the one I reported here: #1256

Thank you! I delete %Temp%\csdevkit\Telemetry\Resources.json file and resolved it!

**Comment by dibarbet** [comment] 2024-07-23 00:44
Yup, closing as duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1256

**Closed by dibarbet** 2024-07-23 00:44 UTC
Labels: bug, area-roslyn, high-priority
