### ISSUE TITLE
[BUG] Can't launch/debug macOS applications

### ISSUE THREAD

**Issue by rolfbjarne** [microsoft/vscode-dotnettools#1485] opened 2024-09-20 08:01 UTC
### Steps To Reproduce

1. Create a new macOS app with `dotnet new macos`
2. Open it in VSCode, try to launch or debug.

Right-click project -> Debug -> Start New Instance (or any of the two other options) results in "'/Users/rolf/test/dotnet/macos/macos.csproj' does not support debugging. No launchable target found.":

![Screenshot 2024-09-20 at 09 58 52](https://github.com/user-attachments/assets/158b8761-45f9-423e-ac00-6892ee153be5)

Menu Run -> Start Debugging:

1. Asks me to select a debugger:

![Screenshot 2024-09-20 at 10 00 13](https://github.com/user-attachments/assets/f9050aeb-04c2-4838-8b47-226593c84e5f)

2. "No C# project is currently loaded. Please create a C# project in order to debug."

![Screenshot 2024-09-20 at 10 00 18](https://github.com/user-attachments/assets/d1dfd2d8-0185-4ff2-a0e5-b7333494f518)

### Expected Behavior

Launch and debug works.

**Comment by WardenGnaw** [comment] 2024-10-07 21:12
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/549

**Closed by WardenGnaw** 2024-10-07 21:12 UTC
Labels: bug, area-dotnet-debugging
