### ISSUE TITLE
[SUGGESTION] Sync with Active Document Functionality like in Visual Studio

### ISSUE THREAD

**Issue by notblong** [microsoft/vscode-dotnettools#700] opened 2023-11-09 06:03 UTC
### Describe the feature you'd like

It would be really helpful to me if there is a functionality called 'Sync with Active Document' from VS. I had using it all the time while using VS and could be nice it is available in Solution Explorer in VS Code.

![image](https://github.com/microsoft/vscode-dotnettools/assets/61457360/bc172eed-8084-498e-a980-e01d0a8dbe92)

It can be placed here for example
![image](https://github.com/microsoft/vscode-dotnettools/assets/61457360/97ccb6a8-1900-49ca-8f3d-d4d3f5a078e4)

**Comment by smitpatel** [comment] 2023-11-09 17:05
Duplicate of #51

**Comment by webreidi** [comment] 2024-04-04 15:15
This is in pre-release now. Try it out and provide feedback. There is a setting to enable it (dotnet.automaticallySyncWithActiveItem).

**Comment by webreidi** [comment] 2024-05-21 22:56
There is a command palette command to manually sync.

**Closed by webreidi** 2024-05-21 22:56 UTC
Labels: enhancement, area-solution, fixed-pending-release

**Comment by notblong** [comment] 2024-05-22 09:19
Hi @webreidi, thanks for the update

@swythan, agreed it is kind of annoying. Luckily, I found the way to fix that is using keybinding for manual sync command

below are steps to do that for anyone come later:

`Ctrl + Shift + P` then search sync, click the gear icon
![image](https://github.com/microsoft/vscode-dotnettools/assets/61457360/9432265d-4764-4814-8a27-2a6bf8f67057)

set up your keybinding here, this is mine:
![image](https://github.com/microsoft/vscode-dotnettools/assets/61457360/b9e2444a-2188-421b-880d-2ead179993f8)

Voila, now just press your short cut keys and it will sync current file manually.
remember to turn off auto sync in settings.json
![image](https://github.com/microsoft/vscode-dotnettools/assets/61457360/6eac4a0a-b0ee-42e7-9cfa-ebc84bf9cab1)

**Comment by swythan** [comment] 2024-05-22 09:33
Thanks for finding that command for me. You saved me the trouble!

I also found there is another issue for preventing the annoying behaviour with the source control view: https://github.com/microsoft/vscode-dotnettools/issues/1117
