### ISSUE TITLE
[BUG] App Freezing After Using Debugger in .NET MAUI

### ISSUE THREAD

**Issue by Wyndal** [microsoft/vscode-dotnettools#1678] opened 2024-12-10 23:08 UTC
### Describe the Issue

When using the debugger in .NET MAUI for an extended period, performing actions such as inspecting objects, stepping through code, or hitting breakpoints, the app often freezes when attempting to continue execution or step over code.

It doesn't always have to be for an extended period, that just seems to increase the likelihood of freezing in my experience.

### Steps To Reproduce

1. Set a breakpoint on the first line in the OnAppearing override within the AssignmentDetailsPageView.xaml.cs
2. Log into QA (this is the default environment provided in the source code - login info available internally)
3. Click on an assignment card under the "Assignments" header. Try clicking on the blue facility name, or the facility image.
4. Wait for the breakpoint to hit
5. Spend 10-20 seconds inspecting objects in the debugger. The longer you spend, the more likely it seems to freeze afterwards.
6. Continue execution or try stepping over a few times afterwards

Video Available Internally

### Expected Behavior

I expect the App to continue processes as normal (finish navigating to the page in this example).

### Environment Information

Mac OS Sequoia 15.0.1
Xcode 16.0
iOS 15 Pro Max on iOS 17.5 (Simulator)

.NET SDK: 8.0.402
.NET Runtime: 8.0.11

VS Code Extensions:
.NET MAUI: 1.6.14
C#: 2.59.14
C# Dev Kit: 1.15.2
.NET Install Tool: 2.2.3

**Comment by mauroa** [comment] 2024-12-12 19:24
I'm closing this issue as a duplicate of: https://github.com/microsoft/vscode-dotnettools/issues/1526

The debugger team is already taking care of it.
Thanks

**Closed by mauroa** 2024-12-12 19:24 UTC
Labels: bug, duplicate, area-maui
