### ISSUE TITLE
[BUG] Allow to provde a path for Add New file on the solution folder

### ISSUE THREAD

**Issue by dileep-hegde** [microsoft/vscode-dotnettools#544] opened 2023-09-20 11:06 UTC
### Describe the Issue

When we choose “Add New File…” on a specific solution folder, a file is created inside the main solution folder where the solution file exists instead of the selected solution folder For Example: Readme file can exist on both main solution and a specific solution folder.

### Steps To Reproduce

1. Create a Solution folder inside a main solution.
2. Click on **Add New File..** on that solution folder.
Or
Right-click on solution folder and select **Add New file**.

### Expected Behavior

New file should be created in that specific solution folder.

### Environment Information

- OS: Windows 11
- VS Code Version: 1.82.2
- Extension: C# Dev Kit v0.4.10

**Comment by smitpatel** [comment] 2023-09-20 23:30
Solution folders are not real folders on disk. Can you elaborate expected behavior with an example?

**Comment by dileep-hegde** [comment] 2023-09-21 05:25
Considering Solution folders are not real folders on disk by design. Please check the example below.

Steps to reproduce the issue.

1.  Create a Solution folder inside a main Solution.
2.  Click on **Add Project..** on that Solution folder. Select Project template. 
3.  While naming the Project, it automatically includes the Solution folder name which creates a physical folder on the disk.
4.  Repeat Step 1 to Step 3 and add another Solution folder and projects.
5.  Now, Click on **Add New File..** on that Solution folder Or Right-click on Solution folder and select **Add New file**. 
6.  Repeat Step 5 on another Solution folder and **try to create a file with same name.**

Please check the folder structure as mentioned below.

```
Main Solution
|
|___Folder1
|   |___Project1
|   |___Project2
|   |___Readme.md
|
|___Folder2
|   |___Project1
|   |___Project2
|   |___Project3
|   |___Project4
|   |___Readme.md
|
|___Readme.md
|___Solution.sln
```

As files are virtually linked with sln file and created on the main solution folder. It won't allow file with same name. It shows **File already exists.**

As per folder structure, we need separate file with identical name (Readme) and should be located on both solution/physical folder and the main solution.

**Comment by smitpatel** [comment] 2024-05-17 21:46
Duplicate of #542 
The behavior in VS for solution folder and project folder is the same. We would be consistent whether we allow providing directory or not.

**Closed by smitpatel** 2024-05-17 21:46 UTC
Labels: enhancement, area-templates, triaged
