### ISSUE TITLE
The Project system ran into an unexpected problem

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#1456] opened 2024-09-10 20:08 UTC
Type: <b>Bug</b>

9/10/2024 4:06:36 PM
LimitedFunctionality
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.ProjectSystem.Server.ProjectLaunchConfigurationService.<InitializeCoreAsync>g__ActionBlockCallback|25_0(IProjectVersionedValue`1 data)
   at Microsoft.VisualStudio.ProjectSystem.ActionBlockSlimSync`1.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)
<--- (Inner Exception #0) 

Extension version: 1.10.16
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900H (20 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (8.11GB free)|
|Process Argv|. --crash-reporter-id c8e3650d-a133-42e9-901c-3aa8e8465629|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
refactort:31108082
pythonrstrctxt:31112756
flightc:31134773
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
defaultse:31133495
ei213698:31121563

```

</details>

**Comment by tmeschter** [comment] 2024-09-11 18:35
@denvifer That's going to be a different problem; could you file a new bug to track that?

**Comment by tmeschter** [comment] 2024-09-11 18:35
@burtonrodman Can you tell me more about your solution? E.g., what kind of projects it contains and how many?

**Comment by kvenkatrajan** [comment] 2024-09-11 18:38
@arkalyanms  - FYI - language service error- https://github.com/microsoft/vscode-dotnettools/issues/1456#issuecomment-2344401520

**Comment by burtonrodman** [comment] 2024-09-11 19:56
@tmeschter I have a workspace referencing 8 repos, each with 2-10 C# projects (Razor Pages, Blazor SSR, Blazor Web App (global webassembly interactive), class libraries, Razor Class Library, xunit test projects, worker service.  Most are net8.0, a few are still net6.0.  a few NuGet package projects multi-target net6.0;net8.0.  Also Aspire AppHost and ServiceDefaults.

**Comment by burtonrodman** [comment] 2024-09-11 19:57
also, I have a global.json in the root of each repo that pins to 8.0.400, rollForward latestMinor

**Comment by dibarbet** [comment] 2024-09-16 18:48
I suspect this might be caused by https://github.com/dotnet/vscode-csharp/issues/7514

@burtonrodman  - two requests
1.  Let me know if C# extension version `2.45.25` fixes the issue
2.  If it does not, please set `dotnet.server.trace` to `Trace`, and attach the 'C#' output window logs here the next time it happens.

**Comment by arkalyanms** [comment] 2024-10-02 21:39
closing this as fixed via https://github.com/dotnet/roslyn/pull/75046. Please reopen if the latest release still hits this issue.

**Closed by arkalyanms** 2024-10-02 21:39 UTC
Labels: bug, needs-more-info, area-roslyn, area-project-cps
