### ISSUE TITLE
[BUG] Xaml intellisence not working using MAUI

### ISSUE THREAD

**Issue by charleypeng** [microsoft/vscode-dotnettools#1082] opened 2024-04-29 05:46 UTC
### Describe the Issue

os: macos 14.4 m1 pro
platform: dotnet8.0.204/ vscode 1.88.1 / maui  v0.10.61/ c# dev kit v1.4.29

xaml intellisense not working at all. 

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/2049886">2049886</a>

**Comment by emaf** [comment] 2024-05-07 14:06
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/565

**Closed by emaf** 2024-05-07 14:06 UTC
Labels: bug, area-maui, vs-sync, vs-syncd
