### ISSUE TITLE
[BUG] Projects failed to load after installing c# Dev Kit

### ISSUE THREAD

**Issue by chemari** [microsoft/vscode-dotnettools#367] opened 2023-08-09 10:12 UTC
### Describe the Issue

After installing C# Dev Kit in my Mac, and opening an Unity project, I receive this error in the console

<img width="117" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/4841449/786eb385-08bc-400c-a92f-d8e322cfc770">

_"Project system initialization finished. 0 project(s) are loaded, and 49 failed to load."_

There are no error descriptions in the console or any clue that could lead me to a solution, so couldnt get any info why this is happening. But since then I cannot navigate through "Go to definition", "Go to references", etc. The red underline compilation errors also disappeared from the editor!

### Steps To Reproduce

1. The project Im opening is an Unity 2021.3 project, in Unity I have the extension Visual Studio Editor 2.0.20
2. Open VS code 1.81 in Mac
3. Install C# Dev Kit 0.3.21 and let the project load
4. Check the console (project) output

**Comment by AzuStar** [comment] 2023-08-09 10:20
Before anyone comments.
Pre-release versions of (C#, C# devkit) do not help. Forcing C# to use `omnisharp: true` and `moderndotnet: flase` also doesn't help.
This is a duplicate of [#366](https://github.com/microsoft/vscode-dotnettools/issues/337), [#337](https://github.com/microsoft/vscode-dotnettools/issues/337), [#335](https://github.com/microsoft/vscode-dotnettools/issues/335)

**Comment by jbevain** [comment] 2023-08-09 12:58
Hi! Based on your error, it looks like VS Code is trying to open a solution containing old csproj files that are not supported by the C# Dev Kit. You can verify it by opening a .csproj, if they start with:

```xml
<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
```

Then that's what is causing the issue.

* You've already upgraded the `Visual Studio Editor` package in Unity to 2.0.20,
* Delete all `.csproj` and all `.sln` files in the root folder of your Unity project,
* In Unity's preferences, make sure Visual Studio Code is selected as your External Editor,
* Press Regenerate Project files.

The `.csproj` files should now start with:

```xml
<Project ToolsVersion="Current" Sdk="Microsoft.NET.Sdk">
```

And the C# Dev Kit should now be able to open the solution.

**Comment by chemari** [comment] 2023-08-09 13:18
Hi, I follow all the steps you mention, and after this I made sure the header of my csproj files is this:

`<Project ToolsVersion="Current" Sdk="Microsoft.NET.Sdk">
`
Unfortunately the problem persists.

**Comment by jtsom** [comment] 2023-08-09 14:55
I am seeing this also, and am seeing this error when looking at the Solution Explorer under each project:
![image](https://github.com/microsoft/vscode-dotnettools/assets/13488/fc79a09c-2d08-4b54-a11d-48a493c3f2bd)

The only thing I haven't tried - I had updated Visual Studio to the latest Preview version (Version 17.8.0 Preview 1.0) and it looks like it installed a preview version of .NET 8:
![image](https://github.com/microsoft/vscode-dotnettools/assets/13488/f81a111a-9e84-44b3-8f8f-021fe9ed02fe)

**Comment by chemari** [comment] 2023-08-09 15:04
In my case seems its working with .NET 7
This is the full output of the project:

```
2023-08-09 16:04:56.154 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  5.0.302 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-09 16:04:56.154 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.203
 Commit:    5b005c19f5

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.203/

Host:
  Version:      7.0.5
  Architecture: x64
  Commit:       8042d61b17

.NET SDKs installed:
  5.0.302 [/usr/local/share/dotnet/sdk]
  7.0.203 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-09 16:05:01.023 [info] Project system initialization finished. 0 project(s) are loaded, and 49 failed to load.
```

**Comment by jbevain** [comment] 2023-08-09 15:13
Thanks for reporting this. You're the second one on macOS 10.15/x64 reporting a similar issue, we're trying to see if we can reproduce it.

**Comment by tmitchel2** [comment] 2023-08-10 09:19
I have this issue.  I looked into the extension logs and found this.

[exthost/ms-dotnettools.csdevkit/ServiceHub/FA474B2D-Microsoft.VisualStudio.ProjectSystem.CompositionService-9528-gwcjacua-1.log]

08/10/2023 10:03:58 Greenwich Mean Time: Error : 9528 :!!Resolve NET Core SDK: Failed
System.DllNotFoundException: Unable to load shared library 'hostfxr' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/hostfxr.dylib, 1): image not found
dlopen(/Users/tmitchel2/.vscode/extensions/ms-dotnettools.csdevkit-0.4.2-darwin-x64/components/CPS/platforms/darwin-x64/node_modules/@microsoft/visualstudio-projectsystem-buildhost.darwin-x64/hostfxr.dylib, 1): image not found

Which in turn relates to this issue in the MSBuildLocator
https://github.com/microsoft/MSBuildLocator/issues/210

**Comment by yuhuihu** [comment] 2023-08-10 11:44
> In my case I am using .NET 7 This is the full output of the project:
> 
> ```
> 2023-08-09 16:04:56.154 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
>  Version:   7.0.203
>  Commit:    5b005c19f5
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/7.0.203/
> 
> Host:
>   Version:      7.0.5
>   Architecture: x64
>   Commit:       8042d61b17
> 
> .NET SDKs installed:
>   5.0.302 [/usr/local/share/dotnet/sdk]
>   7.0.203 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
> 
> 2023-08-09 16:04:56.154 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
>  Version:   7.0.203
>  Commit:    5b005c19f5
> 
> Runtime Environment:
>  OS Name:     Mac OS X
>  OS Version:  10.15
>  OS Platform: Darwin
>  RID:         osx.10.15-x64
>  Base Path:   /usr/local/share/dotnet/sdk/7.0.203/
> 
> Host:
>   Version:      7.0.5
>   Architecture: x64
>   Commit:       8042d61b17
> 
> .NET SDKs installed:
>   5.0.302 [/usr/local/share/dotnet/sdk]
>   7.0.203 [/usr/local/share/dotnet/sdk]
> 
> .NET runtimes installed:
>   Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
>   Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
>   Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
> 
> Other architectures found:
>   None
> 
> Environment variables:
>   Not set
> 
> global.json file:
>   Not found
> 
> Learn more:
>   https://aka.ms/dotnet/info
> 
> Download .NET:
>   https://aka.ms/dotnet/download
> 
> 2023-08-09 16:05:01.023 [info] Project system initialization finished. 0 project(s) are loaded, and 49 failed to load.
> ```

The same issue.

Also mac 13.4.1

**Comment by chemari** [comment] 2023-08-10 13:18
Hi @yuhuihu I tried to add your snippet of code to my setting.json and restart VS, but didnt fix the problem in my case :(

**Comment by xMoRoZoKx** [comment] 2023-08-11 08:05
i have this problem in windows 11((

**Comment by firekim2** [comment] 2023-08-12 05:55
In my case, I found a reason with the .net SDK version.
I installed .net sdk with brew which only support upto 7.0.100 version and seems like not supported with c# dev kit.
After removing dotnet in brew, I updated to 7.0.400 with binary installation and it works now.

https://learn.microsoft.com/en-us/dotnet/core/install/macos
I followed this!

**Comment by roboriaan** [comment] 2023-08-16 10:00
I partially solved the issue by reinstalling the C# Devkit. All projects are loading but no code navigation works (F12). That's a biggy for me. Just as a test I loaded the solution up in Visual studio 2022. Works there but not in vscode. Been long enough with MS vscode tools to tell you this is a trend. Almost feels intentional.

**Comment by eastedgeZack** [comment] 2023-08-16 17:26
Also seeing this problem on Mac Big Sur

**Comment by symbion6** [comment] 2023-08-17 09:09
Also seeing this problem. Running VS Code on an Intel Core i7 MacBook with MacOS 11.3.

* Re-installed .Net Core from this link: https://dotnet.microsoft.com/en-us/download
* Re-installed VS Code
* Added the C# Dev Kit extension
* Added the global.json as per @firekim2 's  recommendation.
* Loaded my project, double checked the first line of the .csproj file, which is OK

This is the log:

```
2023-08-17 11:05:56.569 [info] Project system initialization finished. 0 project(s) are loaded, and 2 failed to load.
2023-08-17 11:05:56.658 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.3
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/myusername/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download


```

**Comment by tmeschter** [comment] 2023-08-17 20:56
@symbion6 When you run into this problem, would you be able to run "Developer: Open Extension Logs Folder" from the command palette, and then zip up and share the "ms-dotnettools.csdevkit" folder? I suspect an error message about this issue may be buried there.

**Comment by SimeonIksanov** [comment] 2023-08-18 06:49
[ms-dotnettools.csdevkit.zip](https://github.com/microsoft/vscode-dotnettools/files/12376289/ms-dotnettools.csdevkit.zip)
same problem

**Comment by chemari** [comment] 2023-08-18 09:36
> 

Thanks @firekim2, unfortunately it didnt work. I updated to 7.0.400 (and removed the older version) and added the global.json file, but I keep getting the same error.

```
2023-08-18 11:35:41.687 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  /Users/jolea/global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-18 11:35:43.594 [info] Project system initialization finished. 0 project(s) are loaded, and 48 failed to load.
```

**Comment by tmeschter** [comment] 2023-08-21 16:58
@YoungXiang I believe that is a different problem; can you please open a new issue so we can track it properly?

**Comment by tmeschter** [comment] 2023-08-21 17:15
For those of you experiencing this issue (specifically, the one where hostfxr is not being found) we are actively working on it. The failure is occurring in a code path that attempts to detect the available .NET SDKs; it is challenging to get this to work correctly across all relevant architectures, operating systems, and install methods.

**Comment by mgmhunt** [comment] 2023-08-25 02:35
On Mac this will fix the 'xx project failed to load' (adjust version as necessary), thanks to 

Copy this file:
/usr/local/share/dotnet/host/fxr/7.0.10/libhostfxr.dylib

To:
/usr/local/share/dotnet/shared/Microsoft\.NETCore\.App/7\.0\.10/libhostfxr\.dylib

(which is where the extension is looking, thanks to @tmitchel2  for pointing out the log location.

**Comment by jonnymarkd** [comment] 2023-08-27 22:19
Same issue.

mgmhunt's temp fix (comment above) doesn't work for me. I don't have the ...Microsoft.NetCore.App/ folder...

Output as follows: 

2023-08-27 23:11:32.380 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.400/

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

.NET SDKs installed:
  3.1.302 [/usr/local/share/dotnet/sdk]
  6.0.413 [/usr/local/share/dotnet/sdk]
  7.0.101 [/usr/local/share/dotnet/sdk]
  7.0.400 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.10 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-27 23:11:32.385 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.

**Comment by mgmhunt** [comment] 2023-08-27 23:28
> Same issue.
> 
> mgmhunt's temp fix (comment above) doesn't work for me. I don't have the ...Microsoft.NetCore.App/ folder...
> 
> Output as follows:
> 
[/usr/local/share/dotnet/shared/Microsoft.NETCore.App] Microsoft.NETCore.App 7.0.10 

Have you tried right-clicking on the Microsoft.NETCore.App and choosing Show Package Contents?  should take you to folder structure

**Comment by jonnymarkd** [comment] 2023-08-28 08:58
Thanks @mgmhunt - Did the trick for me. Now for the ext fix...

**Comment by chemari** [comment] 2023-08-28 12:41
> On Mac this will fix the 'xx project failed to load' (adjust version as necessary)... until the ext is fixed
> 
> Copy this file: /usr/local/share/dotnet/host/fxr/7.0.10/libhostfxr.dylib
> 
> To: /usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10/libhostfxr.dylib
> 
> (which is where the extension is looking, thanks to @tmitchel2 for pointing out the log location.)

I tried this. I keep receiveing the same "0 projects loaded 45 failed to load". But now I receive some extra errors I have never seen before. I get one of this for each project:

`2023-08-28 14:39:08.772 [error] Failed to load project '/Users/jxxx/Projects/tribes/Unity.PlayerPrefsEditor.Samples.SampleScene.csproj'. One or more errors occurred. (This project is not supported in C# Dev Kit.)`

**Comment by mgmhunt** [comment] 2023-08-28 22:56
@chemari sounds like progress actually :) ie generating errors vs not loading at all.  Maybe regen the csproj files via Unity Preferences -> External Tools. I'm running the exact setup as you in the original comment.

**Comment by YuliiaKovalova** [comment] 2023-08-30 15:07
The issue was addressed in the scope of https://github.com/dotnet/msbuild/issues/9038

You can use the package with the fix https://www.nuget.org/packages/Microsoft.Build.Locator/1.6.1.

**Comment by zihli** [comment] 2023-08-31 14:57
I had the same issue on macOS Big Sur. I updated OS to Monterey and it works now.

**Comment by pH7-Simpl** [comment] 2023-09-03 11:09
2023-09-03 18:07:23.728 [warning] The project file 'c:\Users\ASUS\Documents\SimpleFuturistic's Coding Projects\C# Projects\Explore2D\Assembly-CSharp.csproj' is in unsupported format (for example, a traditional .NET Framework project). It need be converted to new SDK style to work in C# Dev Kit.
2023-09-03 18:07:23.860 [error] Failed to load project 'c:\Users\ASUS\Documents\SimpleFuturistic's Coding Projects\C# Projects\Explore2D\Assembly-CSharp.csproj'. One or more errors occurred. (This project is not supported in C# Dev Kit.)
2023-09-03 18:07:23.867 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.
<img width="315" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/116820141/c4b80b8f-93a1-4637-8cda-0ca7d2ac2cda">
How to fix the typo on the csproj' ?

**Comment by lifengl** [comment] 2023-09-06 02:36
there are multiple different issues in this thread:
 1, a common problem, the extension cannot resolve SDK on macOS Big Sur. The same issue happens with SDK installed with HomeBrew, and also it hits some Linux distributions. That problem, as Yullia mentioned, should be fixed when the next pre-release update comes out in a few days.

2, traditional unity projects, (or other traditional mono projects or Framework projects on windows)  those are currently not supported by C# Dev Kit, but some pending fix in this area would allow language experience to work. It is still on-going work.

3, extension was broken when NET 8 preview 7 was out. it was a gap between multiple product line due to the extension runs on NET 7 runtime loads build related assemblies from SDK, which were updated to build on NET 8 runtime.  During initialization, this corrupted a cache file, which lead it tricky to apply a workaround (that is why some people might not get it to work with a global.json file, but some might) This issue should have been addressed with a later update.

**Comment by 1337CodeGod** [comment] 2023-09-07 18:49
This post from Unity solved my issues:
https://forum.unity.com/threads/microsoft-previews-unity-extension-for-visual-studio-code.1468913/

- You need Unity 2021 or higher and the "Visual Studio Editor" package version 2.0.20 or above installed in your Unity project.
- Remove any old, deprecated VS Code packages from Unity. Install the new Unity Extension in Visual Studio Code, which will also install necessary dependencies like the C# Dev Kit.
- Set Visual Studio Code as your external script editor in Unity Editor under External Tools.
- You can also get the latest [Unity Extension for VS Code](https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/)

**Comment by CrisViM** [comment] 2023-09-12 10:22
> This post from Unity solved my issues: https://forum.unity.com/threads/microsoft-previews-unity-extension-for-visual-studio-code.1468913/
> 
> * You need Unity 2021 or higher and the "Visual Studio Editor" package version 2.0.20 or above installed in your Unity project.
> * Remove any old, deprecated VS Code packages from Unity. Install the new Unity Extension in Visual Studio Code, which will also install necessary dependencies like the C# Dev Kit.
> * Set Visual Studio Code as your external script editor in Unity Editor under External Tools.
> * You can also get the latest [Unity Extension for VS Code](https://devblogs.microsoft.com/visualstudio/announcing-the-unity-extension-for-visual-studio-code/)

It worked for me. Thank's a lot!

**Closed** 2023-09-14 17:54 UTC
Labels: bug, area-project-cps, area-unity, mac

**Comment by AmineAndam04** [comment] 2023-09-24 21:38
Hi.
The same thing happened to me. I updated the Visual Studio Editor package at the Package Manager and this solved the issue for me.

**Comment by aoshfan** [comment] 2024-06-30 10:24
> Hi! Based on your error, it looks like VS Code is trying to open a solution containing old csproj files that are not supported by the C# Dev Kit. You can verify it by opening a .csproj, if they start with:
> 
> ```
> <Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
> ```
> 
> Then that's what is causing the issue.
> 
> * You've already upgraded the `Visual Studio Editor` package in Unity to 2.0.20,
> * Delete all `.csproj` and all `.sln` files in the root folder of your Unity project,
> * In Unity's preferences, make sure Visual Studio Code is selected as your External Editor,
> * Press Regenerate Project files.
> 
> The `.csproj` files should now start with:
> 
> ```
> <Project ToolsVersion="Current" Sdk="Microsoft.NET.Sdk">
> ```
> 
> And the C# Dev Kit should now be able to open the solution.

This kind of similar fix for me.

but my place need to change was in `.sln` file. 
In the file I just need to fix the location of my `.csproj`. file.
