### ISSUE TITLE
Two solution files created by default

### ISSUE THREAD

**Issue by n3rdworldorder** [microsoft/vscode-dotnettools#408] opened 2023-08-18 09:23 UTC
Type: <b>Bug</b>

1. Create a new .NET MAUI application via the command palette.
2. When the solution is created there are two solution files, one at the top-level of the folder hierarchy and one under the default "MauiApp1" folder.
3. Both solution files are different.
4. User then prompted to select which solution file to use for Intellisense.

Extension version: 0.2.13
VS Code version: Code 1.81.1 (6c3e3dba23e8fadc360aed75ce363ba185c49794, 2023-08-09T22:22:42.175Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (15.58GB free)|
|Process Argv|--crash-reporter-id e5c4b93d-b44a-4fe4-97d5-2d71b2d866e9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
89544117:30613380
a9j8j154:30646983
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv1:30812748

```

</details>

**Comment by mcumming** [comment] 2023-08-18 18:54
@n3rdworldorder , What version of .NET and the .NET MAUI workloads are you using? This was fixed in the latest releases of .NET 7 and .NET 8 Preview. Try upgrading your version of .NET to the latest and this issue should be reolved.

**Comment by mauroa** [comment] 2024-03-19 17:16
Hi @n3rdworldorder.
We are trying to re-activate or cleanup old issues related to the VS Code MAUI extension that were left into "Need More Info" state and didn't get a response in a while.
I would like to know if you continued working with MAUI projects in VS Code and if you still have any issue related to this ticket.
We will proceed to close this ticket in case we don't get a new response in a few days.
Thanks in advanced.

**Comment by mauroa** [comment] 2024-03-28 15:45
Closing due to lack of activity and because the ticket is too old. Please try to reproduce the issue with the latest VS Code MAUI version and if you still experience it, feel free to request a re-opening or open a new ticket. Thanks

**Closed by mauroa** 2024-03-28 15:45 UTC
Labels: needs-more-info, triaged, area-maui
