### ISSUE TITLE
XAML Hot Reload broken?

### ISSUE THREAD

**Issue by sindrevr** [microsoft/vscode-dotnettools#1266] opened 2024-07-07 10:43 UTC
### Describe the Issue

Hi,

In the beginning of June after using pre-release of .NET MAUI / C# and C# Dev Kit XAML hot reload was working on my VSCode for Mac (android,ios). Now its broken. Tried removing everything and reinstalled VSCode. Installed only stable version of .NET Maui / C# and C# Dev. kit. XAML hot reload worked then when testing with a new project. But then stopped again. And no matter if i use pre-release or stable I could not have it working again. C# hot reload works though, but not XAML part. Tried installing a fresh VSCode on my Windows, and tested both Stable and pre-release on a blank Windows app. Same result. C# hot reload works... But XAML hot reload does not.

### Steps To Reproduce

1. Windows or Mac does not matter.
2. Create new project and XAML hot reload will not work.

**Comment by sindrevr** [comment] 2024-07-08 06:16
Some more information about my system, I have tried both with "Just My Code" enabled and disabled.
Any hints is appreciated.

Android:
```
[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.HotReload.Forms.dll
Loaded '/Users/sindrevr/Downloads/sau1234/sau1234/obj/Debug/net8.0-android/android/assets/Microsoft.Maui.Controls.HotReload.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
```

iOS:
`Loaded '/Users/sindrevr/Library/Developer/CoreSimulator/Devices/090E3F13-BE0F-471E-B2AF-F0B20567F94C/data/Containers/Bundle/Application/B23DB5E3-FB69-4D1F-BCB3-9BF560BDE128/sau1234.app/Microsoft.Maui.Controls.HotReload.Forms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.`

sindrevr@Sindres-MacBook-Pro-2 dotnet-core-uninstall % dotnet --info
.NET SDK:
 Version:           8.0.302
 Commit:            ef14e02af8
 Workload version:  8.0.300-manifests.3d4bb602
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.302/

.NET workloads installed:
 [maui]
   Installation Source: SDK 8.0.300
   Manifest Version:    8.0.40/8.0.100
   Manifest Path:       /usr/local/share/dotnet/sdk-manifests/8.0.100/microsoft.net.sdk.maui/8.0.40/WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.6
  Architecture: arm64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.302 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by emaf** [comment] 2024-07-15 17:31
@BretJohnson

**Comment by ziomek64** [comment] 2024-07-16 10:16
For me XAML hot reload works in emulator but doesn't in real device

**Comment by BretJohnson** [comment] 2024-07-23 07:26
> For me XAML hot reload works in emulator but doesn't in real device

@ziomek64 - For issues with XAML hot reload not working on android physical devices, can you please reply on https://github.com/microsoft/vscode-dotnettools/issues/1241 or create a new issue (that should be fixed now, but I'd like you to confirm you don't have any other issues).

**Comment by BretJohnson** [comment] 2024-07-23 07:28
@sindrevr Assuming this still fails for you, can you please search the Debug output panel for the string "Hot Reload" and share what messages are there. Most errors starting up XAML Hot Reload will show up there. Thanks.

**Comment by yurkinh** [comment] 2024-07-23 10:35
Same for me.
 Created a blank new project, updated maui nugets to the latest one (8.0.70).
C# hot reload works but Xaml hot reload -does not.
Debug output : "No changes were found."

**Comment by BretJohnson** [comment] 2024-07-23 15:58
@yurkinh - I tested and it worked for me on iOS simulator, using with the latest pre-release versions of MAUI extensions (v1.2.3), C# (2.39.28), and C# DevKit (v1.9.8). Here are some things to look for:
- When launching the app, ensure that "Including assemblies for Hot Reload support" shows up in the Terminal window
- After the app launch, look in the `Debug Console` output panel. Search for `Hot Reload`. Any errors creating the Hot Reload connection should be noted there.
- Finally you can look in the .NET Hot Reload output pane, for messages like "11:50:8 XAML: Applying XAML Hot Reload update." - the XAML prefix indicates it's XAML Hot Reload, not C# Hot Reload.
Let me know what you find with the above & also please share the extension versions you are using (for MAUI, C#, and C# DevKit).

**Comment by yurkinh** [comment] 2024-07-23 16:32
I'm using the same config also tried with release versions.
"_Bundle Id: com.companyname.testhotreload
    App Id: com.companyname.testhotreload
  Including assemblies for Hot Reload support
  TestHotReload -> /Users/yholemb/Downloads/TestHotReload/bin/Debug/net8.0-ios/iossimulator-arm64/TestHotReload.dll"_

  Debug output ".NET Hot Reload":
  19:30:2 Changes were successfully applied.
19:30:21 💡 Possible changes were found. -> C# changes
19:30:24 Changes were successfully applied.
19:30:41 No changes were found. -> Xaml Changes

**Comment by BretJohnson** [comment] 2024-07-23 18:09
Your launch.json looks fine. Can you also share the output of the `Debug Console` pane, searching for `Hot`. See below.
Normally errors will show up there (though I don't have any errors in the screenshot below).
You can also try setting 


![image](https://github.com/user-attachments/assets/2f1fa4e3-96d6-434e-9e1c-df8416e8dd4a)

**Comment by yurkinh** [comment] 2024-07-24 08:47
Created a blank new app and launched it in debug.
After changing xaml still -> 11:42:15 No changes were found.

![Screenshot 2024-07-24 at 11 42 33](https://github.com/user-attachments/assets/3d299d2a-8945-4020-a4ed-a3d61b780de6)
![Screenshot 2024-07-24 at 11 45 56](https://github.com/user-attachments/assets/36caedbb-4c53-41bc-8798-8bdda2e41fe3)

**Comment by yurkinh** [comment] 2024-07-25 15:27
@BretJohnson  I have tried also on my windows machine and got a bit different output in debug pane

"[monodroid-assembly] open_from_bundles: failed to load assembly Microsoft.Maui.Controls.HotReload.Forms.dll
Loaded 'G:\Projects\TestApp3\obj\Debug\net8.0-android\android\assets\Microsoft.Maui.Controls.HotReload.Forms.dll'"

**Comment by BretJohnson** [comment] 2024-07-26 21:01
@yurkinh - Here are two other things to check:
- When launching the app can you ensure that the message "Including assemblies for Hot Reload support" shows up in the Terminal window. This message is output while the app is being built, about to be started.
- Assuming the "Including assemblies for Hot Reload support" message is there, next try this: Set the `HOTRELOAD_XAML_LOG_MESSAGES` environment variable to any non-empty value. Launch VS Code from a console window with the env variable set. Then rebuild/rerun the app. With env variable set, verbose logging will be enabled on the app, showing more information in the Debug pane. Continue to search for the string `Hot` there. If it tries to initial hot reload at all, you should see more info indicating that. Share what you see.

If neither of the above two things produces useful results, we can also do a call to investigate together on Teams. I'm up for that if you are. I can provide a booking link if/when the time comes for that - but try the other two things first. And thanks for your help tracking this problem down.

**Comment by BretJohnson** [comment] 2024-07-26 21:03
Oh @yurkinh also ensure that XAML Hot Reload didn't get disabled for some reason, ensuring this option is checked (it is by default):
![image](https://github.com/user-attachments/assets/be8cf780-7358-4f6e-995f-e97aba2441c8)

**Comment by yurkinh** [comment] 2024-07-29 17:17
Hi @BretJohnson 
Finally I was able to fix Xaml HotReload. I have managed to do this with a clean (and separate profile) in VScode containing bare minimal and only needed extensions for MAUI development (C# + Devkit.NET + MAUI extension). It looks like it was conflicting with the .NET Meteor extension. All checkmarks related to HotReload are enabled.
There are still a few issues to investigate.
1. Start Maui profile (maui extensions) . Then meteor profile and start the app. Then back to Maui profile. And Xaml Hot reload will stop working.
2. In some more complex apps Xaml HotReload works (according to logs) but the UI is not updated, especially if I do some navigation. I can demo it if needed to clarify the steps

**Comment by BretJohnson** [comment] 2024-07-29 19:29
@yurkinh I tested with the .NET Meteor extension enabled, and MAUI XAML Hot Reload still works for me, so I'm not sure that there really is a Meteor conflict - it may be something else you're seeing. Do you want to do a call? That maybe the best way to demo/investigate both the issues with Hot Reload not working at all (sometimes) and the issues you mentioned with complex XAML.  You can use this link to book a call: [Bookings with me - Bret Johnson - Outlook (office.com)](https://outlook.office.com/bookwithme/user/2ce3c3bdf1a146fcbfbe974530aefe8e%40microsoft.com/meetingtype/fe7eaa5f-755e-4e31-acdc-58183f966277?anonymous=). Thanks for helping track these issues down.

**Comment by yurkinh** [comment] 2024-07-29 20:03
Sure. I will show you all the issues I found with Xaml hot reload.
I have scheduled a meeting for tomorrow.

**Comment by ziomek64** [comment] 2024-08-09 14:05
I also started getting this issue..

**Comment by nm4568** [comment] 2024-08-10 16:51
I have the same issue and similar environment.  Here is the Exception I see in the Debug Console.

```
Hot Reload initialization error: Hot Reload Bootstrap failed: System.AggregateException: One or more errors occurred. (Connection refused)
``` 

MacOS Sonoma v14.5
VS Code v1.92
.NET MAUI Extension v1.2.12
C# Dev Kit v1.10.4
C# v2.41.26

**Comment by BretJohnson** [comment] 2024-08-20 16:54
@nm4568 - Would you mind creating a separate bug for your issue. Also, can you please note if it always fails when debugging using the iOS simulator or just intermittently. I'd like to track it down (and sorry for the late reply on this).
@ziomek64 - Can you please create a separate bug for your failure as well. Also please check these things: https://github.com/microsoft/vscode-dotnettools/issues/1266#issuecomment-2245634891. Thanks.

**Comment by ziomek64** [comment] 2024-08-20 17:09
> @nm4568 - Would you mind creating a separate bug for your issue. Also, can you please note if it always fails when debugging using the iOS simulator or just intermittently. I'd like to track it down (and sorry for the late reply on this).
> @ziomek64 - Can you please create a separate bug for your failure as well. Also please check these things: https://github.com/microsoft/vscode-dotnettools/issues/1266#issuecomment-2245634891. Thanks.

It started to work, i think i wasn't initializing debugger correctly, I didn't set launch settings

**Comment by nm4568** [comment] 2024-08-21 00:15
> @nm4568 - Would you mind creating a separate bug for your issue. Also, can you please note if it always fails when debugging using the iOS simulator or just intermittently. I'd like to track it down (and sorry for the late reply on this). @ziomek64 - Can you please create a separate bug for your failure as well. Also please check these things: [#1266 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/1266#issuecomment-2245634891). Thanks.

I created a new issue - https://github.com/microsoft/vscode-dotnettools/issues/1381

I noted in the issue that the exception is thrown intermittently.  Regardless, hot reload doesn't function at all whether or not this exeption is thrown.

**Comment by mattleibow** [comment] 2024-08-26 16:20
I don't seem to have hot reload either, 
![image](https://github.com/user-attachments/assets/3ced41ae-da0e-4eea-848a-5a751236c8e6)

![image](https://github.com/user-attachments/assets/82a5d244-e6c1-405e-874a-514e69432b29)

I am using .NET 9 preview 7 with the latest workloads and the latest preview versions of the extensions.

**Comment by mattleibow** [comment] 2024-08-26 16:24
Seems I had to reload windows yet again, so sad me but now less sad me.

**Comment by mattleibow** [comment] 2024-08-27 14:56
Not sure how related, but this is a new issue I created with more steps that are not really reproducible after trying again a few times.

**Comment by BretJohnson** [comment] 2024-08-27 15:01
@mattleibow - if you created a new issue, can you share the link; thx

**Comment by mattleibow** [comment] 2024-08-27 15:04
Oops :) https://github.com/microsoft/vscode-dotnettools/issues/1401 Forgot to paste

**Comment by BretJohnson** [comment] 2024-10-22 22:56
Closing - The original issue was a conflict with Meteor & subsequent reported problems are tracked as separate bugs (links above).

**Closed** 2024-10-22 22:57 UTC
Labels: bug, area-maui, area-hotreload, delighter-sc
