### ISSUE TITLE
[BUG] ".NET MAUI SDK not found" error with VS Code if folder contains more than one file with an extension ending with 'proj'

### ISSUE THREAD

**Issue by whodges** [microsoft/vscode-dotnettools#654] opened 2023-10-26 18:13 UTC
### Describe the Issue

VS Code will present a ".NET MAUI SDK verification failed with an unexpected error: Failed to retrieve the .NET SDK information" if there's more than one file in the MAUI project folder with a file extension that ends with 'proj'.  At least on my MacBook.  Some example file scenarios:

MauiApp1.csproj and PreBuild.proj:  FAIL
MauiApp1.csproj and PreBuild.proj1:  SUCCESS
MauiApp1.csproj and PreBuild.xyzproj:  FAIL

### Steps To Reproduce

1. Install VS Code on a MacBook (maybe this happens on other platforms too...I haven't tried).
2. Create a .NET MAUI app (e.g., MauiApp1).  I used .NET 7 since I'm on a Mac.
3. Add a file named 'SomeFile.proj' to the same folder where MauiApp1.csproj resides.
4. Load the folder/solution in VS Code that already has the .NET MAUI and C# Dev extensions installed.
5. The ".NET MAUI SDK not found" error should appear in the lower right.

### Expected Behavior

The .NET MAUI SDK should be found...it shouldn't care that there are other files with extensions ending in 'proj'.

### Environment Information

macOS 13.6
VS Code 1.83.1
.NET MAUI extension 0.5.32 (pre-release)
C# Dev Kit extension 1.0.12 (pre-release)

> VS bug [#1910900](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1910900)

**Comment by tmeschter** [comment] 2023-10-26 21:23
Moving to "area-maui" for initial investigation as this seems to be specific to MAUI projects.

**Comment by whodges** [comment] 2023-11-01 18:36
I confirmed that it happens with VS Code on Windows too.

**Comment by emaf** [comment] 2023-11-03 14:54
Dupe of https://github.com/microsoft/vscode-dotnettools/issues/523

**Closed by emaf** 2023-11-03 14:54 UTC
Labels: bug, triaged, area-maui, vs-sync
