### ISSUE TITLE
[BUG] Code text color issue

### ISSUE THREAD

**Issue by BachiMjavanadze** [microsoft/vscode-dotnettools#264] opened 2023-07-14 15:53 UTC
There are no colors in the code text. Changing theme (dark, light) does not helps:

![image](https://github.com/microsoft/vscode-dotnettools/assets/38082501/37afdb15-3a9f-49c4-983d-71ef6163e806)

After rebooting the VSCode, sometimes the colors come back but I can't catch the logic.

**Comment by timheuer** [comment] 2023-07-14 18:34
Dupe of #211

**Comment by BachiMjavanadze** [comment] 2023-07-14 19:51
closed because of dupe

**Closed** 2023-07-14 19:51 UTC
Labels: bug, area-editing
