### ISSUE TITLE
Jump to test implementation

### ISSUE THREAD

**Issue by nrader95** [microsoft/vscode-dotnettools#506] opened 2023-09-11 17:14 UTC
Type: <b>Feature Request</b>

Currently there is no way to navigate to the place where specific test is defined when using DevKit's tests tab, so even if i want to see result of failed test or want to place a break point before debugging it, first i need to go search it by name manually.
It would be nice to have context menu entry for tests to directly jump to test method implementation.

Extension version: 0.4.10
VS Code version: Code 1.82.0 (8b617bd08fd9e3fc94d14adb8d358b56e3f72314, 2023-09-06T22:07:18.759Z)
OS version: Linux x64 5.13.0-40-generic
Modes:

**Comment by jacobcarpenter** [comment] 2023-09-15 17:58
@webreidi I do not see these icons in my Testing panel; I only get "Run Test" and "Debug Test". My test project is NUnit-based. I'm on

OS: macOS
VS Code Version: 1.82.2 (Universal)
Extension Version: v0.4.10

**Comment by peterwald** [comment] 2023-09-15 19:04
This would happen if your tests are not built with symbols, so that source code location is not reported for the tests. Can you confirm that this build is generating symbols?

**Comment by jacobcarpenter** [comment] 2023-09-15 20:11
I see a pdb file corresponding to the assembly that contains the tests in my `.bin/Debug/net7.0` folder:

<img width="667" alt="Screenshot 2023-09-15 at 1 08 36 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/194333/21a41200-6005-4bdc-88fa-f3404a356036">

For local development I'm typically just building with `dotnet build` and was previously testing with `dotnet test`.

**Comment by jacobcarpenter** [comment] 2023-09-15 20:27
It looks like if I initiate the build via the Testing panel (or the Build task in VS Code) it builds with some additional parameters:

```
Executing task: dotnet build /[...]/PopularQuotesApi/PopularQuotesApi.sln /property:GenerateFullPaths=true /consoleloggerparameters:NoSummary
```

I believe those additional args came from an editor-created default build task in `.vscode/tasks.json`. It doesn't _look_ like those would suppress symbols (but perhaps the "full paths" bit is relevant?)...

**Comment by nrader95** [comment] 2023-09-18 07:57
> @nrader95 if you hover over the right of the test, you should see three icons. The third one is go to test.
> 
> ![image](https://user-images.githubusercontent.com/55603905/268045456-cc30e4e2-fe89-4e0f-83f5-423245e23d88.png)

I do not have the third icon on the panel on my linux machine even after building the whole project. So i guess this topic should be marked as bug.

**Comment by jacobcarpenter** [comment] 2023-09-22 21:17
@peterwald did my reply answer your question about whether symbols were being generated? Is there some additional command line option I need to ensure to pass to `dotnet build`?

**Comment by peterwald** [comment] 2023-11-06 20:11
> @peterwald did my reply answer your question about whether symbols were being generated? Is there some additional command line option I need to ensure to pass to `dotnet build`?

Yes, it appears that symbols are being generated. I could not reproduce the issue in my local testing with NUnit on Linux. The code navigation button does show up for me in the test tree. One note is that the "navigate to test" button only shows on the lowest level of the test tree (on the test itself). 

![image](https://github.com/microsoft/vscode-dotnettools/assets/5578/b90d2c3f-6caa-4ec2-a7ab-ac9e5f9699f3)

I'm curious, do you see a test glyph in the margins next to your tests in the editor? If not, then that is another indication that test source location data is missing.

![image](https://github.com/microsoft/vscode-dotnettools/assets/5578/7529a14c-35bf-4b5f-8a48-8a6178c0c4e6)

**Comment by jacobcarpenter** [comment] 2023-11-06 23:02
@peterwald Thanks for getting back to me! I just re-opened the project I reported the problem in, and I do now see both indicators (navigate to source in Testing panel and the margin indicator in code files) 🎉

In case you care, I'm now showing C# Dev Kit (`ms-dotnettools.csdevkit`) is `v1.0.14` and C# (`ms-dotnettools.csharp`) is `v2.9.20`.

**Comment by peterwald** [comment] 2023-11-07 18:44
Thanks for reporting this @jacobcarpenter. I'm going to close this out as I believe it was fixed in a newer release.

**Closed by peterwald** 2023-11-07 18:44 UTC
Labels: bug, area-test
