### ISSUE TITLE
Solution being created in the project folder, and intellisense not activating when opening a solution with 2 projects

### ISSUE THREAD

**Issue by Nemonek** [microsoft/vscode-dotnettools#247] opened 2023-07-12 09:35 UTC
Type: <b>Bug</b>

Hi, I'm encountering a problem: when I create a project inside a solution, it's everything ok, but when I open that project without opening the parent folder with the sln file inside, a new sln file gets created; then, if I open the parent folder of the project, with the sln file, I don't get intellisense.

Extension version: 0.1.103
VS Code version: Code 1.80.0 (660393deaaa6d1996740ff4880f1bad43768c814, 2023-07-04T15:06:02.407Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|11.75GB (1.73GB free)|
|Process Argv|C:\\Users\\pirel\\Desktop\\Personal Projects\\HammingCode --crash-reporter-id 7fb83dd0-7c68-475b-acce-155cd3b4911b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263:30784847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
2e4cg342:30602488
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
hideindicator:30785051
pythongtdpath:30769146
i26e3531:30780429
pythonnosmt12:30779714
pythonidxpt:30784022
pythonnocebcf:30776496
e537b577:30786199

```

</details>

**Comment by ianjirka** [comment] 2023-08-08 02:32
I would love a setting to prevent the extension from creating a .sln and the 'default solution' settings addition to workspace or settings files unless I ask it to.  I often open subsets of a repo and having to clean up this all the time is a bit frustrating.

**Comment by webreidi** [comment] 2024-01-19 19:07
@sayedihashimi is this a duplicate of [[BUG] C# Dev Kit automatically adds unrequested solution files · Issue #31 · microsoft/vscode-dotnettools (github.com)](https://github.com/microsoft/vscode-dotnettools/issues/31)

**Comment by sayedihashimi** [comment] 2024-01-20 00:29
@webreidi this sounds like a different issue. From my understanding of this issue, the user opens a folder that is in a sub-folder where the sln file is located. C# Dev Kit doesn't find that sln file and instead creates a new one in that child folder. When the user opens the parent folder there is some issue with loading the solution or something else that interferes with IntelliSense.

Seems like there could be two issues here.

 1. In the case where the user opens a folder that's a sub-folder where the sln file is located. We probably should be finding that sln file instead of creating a new one but I'm not 100% sure.
 2. User isn't getting IntelliSense after opening the parent folder contain the sln file. I think we need more info here to better understand what is happening.

**Comment by sayedihashimi** [comment] 2024-01-20 00:31
> I would love a setting to prevent the extension from creating a .sln and the 'default solution' settings addition to workspace or settings files unless I ask it to. I often open subsets of a repo and having to clean up this all the time is a bit frustrating.

We have added an option to disable generation of the sln file in the workspace. More info at https://github.com/microsoft/vscode-dotnettools/issues/31#issuecomment-1900809375. Please let me know if that doesn't meet your needs.

**Comment by webreidi** [comment] 2024-04-04 15:12
@sayedihashimi should project system find the sln file in the parent folder so that C#DK understands the full solution and IntelliSense and navigation and everything else will work properly? Is that the bug? Or is this just a duplicate request of #31 to have it not generate a new sln file?

**Comment by sayedihashimi** [comment] 2024-04-04 18:44
> @sayedihashimi should project system find the sln file in the parent folder so that C#DK understands the full solution and IntelliSense and navigation and everything else will work properly? Is that the bug? Or is this just a duplicate request of #31 to have it not generate a new sln file?

I thought that VS Code would prompt the user to open the Workspace root, is that not happening? If the sln file is above, or outside of, the workspace root, I would not expect the sln file to be discovered.

**Comment by webreidi** [comment] 2024-09-25 15:57
@Nemonek does the option added in January (https://github.com/microsoft/vscode-dotnettools/issues/31#issuecomment-1900809375) to disable the generation of the sln file in the workspace meet your needs for this issue?

Or do you want to open the whole sln even though you only opened a part of the solution? Are you looking for solution filter support?

cc: @sayedihashimi

**Comment by Nemonek** [comment] 2024-11-03 17:52
Yes, it solves the problem!

**Closed** 2024-11-04 15:34 UTC
Labels: bug, triaged, area-solution
