### ISSUE TITLE
'generated_code = true' from .editorconfig not respected when formatting code on save

### ISSUE THREAD

**Issue by tomekpaszek** [microsoft/vscode-dotnettools#1586] opened 2024-11-06 11:17 UTC
Type: <b>Bug</b>

.editorconfig allow you to configure "generated code" (https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-options#exclude-generated-code) which the regular 'dotnet format' command ignored, when formatting files. 
In VSCode, this paramtere seems to be ignored and the files are formatted anyways.

Extension version: 1.11.14
VS Code version: Code 1.95.1 (Universal) (65edc4939843c90c34d61f4ce11704f09d3e5cb6, 2024-10-31T05:14:54.222Z)
OS version: Darwin arm64 24.1.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|5, 5, 6|
|Memory (System)|64.00GB (11.86GB free)|
|Process Argv|--crash-reporter-id 1e93c983-f3ef-4024-bca4-3c2e914c0328|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
962ge761:30959799
pythongtdpath:30769146
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
jg8ic977:31013176
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl1:31139838
refactort:31108082
pythonrstrctxt:31112756
cf971741:31144450
iacca1:31171482
notype1:31157159
5fd0e150:31155592
dwcopilot:31170013

```

</details>

**Comment by dibarbet** [comment] 2024-12-04 22:09
Both VS and VSCode format generated documents when explicitly asked (e.g. format document, format selection, etc).  VSCode sends a [document formatting](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_formatting) request when format on save is enabled.

Closing as by design.  An explicit formatting request was made, so we format the document.  Additionally, as this setting is designed to be used with generated files, editing these files by hand in the IDE should not be a common scenario.

Even if we wanted to change this scenario, we do not have a way to detect this in VSCode as the protocol does not specify if a document format request was triggered by a save.

**Closed by dibarbet** 2024-12-04 22:09 UTC
Labels: bug, area-roslyn
