### ISSUE TITLE
[BUG] Language server fails and stops when opening diff view on .cs file

### ISSUE THREAD

**Issue by KuraiAndras** [microsoft/vscode-dotnettools#1320] opened 2024-07-29 12:04 UTC
### Describe the Issue

The language server failes when opening a file diff view when selecting the non-inlined view.
Error log:
```log
[LanguageServerHost] System.InvalidOperationException: Unsupported extension '.cs%22,%22ref%22:%22~%22%7D' and LSP language id ''
   at Microsoft.CodeAnalysis.LanguageServer.LanguageInfoProvider.GetLanguageInformation(String documentPath, String lspLanguageId) in /_/src/LanguageServer/Protocol/LanguageInfoProvider.cs:line 63
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.GetLanguageForUri(Uri uri) in /_/src/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 417
   at Microsoft.CodeAnalysis.LanguageServer.RoslynLanguageServer.GetLanguageForRequest(String methodName, Object serializedParameters) in /_/src/LanguageServer/Protocol/RoslynLanguageServer.cs:line 211
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync()
```

### Steps To Reproduce

1. Initialize git
2. Create new c# project
3. Commit
4. Change `Program.cs`
5. Select the changed file
6. Deselect `Inline view`
7. Close the window
8. Open the diff view again

### Expected Behavior

The language server does not fail and intellisense works on the current state of the code.

### Environment Information

- OS: Windows 10 and 11
- VSCode: 1.91.1
- ms-dotnettools.csharp: 2.39.29

**Comment by dibarbet** [comment] 2024-07-29 18:08
Fixed by https://github.com/dotnet/roslyn/pull/74544

Will reply here once the fix is available

**Comment by dibarbet** [comment] 2024-07-29 18:09
@KuraiAndras as a workaround, unchecking this option should prevent the server from crashing:
![image](https://github.com/user-attachments/assets/2788a8af-41fe-4183-9429-b4def81de158)

**Comment by dibarbet** [comment] 2024-08-01 01:39
Closing as a duplicate of https://github.com/dotnet/vscode-csharp/issues/7399.  I will post an update to that issue when the fix is uploaded to the marketplace.

**Closed by dibarbet** 2024-08-01 01:39 UTC
Labels: bug, area-roslyn, fixed-pending-release
