### ISSUE TITLE
dotnet wants to sign using key "Imported Private Key" in your keychain

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1244] opened 2024-06-25 19:44 UTC
Type: <b>Bug</b>

This is in .net Maui in VS Code for Mac.

I updated Maui.Controls today and, after doing so, I get a prompt to enter a keychain password every time I run the app.  Only problem is that it isn't an item I recognize.  The username it's asking for the password for is a seemingly random string of characters.  Not only that, it's a different string every time I run the app.

dotnet wants to sign using key "Imported Private Key" in your keychain.

To allow this, enter the "42344b4bd8e84b219..." keychain password.

Extension version: 1.0.6
VS Code version: Code 1.90.2 (5437499feb04f7a586f677b155b039bc2b3669eb, 2024-06-18T22:54:35.075Z)
OS version: Darwin arm64 23.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Max (14 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|15, 12, 11|
|Memory (System)|96.00GB (0.79GB free)|
|Process Argv|--crash-reporter-id 1618046c-b005-4c1a-89ae-cb627902572c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
2e7ec940:31000449
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
jchc7451:31067544
chatpanelt:31048053
dsvsc021:30996838
0ee40948:31013168
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupytercf:31046870
2f103344:31071589
legacy_priority:31077528

```

</details>

**Comment by mmiller-d8** [comment] 2024-06-25 19:47
Edit:  Maybe a fluke?  I closed and reopened the project and now it's launching without the prompt.

**Comment by mauroa** [comment] 2024-07-01 21:01
We couldn't reproduce the problem or find a valid root cause, so I'm closing for now. Please fell free to request a reopening in case it happens again. Thanks for your feedback

**Closed** 2024-07-01 21:02 UTC
Labels: area-maui

**Comment by SotoiGhost** [comment] 2024-07-01 23:58
I just moved from dotnet v8.0.204 to v8.0.302, installed the `maui`, `maui-ios`, `maui-android`, maui-maccatalyst` workload, ran the project and the windows started to appear every time I run the project.

<img width="546" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/5924210/179e85d4-004f-47eb-8975-4fc6460234b2">

MAUI VSCode extension v1.1.8 (pre-release)

**Comment by ahmad-crossplatform** [comment] 2024-07-11 12:56
@SotoiGhost  Same here

**Comment by ktravelet** [comment] 2024-08-09 20:17
![image](https://github.com/user-attachments/assets/37bb7e76-a04f-407b-bc48-c5befb4a156f)

**Comment by gktval** [comment] 2024-08-27 13:52
Same here. Happened after opening Visual Studio and updating tools in there. Now this pops up every time I debug in VSCode. Please reopen.

**Comment by MLB-BIOMETRIC** [comment] 2025-03-04 13:55
@mauroa Please consider re-opening this.

I just upgraded from .NET 8 to .NET 9 when running i get this:

![Image](https://github.com/user-attachments/assets/01f1bba2-a666-4cc5-a2cc-a3500697b264)

**Comment by MLB-BIOMETRIC** [comment] 2025-03-04 14:21
Additionally, I get this error below if i click ``Deny``.

```
Hot Reload initialization error: Hot Reload Bootstrap failed: System.AggregateException: One or more errors occurred. (Authentication failed, see inner exception.)
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> Interop+AppleCrypto+SslException: forkert protokolversion
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<ForceAuthenticationAsync>d__157`1[[System.Net.Security.AsyncReadWriteAdapter, System.Net.Security, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.TcpNetworkStream.AcceptAsync(TimeSpan timespan, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.DesignTools.TapContract.Networking.TcpDataBridge.InitializeAsync(TimeSpan timeout, CancellationToken token)
   at Microsoft.VisualStudio.DesignTools.MobileTapContracts.Bootstrapper.Boot(Boolean inboundClient, IPAddress[] ipAddresses, Int32 port, String connectionString, CancellationToken token)
   --- End of inner exception stack trace --
```

**Comment by jimmy84** [comment] 2025-03-19 07:55
weird i had similiar issue with sdk 8.0.407, didnt even whats the password

**Comment by timoteo0204** [comment] 2025-06-17 18:39
I have the same issue on 8.0.303

**Comment by Efe-Roy** [comment] 2025-06-20 11:00
> We couldn't reproduce the problem or find a valid root cause, so I'm closing for now. Please fell free to request a reopening in case it happens again. Thanks for your feedback

Has there been any solution yet

**Comment by jeremy-visionaid** [comment] 2025-06-29 23:39
I just hit this too after installing some additional workloads (dotnet sdk 9.0.301)

**Comment by jeremy-visionaid** [comment] 2025-06-30 00:22
Seemed to fix itself after restarting VS Code and `git clean -dfx`

**Comment by bnSonic** [comment] 2025-07-10 12:03
i've had the same today after I updated the maui workload to the .302 release. VSCode was open while I was doing this (on a Mac)
After that I deleted all bin / obj directories. Then I started to debug on a iOS Simulator and got this exact message (keychain)

I quit VSCode and reopened it. Problem seems to be gone now
