### ISSUE TITLE
Referenced Blazor component not recognized

### ISSUE THREAD

**Issue by danroth27** [microsoft/vscode-dotnettools#137] opened 2023-06-14 06:37 UTC
Type: <b>Bug</b>

I created a Blazor Server project that references a default Razor Class Library. When I try to use Component1 from the RCL in my Blazor app, it isn't recognized in the editor. The app builds and runs fine.

![image](https://github.com/microsoft/vscode-dotnettools/assets/1874516/004a6a7d-76ee-41f6-8bcc-6285b46adf01)

Extension version: 0.1.83
VS Code version: Code 1.79.1 (4cb974a7aed77a74c7813bdccd99ee0d04901215, 2023-06-12T16:14:05.102Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (41.73GB free)|
|Process Argv|. --crash-reporter-id 4f9325b6-0f0b-4512-95c8-0e78b95da0c9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vscccc:30610679
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixhidewlkth:30730051
pythongtdpathcf:30739705
e440d664:30763025
pythonnosm12tcf:30765602

```

</details>

**Comment by danroth27** [comment] 2023-06-14 06:37
@phil-allen-msft

**Comment by phil-allen-msft** [comment] 2023-08-17 21:46
Duplicate of #49

**Closed** 2023-08-17 21:47 UTC
Labels: area-razor
