### ISSUE TITLE
Intellisense and Type Navigation Not Working

### ISSUE THREAD

**Issue by terryaney** [microsoft/vscode-dotnettools#30] opened 2023-06-07 03:48 UTC
Type: <b>Bug</b>

I've opened a workspace file (web site, two library projects, and miscellaneous folder) and intellisense is not working.  In the gif below, you see a few issues from start to finish.

1. I hover over BaseCachedResponseEndpoint and get no context tip.

2. I typed `All` ctrl+space...I should have seen methods available but it said 'No Suggestions'

3. I did a 'Go To Definition' on BaseCachedResponseEndpoint and said it couldn't navigate.

4. I did a ctrl+t and typed BaseCached and nothing showed up.

I don't know if I have conflicting/missing extensions or what.

Unfortunately, it is a private repo.  I could send the workspace file is about it, or any logs you might request.

Please advise.

![intellisense](https://github.com/microsoft/vscode-dotnettools/assets/6237247/60425aaa-4157-4d1d-8924-4c4a6591d03a)

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.70GB (45.13GB free)|
|Process Argv|--crash-reporter-id 3a73b254-9ee7-4cb6-b1eb-57f9149a1430|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
2e4cg342:30602488
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
showlangstatbar:30737416
vsctsb:30748421
pythonms35:30701012
03d35959:30757346
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30730052
showsbindicator:30760979
pythongtdpathcf:30739705
pythonnosmt12:30757131

```

</details>

**Comment by terryaney** [comment] 2023-06-07 03:54
Do I need to be using *.sln files to leverage Dev Kit?  Does everything work with only opening a folder or a workspace?

**Comment by arkalyanms** [comment] 2023-06-08 00:21
At the moment, you need a sln file for the rest of the ecosystem to light up.

**Comment by timheuer** [comment] 2023-06-09 23:48
> If I've deleted the sln file and the 'setting' I found in my .vscode folder, how can I 'regenerate' them to test? (I originally uninstalled Dev Kit to get functionality back and after reinstalling, when I opened my workspace, it didn't generate the sln file).

Hmm, if when you open a folder it isn't creating a SLN for (when one isn't present) there may be some weird state.  For now use the terminal and `dotnet new sln` and then `dotnet sln add <path to your csproj>` to get you unblocked.

**Comment by lucky51** [comment] 2023-06-29 09:31
c# for visual studio  code : pre-release 2.0.248 
c# dev kt :0.2.99 

c# output
```
.dotnet\7.0.8\dotnet.exe
Activating C# + C# Dev Kit + C# IntelliCode...
info: LanguageServerHost[0]
      Starting server...
```
c# dev kit output 
```
Starting Spawn .NET server...
Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
.NET server started and IPC established in 2645ms
Completed Spawn .NET server (2672ms)
Completed Clear environment (3074ms)
Completed Open a solution with environment service (3122ms)
Starting Restore solution...
Completed Open a solution (3129ms)
Completed Restore solution (3642ms)
```

Open vscode in the folder containing the sln file.
why  navigation not working  with f12 
![image](https://github.com/microsoft/vscode-dotnettools/assets/27793729/03780cdf-ecd9-4ebe-bf58-41994ea70b15)
if I swich to release version(c# for vscode) ,solution explorer is missing.
![image](https://github.com/microsoft/vscode-dotnettools/assets/27793729/cb823bea-88dc-4504-8e30-2652e1d1a466)

**Comment by timheuer** [comment] 2023-06-29 15:24
@arkalyanms can we take another look at this one -- seems code-nave related.

**Comment by arkalyanms** [comment] 2023-06-29 16:26
Yes. 

@lucky51 first of all thanks for continuing to drive clarity into the repro. I tried this locally with a few of our projects and test solutions without luck. So if there is a minimal repro solution you could share, that would be helpful. 

Of a few other signals that might also help are:
1. Is only F12 broken or all language service activities broken? (completion, ctrl+., hover, lightbulb - any of these working?). If it is the latter this could still be a project load issue in populating the workspace. 
2. Things that are broken with the C# + C# Dev Kit - does the same work with just the C# prerelease 2.0.248? (no C# Dev Kit installed)

**Comment by nick-beer** [comment] 2023-06-29 19:46
I'm seeing the same problem.  Unfortunately, I also can only reproduce the issue on an internal repo.

I have the repo cloned on my Windows 11 laptop, as well as in WSL2 on the same laptop.  The issue only reproduces in the WSL2 version of the repo.

@arkalyanms - For me:

1. It's mostly type navigation, find references, go to definition etc that's broken.  Completion, intellicode, quick fix, etc all seem to be working.
2. With C# Dev Kit _not installed_ and C# prerelease 2.0.248 _installed_, things start working again.  When I re-install C# Dev Kit, it goes back to being broken.

**Comment by arkalyanms** [comment] 2023-06-29 21:32
thanks for the additional info @nick-beer!

This then seems to be the same as https://github.com/microsoft/vscode-dotnettools/issues/210. I will let @tmeschter and team dup as they deem fit.

**Comment by lucky51** [comment] 2023-06-30 14:36
@arkalyanms  @timheuer  
Thanks for your reply. 
I'm sorry, it may be the problem of my environment, I tried to change a different version, I accidentally click ctrl + left mouse  on the type field, the code navigation can work and f12 can also work.The previous problems did not recur.

**Comment by tmeschter** [comment] 2023-07-10 23:17
@lucky51 Going back to this image:
![image](https://github.com/microsoft/vscode-dotnettools/assets/10506730/4bf57129-36ad-41d3-9bd5-977ab6d8cc0f)
Is DataModel in a referenced project, or the same project as the source file?

**Comment by myty** [comment] 2023-07-12 13:48
I get the same thing and the workaround, for me, is to disable C# Dev Kit, reload the window.  At this point C# intellisense is back and works great.  I can then re-enable the C# Dev kit extension, but ignore the notification to restart the C# LSP.

> c# for visual studio code : pre-release 2.0.248 c# dev kt :0.2.99
> 
> c# output
> 
> ```
> .dotnet\7.0.8\dotnet.exe
> Activating C# + C# Dev Kit + C# IntelliCode...
> info: LanguageServerHost[0]
>       Starting server...
> ```

**Comment by lucky51** [comment] 2023-07-16 08:35
> referenced project

In a referenced project.

**Comment by tmeschter** [comment] 2023-08-17 18:59
@terryaney, @lucky51: Can you try the 0.4.5 version of C# Dev Kit and let me know if that helps?

**Comment by tmeschter** [comment] 2023-09-05 18:18
@terryaney I'm going to go ahead and close this as we can't make further progress on it based on the information we have. Please let us know if you have a chance to try a newer version of C# Dev Kit and you're still seeing issues.

**Closed by tmeschter** 2023-09-05 18:18 UTC
Labels: bug, area-project, needs-more-info
