### ISSUE TITLE
[BUG] IntelliSense for XAML is not working correctly in Visual Studio Code.

### ISSUE THREAD

**Issue by GabrielLimaG3** [microsoft/vscode-dotnettools#1108] opened 2024-05-09 00:39 UTC
### Describe the Issue

IntelliSense, which provides code suggestions, auto-completion, and contextual information when editing XAML files, is not operating as expected. This implies that coding assistance features such as property, method, and event suggestions are not being displayed in Visual Studio Code as the user types in the XAML file.

### Steps To Reproduce

1 - Ubuntu Environment
2 - Install Ubuntu
3 - Configure .NET MAUI
4 - Install the extensions
5 - Typing anything, like 'b' for Button, and no suggestion is displayed

### Expected Behavior

provides code suggestions, auto-completion, and contextual information when editing XAML files

### Environment Information

-OS: Ubuntu 22.04.4
-VS Code version: 1.89.0
-Extension Version: .NET MAUI 0.11.57

**Comment by mgoertz-msft** [comment] 2024-05-10 22:44
The status of XAML IntelliSense for .NET MAUI is tracked by this issue already:

#565 [BUG] Better Intellisense for .NET MAUI XAML files

**Comment by mgoertz-msft** [comment] 2024-05-10 22:46
Not sure how useful the .NET MAUI extension is on any OS besides Window or macOS though.

**Comment by GabrielLimaG3** [comment] 2024-05-11 00:09
Thanks for the info! I had no idea the issue was already being tracked. It would be really amazing to develop mobile apps on all three major platforms. This would not only increase the number of .NET MAUI developers, but also expand the reach and availability of applications to users across multiple platforms, which is the key differentiator of this technology.

**Comment by emaf** [comment] 2024-05-13 14:36
Closing as duplicate of #565

**Closed by emaf** 2024-05-13 14:35 UTC
Labels: bug, area-maui
