### ISSUE TITLE
[BUG] MAUI iOS device picker shows all devices running

### ISSUE THREAD

**Issue by mattleibow** [microsoft/vscode-dotnettools#846] opened 2024-01-09 15:15 UTC
### Describe the Issue

I only have a single device running, yet they are all marked as running

<img width="529" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/1096616/8592cfed-5c54-4d73-9c3f-f6e7b6a26174">

### Steps To Reproduce

1. Open a sln
2. Select a device

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_queries/edit/1937562">1937562</a>

**Comment by emaf** [comment] 2024-01-09 20:04
Duplicate of #677

**Closed by emaf** 2024-01-09 20:04 UTC
Labels: bug, triaged, area-maui, vs-sync, vs-syncd
