### ISSUE TITLE
Console/Debug output with useVSDbg=true

### ISSUE THREAD

**Issue by yaliashkevich** [microsoft/vscode-dotnettools#1064] opened 2024-04-16 17:12 UTC
I've noticed following behaviour with useVSDbg=true flag while working on dotnet-ios/android app:

- Application output written by`Console.WriteLine` gets into **Terminal** window (same as build output).
- Application output written by `Debug.WriteLine` gets nowhere, atleast I can not find it.

Is it intended behavior?
Previously with useVSDbg=false all output above were shown at **DEBUG CONSOLE** window which has convenient controls to clear/filter.

**Comment by mauroa** [comment] 2024-04-16 20:03
This is a duplicate of: https://github.com/microsoft/vscode-dotnettools/issues/685. Closing this, so please follow the status on the other ticket. Thanks

**Closed by mauroa** 2024-04-16 20:03 UTC
Labels: duplicate, question, area-debugging, area-maui
