### ISSUE TITLE
The official Microsoft Unity extension breaks Line Comment Shortcuts on certain file types at random

### ISSUE THREAD

**Issue by mbullister** [microsoft/vscode-dotnettools#824] opened 2023-12-24 01:20 UTC
Type: <b>Bug</b>

The ctrl+k ctrl+c shortcut for line/multiline comments and associated "Edit" menu option will sometimes stop working for files using the "UnityShader" language association, seemingly at random.  Forcing the affected files to be interpretted as the C language instead prevents the problem.

Extension version: 0.9.3
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by jbevain** [comment] 2024-01-03 01:51
Hi,

Thanks for reaching out, I believe this is a duplicate of #702, I'll close it as such.

On the bright side, we have a fix that will ship in the preview.

Thanks again!

**Closed by jbevain** 2024-01-03 01:51 UTC
Labels: bug, area-unity
