### ISSUE TITLE
Nuget restore loops when the `<Version>` property is dynamic

### ISSUE THREAD

**Issue by Blokyk** [microsoft/vscode-dotnettools#698] opened 2023-11-09 01:16 UTC
# Describe the Issue

When working on a project with a `<Version>` property that includes the current date, the dev kit enters into a loop where it keeps trying to restore the project/solution over and over again as soon as a rebuild or restore is triggered.

![Output screenshot](https://github.com/microsoft/vscode-dotnettools/assets/32983140/d76c86eb-4d38-41f3-b8bc-d3f441451031)

# Steps to reproduce

[Minimal repro](https://github.com/blokyk/devkit-698-repro)

1. Create a library project and open it in vscode
2. Set the `<Version>` property  to something dynamic (e.g. `$([System.DateTime]::UtcNow.ToString(ss))`)
3. Launch a restore or build (from either the CLI or vscode)

Extension version: 1.0.14
VS Code version: Code 1.84.1 (2b35e1e6d88f1ce073683991d1eff5284a32690f, 2023-11-06T12:35:31.181Z)
OS version: Linux x64 5.19.0-46-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 4000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|15.45GB (4.98GB free)|
|Process Argv|. --crash-reporter-id 46de1db0-1a58-443a-b7bf-af59b3133719|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by timheuer** [comment] 2023-11-09 03:53
Thanks for the details, screenshot, and minimal repro @Blokyk! -- can you tell me a bit more about the env? I see `/tmp` in the screenshot...Unity project?  I've tried your repro project in devcontainer and in Ubuntu (WSL-22.04) and restore happens fine without repeats.

You are also indicating that just dotnet build from the CLI (regardless of VSCode open or not) also exhibits this behavior for you? Can you confirm that statement? I want to isolate if you're experiencing something at the lower level of `dotnet build` versus anything that the VSCode extensions are doing.

**Comment by Blokyk** [comment] 2023-11-09 17:12
Oh btw, I just noticed I left the other packaging stuff in the csproj file, but that's not needed to repro (at least not for me), I just copied stuff from my real project and somehow forgot to delete that part... I'll update my repro's repo, sorry about that!

**Comment by smitpatel** [comment] 2023-11-09 17:14
Also see https://github.com/dotnet/project-system/issues/1457

**Comment by jebriede** [comment] 2024-06-24 20:35
Team triage: This is a duplicate of https://github.com/dotnet/project-system/issues/1457.

**Closed by jebriede** 2024-06-24 20:35 UTC
Labels: bug, duplicate, triaged, area-nuget, area-project-cps, area-restore
