### ISSUE TITLE
[BUG] Reference of fields are missing

### ISSUE THREAD

**Issue by Skullester** [microsoft/vscode-dotnettools#356] opened 2023-08-08 07:46 UTC
### Describe the Issue

Reference of fields are gone, there are only references for methods and classes. Also there are constant readonly modifier advice for private fields that look a little annoying. All extensions are set to the latest version
![zdyou1arybs](https://github.com/microsoft/vscode-dotnettools/assets/138435791/f7e2cba5-9f61-4dc3-9834-5c1747ee8910)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/8e5b03e3-35aa-4f08-ac22-cafd25cd27e7)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/5a05317e-cc35-4396-a763-3d208ca285c7)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/ebbeac63-54f2-4db4-bb3e-e832554fcc2e)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/c639ac7c-ef4f-4053-9f81-9d98dfda5a45)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/cdc8f832-7f8b-4bd9-939e-9c6c749fdc39)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/ddd8861b-f979-4856-a4a8-963936024dcd)
![image](https://github.com/microsoft/vscode-dotnettools/assets/138435791/fcfd5128-8bf2-4347-bc10-edc206e5dfa1)

Could you give me a solution to be able to have the references for fields and get rid of advice.
Thank you very much in advance.

### Expected Behavior

Working references and lack of advice

### Environment Information

Version: 1.81.0 (user setup)
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by jbevain** [comment] 2023-08-08 12:06
This is a duplicate of #350.

**Comment by Skullester** [comment] 2023-08-08 21:44
> This is a duplicate of #350.

This solved the problem only half, there are still no references of fields

**Comment by arkalyanms** [comment] 2023-08-22 22:46
Fixed via https://github.com/dotnet/roslyn/pulls?q=is%3Apr+author%3Asharwell+is%3Aclosed

**Closed by arkalyanms** 2023-08-22 22:46 UTC
Labels: bug, area-roslyn
