### ISSUE TITLE
No launchable projects found with new launch experience

### ISSUE THREAD

**Issue by emaf** [microsoft/vscode-dotnettools#1439] opened 2024-09-06 18:15 UTC
Type: <b>Bug</b>

With the C# Dev Kit improved launch experience enabled, open VS code and try to create a new .NET project. Either if you end up creating one or not, and after a couple of seconds, you will get the "No launchable projects found" error.

![image](https://github.com/user-attachments/assets/c7a58e19-e33a-45e6-a467-f82a577a3532)

It does not affect functionality, because after opening or creating a project everything works, but it is misleading.

Extension version: 1.11.4
VS Code version: Code 1.93.0 (4849ca9bdf9666755eb463db297b69e5385090e3, 2024-09-04T13:02:38.431Z)
OS version: Darwin arm64 23.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|7, 8, 6|
|Memory (System)|32.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 699c6959-4440-48f2-a2f1-3a0272f47e36|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
01bff139:31013167
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
impr_priority:31102340
nativerepl2:31104044
refactort:31108082
pythonrstrctxt:31112756
flightc:31119335
wkspc-onlycs-t:31132770
wkspc-ranged-c:31125598
fje88620:31121564

```

</details>

| VS Bug <a href="https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2279551/">2279551</a>

**Comment by anaisbetts** [comment] 2024-10-15 15:46
> It does not affect functionality, because after opening or creating a project everything works, but it is misleading.

In my experience actually quite a few things are broken because of this. The biggest one is, you can't run the project! Another one is, you are unable to set the active TargetFramework if your project defines multiple. This is important because if you e.g. have:

```csharp
#if WINDOWS  // defined in all net8.0-windows projects

// Any code in here is effectively ignored, types don't resolve etc etc

#endif
```

To repro this scenario, create an Avalonia project and make `TargetFrameworks` be `net8.0-macos;net8.0-windows`, it's a pretty frustrating experience

**Comment by smitpatel** [comment] 2024-10-15 17:46
If you restart vscode instance then things should be working. If it is not working for you then it is not same as this issue. Please file a different issue for it.

**Comment by smitpatel** [comment] 2024-10-16 20:29
@emaf - Can you try reproducing it when .NET MAUI extension is not installed or disabled?

**Comment by emaf** [comment] 2024-10-17 15:16
I was originally able to reproduce this without the MAUI extension installed. I'm closing this as I cannot longer reproduce this issue using the latest prerelease of C# Dev Kit (v1.12.16).

**Comment by emaf** [comment] 2024-10-17 20:00
Reopening and tagging MAUI

**Comment by AllenD-MSFT** [comment] 2024-12-06 17:28
This has been fixed in a recent update. Please try the latest update and you should see better behavior in this regard.

**Closed by AllenD-MSFT** 2024-12-06 17:28 UTC
Labels: bug, triaged, area-maui, vs-syncd, fixed
