### ISSUE TITLE
[BUG] Opening a project in VS Code auto-creates a .sln file

### ISSUE THREAD

**Issue by seangwright** [microsoft/vscode-dotnettools#205] opened 2023-06-27 00:10 UTC
### Describe the Issue

This extension auto-creates a .sln file in the directory of a project (if there's only 1 project) as soon as I open a folder containing the project in VS Code if there isn't a .sln file.

This is kinda annoying and I cannot see a way to disable it.

If I want a .sln file, I'll create my own, name it what I want, and place it where I want it to be.

In addition to this, the `dotnet watch` command appears to be bugged when there are multiple project/solution files in the same directory and doesn't work.

If I have both a `.csproj` and the auto-generated `.sln` from this extension in the same directory and use `dotnet watch` with the project flag, this is what I get:

```
dotnet watch run --project .\app.sln
dotnet watch 🔥 Hot reload enabled. For a list of supported edits, see https://aka.ms/dotnet/hot-reload.
  💡 Press "Ctrl + R" to restart.
dotnet watch 🔧 Building...
MSBUILD : error MSB1011: Specify which project or solution file to use because this folder contains more than one project or solution file.
dotnet watch ⏳ Waiting for a file to change before restarting dotnet...
```

Before this extension started auto-adding `.sln` files, I could just type `dotnet watch` in my project folder and everything worked great because there was only 1 project/file to run.

I've tried this will all the SDK versions listed below.

### Steps To Reproduce

1. Install the C# extension in VS Code
2. Open a folder containing a C# project (or a folder with a subfolder containing a C# project)
3. Note that a `.sln` file is auto created

### Expected Behavior

When I open a folder containing a C# project (or containing a subfolder with a C# project), the extension does not create any .sln files or at least provides me a User Setting in VS Code to disable this behavior.

### Environment Information

- OS: Windows 11 Pro
- VS Code: 1.79.2
- `ms-dotnettools.csdevkit`: v0.2.70
- .NET SDK: 7.0.304, 7.0.305,  8.0.100-preview.5.23303.2

**Comment by smitpatel** [comment] 2023-06-27 02:41
Duplicate of #31

**Closed by smitpatel** 2023-06-27 02:41 UTC
Labels: bug, area-project
