### ISSUE TITLE
[BUG] Long file lock on workspace folder after closing Visual Studio Code

### ISSUE THREAD

**Issue by just-ero** [microsoft/vscode-dotnettools#716] opened 2023-11-13 17:10 UTC
### Describe the Issue

After closing a Visual Studio Code workspace which contained a .NET solution, the workspace remains being used by some running processes, often for over a minute or two. Those processes are the following:
* `Microsoft.VisualStudio.Code.Server.exe`
* `Microsoft.VisualStudio.Code.ServiceHost.exe`
* `Microsoft.VisualStudio.Code.ServiceHost.exe`
* `dotnet.exe`

`dotnet.exe`'s CLI command is `"C:\Program Files\dotnet\dotnet.exe" "C:\Program Files\dotnet\sdk\8.0.100-rc.2.23502.2\vstest.console.dll" /parentprocessid:4548 /port:58238`. The parent process `4548` is one of the two `Microsoft.VisualStudio.Code.ServiceHost.exe` instances.

After some time, `dotnet.exe` and its parent `Microsoft.VisualStudio.Code.ServiceHost.exe` close. Sometimes, the other two processes stay for a little longer.

### Steps To Reproduce

1. Open any .NET solution workspace in Visual Studio Code on Windows.
2. After the solution was successfully loaded, close Visual Studio Code.
3. Attempt to rename, move, delete (etc.) the workspace folder.

### Expected Behavior

The folder is not locked after Visual Studio Code was closed.

I run into this problem quite often, as I create small projects to benchmark or test a certain thing. Once I'm done, I no longer need the project and I attempt to delete it, but am forced to wait until those processes close.

### Environment Information

* OS: Windows 11 Pro (10.0.22631 Build 22631)
* VSCode: 1.84.2, 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e, x64
* C# extension: v2.10.28, C# Dev Kit extension: v1.1.9

**Comment by tmeschter** [comment] 2023-11-13 18:29
Moving to "area-test" as at least one of the processes is concerned with testing.

**Comment by ocallesp** [comment] 2024-04-04 15:16
@ocallesp  investigate

**Comment by ocallesp** [comment] 2024-05-03 00:20
This issue doesn't repro anymore.

BUT found a similar one caused by dotnet.exe using <repo folder>\.git\objects\pack\pack-<some numbers>.idx which is an issue in VS Code because this reproes when cloning from the IDE.

**Closed** 2024-05-03 00:29 UTC
Labels: bug, area-test, needs-investigation
