### ISSUE TITLE
[BUG] The messages logged by the Azure Artifacts credential providers in C# Dev Kit are not localized.

### ISSUE THREAD

**Issue by kartheekp-ms** [microsoft/vscode-dotnettools#964] opened 2024-02-28 23:20 UTC
### Describe the Issue

The messages logged by the Azure Artifacts credential providers in C# Dev Kit are not localized.

### Steps To Reproduce

1. Change VS Code display language to something other than English.
2. Open any solution in VS Code with C# Dev Kit extension installed.
3. Navigate to NuGet output window.
4. As you can see from the logs below, Azure DevOps credentials provider displays log messages in English instead of VS Code display language. 

![image](https://github.com/microsoft/vscode-dotnettools/assets/52756182/b40c894a-3db2-4b98-9bda-26d489362a17)

### Expected Behavior

The logs are displayed based on the user's language of choice.

**Comment by kartheekp-ms** [comment] 2024-02-28 23:22
Related: https://github.com/microsoft/artifacts-credprovider/issues/464

**Comment by timheuer** [comment] 2024-03-01 17:33
@kartheekp-ms should we close this as the issue is tracked there?

**Comment by AbhitejJohn** [comment] 2024-03-07 05:21
@kartheekp-ms : Gently pinging back on the question Tim had above.

**Comment by timheuer** [comment] 2024-03-29 00:59
Closing this...it's not for this repo to fix. Linked issue is the source.

**Closed by timheuer** 2024-03-29 00:59 UTC
Labels: bug, area-localization
