### ISSUE TITLE
Support intellisense in the debug console and watch window

### ISSUE THREAD

**Issue by amine-aboufirass** [microsoft/vscode-dotnettools#573] opened 2023-09-29 14:14 UTC
### Describe the feature you'd like

Currently the debug console and watch window do not support intellisense. It would be great to have access to intellisense when either:

1. Adding a watch
2. Inspecting objects and variables in the debug console

### Alternatives considered

Alternatives include temporarily entering things into a source file to make use of the Intellisense there and then copying and pasting to either the debug console and watch window. However this is not a sustainable solution for long term development.

### Environment Information

- OS: Windows
- VS Code version: 1.82.2
- Extension version `v0.4.10`

**Comment by gregg-miskelly** [comment] 2023-10-02 16:19
This is a duplicate of https://github.com/dotnet/vscode-csharp/issues/1609

**Closed by gregg-miskelly** 2023-10-02 16:19 UTC
Labels: enhancement, area-debugging

**Comment by gregg-miskelly** [comment] 2023-10-02 16:21
Sorry, that one is also a duplicate. Correct root issue: https://github.com/dotnet/vscode-csharp/issues/299
