### ISSUE TITLE
[BUG] Language Server crashed 5 times in the last 3 minutes

### ISSUE THREAD

**Issue by zcampbell519** [microsoft/vscode-dotnettools#723] opened 2023-11-15 17:06 UTC
### Describe the Issue

On startup of a C# solution file that contains both a Blazor Server project and a WebAPI project, the language server crashes. Opening each project individually of each other does not result in a crash of the server in my testing. 

### Steps To Reproduce

1. Open new command prompt in desired solution folder. 
2. `dotnet new sln -n TestApp`
3. `dotnet new blazorserver -n TestApp.UI -o UI`
4. `dotnet new webapi -n TestApp.API -o API`
5. `dotnet sln add .\api\`
6. `dotnet sln add .\ui\`
7. `code .`
8. Observe language server crash (attached log file from C# Dev kit, attached error stack trace from C# )
[20231115_C#Log.txt](https://github.com/microsoft/vscode-dotnettools/files/13367341/20231115_C.Log.txt)
[20231115_C#DevKitLog.txt](https://github.com/microsoft/vscode-dotnettools/files/13367342/20231115_C.DevKitLog.txt)
10. Close VS Code
11. `cd ui `
12. `code .`
13. Observe language server start
14. `cd ..\api`
15. `code .`
16. Observe language server start

### Expected Behavior

Solution opens and language server starts as expected. 

### Environment Information

VS Code About: 
   Version: 1.84.2 (user setup)
   Commit: 1a5daa3a0231a0fbba4f14db7ec463cf99d7768e
   Date: 2023-11-09T10:51:52.184Z
   Electron: 25.9.2
   ElectronBuildId: 24603566
   Chromium: 114.0.5735.289
   Node.js: 18.15.0
   V8: 11.4.183.29-electron.0
   OS: Windows_NT x64 10.0.19045

-C# Dev Kit v1.0.14
-C# v2.10.28

All other extensions disabled for testing

**Comment by dibarbet** [comment] 2023-11-28 18:15
Error is 
```
[Error - 9:51:45 AM] [LanguageServerHost] System.InvalidOperationException: didOpen received for virtualcsharp-razor:///[REDACTED]source/repos/test/BasicAuthExample/ui/Pages/Error.cshtml__virtual.cs which is already open. - line 106
   at Roslyn.Utilities.Contract.Fail(String message, Int32 lineNumber) in /_/src/Workspaces/SharedUtilitiesAndExtensions/Compiler/Core/Utilities/Contract.cs:line 154
   at Microsoft.CodeAnalysis.LanguageServer.LspWorkspaceManager.StartTrackingAsync(Uri uri, SourceText documentText, String languageId, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Workspaces/LspWorkspaceManager.cs:line 106
   at Microsoft.CodeAnalysis.LanguageServer.Handler.DocumentChanges.DidOpenHandler.HandleNotificationAsync(DidOpenTextDocumentParams request, RequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Protocol/Handler/DocumentChanges/DidOpenHandler.cs:line 42
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken) in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/QueueItem.cs:line 136
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, CancellationToken cancellationToken)
   at Microsoft.CommonLanguageServerProtocol.Framework.RequestExecutionQueue`1.ProcessQueueAsync() in /_/src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/RequestExecutionQueue.cs:line 239
```

This should be a dupe of https://github.com/dotnet/vscode-csharp/issues/6644 which will be fixed in the next release (cc @davidwengier).

**Closed by dibarbet** 2023-11-28 18:15 UTC
Labels: bug, area-roslyn

**Comment by davidwengier** [comment] 2023-12-04 00:20
Yep, looks like a clear dupe. The different casing of the paths in the `dotnet new` vs `dotnet sln` commands causes the .sln file to have mixed case.
