### ISSUE TITLE
[BUG] Go To Definition issue in Unity project

### ISSUE THREAD

**Issue by iantierney** [microsoft/vscode-dotnettools#1093] opened 2024-05-02 15:00 UTC
### Describe the Issue

However when I right click a function call from another class, and select "Go to definition", visual studio code says "No definition found" for that function even though the function definition is in the project.

### Steps To Reproduce

 right click a function call from another class, and select "Go to definition", visual studio code says "No definition found" for that function even though the function definition is in the project.

Tried:
Generating a new workspace
Restarting OmniSharp

### Expected Behavior

Goes to the function

### Environment Information

Using the Unity Unity v1.0.1 with VS code for mac Version: 1.88.1.
OSX 14.3
I have the extension "intellicode for C# dev kit" and the "C# dev kit" extensions installed.

**Comment by jbevain** [comment] 2024-05-02 16:11
Hello,

This looks like a setup issue:

* Close VS Code
* In Unity's Package Manager, please make sure your "Visual Studio Editor" package is the latest (2.0.22).
* In Unity's preferences, please make sure that Visual Studio Code is selected as the External Editor
* In Unity's preferences, do Regenerate Project Files
* Double click on a C# file in Unity to open VS Code.

The Unity extension relies on the C# DevKit and the new C# extension. Omnisharp is not supported for this scenario.

**Comment by iantierney** [comment] 2024-05-03 11:06
Thanks for the quick reply!
Completed all steps and I still have the same issue.

**Comment by jbevain** [comment] 2024-05-14 17:32
@iantierney unfortunately we've been unable to reproduce the issue. Is this happening on a completely new Unity project or is it specific to one project?

In the project where this is happening, are you getting proper intellisense or is it only the "Go To Definition" feature which is not working properly?

**Comment by ovilaro** [comment] 2024-06-06 16:37
Opening a Unity project that I had not opened for +6 months, the same thing happened to me, I was able to debug from vscode but I could not navigate through any symbols from vscode nor did it recognize errors if I caused one in the code. In the end, installing .NET 8.0.x as @td-bo said worked for me.

**Comment by jbevain** [comment] 2024-06-12 00:44
Sounds like another case of #1188. Closing this as we're tracking everything there. Thanks!

**Closed by jbevain** 2024-06-12 00:44 UTC
Labels: bug, needs-more-info, area-unity
