### ISSUE TITLE
[SUGGESTION] Adding Dependencies to Project with Right Mouse Button

### ISSUE THREAD

**Issue by fiqriismail** [microsoft/vscode-dotnettools#190] opened 2023-06-21 16:02 UTC
### Describe the feature you'd like

This is a nice to have feature. 

1. Click Right Mouse Button on the Dependencies 
2.  Add Project Reference or NuGet Package Reference

### Alternatives considered

Add reference to the csproj file manually. 

### Environment Information

- Ubuntu 22.04
- VS Code 1.79.2
- C# Dev Kit 0.1.103 Preview

**Comment by timheuer** [comment] 2023-06-21 18:12
Number 2 here is #62

**Comment by timheuer** [comment] 2023-06-28 17:35
Given that #47 and #62 cover these, just closing this as a dupe of those being tracked.  Thanks for the +1 on the suggestions @fiqriismail

**Closed by timheuer** 2023-06-28 17:35 UTC
Labels: enhancement, area-project
