### ISSUE TITLE
[BUG] Language of Extension does not match VS Code language

### ISSUE THREAD

**Issue by tthiery** [microsoft/vscode-dotnettools#85] opened 2023-06-08 16:50 UTC
### Describe the Issue

When starting VS Code with English language selected (I think I never selected a language) on a German Windows installation I see mixed language within the same screen

![image](https://github.com/microsoft/vscode-dotnettools/assets/442577/02ca2fca-0e7f-4d79-9d7a-5a9be7530971)

The "6 Verweise" is "6 References" in English.

Now I have english editor, german intellisense/code actions/etc, and english source code. Aside of the operation system install, I never made a choice for a non-English .NET SDK or Editor.

### Steps To Reproduce

German Windows, Default VS Code Install, Marketplace installation of C# Dev Kit.

### Expected Behavior

The editor dictates the compiler/language service language.

### Environment Information

Windows 10, VS Code 1.7.8, .NET SDK 7.0.105

**Comment by dibarbet** [comment] 2023-06-09 21:35
Duplicate of https://github.com/dotnet/vscode-csharp/issues/5716 - a fix here is being planned for preview 2.

**Closed by dibarbet** 2023-06-09 21:35 UTC
Labels: bug, triaged, area-localization
