### ISSUE TITLE
[BUG] Test display should show test name only in hierarchy view

### ISSUE THREAD

**Issue by jaredpar** [microsoft/vscode-dotnettools#393] opened 2023-08-14 20:34 UTC
### Describe the Issue

The test window display is a hierarchy view which starts at the assembly level, dives down into namespaces, types, etc ... all the way until you get to the actual test methods. Every level of the tree view, except the leaf, shows the name only. The leaf though shows the entire test name and that makes it very hard to see what the test is. 

Consider this example where I have my tree view fully expanded and I can clearly see every name except for the actual tests 

<img width="240" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/146967/65b53bec-ed3a-4f55-a732-c6cbe61572c4">

In order to see the test names I have to expand the window significantly.

<img width="565" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/146967/57dba3d2-2a63-4536-b560-548613f80094">

I don't want to do this every time just to see the test that I'm going to run. 

### Steps To Reproduce

1. Clone a repo with tests
2. Build
3. Examine the hierarchy view for Tests

### Expected Behavior

Expect at the leaf level that only test names are displayed.

**Comment by timheuer** [comment] 2023-08-16 21:32
Closing as dupe of #295

**Closed by timheuer** 2023-08-16 21:32 UTC
Labels: bug, area-test
