### ISSUE TITLE
[BUG] Anonymous type incorrectly reported

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode-dotnettools#1015] opened 2024-03-21 20:04 UTC
### Describe the Issue

In the screenshot below, I would expect the Dev Kit to report that following is an anonymous type. It appears that perhaps it's trying and is reporting "a" instead? It also appears like the hover is not properly tokenizing the variable name as evidenced by the difference in color on the final "a" character.

![Image](https://github.com/microsoft/vscode-dotnettools/assets/686963/2b5fd8c4-91f8-4238-885b-8d94dcd9ba6d)

### Steps To Reproduce

1. In a .cs file
2. Create a new anonymous object
    
```csharp
var data = new {
   prop1,
   prop 2
}
```

3. Place the mouse cursor over the "data" variable instance.

### Expected Behavior

The hover information should identify this is "object" or "anonymous"? I'm not entirely sure tbh.

### Environment Information

Version: 1.87.2
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:57.520Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Darwin arm64 23.4.0

DevKit: v1.4.29

**Comment by dibarbet** [comment] 2024-04-24 20:47
This is a limitation of the textmate classification that VSCode does in hover.
Duplicate of https://github.com/dotnet/vscode-csharp/issues/6672

**Closed by dibarbet** 2024-04-24 20:47 UTC
Labels: bug, area-roslyn
