### ISSUE TITLE
[BUG] Cannot attach breakpoint in the Source which is import by UPM

### ISSUE THREAD

**Issue by sableangle** [microsoft/vscode-dotnettools#345] opened 2023-08-07 05:51 UTC
### Describe the Issue

Sometimes we will import the package by UPM (Unity Package Manager) from disk or git like this:
```
{
  "dependencies": {
    "com.coolpackage.fromdisk": "file:../{some where of your codes}",
    "com.coolpackage.fromgit": "https://{some where of your codes}.git",
 }
}
```

If I trying to attach break point on the code which is from package, the breakpoint not work.

BTW, the obsolete Unity official VSCode debugger doesn't get the errors, and the breakpoint works great in Visual Studio for Mac, but not working on VS Code.

### Steps To Reproduce

1. Import some package using file:// in the manifest.json
2. Try to attach breakpoint in the source file which is from 1. 
3. See the result that breakpoint is attach fails

### Expected Behavior

In the obsolete Unity official VSCode debugger, it just work as a normal script in project, not sure the reason and the difference between these two debugger.

### Environment Information

- OS: Mac OS 13.2.1
- VS Code Version: 1.81.0
- Extension version : 0.9.0
- Unity Version: 2022.3.0f1

**Comment by jbevain** [comment] 2023-08-07 11:18
Thanks for filing this issue and providing repro steps. We'll look into it and get back to you.

**Comment by jbevain** [comment] 2023-09-07 21:07
@sableangle I've not been able to reproduce the issue.

I've created a new package outside of my project and imported it in my project by using `file:` in the manifest.json.
I can create a breakpoint hit it in the code of the package.

Is there a way you could create a project that reproduces the issue you're seeing? Thanks!

**Comment by sableangle** [comment] 2023-09-08 08:51
I'll try to make a minimal project to reproduce the issue and share with the team!

**Comment by jbevain** [comment] 2023-10-03 21:41
@sableangle I've been unable to reproduce this. Closing this for now. Feel free to re-open if you can create a way to reproduce the issue Thank you!

**Closed by jbevain** 2023-10-03 21:41 UTC
Labels: bug, needs-more-info, area-unity, mac
