### ISSUE TITLE
.NET 7.0 Project Fail to load

### ISSUE THREAD

**Issue by pedroreys** [microsoft/vscode-dotnettools#359] opened 2023-08-08 12:37 UTC
### Describe the Issue

I just created a new console project (`dotnet new console`) and it fails to load.

Solution Explorer says: `A compatible .NET SDK was not found`.

Projects Output has:

```
2023-08-08 09:33:22.280 [info] Additional information of .NET SDKs for diagnostic.NET SDK:
 Version:   7.0.201
 Commit:    68f2d7e7a3

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.7
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.201/

Host:
  Version:      7.0.3
  Architecture: x64
  Commit:       0a2bda10e8

.NET SDKs installed:
  3.1.415 [/usr/local/share/dotnet/sdk]
  6.0.102 [/usr/local/share/dotnet/sdk]
  7.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

2023-08-08 09:33:22.306 [info] Project system initialization finished. 0 project(s) are loaded, and 1 failed to load.
```

**Comment by manwey** [comment] 2023-08-16 15:30
I managed to solve the issue by copying this file libhostfxr.dylib (Notice that my version is 7.0.10 and yours 7.0.201 so your path will be a little different).

sudo cp /usr/local/share/dotnet/host/fxr/7.0.10/libhostfxr.dylib /usr/local/share/dotnet/shared/Microsoft.NETCore.App/7.0.10

**Comment by lifengl** [comment] 2023-09-01 00:58
this is a known issue affecting X64 mac machine with older version of OS, basically similar issue as https://github.com/dotnet/msbuild/issues/9038 (the issue is not unique to homebrew usage).

It should be fixed by future pre-release of the C# Dev Kit extension carrying that fix.

**Closed by lifengl** 2023-09-01 00:58 UTC
Labels: bug, area-sdk, fixed (release pending), mac

**Comment by ps2goat** [comment] 2023-09-06 19:17
> It should be fixed by future pre-release of the C# Dev Kit extension carrying that fix.

Thanks; I hate using pre-release, but I wasn't able to see the solution explorer until I did this. `0.4.10` did not have this, but the pre-release `0.5.2` does. 🤞hopefully nothing breaks like it usually does...

I usually don't like having the latest version, as even Omnisharp would introduce bugs nearly every release of their extension, but it looks like that `0.4.10` version was from 6 days ago, and it's been longer than that since I last went through this routine 🙄

This update also appears to have fixed my ".NET: Generate Assets for Build and Debug" command.
