### ISSUE TITLE
[BUG] Console.WriteLine and Console.Debug do not log to VSCode console

### ISSUE THREAD

**Issue by tpitman** [microsoft/vscode-dotnettools#1309] opened 2024-07-24 20:10 UTC
### Describe the Issue

I develop mobile apps on a Mac. I have many mobile apps written for Xamarin Forms that I am updating to MAUI.

One of the things I do while developing is use the Console.WriteLine method to put in quick debugging things to help find issues that are hard to find while debugging. This way I can just run the app without breakpoints and see how things go.

In Visual Studio all of these outputs go to the debug console output.

In VSCode the Android output is going there, but iOS output is not.

I seem to remember not long ago it was the other way around...iOS output showed up, but Android didn't.

I am using dotnet SDK 8.0.70 via the nuget packages.

Please advise...

### Steps To Reproduce

1. Upgrade a Xamarin Forms app to MAUI
2. Debug on Android with VSCode
3. Notice that Console.WriteLine output shows up in the debug console
4. Debug on iOS with VSCode
5. Notice that Console.WriteLine output does not show up in the debug console

### Expected Behavior

Console.WriteLine output should show up in debug console output window in VSCode no matter the debug target.

### Environment Information

- OS: MacOS Sonoma 14.5
- VSCode: Latest

**Comment by tpitman** [comment] 2024-07-24 20:29
For clarification I basically need the same output that Visual Studio provides in the "Application Output" panel.

**Comment by emaf** [comment] 2024-09-17 21:53
Closing as duplicate of #1431

**Closed by emaf** 2024-09-17 21:53 UTC
Labels: bug, area-maui
