### ISSUE TITLE
[BUG] Cannot read properties of undefined when running in a dev container

### ISSUE THREAD

**Issue by kk-jechan** [microsoft/vscode-dotnettools#1528] opened 2024-10-11 01:18 UTC
### Describe the Issue

I'm running the C# Dev kit in a dev container, and I consistently get this error (non-fatal)

10/11/2024 1:12:03 AM
LimitedFunctionality
StreamJsonRpc.RemoteInvocationException: Request nominateProject failed with message: Cannot read properties of undefined (reading 'size')
   at StreamJsonRpc.JsonRpc.InvokeCoreAsync[TResult](RequestId id, String targetName, IReadOnlyList`1 arguments, IReadOnlyList`1 positionalArgumentDeclaredTypes, IReadOnlyDictionary`2 namedArgumentDeclaredTypes, CancellationToken cancellationToken, Boolean isParameterObject)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageReferences.NuGetRestoreService.NominateAsync(ProjectRestoreInfo restoreData, IReadOnlyCollection`1 inputVersions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.NominateForRestoreAsync(ProjectRestoreInfo restoreInfo, IReadOnlyCollection`1 versions, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.RestoreCoreAsync(PackageRestoreUnconfiguredInput value)
   at Microsoft.VisualStudio.ProjectSystem.PackageRestore.PackageRestoreDataSource.RestoreAsync(IProjectVersionedValue`1 e)
   at Microsoft.VisualStudio.ProjectSystem.TransformBlockSlim`2.TransformManyBlockSlimAsync.ProcessInputAsync(TInput input)
   at Microsoft.VisualStudio.ProjectSystem.DataReceivingBlockSlim`1.ProcessInputQueueAsync(InputDataBuffer inputQueue)

### Steps To Reproduce

Create a dev-container based on  mcr.microsoft.com/devcontainers/dotnet:1-8.0-bookworm
using VSCode Dev-Containers, choosing the .NET container package (and docker-compose)

Because I'm working within a corp firewall, I build a image based on this container, and then push to local azure container registry.
I then point the docker-compose to build a dev container using that image, plus a MSSQLserver container.

### Expected Behavior

I expect no errors when I startup the dev container and the background extension loadup.

### Environment Information

windows 10
vscode 1.94.1
C# Dev Kit 1.11.14

**Comment by kk-jechan** [comment] 2024-10-11 01:19
more detailed info on VSCode
Version: 1.94.1 (system setup)
Commit: e10f2369d0d9614a452462f2e01cdc4aa9486296
Date: 2024-10-05T05:44:32.189Z
Electron: 30.5.1
ElectronBuildId: 10262041
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by smitpatel** [comment] 2024-10-11 07:06
Duplicate of #636

**Closed** 2024-10-14 21:33 UTC
Labels: bug, area-project, area-restore
