### ISSUE TITLE
[SUGGESTION] Unity: Provide Completions for Event Functions

### ISSUE THREAD

**Issue by Number-3434** [microsoft/vscode-dotnettools#913] opened 2024-02-11 13:10 UTC
Provide completions for Unity Event Functions such as `Awake()`, `Start()`, `Update()`, etc.

**Comment by dgileadi** [comment] 2024-02-22 17:00
I use the [Unity Snippets extension](https://marketplace.visualstudio.com/items?itemName=YclepticStudios.unity-snippets) for this.

**Comment by Number-3434** [comment] 2024-02-22 17:06
I use Unity Toolbox, which also checks if the method exists, and provides some other features.

I think it would be better done properly in the official Unity extension, instead of using regexes and ANTLR.

**Comment by jbevain** [comment] 2024-03-14 22:57
This is a duplicate of #370. I'll closing this one while we track the first issue. Thank you!

**Closed by jbevain** 2024-03-14 22:57 UTC
Labels: enhancement, area-unity
