### ISSUE TITLE
The "PrepareResourceRules" task failed unexpectedly. 

### ISSUE THREAD

**Issue by mctainsh** [microsoft/vscode-dotnettools#993] opened 2024-03-14 00:38 UTC
Type: <b>Bug</b>

Trying to run a .net MAUI project on VS Code.
Working envidonment;
 - Visual Studio 
 - Windows 11
 - iPhone 12
Failing environment
  - VS Code
  - Mac M3 OS 14.3

Error 
[{
	"resource": "/usr/local/share/dotnet/packs/Microsoft.iOS.Sdk/17.2.8043/tools/msbuild/iOS/Xamarin.Shared.targets",
	"owner": "msCompile",
	"code": "MSB4018",
	"severity": 8,
	"message": "The \"PrepareResourceRules\" task failed unexpectedly. [/Users/bvm437/iSurv8/iSurv8.App/iSurv8.App.csproj::TargetFramework=net8.0-ios]",
	"source": "cpp",
	"startLineNumber": 2308,
	"startColumn": 3,
	"endLineNumber": 2308,
	"endColumn": 3
}]

Extension version: 0.9.5
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.3.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M3 Pro (12 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|36.00GB (1.31GB free)|
|Process Argv|--crash-reporter-id fa081640-0e81-4da3-9f82-c95627839e4e --crash-reporter-id fa081640-0e81-4da3-9f82-c95627839e4e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:30986170
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30981708
cppperfnew:30979542
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
dsvsc020:30976470

```

</details>

**Comment by mauroa** [comment] 2024-03-19 19:20
Hi @mctainsh.
Could you tell us more about your project? Is it a new MAUI project or an existing project? Are you able to build it with command line and/or VS Mac? Is there any chance you can share the project with us so we can try it?

**Comment by mauroa** [comment] 2024-04-12 15:50
I'm closing this issue since we haven't received the requested information to the user. Please feel free to reopen it in case you still reproduce the issue and have the requested information.
Thanks for your feedback and help.

**Closed by mauroa** 2024-04-12 15:50 UTC
Labels: bug, needs-more-info, triaged, area-maui
