### ISSUE TITLE
[BUG] support relative paths of `dotnet.defaultSolution` in `.codeWorkspace`

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode-dotnettools#43] opened 2023-06-07 13:51 UTC
### Describe the Issue

![image](https://github.com/microsoft/vscode-dotnettools/assets/1876302/48193687-416f-421f-8264-673b58f70231)

### Steps To Reproduce

![image](https://github.com/microsoft/vscode-dotnettools/assets/1876302/084b3d69-1f2e-4ebf-b6e9-38e67f80ae61)

**Comment by heartacker** [comment] 2023-06-07 14:59
please support related path in the solution path setting

**Comment by brock-holum** [comment] 2023-06-07 15:20
@timheuer - I believe @heartacker is talking about relative paths to the solution file not persisting in the workspace file. For example, my workspace and solution file are in a root directory with all projects in a "src" folder within. If I want to specify, `"dotnet.defaultSolution": "../MySolution.sln"` in the workspace file, it updates the value to the full path instead when the workspace is loaded. Example workspace file:

```
{
    "folders": [{
        "name": "src",
        "path": "src"
    },
    {
        "name": "docs",
        "path": "docs"
    },
    {
        "name": "pipeline",
        "path": "pipeline"
    }],
    "settings": {
        "files.exclude": {
            "**/bin/**": true,
            "**/obj/**": true
        },
        "search.exclude": {
            "**/bin/**": true,
            "**/obj/**": true,
            "**/packages/**": true
        },
        "dotnet.defaultSolution": "/Users/bholum/Documents/development/MySolution/MySolution.sln"
    }
}
```

**Comment by arkalyanms** [comment] 2023-06-08 00:00
I believe this will need changes on both the C# and CDK side. cc: @jasonmalinowski for the C# side.

**Comment by jasonmalinowski** [comment] 2023-06-08 00:09
@arkalyanms The only writing the C# extension should be doing is if we're migrating from the Omnisharp option to dotnet.defaultSolution, but a quick peek at the code looks like we'll just move the option verbatim, so I don't think we'd have be the cause of that. So I'd _expect_ this to be C# Dev Kit only. (But, well, I've probably just jinxed myself.)

**Comment by arkalyanms** [comment] 2023-06-08 00:31
> @arkalyanms The only writing the C# extension should be doing is if we're migrating from the Omnisharp option to dotnet.defaultSolution, but a quick peek at the code looks like we'll just move the option verbatim, so I don't think we'd have be the cause of that. So I'd _expect_ this to be C# Dev Kit only. (But, well, I've probably just jinxed myself.)

Ah I remember now, think I added the line to write defaultsolution in the C# extension in your PR, but we decided to not take it.

**Comment by erikrenaud** [comment] 2023-06-15 20:21
Just noticed that my latest commit had this issue also (in a vsvode workspace).
The path should not be relative...

Will hope that this does not affect others on my team till this is fixed.

**Comment by Michael-Eng** [comment] 2023-06-15 20:27
The bug title says the path should be relative, but @erikrenaud says the path should not be relative. Before we do anything is there a consensus here on what path (relative or absolute) we should use?

**Comment by erikrenaud** [comment] 2023-06-15 20:29
> 
Good catch Michael-Eng - I've modified my comment.
It should be relative !

**Comment by heartacker** [comment] 2023-06-30 13:56
can anybody make this fixed , this setting is vary important for team work

**Comment by lifengl** [comment] 2023-07-01 01:15
this specific issue should have been fixed in C# Dev Kit Prelease channel. Can you check whether the fix addressed your issue?

Here are changes related to this issue:

1, if you handcraft a path in the defaultSolution setting, and it is used to open the solution. It would not be updated into any other form automatically, no matter it is a relative path or an absolute path, or can be further normalized. (So if your workspace is now using an absolute path, the newly updated extension will not fix it automatically for you. You would need update it manually once.)

2, we now save relative path for multi-root workspaces (when the setting hasn't been set). The extension always saves relative path for single root workspace, and since relative path can be interpreted on different roots in a multi-root workspace, we didn't do the conversion.  It is important that those relative paths are relative to folders in the workspace, not relative to the workspace file (-- in VS code API, you can create multiple root workspace, and save it very later before you close the workspace, so there is no meaningful way to compute relative path to the workspace setting file, as we don't know where it is.)

 It turns out that vscode has an existing pattern to prefix the folder name for the relative path, so, the relative path under src folder would look like src/solutions/mySolution.sln. 'src/' is the prefix part so we know the relative path solutions/mySolution.sln is interpreted inside the src folder, but not docs folder.  (@jasonmalinowski : as we save this to the defaultSolution setting, the C# extension would need be updated to work with this form of relative path, if it hasn't done so).
 
 Note: although we don't create bare form of relative path like solutions/mySolution.sln, and save into defaultSolution settings, if you create it manually, it will be supported. We will enumerate all root folders in the workspace, and find the first location it is valid, and treat it as the solution file you want to open. (As the 1st issue, we would not update the setting, so it will remain in this state.) (@jasonmalinowski: not sure C# extension need enumerate root folders to find how to interpret a relative path.
 
 Because a relative path can be in either form, we will treat it as the first form, and interpret in the second way only when it is not a valid path as the first form.
 
 We hope this gives you flexible to use in your environment.
 
relative path to the workspace setting file would not work.  Also, we assume the solution file must be inside one of the root folder. The extension doesn't work correctly if the solution is outside of all folders in the workspace. In that case, even if you can open the solution (we will not convert that path to a relative path starting with '..'. Also some features would be broken if the solution file is outside of all folders.

**Comment by lifengl** [comment] 2023-07-01 01:54
@brock-holum : as we explained in the previous comments. In your workspace, because the solution file is outside of all workspace folders, the extension will not generate a relative solution path and save to the defaultSolution setting for you. As we said, the relative path would need be based on one of the folder listed in your workspace. When it is outside of all of them, we would not pick up one, although in your special case, all folders are under a same parent folder, so they would produce same relative path to the solution file in the common root. However, if you manually set the relative path, it would work to a degree, and with the later fix, it would not be overwritten any more.

A solution file outside of workspace roots are not an intended scenario we support.  Under your situation, you may see most feature works, but others may run into gaps. For example, we watch file changes under workspace roots to update projects. Although the solution file outside would be watched as well, other files in the same folder could be missed. For example, when you have Directory.Build.props file along with it, editing it would not cause projects to be updated automatically.  Of course, those are independent to this thread.

**Closed by lifengl** 2023-07-01 01:54 UTC
Labels: bug, triaged, area-solution

**Comment by heartacker** [comment] 2023-07-01 02:36
We believe that if the workspace file and the solution are placed in the same folder, our c# dev kit should be able to parse the user's manually written configuration (perhaps not actively created and fixed), instead of only supporting the folder defined inside the workspace.

In a workspace with multiple roots, when we set the dotnet.defaultSolution in the workspace file, then the relative path should be relative to the workspace file.

![image](https://github.com/microsoft/vscode-dotnettools/assets/1876302/0a485e25-19f9-4f49-b81e-c24210d0a116)

![image](https://github.com/microsoft/vscode-dotnettools/assets/1876302/73b4713e-f88d-4bc3-8f0a-6db4089b63bb)

**Comment by heartacker** [comment] 2023-07-01 02:37
but now it is not supported

**Comment by heartacker** [comment] 2023-07-01 02:41
This relative path should be relative to the "codeworkspace file"

**Comment by lifengl** [comment] 2023-07-02 05:43
I don't think relative path to the workspace configuration can be supported. 
 1, when a user creates a multi-root workspace, the workspace file may not exist, and that file can be created much later when the user decides to save it, all settings were set much earlier than that.
 2, i could not find any VS Code API to allow extensions to get that file path.
