### ISSUE TITLE
can't connect to server

### ISSUE THREAD

**Issue by phutuan123vn** [microsoft/vscode-dotnettools#336] opened 2023-08-06 06:26 UTC
Type: <b>Bug</b>

C# dev kit always active fail

Extension version: 0.4.2
VS Code version: Code 1.81.0 (6445d93c81ebe42c4cbd7a60712e0b17d9463e97, 2023-08-02T12:37:13.485Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|13.94GB (5.83GB free)|
|Process Argv|--crash-reporter-id bc14a040-944e-47c2-9163-04eaf05cdf11|
|Screen Reader|no|
|VM|44%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
py29gd2263cf:30792227
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
3biah626:30602489
f6dab269:30613381
a9j8j154:30646983
showlangstatbar:30737416
vsctsb:30748421
a2ce3375:30757347
pythonfmttext:30731395
pythoncmv:30756943
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
e537b577:30795824
dsvsc013:30795093
dsvsc014:30804076

```

</details>

**Comment by timheuer** [comment] 2023-08-06 21:31
Hi @phutuan123vn can you provide a bit more information? Are you getting errors? ANything from the C# Dev Kit or Extension Host logs you can share?

**Comment by arkalyanms** [comment] 2023-08-16 21:22
Failure still in the dataflow formation. Starting with project.

**Comment by phutuan123vn** [comment] 2023-08-17 05:42
> Failure still in the dataflow formation. Starting with project.

I always get that whenever I create or open a project.

**Comment by kvenkatrajan** [comment] 2023-08-17 18:35
Duplicate of #368

**Comment by phil-allen-msft** [comment] 2023-08-17 21:44
Duplicate of #368

**Closed by phil-allen-msft** 2023-08-17 21:44 UTC
Labels: bug, area-project, area-razor
