### ISSUE TITLE
[BUG] Dowload .NET Runtime always failed

### ISSUE THREAD

**Issue by jamesfancy** [microsoft/vscode-dotnettools#138] opened 2023-06-14 07:14 UTC
### Describe the Issue

[.NET Runtime] output

```plaintext
Downloading the .NET Runtime.
Using configured .NET path: C:\Program Files\dotnet\dotnet.exe
Downloading the .NET Runtime.
Downloading .NET version(s) 7.0.7 .......................................................................................................................... Error!
Failed to download .NET 7.0.7:
.NET installation timed out.

 Error!
.NET Acquisition Failed: Installation failed: Error: .NET installation timed out.
```
--- 

I have installed newest .NET SDK & Runtime which versions are 7.0.304 & 7.0.7。I have also set `existingDotnetPath`。

I don't know why it try to download yet.  And the downloading always failed.

![image](https://github.com/microsoft/vscode-dotnettools/assets/3953094/73b7d4fe-02c5-4f27-9e30-d58af0278d18)

### Steps To Reproduce

Just use Code to open a dotnet project directory.

### Environment Information

```powershell
❯❯❯ dotnet --info
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

运行时环境:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.301 [C:\Program Files\dotnet\sdk]
  5.0.408 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.118 [C:\Program Files\dotnet\sdk]
  6.0.402 [C:\Program Files\dotnet\sdk]
  6.0.410 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  arm64 [C:\Program Files\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\arm64\InstallLocation]
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

```powershell
❯❯❯ where.exe dotnet
C:\Program Files\dotnet\dotnet.exe
```

**Comment by PostCyberPunk** [comment] 2023-06-14 08:23
global proxy fixed my problem...

**Comment by jamesfancy** [comment] 2023-06-15 10:15
I add two more config items to solve the problem

```json
    "dotnetAcquisitionExtension.existingDotnetPath": [
        {
            "extensionId": "ms-dotnettools.csdevkit",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.csharp",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        },
        {
            "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"
        }
    ]
```

**Comment by pty819** [comment] 2023-06-30 06:41
you can use clash's TUN mode to solve that. But Microsoft should change this link to a gfw-unbanned address....

**Comment by kid1412621** [comment] 2023-07-06 14:32
> I add two more config items to solve the problem
> 
> ```json
>     "dotnetAcquisitionExtension.existingDotnetPath": [
>         {
>             "extensionId": "ms-dotnettools.csdevkit",
>             "path": "C:\\Program Files\\dotnet\\dotnet.exe"
>         },
>         {
>             "extensionId": "ms-dotnettools.vscodeintellicode-csharp",
>             "path": "C:\\Program Files\\dotnet\\dotnet.exe"
>         },
>         {
>             "extensionId": "ms-dotnettools.csharp",
>             "path": "C:\\Program Files\\dotnet\\dotnet.exe"
>         },
>         {
>             "extensionId": "ms-dotnettools.vscode-dotnet-runtime",
>             "path": "C:\\Program Files\\dotnet\\dotnet.exe"
>         }
>     ]
> ```

Thanks, I cannot even find this in official doc.

**Comment by nagilson** [comment] 2023-09-12 17:37
cc @baronfel

**Comment by nagilson** [comment] 2023-09-18 19:00
I'm sorry you're having this bad experience with the runtime extension, this is an issue with the install scripts CDN. [AzureFeed 'dotnetcli.azureedge.net/dotnet' in dotnet-install script was too slow in China · Issue #7239 · dotnet/core (github.com)](https://github.com/dotnet/core/issues/7239) This is technically a duplicate of this issue so it's being tracked here, our current CDN has issues in China and we are thinking of switching

**Comment by nagilson** [comment] 2023-09-18 19:03
I would be willing to re open the issue. It would help us sell the change to a new CDN if we had the information to prove China is experiencing CDN issues. I know it's asking a lot but can you help provide us with more information without a proxy so we can get change needed from our networking partners to resolve this? If you don't want to disclose this information publicly, let us know and we can receive it in a private forum.

@YUTOM233 @pty819 @jamesfancy @PostCyberPunk 

##

Instructions: (Provide the following)

Public IP (visit https://ipinfo.io/)
HAR file while the issue occurs
MTR (100 count) to "dotnetcli.azureedge.net" (excluding quotations)
Visit/provide us the results from http://wpc.2dcc.edgecastcdn.net/002DCC/n2/
Visit/provide us the results from https://tools.vdms.com/
We've additionally included steps on how to obtain a HAR/MTR below should the end user require assistance to the ask above. This information would help our team greatly towards our efforts in investigating the report.

Below are the steps for collecting HAR/MTR

HAR file :
Here is a guide from Google support, explaining how to use the developer tools to capture the full log of the interaction.
https://support.google.com/admanager/answer/10358597?hl=en

MTR:
Download and install WinMTR: Visit the WinMTR website (https://sourceforge.net/projects/winmtr/) and download the latest version of WinMTR suitable for your operating system.
Launch WinMTR: After installation, open WinMTR from the location where it was installed.
Enter the target destination: In the "Host" field, enter the IP address or domain name of the destination you want to test. For example, you can enter a website URL or an IP address , the domain name portion of the URL of the site where you are seeing 504 errors.
Start the test: Click on the "Start" or "Start/Stop" button to begin the test. WinMTR will start sending packets to the destination and collect data about each network hop along the way.
Copy the data or send a screenshot of the MTR to help us diagnose what server may be returning that code.

(Taken from @timheuer )

**Comment by jamesfancy** [comment] 2023-09-21 07:14
I cannot visit google.com since a well known reason.

My IP is dynamical, current it's `171.93.137.212`.

I haven't meet the issue again since I changed the configuration.

Here are information:

---

MTR  for dotnetcli.azureedge.net

```plain
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                   No response from host -  100 |    6 |    0 |    0 |    0 |    0 |    0 |
|                               10.1.0.53 -    0 |   32 |   32 |   19 |   93 |  325 |   58 |
|                   No response from host -  100 |    6 |    0 |    0 |    0 |    0 |    0 |
|                           182.144.10.77 -    0 |   32 |   32 |   21 |   95 |  325 |   72 |
|                            182.144.6.13 -   27 |   15 |   11 |   19 |   52 |  186 |   61 |
|                   No response from host -  100 |    6 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |    6 |    0 |    0 |    0 |    0 |    0 |
|                             202.97.12.9 -   46 |   11 |    6 |    0 |   66 |   86 |   53 |
|                           202.97.27.238 -    0 |   32 |   32 |  208 |  285 |  532 |  242 |
|                            218.30.53.85 -   27 |   15 |   11 |    0 |  295 |  469 |  276 |
|                            63.223.17.57 -   50 |   10 |    5 |  365 |  390 |  442 |  372 |
|     63-218-115-82.static.pccwglobal.net -   25 |   16 |   12 |  390 |  472 |  700 |  506 |
|         ae-66.core1.hkc.edgecastcdn.net -   34 |   12 |    8 |  374 |  419 |  560 |  374 |
|                          117.18.232.200 -   37 |   11 |    7 |  387 |  495 |  700 |  451 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

---

I cannot open http://wpc.2dcc.edgecastcdn.net/002DCC/n2/,

MTR for wpc.2dcc.edgecastcdn.net

```plain
|------------------------------------------------------------------------------------------|
|                                      WinMTR statistics                                   |
|                       Host              -   %  | Sent | Recv | Best | Avrg | Wrst | Last |
|------------------------------------------------|------|------|------|------|------|------|
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                               10.1.0.53 -    0 |  418 |  418 |   18 |   94 |  968 |   22 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                           182.144.10.77 -    0 |  418 |  418 |   18 |   91 |  899 |   37 |
|                            182.144.6.62 -   10 |  301 |  271 |    0 |   78 |  748 |   32 |
|                           202.97.21.185 -   97 |   86 |    3 |    0 |  156 |  311 |   98 |
|                           202.97.94.134 -   62 |  121 |   46 |   47 |  101 |  805 |   68 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|                   No response from host -  100 |   84 |    0 |    0 |    0 |    0 |    0 |
|________________________________________________|______|______|______|______|______|______|
   WinMTR v0.92 GPL V2 by Appnor MSP - Fully Managed Hosting & Cloud Provider
```

attached `chromewebdata.har` (in zip) is for this URL.

---

attached `tools.vdms.com.har`  (in zip) is for https://tools.vdms.com/

[attachment.zip](https://github.com/microsoft/vscode-dotnettools/files/12681461/attachment.zip)

**Comment by nagilson** [comment] 2023-09-25 23:08
@jamesfancy Thank you so much, this is extremely useful information. 😄  We will use this to evaluate a new cost-center and server to host our content so users in China can have a better experience

**Comment by nagilson** [comment] 2023-11-01 21:33
For the record, Verizon basically used your info to confirm their servers dont work well in China or India, and then told us they wont be fixing that problem. So, we are investing in changing to use our own infrastructure.

**Comment by nagilson** [comment] 2024-07-30 17:34
We believe this issue has been fixed, if you still encounter it, please let us know.

**Closed by nagilson** 2024-07-30 17:34 UTC
Labels: bug, area-sdk
