### ISSUE TITLE
Please highlight the open file in Solution Explorer

### ISSUE THREAD

**Issue by mmiller-d8** [microsoft/vscode-dotnettools#1007] opened 2024-03-19 18:18 UTC
Type: <b>Feature Request</b>

It would be really nice to have the open file highlighted in the Solution Explorer similar to what is done in Visual Studio for Mac.  That feature is especially helpful for large projects.

I don't know if that's possible since you could potentially have the Solution Explorer closed and be working out of the File Explorer instead, but it would be really nice if you could.  

Extension version: 1.4.29
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:57.520Z)
OS version: Darwin arm64 23.2.0
Modes:

**Comment by webreidi** [comment] 2024-03-20 17:34
This feature is actively being worked on. Closing as duplicate of https://github.com/microsoft/vscode-dotnettools/issues/51.

**Closed by webreidi** 2024-03-20 17:34 UTC
Labels: enhancement
