### ISSUE TITLE
[SUGGESTION] Use diff test explorer rendering on assert failures

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#1330] opened 2024-07-31 20:26 UTC
### Describe the feature you'd like

Originally filed by @rmannibucau at https://github.com/dotnet/vscode-csharp/issues/7410

## Is your feature request related to a problem? Please describe.
When running a test (xunit or nunit) the assert failures are poorly readable when one liners and impossible to use when > 1 line.

## Describe the solution you would like
There is a new vscode API to show the "diff" side by side so it would be neat to use that instead of just the runner output (see https://github.com/microsoft/vscode-java-test/issues/1070 for the kind of view which could help).

## Applicable Scenarios
Anytime an assert fails comparing two values.

## Describe alternatives you've considered
Rewrite all the asserts to extract the two values (either in files or in debug mode).

(indeed it is not satisfying)

**Comment by ocallesp** [comment] 2024-08-13 22:47
Duplicate of https://github.com/microsoft/vscode-dotnettools/issues/1294

**Comment by rmannibucau** [comment] 2024-08-14 06:57
Not sure it is a duplicate since both affect different ui parts and features - but happy to get both ;)

**Comment by ocallesp** [comment] 2024-09-09 15:10
You are right @rmannibucau. Is not the same.

**Comment by ocallesp** [comment] 2024-09-19 22:28
merged this code change today. This will be available in the next release.

**Closed by ocallesp** 2024-09-19 22:28 UTC
Labels: enhancement, area-test

**Comment by AbhitejJohn** [comment] 2024-10-01 23:22
xunit tests do not seem to be benefitting from this work, we've logged this to track enabling that: #1504
