### ISSUE TITLE
[BUG]  Solution Explorer not opening after moving to the right side

### ISSUE THREAD

**Issue by dibarbet** [microsoft/vscode-dotnettools#864] opened 2024-01-17 21:18 UTC
### Describe the Issue

Copied from https://github.com/dotnet/vscode-csharp/issues/6811, originally filed by @karl-gardner 

## Environment data
VS Code version:
Newest version available
C# Extension version:
Newest Version available

## Steps to reproduce

1. Download vscode and C# Dev Kit extension
2. Open existing C# projects/solution or create a new project with "dotnet new console" command.
3. Close vscode
4. Open folder containing c# project with vscode and notice the solution explorer pop up on the bottom left side (might need to sign in to microsoft to use c# dev kit):
<img width="1305" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/6d433c02-2bfe-44e0-8eac-56f22e2a0d4f">

5.  Drag the solution explorer over to the right side to be able to see it better instead of the bottom left side (outlined in red):

<img width="1336" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/22849b40-e2ae-4a1c-96e4-2b16129f330d">

6. Close vscode. Open same folder or any other folder containing c# project (csproj files). Now solution explorer is missing:

<img width="1312" alt="image" src="https://github.com/dotnet/vscode-csharp/assets/91646805/0cca9e90-eb73-4a12-a343-c40c0b8d9e35">

## Expected  behavior
The solution explorer is supposed to show up in vs code when opening a c# project containing a csproj file. Preferably it will show up in the same location that it was left at like on the right side of the screen.

## Actual behavior
Does not even show up anywhere. 

## Additional context
Once the solution explorer is moved to the right side of the screen and vs code is closed it will not show up anywhere and I can't find where to open it again. Let me know if you are not able to recreate this. I have recreated it multiple times now.

**Comment by timheuer** [comment] 2024-01-18 18:39
@karl-gardner the screenshot showed that the view doesn't look like it is selected (blue underline):

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/05631d5b-32f4-43c7-b26f-f5f517c92294)
vs:
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/be6aedcd-f61c-448c-9018-617af5b446d7)
(not selected)

Can you confirm you are selecting the view.  It is showing up for me:

https://github.com/microsoft/vscode-dotnettools/assets/4821/fc67b407-4a7e-42e2-9fc7-84d8ce21d1f5

**Comment by karl-gardner** [comment] 2024-01-19 00:30
Hello @timheuer thanks for checking. 

Everytime I open vscode I have to click the "view" button and then "Enable Preview Editors" to get it their. But when I click "Enable Preview Editors" again it stays their:

https://github.com/microsoft/vscode-dotnettools/assets/91646805/b91cb130-0529-4c4e-835f-dd8754b7fdc6

Is it supposed to happen like that?

**Comment by timheuer** [comment] 2024-01-19 18:34
Wow, good additional tip here, but I can't reproduce either even with that toggle change.  Will have to see if someone else can reproduce.  Unfortunately I think this isn't something that logs emit anything of value here.

**Comment by timheuer** [comment] 2024-01-19 20:23
Ok, quick chat with colleagues -- this is likely a VSCode issue -- unfortunately I cannot transfer the issue to that repo -- @karl-gardner can you open it and copy all the screenshots and your video to a new issue on https://github.com/microsoft/vscode repo and link it here -- I'll nudge it to some folks

**Comment by timheuer** [comment] 2024-01-29 16:45
Closing as issue moved to microsoft/vscode

**Closed by timheuer** 2024-01-29 16:45 UTC
Labels: bug, area-vscode
