### ISSUE TITLE
[BUG] Intellisense broke

### ISSUE THREAD

**Issue by CallMeTheWolf** [microsoft/vscode-dotnettools#329] opened 2023-08-05 01:57 UTC
### Describe the Issue

Intellisense is not picking up anything from Unity variables/methods.  It worked prior to installing the new extension.  The problem began when switching to Microsoft Unity extension.  A few examples are provided.  

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/eeac1e50-2aba-4165-9b64-ca2f9491957c)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/6b3db821-72e1-4de6-b931-d4c2bd00065a)

Thank you for your time and assistance.

### Steps To Reproduce

1.  Install Windows Unity Extension v0.9.0
2.  Login for C# Dev Kit
3.  Close VS Code
5.  Update VS Editor in Unity
6.  Select VS Code under preferences in Unity
7.  Generate .csproj files
8.  Open script in unity
9.  Sigh in defeat

### Expected Behavior

Intellisense to pick up Unity Variables and functions.  When typing the intellisense populate with options used by unity.  Colors change and when hovering over a variable vscode gives the tooltip.

### Environment Information

- OS: Windows 11 22H2
- VSCode v1.81.0
- Tried Unity 2022.3.5f1 and 2022.3.6f1
- Visual Studio Editor v2.0.20
- .Net 7.0.306
![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/5bfc9e00-60f2-428d-8c51-9edb9e9fec95)

Extensions:
- C# Dev Kit v0.4.2
- Microsoft Unity v0.9.0
- C# v2.0.328

**Comment by lc-spxl** [comment] 2023-08-05 05:07
Hi from ubuntu: Projects in bar spinning endless and no autocomplete. Thanks

**Comment by 976047167** [comment] 2023-08-05 13:55
![image](https://github.com/microsoft/vscode-dotnettools/assets/29335242/f170db2e-52ea-44db-96b7-cd4b7530a26e)
I am same .this is mylog

**Comment by CallMeTheWolf** [comment] 2023-08-05 14:38
![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/7fb7a5a2-cde9-470e-8d6e-98dfc408da0f)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/ec4dbe2f-9c94-47ba-9c48-99d1eea01ded)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/59de29d2-15f2-4a64-8b5c-ee142b22bbad)

**Comment by CallMeTheWolf** [comment] 2023-08-05 14:41
I did not mean to close the ticket, was a misclick.  But I am not showing an infinite load like others, but it does look like mine is stuck creating a server.

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/73d8fd2a-4675-4053-9b1b-dfc790e94b64)

**Comment by cacheflowe** [comment] 2023-08-05 16:07
> I did not mean to close the ticket, was a misclick. But I am not showing an infinite load like others, but it does look like mine is stuck creating a server.
> 
> ![image](https://user-images.githubusercontent.com/71703891/258591281-73d8fd2a-4675-4053-9b1b-dfc790e94b64.png)

I'm having this same issue - my output log stops at `Starting Server...`, and I have no Intellisense for Unity libraries. I've updated Unity's Visual Studio package to 2.0.20 as instructed, and removed all previous Unity/C#-related extensions in VSCode, then reinstalled the new official Unity/MS package and dependencies. This is happening on both Mac & PC for me.

**Comment by jbevain** [comment] 2023-08-05 16:22
Hi folks,

Thanks for filling this issue. Looks like a few of you are facing this issue with our preview, hopefully you all share a common root cause that we can diagnose and fix promptly. We haven't seen this happening, so it will take some investigation.

For what it's worth, while “it works on my machine”, the C# output for me is similar to yours:

<img width="985" alt="C# output" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/0cba0463-62a8-4272-8911-b32d61587c6e">

A few questions:

* Do you see any issue or exception in Unity that could be triggered by our project generation?

* In your Unity project folder, do you see the `.sln` and `.csproj` that our package should generate? In Unity's preferences, External Tools, could you do `Regenerate project files` just in case? Do the `.csproj` and `.sln` look weird?
 
<img width="845" alt="External Tools" src="https://github.com/microsoft/vscode-dotnettools/assets/79284/594b3e9a-38ee-4f65-aceb-5c1f2ce41633">

* There are other Output categories, like `C# Dev Kit`, `C# LSP Trace Logs`. Do any of those have any information?

* What happens if you use the VS Code command `.NET Open Solution`? Or `.NET Close Solution` then `.NET Open Solution`? Or `.NET Restart Language Server`?

**Comment by jbevain** [comment] 2023-08-05 16:48
Also from #333 we've learned that having the Unity Package `Netcode for Entities` crashes the Language Server Protocol providing code completion.

**Comment by lc-spxl** [comment] 2023-08-05 17:23
Relevant logging from C# output is `Starting server...`

**Comment by cacheflowe** [comment] 2023-08-05 18:02
Thank you for looking @jbevain !

I didn't find anything odd about my project files, and everything else works as it should. 

I did just run `.NET Open Solution` from the command palette, and that brought back Intellisense recognition of Unity library definitions! However, it died shortly after that. I think I had changed something in VSCode settings.json. 

After more fiddling, I ran `.NET Clean`, then `.NET Open Solution`, and now it's working again, for now 😱 It tok a little while for things to rebuild.

**Comment by CallMeTheWolf** [comment] 2023-08-05 18:09
I have tried regenerating the project files many times to no avail.  I do get this error though when running .Net Open Solution, perhaps something wrong with a .sln?

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/2fb7ee08-edb5-43da-9e62-09ba78f7d6bc)

**Comment by CallMeTheWolf** [comment] 2023-08-05 18:11
> Tried regenerating the sln files from Unity also adding those as you shared.
> 
> Relevant logging only from C# tap that outputs `Starting server...` .
> 
> Projects keep spinning.
> 
> ![image](https://user-images.githubusercontent.com/105427834/258599331-0d3a30ce-8553-45e3-a257-68b023c8a45b.png)
> 
> .NET open / close projects does nothing in my editor
> 
> Another note, closing and reopening the editor, ask me to reinstall the Unity package ...

I had that same issue, what fixed it for me was to turn off settings sync, go into the vscode folder and delete the extensions.json for the saved extensions, and let vscode repopulate it then downloading it again.

**Comment by cacheflowe** [comment] 2023-08-06 00:38
I fixed on my PC earlier (after running in circles), and just fixed it on my Mac with a much more focused set of steps. I noticed some error messages about my project files being out of date while I was doing this. 

**In Unity**
- Manually update the Visual Studio Editor package in Unity Package Manager. Ignore the VS Code package, even though we're wanting our VS Code IDE to work properly. It sounds like that one's getting deprectad.
  - Click on the Visual Studio Editor package
  - Click the "Unlock" button in upper-right
  - Click "Version History"
  - Update to `2.0.20`
- Go to Unity's Preferences section: External Tools
  - Choose Visual Studio Code as the External Script Editor
  - Click "Regenerate Project Files"

**In VS Code**
- Update VSCode extensions to pre-release versions:
  - C# Dev Kit `v0.4.2`
  - C# `v2.0.328`
- Back in VS Code, run the following commands from the command palette
  - `.NET Clean`
  - `.NET Open Solution`
  - Maybe try `.NET Restart Language Server` too

Hopefully this helps someone!

**Comment by CallMeTheWolf** [comment] 2023-08-06 02:34
> I fixed on my PC earlier (after running in circles), and just fixed it on my Mac with a much more focused set of steps. I noticed some error messages about my project files being out of date while I was doing this.
> 
> **In Unity**
> 
> * Manually update the Visual Studio Editor package in Unity Package Manager. Ignore the VS Code package, even though we're wanting our VS Code IDE to work properly. It sounds like that one's getting deprectad.
>   
>   * Click on the Visual Studio Editor package
>   * Click the "Unlock" button in upper-right
>   * Click "Version History"
>   * Update to `2.0.20`
> * Go to Unity's Preferences section: External Tools
>   
>   * Choose Visual Studio Code as the External Script Editor
>   * Click "Regenerate Project Files"
> 
> **In VS Code**
> 
> * Update VSCode extensions to pre-release versions:
>   
>   * C# Dev Kit `v0.4.2`
>   * C# `v2.0.328`
> * Back in VS Code, run the following commands from the command palette
>   
>   * `.NET Clean`
>   * `.NET Open Solution`
>   * Maybe try `.NET Restart Language Server` too
> 
> Hopefully this helps someone!

I'm glad you got your project working and appreciate the help!  In my case though the steps didn't change anything for my projects.  I tried deleting all the .csproj and the .sln, the project manager visual studio extension, and then restarted the process again.  It still is stuck at the same spot of the posts above, no intellisense, server looks like it starts ok, no issues in the other consoles, I get no errors or anything strange in Unity, and I get the error that no solution is found when .Net Open Solution is run.  Thanks y'all for the helpful leads.

**Comment by CallMeTheWolf** [comment] 2023-08-06 02:57
![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/96abe94d-972e-42b4-9294-00643c574b79)

**Comment by lc-spxl** [comment] 2023-08-06 04:33
I tried to run the language server with debug logging and when moving hover `UnityEngine` it says no reference.

The Solution Explorer tab shows the sub projects that looks ok. However, trying to expand them result in the usual endless spinner 

![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/60490dfc-03d6-4588-8411-5c373c9c8967)

Where could I see the logging of the Projects loading process ?

Thx

**Comment by nkoudelia** [comment] 2023-08-06 14:00
For me adding the `.vscode/settings.json` with a path to the solution file fixes the issue of broken intellisense:

```json
{
    "dotnet.defaultSolution": "path/to/my/solution/file.sln"
}
```

But most of my projects are simple console apps without a solution file... what should I do then?

**Comment by CallMeTheWolf** [comment] 2023-08-07 05:23
@nkoudelia I appreciate the insight, was there anything else you did besides modify the settings.json?  I was not able to get the fix to work unfortunately, this is the error I get:

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/4e0cff6a-242a-48ed-ac2a-89b7bf9eb2d9)

It's like vscode is not correctly loading the project files and/or solution.    Is there anything amiss from this .csproj file that may be causing the issue?  I omitted the sections following the pictured that have all the Reference Include's.

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/71dc4558-3aa2-45a0-ad7f-d9d49bb1ffc0)



-*.sln
Microsoft Visual Studio Solution File, Format Version 12.00
Visual Studio 15

**Comment by nkoudelia** [comment] 2023-08-07 07:56
Nope, not doing anything else. Here are my steps:

1. Create an empty console app
![image](https://github.com/microsoft/vscode-dotnettools/assets/91388229/b504bcc7-6811-4df7-af32-663903c623a4)

2. Open VS Code and see broken intellisense
![image](https://github.com/microsoft/vscode-dotnettools/assets/91388229/cb98ccf9-de73-44ce-8985-6f9d7e02ea78)

3. Create a .sln file and add .vscode/settings.json.
![image](https://github.com/microsoft/vscode-dotnettools/assets/91388229/c19b04a3-ccac-4c38-8f35-5955fdc7e2ea)
![image](https://github.com/microsoft/vscode-dotnettools/assets/91388229/6bcaf047-0adc-4264-85df-4f62e97abbfc)

4. Ctrl+Shift+P & Reload Window - intellisense works now
![image](https://github.com/microsoft/vscode-dotnettools/assets/91388229/6a76f7d1-e4f0-435a-98ba-bd763b688af1)

**Comment by lc-spxl** [comment] 2023-08-07 08:05
Unity extension add it by its own. However is not enough to have intellisense to work. Seems to me there is something not working properly in the Projects parts as it fails after a while loading subprojects

**Comment by nkoudelia** [comment] 2023-08-07 08:24
The root cause might be much deeper than Unity if even a simple console app is failing

**Comment by jbevain** [comment] 2023-08-07 11:53
@CallMeTheWolf does this happen also if you create a new Unity project and add just one script, or is this specific to your current Unity project?

**Comment by CallMeTheWolf** [comment] 2023-08-07 12:18
> @CallMeTheWolf does this happen also if you create a new Unity project and add just one script, or is this specific to your current Unity project?
> 
> We've already identified one Unity package that causes the Intellisense to crash, it's possible there's more.

I have attempted using a brand new project with just the basic extensions that come with a Unity2D project with the latest Unity Version, same result as the main project I was using.  Perhaps one of the 2D packages are causing it?  Also, I'm not using the unity plugin that was identified on the other post.  Thank you for your time.

**Comment by MrRadian** [comment] 2023-08-07 15:00
Hi, I have this problem to. 
What I have noticed if you open a folder with vs code and select your sln file after asking for a solution then intellisense works. If you fire up the file from unity then vs code reloads the entire workspace and intellisense does not work

File open from unity
![obraz](https://github.com/microsoft/vscode-dotnettools/assets/62394971/65da81b0-1970-45d5-9a3b-0905cfdf6285)

File loaded with open folder
![obraz](https://github.com/microsoft/vscode-dotnettools/assets/62394971/7799d8ce-9d51-45f9-a3d6-061c186b4325)

**Comment by CallMeTheWolf** [comment] 2023-08-07 15:52
@MrRadian Thank you for your assistance.  I had added the line of code to the .vscode/settings.json previously like I mentioned some comments ago, and it didn't appear to do anything initially, but the project files started to populate under the solution explorer tab.  Your lead though got me poking around the files though double checking stuff.  I found that, at least in my case, it finally fixed itself when I right click the project in Solution Explorer and hit clean there.  For some reason it didn't work when I input the command in the terminal, only when I did it through the right click.  

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/e868a384-121a-41a2-9f22-800e2a9333fc)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/037c17dc-b72f-41b4-9077-9d7c9eb6830c)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/a6f33c07-d507-425f-aa9c-2752bbfb1de8)


There is now the annoyance that everytime I open vscode I must right click that folder and hit clean so that intellisense starts registering, but at least intellisense is back in business.  Major win, thank you!

After closing and opening vscode many times, it seems it loads dependencies randomly, mainly references to other scripts so intellisense doesn't pick them all up, but doing the right click clean everything appears to work perfectly for that session.  

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/83605b09-8ba0-4249-bc8a-3d1b0f5f7922)

![image](https://github.com/microsoft/vscode-dotnettools/assets/71703891/9f35ffe7-9435-49cb-97be-8d0359b36efb)

**Comment by lc-spxl** [comment] 2023-08-08 04:12
Happy to see it's working somehow, adding a fullpath to setting.json and clean the solution has not helped in my case..

**Comment by MrRadian** [comment] 2023-08-08 09:08
@lc-spxl did you try to open entire project with open folder option under File tab?

**Comment by lc-spxl** [comment] 2023-08-08 09:21
Yes but it is the same as opening from unity.

It does open and for a moment I see the `using` as green but the goes back to azure. 

Also, every time it ask to install the Unity extension.

Thx

**Comment by MrRadian** [comment] 2023-08-08 09:40
@lc-spxl what version of C# Dev Kit you are using?

**Comment by MrRadian** [comment] 2023-08-08 09:57
I am on Linux too. Try one more thing. Go to C# extension
![obraz](https://github.com/microsoft/vscode-dotnettools/assets/62394971/9c6cfc87-4073-45c5-93aa-a978406040d2)
 
Open settings of this extension and under Omnisharp search for "Use modern net"
![obraz](https://github.com/microsoft/vscode-dotnettools/assets/62394971/f68f5772-57e2-4c44-8570-49c4261bb711)
If you have this option check, uncheck it and restart code.

**Comment by lc-spxl** [comment] 2023-08-08 10:02
Thank you very much, it is unchecked.

What make me sick is that for a couple of seconds it seems to work

![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/243f6328-e94e-4019-9a43-4d2f240754a2)

then goes away

![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/619cb0e5-aa1a-4f87-81e7-afe430aed0d4)

:cry:

**Comment by MrRadian** [comment] 2023-08-08 10:08
Did you try now open folder option, maybe remove defaultSolution option in settings.json of your project

**Comment by lc-spxl** [comment] 2023-08-08 11:40
Ok tried. Closing the solution from solution explorer cleans the settings.json flag.  Restarted various times. Also tried opening solution, Clean and then close + reload. Still no luck. 

Let's not clutter everyone email with my personal issue. I'll keep watching here for updates. 

In the meanwhile I'll go on developing with notepad-like features :parasol_on_ground:

**Comment by jbevain** [comment] 2023-08-08 12:44
@lc-spxl, do you have any error in the `Output` tab, category `C#`?

**Comment by lc-spxl** [comment] 2023-08-08 12:57
No errors. With solution open or not what I see is this

![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/a5e9c4d8-15cb-4832-bf21-3fca028b13b9)
![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/21377434-0031-4b06-ab56-52b8b98afed2)
![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/d845bcc3-86d4-484b-9486-c4dd0eba2777)

**Comment by MrRadian** [comment] 2023-08-08 13:20
What you have in C# dev kit output?

**Comment by lc-spxl** [comment] 2023-08-08 13:22
![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/03f9a70d-3934-4790-badd-27b8fc2f37f0)


and this popping out every time, regardless of having installed it many times
![image](https://github.com/microsoft/vscode-dotnettools/assets/105427834/30137225-890a-4cbb-b507-ba7d536612d2)

**Comment by sailro** [comment] 2023-08-12 08:23
> Maybe remove all unity plugins and install it again Try to remove folder .vscode and .config/vscode folders. This will remove all extensions and potencial bug settings

Be careful removing your `.vscode` folder, because we store dedicated settings and launch profiles. At least regenerate project files from Unity to restore default settings/profiles after deletion.

**Comment by sailro** [comment] 2023-08-12 08:38
I'm trying to summarize the thread with the following:

1- Make sure you have the proper `VSCode` prerequisites:
- C# Dev Kit v0.4.2
- Microsoft Unity v0.9.0
- C# v2.0.328

2- Make sure you have the proper `Unity` prerequisites:
- Visual Studio Editor Package 2.0.20
- `VSCode` should be selected as your preferred external editor. You should selected something like `Visual Studio Code [[Version]]`

3- Make sure C# Devi Kit is not displaying any error message:
- regarding .NET runtime acquisition (perhaps you need to bump the timeout: In `VSCode`, go to `File/Preferences/Settings, Extension/.NET Install Tool` and bump install timeout value to 1200).
- regarding .NET SDK not found (install the recommended SDK version).
- regarding unsupported projects (check Unity prerequisites, select `VSCode` as your external editor and to regenerate project files from Unity)

4- Inspect your `.vscode/settings.json`
- you should have a "dotnet.defaultSolution" pointing to solution file.
- you can even delete the `.vscode` folder then try to regenerate project files from `Unity` to restore defaults.
- back in VS Code, you can try to run the following commands from the command palette: `.NET Clean`, `.NET Open Solution`, ` .NET Restart Language Server`.


5- Misc
- We have found that Unity Package `Netcode for Entities` crashes the Language Server Protocol providing code completion

**Comment by inancelal** [comment] 2023-08-12 15:07
I was doing fine since last week, I am having this problem as you can see in the pictures, i guess something updated but idk what. If someone would tell me how to figure out i would be thankful.

<img width="1386" alt="Screenshot 2023-08-12 at 6 01 57 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/129279817/d95c99a4-3ed3-4465-9986-ce7a5585e937">
<img width="294" alt="Screenshot 2023-08-12 at 6 02 16 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/129279817/59465b73-b8ac-4bb4-9211-3cef843623f1">
<img width="288" alt="Screenshot 2023-08-12 at 6 02 28 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/129279817/56604485-1efb-479c-ae1f-ff4087b36bea">

**Comment by sailro** [comment] 2023-08-12 17:10
> I was doing fine since last week, I am having this problem as you can see in the pictures, i guess something updated but idk what. If someone would tell me how to figure out i would be thankful.
> 
> <img alt="Screenshot 2023-08-12 at 6 01 57 PM" width="1386" src="https://user-images.githubusercontent.com/129279817/260238268-d95c99a4-3ed3-4465-9986-ce7a5585e937.png"> <img alt="Screenshot 2023-08-12 at 6 02 16 PM" width="294" src="https://user-images.githubusercontent.com/129279817/260238270-59465b73-b8ac-4bb4-9211-3cef843623f1.png"> <img alt="Screenshot 2023-08-12 at 6 02 28 PM" width="288" src="https://user-images.githubusercontent.com/129279817/260238271-56604485-1efb-479c-ae1f-ff4087b36bea.png">

I think the solution is here (section 2):
https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278

I guess you are not using the latest VS Editor package v2.0.20. Please update using Unity Package Manager.

**Comment by gingaramo** [comment] 2023-08-13 07:32
I had the same problem of not getting code navigation and completion working, I followed all the steps in comment [#329](https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278) plus a few dozen other SO and issue discussions too, spending a few hours trying everything from re-installing Unity VSCode, trying different extensions versions, etc.

Finally arrived to [a workaround](https://github.com/microsoft/vscode-dotnettools/issues/120#issuecomment-1640892593) that worked for my issue. 

I had the problem of infinite load, and of project not loading without helpful messages. Upon expanding the "Solution Explorer" tab I saw "A compatible .NET SDK was not found" and that ended up taking me to a few more issues discussed in the past month, with finally a workaround that worked.

![image](https://github.com/microsoft/vscode-dotnettools/assets/488509/9ea0766a-5d7f-481e-a2bc-009ce1fa02e4)

Hope that helps you.

**Comment by inancelal** [comment] 2023-08-14 10:35
> > I was doing fine since last week, I am having this problem as you can see in the pictures, i guess something updated but idk what. If someone would tell me how to figure out i would be thankful.
> > <img alt="Screenshot 2023-08-12 at 6 01 57 PM" width="1386" src="https://user-images.githubusercontent.com/129279817/260238268-d95c99a4-3ed3-4465-9986-ce7a5585e937.png"> <img alt="Screenshot 2023-08-12 at 6 02 16 PM" width="294" src="https://user-images.githubusercontent.com/129279817/260238270-59465b73-b8ac-4bb4-9211-3cef843623f1.png"> <img alt="Screenshot 2023-08-12 at 6 02 28 PM" width="288" src="https://user-images.githubusercontent.com/129279817/260238271-56604485-1efb-479c-ae1f-ff4087b36bea.png">
> 
> I think the solution is here (section 2): [#329 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278)
> 
> I guess you are not using the latest VS Editor package v2.0.20. Please update using Unity Package Manager.

I did everything on section 2 except version of editor, I updated Editor package v2.0.20 but it did not fix anything and now I am having this error:
<img width="1137" alt="Screenshot 2023-08-14 at 1 30 36 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/129279817/da48b0fc-a342-444d-a17d-5cca4da31056">
<img width="804" alt="Screenshot 2023-08-14 at 1 30 13 PM" src="https://github.com/microsoft/vscode-dotnettools/assets/129279817/c7677cac-5a8f-47fa-9b99-05fe6c785287">

**Comment by z79422957** [comment] 2023-08-15 07:21
Encountered the same problem as CallMeTheWolf

**Comment by sailro** [comment] 2023-08-15 09:16
> > > I was doing fine since last week, I am having this problem as you can see in the pictures, i guess something updated but idk what. If someone would tell me how to figure out i would be thankful.
> > > <img alt="Screenshot 2023-08-12 at 6 01 57 PM" width="1386" src="https://user-images.githubusercontent.com/129279817/260238268-d95c99a4-3ed3-4465-9986-ce7a5585e937.png"> <img alt="Screenshot 2023-08-12 at 6 02 16 PM" width="294" src="https://user-images.githubusercontent.com/129279817/260238270-59465b73-b8ac-4bb4-9211-3cef843623f1.png"> <img alt="Screenshot 2023-08-12 at 6 02 28 PM" width="288" src="https://user-images.githubusercontent.com/129279817/260238271-56604485-1efb-479c-ae1f-ff4087b36bea.png">
> > 
> > 
> > I think the solution is here (section 2): [#329 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278)
> > I guess you are not using the latest VS Editor package v2.0.20. Please update using Unity Package Manager.
> 
> I did everything on section 2 except version of editor, I updated Editor package v2.0.20 but it did not fix anything and now I am having this error: <img alt="Screenshot 2023-08-14 at 1 30 36 PM" width="1137" src="https://user-images.githubusercontent.com/129279817/260425083-da48b0fc-a342-444d-a17d-5cca4da31056.png"> <img alt="Screenshot 2023-08-14 at 1 30 13 PM" width="804" src="https://user-images.githubusercontent.com/129279817/260425098-c7677cac-5a8f-47fa-9b99-05fe6c785287.png">

It seems there was an issue on the Unity side when fetching the package.

Could you try to close Unity, then delete your `Library/PackageCache` folder ? this will invalidate and rebuild the package cache when re-opening Unity.

If you are still hitting the issue after this, we recommend to remove the meta-package `Engineering` and re-add necessary package as standalone ones.

**Comment by inancelal** [comment] 2023-08-15 12:47
> > > > I was doing fine since last week, I am having this problem as you can see in the pictures, i guess something updated but idk what. If someone would tell me how to figure out i would be thankful.
> > > > <img alt="Screenshot 2023-08-12 at 6 01 57 PM" width="1386" src="https://user-images.githubusercontent.com/129279817/260238268-d95c99a4-3ed3-4465-9986-ce7a5585e937.png"> <img alt="Screenshot 2023-08-12 at 6 02 16 PM" width="294" src="https://user-images.githubusercontent.com/129279817/260238270-59465b73-b8ac-4bb4-9211-3cef843623f1.png"> <img alt="Screenshot 2023-08-12 at 6 02 28 PM" width="288" src="https://user-images.githubusercontent.com/129279817/260238271-56604485-1efb-479c-ae1f-ff4087b36bea.png">
> > > 
> > > 
> > > I think the solution is here (section 2): [#329 (comment)](https://github.com/microsoft/vscode-dotnettools/issues/329#issuecomment-1675794278)
> > > I guess you are not using the latest VS Editor package v2.0.20. Please update using Unity Package Manager.
> > 
> > 
> > I did everything on section 2 except version of editor, I updated Editor package v2.0.20 but it did not fix anything and now I am having this error: <img alt="Screenshot 2023-08-14 at 1 30 36 PM" width="1137" src="https://user-images.githubusercontent.com/129279817/260425083-da48b0fc-a342-444d-a17d-5cca4da31056.png"> <img alt="Screenshot 2023-08-14 at 1 30 13 PM" width="804" src="https://user-images.githubusercontent.com/129279817/260425098-c7677cac-5a8f-47fa-9b99-05fe6c785287.png">
> 
> It seems there was an issue on the Unity side when fetching the package.
> 
> Could you try to close Unity, then delete your `Library/PackageCache` folder ? this will invalidate and rebuild the package cache when re-opening Unity.
> 
> If you are still hitting the issue after this, we recommend to remove the meta-package `Engineering` and re-add necessary package as standalone ones.

Even if I delete one project's `Library/PackageCache` folder, problem is happening in all other unity projects even in new projects. I dont know what you mean by saying "remove the meta-package Engineering and re-add necessary package as standalone ones" could you explain with more details pls ?

**Comment by Wollbobaggins** [comment] 2023-08-15 22:00
Maddening... ugh sigh. VSCode was working fine up until today when I installed the Microsoft Unity extension. I have an infinite server load problem and so far nothing has worked from above.

**Comment by z79422957** [comment] 2023-08-16 04:57
I tested, Temporary resolution of no code prompts and intelligent perception issues:

I have annotated all of the user's settings. json.

2. Close vscode, open the script from the Unity editor, and wait for files such as SLN to load

3. Switch to other scripts to refresh code prompts and intelligent perception normally (each time you open vscode for the first time, you need to operate it once)

4. I have uncommented all of the user's settings. json.

5. Complete.

**Comment by boxedworks** [comment] 2023-08-21 02:59
For me, my VSCode had the wrong solution selected after installing the new Microsoft Unity extension. I think this is due to my project including code from other projects in it.

So running from the command palette:
.NET Open Solution

Then I had 3 selections to choose from for the solution. So I chose the one for my project (the shortest one) and after it loaded for a bit, it is now working.

**Comment by jbevain** [comment] 2023-08-22 20:55
@Wollbobaggins thanks for taking the time to report how you fixed your issue. Today we're simply generating a new `.vscode/settings.json` if you don't have one already, and if you have one we're not touching it.

Now we're thinking about adding a step that looks at an existing `.vscode/settings.json` to remove the `.sln` file exclusion if there's one.

**Comment by alanbork** [comment] 2023-09-08 20:36
I'm not sure what to expect here - there's tons of junk in the autocomplete, such as all the floats that you can write with 3 digits.  does this count as "working"? Also, all the variables, classes, etc, are listed as type "abc" which isn't super helpful.

**Comment by sailro** [comment] 2023-09-14 14:29
We added a bunch of setting fixes in the VS Editor Package `2.0.21`, this should help for those still hitting issues here. Please bump your package version in Unity package manager.

**Comment by alanbork** [comment] 2023-09-14 15:14
> We added a bunch of setting fixes in the VS Editor Package `2.0.21`, this should help for those still hitting issues here. Please bump your package version in Unity package manager.

What counts as working? My first couple pages of intellisense suggestions are floating point numbers like .015f, pretty darn useless.

**Comment by jbevain** [comment] 2023-09-14 17:56
Hi,

At this point we believe the `C#` and `C# Dev Kit` have pushed a fix for the loading issue, so we're going to close this issue. Please make sure both extensions are up to date and you've followed the README of the `Unity extension`:

* In Unity, you need to upgrade the `Visual Studio Editor` package to 2.0.20 or above (the latest is 2.0.21)
* Select Visual Studio Code as the External Editor.
* Regenerate Project Files

Because this issue evolved with multiple different issues, if you hit more loading issues please open a new one.

Thank you!

**Comment by jbevain** [comment] 2023-09-14 17:57
@alanbork please open a new issue for this, thank you!

**Closed by jbevain** 2023-09-14 17:56 UTC
Labels: bug, area-unity
