### ISSUE TITLE
[BUG]  I can't add files from solution explorer

### ISSUE THREAD

**Issue by john-laststone** [microsoft/vscode-dotnettools#1000] opened 2024-03-17 09:18 UTC
### Describe the Issue

I can't add files from solution explorer from a simple project. Gives me this error:

`Error running command csdevkit.addNewFile: Failed with ExitCode(6) Details No templates found matching: 'class'. To list installed templates, run: dotnet new --list To search for the templates on NuGet.org, run: dotnet new class --search . This is likely caused by the extension that contributes csdevkit.addNewFile.`

I tried different version of c# extension and dev kit but the result  is the same. I also tried to reinstall vscode and .NET SDK

### Steps To Reproduce

dotnet new console -o TestProject
code TestProject
add new file from solution explorer

### Environment Information

- OS: Pop os 22.04
- .NET 6
- VSCode 1.87.2
- C# extension 2.32.2
- C# dev kit 1.4.29

**Comment by kvenkatrajan** [comment] 2024-03-22 20:16
Thanks for your feedback. The class template was added in SDK version : 7.0.200 and hence is unavailable to be used in earlier version. Please upgrade to [.NET8 sdk version](https://dotnet.microsoft.com/en-us/download) or 7.0.2xx or higher

**Comment by tmeschter** [comment] 2024-03-28 17:51
Closing as this is by design. C# Dev Kit only support projects using the 7.0.2xx or higher SDK.

**Closed by tmeschter** 2024-03-28 17:51 UTC
Labels: bug, area-templates, high-priority
