### ISSUE TITLE
Change the configuration for debug

### ISSUE THREAD

**Issue by danardelean** [microsoft/vscode-dotnettools#735] opened 2023-11-18 16:43 UTC
### Describe the feature you'd like

Just wanted to know if it is possible to set the active configuration when starting a new instance of Debug.

 In my project I don't have simple Debug configuration but multiple ones Debug Dev, Debug Stage, Debug Prod (especially because this is a mobile project that uses multiple AndroidManifest, Info.plist, ...)

Is it something that is already present in Dev Kit?

**Comment by WardenGnaw** [comment] 2023-11-27 16:57
I believe this is a duplicate of https://github.com/microsoft/vscode-dotnettools/issues/72. 

Feel free to re-open if you believe the request is different.

**Closed by WardenGnaw** 2023-11-27 16:57 UTC
Labels: enhancement, area-debugging

**Comment by danardelean** [comment] 2023-12-18 11:45
This is not about setting the Startup Project but rather setting the Debug configuration. 

In the image switching between Dev Stage and Prod on the image below.

To be even clearer I need to be able to set the -c parameter in the Dotnet build command line

dotnet build  -f net8.0-android  -c 'Debug Stage'

![image](https://github.com/microsoft/vscode-dotnettools/assets/1352599/35344382-d744-4bf1-804d-3dcfd64e47b0)
