### ISSUE TITLE
.vscode folder not found

### ISSUE THREAD

**Issue by JACOBnotpro** [microsoft/vscode-dotnettools#629] opened 2023-10-17 14:11 UTC
Type: <b>Bug</b>

When I create new C# project, I want to enter the .vscode folder to moldify setting.json but i don't see it any more.
Just similar to this video but the folder is gone
https://youtu.be/2L4apvBifaU

Extension version: 0.6.3
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5625U with Radeon Graphics          (12 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.36GB (0.39GB free)|
|Process Argv|--crash-reporter-id 0dea81d6-7452-4395-b4e6-2d5b53db25ce|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30856253
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
282f8724:30602487
f6dab269:30613381
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30859502
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
pythonmpsinfo:30842941
dsvsc015:30845448
pythonregdiag:30859691
h48ei257:30862707

```

</details>

**Comment by timheuer** [comment] 2023-10-17 16:41
@JACOBnotpro the `.vscode` folder gets created when you do something within VS Code that creates it, such as adding launch/task json files or modifying user-settings in VSCode.  So if you go to settings and modify some settings for your workspace, the settings.json file gets created in `.vscode` and is visible in your workspace.  One thing to note is that the `.vscode` folder is not a part of your solution typically, so is accessible via the workspace view (all files) and not the solution view...such as this:

![2023-10-17_09-40-31](https://github.com/microsoft/vscode-dotnettools/assets/4821/0cf7afe3-68bc-4b7d-9e4e-3fde313f4258)

Hopefully this helps.  I'm inclined to close this as not a C# Dev Kit bug really, but want to make sure you are seeing the normal VSCode flow as expected in my example.

**Comment by webreidi** [comment] 2023-10-17 17:33
Also to add to what Tim said, the .vscode folder, if exists, is hidden from the Solution Explorer view, but you can access it from the file explorer view as shown in Tim's screenshot.

**Comment by timheuer** [comment] 2023-10-20 15:24
@JACOBnotpro I'm going to close this as not a bug as the .vscode folders are working as designed showing in the workspace view.

**Closed by timheuer** 2023-10-20 15:24 UTC
Labels: wontfix
