### ISSUE TITLE
unit tests not discovered

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode-dotnettools#385] opened 2023-08-13 06:23 UTC
Type: <b>Bug</b>

1.  create a Class Library project, and add to solution
2.  create an xUnit project, add to solution
3.  add ref to Class Library project
4.  configuration tasks.json to build the project
5.  build the project.  notice the Testing view doesn't discover tests

6.  run `dotnet test`, tests run successfully
7.  open Visual Visual Studio, run tests, tests run successfully

Extension version: 0.3.21
VS Code version: Code 1.79.2 (695af097c7bd098fbf017ce3ac85e09bbc5dda06, 2023-06-14T08:57:04.379Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.08GB free)|
|Process Argv|--folder-uri file:///c%3A/source/burtonrodman/ServiceConstructorGenerator --crash-reporter-id 153d32f1-00c6-4725-ae16-14ebd9132050|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30803844
282f8724:30602487
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
a2ce3375:30757347
pythonfmttext:30731395
pythoncmvfstrcf:30756944
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
gsofa:30804715
pythonnosmt12:30797651
pythonidxptcf:30805731
pythonnoceb:30805159
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30810526

```

</details>

**Comment by burtonrodman** [comment] 2023-08-13 06:24
behaves the same in Insiders and Stable channels; C# Dev Kit preview and release.

**Comment by burtonrodman** [comment] 2023-08-13 06:27
https://github.com/burtonrodman/vscode_unittest_classlib

**Comment by burtonrodman** [comment] 2023-08-13 06:29
https://github.com/burtonrodman/ServiceConstructorGenerator

**Comment by timheuer** [comment] 2023-08-16 21:36
Working for me :-(
![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/2181a64c-289d-4914-90a7-24ad8bc771a6)

**Comment by burtonrodman** [comment] 2023-08-16 21:51
i’ll try it again.  super frustrating when this stuff only works half the time (literally a coin toss if tests or intellisense is going to work at any given time.  probably 25% chance if code fixes are going to work.  i’m about done with vscode.  but i’m hopeful that C# Dev Kit will fix these issues.  thanks for all your hard work!

**Comment by burtonrodman** [comment] 2023-08-16 21:59
still not working after Reload Window, Rebuild, Clean, reboot, etc...

I have Windows 11 23H2 22631.2191,  Visual Studio Enterprise 2022 Preview 17.8.0 Preview 1.

dotnet --list-sdks
5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]
6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
6.0.300 [C:\Program Files\dotnet\sdk]
6.0.316 [C:\Program Files\dotnet\sdk]
6.0.400-preview.22301.10 [C:\Program Files\dotnet\sdk]
6.0.413 [C:\Program Files\dotnet\sdk]
8.0.100-preview.6.23330.14 [C:\Program Files\dotnet\sdk]
8.0.100-preview.7.23376.3 [C:\Program Files\dotnet\sdk]

**Comment by timheuer** [comment] 2023-08-17 04:05
@burtonrodman Stay with us!!! :-) -- seriously thanks for reporting these things.  Okay, based on the SDKs you have installed I _think_ you are experiencing #318 -- can you take the C# Dev Kit `v0.4.5` prerelease update and set the setting to enable existing SDK (should get a popup) and let's see if it is related.  .NET 8 Preview 7 introduced a behavior change we haven't fully reacted to yet, so we have a little hot fix to change SDK setting.

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/4994fad5-2c06-4117-960d-58ff39cd389f)

![image](https://github.com/microsoft/vscode-dotnettools/assets/4821/be288d2b-5dbc-4909-9c59-daa8e66cf0fe)

**Comment by burtonrodman** [comment] 2023-08-17 15:58
That fixed it.

I'll pay more attention to my active runtime and SDK -- across the 3 machines I regularly use.

Is there a doc or rule of thumb that you can share to ensure a working combination of vscode, extensions, SDK and runtime?

**Comment by timheuer** [comment] 2023-08-17 17:27
> That fixed it.
> 
> I'll pay more attention to my active runtime and SDK -- across the 3 machines I regularly use.
> 
> Is there a doc or rule of thumb that you can share to ensure a working combination of vscode, extensions, SDK and runtime?

It's definitely not your fault, this is an unexpected break for us that we are navigating how we build everything together.  We're trying to get better at keeping changelog.md up to date with more info...this one was more reactionary.

I'm going to close this as dupe of #318 for now.

**Closed by timheuer** 2023-08-17 17:27 UTC
Labels: area-test
