### ISSUE TITLE
[BUG] Quick Fix fail when project have Roslyn Analyzer NuGet reference

### ISSUE THREAD

**Issue by viniciusjarina** [microsoft/vscode-dotnettools#1290] opened 2024-07-17 21:53 UTC
### Describe the Issue

Quick Fix fail when clicking in the 💡 and trying to apply the fix and the project have reference for Roslyn Analyzer (`Microsoft.CodeAnalysis.CSharp.CodeStyle`)

Roslyn Analyzers + `.editorconfig` are great to catch style errors at build time.

But C# DevKit is failing when trying to apply Quick Fixes.

https://github.com/user-attachments/assets/3b846a1e-1735-4a0f-b175-aa78c788fdf2

FYI: It works fine on VS (Win), Rider (Win/Mac), VS for Mac.

### Steps To Reproduce

Using VSCode + C# DevKit
* Create a new project `dotnet new console --use-program-main`
* Add NuGet reference `Microsoft.CodeAnalysis.CSharp.CodeStyle`
* Create a `enum` with a few values
```csharp
enum MyEnum
    {
        Value0,
        Value1,
        Value2
    }

    static void Main(string[] args)
    {
        MyEnum value = MyEnum.Value0;

        switch (value)
        {
            case MyEnum.Value0:
                break;
        }
        Console.WriteLine("Hello, World!");
    }
```

* Try to use the light bulb to `Add missing cases`
* See VSCode extension failing

Output:

```
[Info  - 1:49:03 PM] [WorkspaceProjectFactoryService] Project /Users/viniciusjarina/projects/Test/Test.csproj loaded by C# Dev Kit
[Error - 1:50:48 PM] [LanguageServerHost] System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.MefHostExportProvider.Create(String languageName)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices..ctor(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.Create(HostLanguageServices hostLanguageServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.GetRequiredMappedCodeStyleLanguageServices(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.AddMissingBraces(Document document, SyntaxNode& root, TSwitchSyntax& switchNode)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchStatementCodeFixProvider`3.FixOneDiagnostic(Document document, SyntaxEditor editor, SemanticModel semanticModel, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, Boolean hasMissingCases, Boolean hasMissingDefaultCase, TSwitchSyntax switchNode, ISwitchOperation switchOperation)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixOneDiagnosticAsync(Document document, SyntaxEditor editor, Diagnostic diagnostic, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixWithEditorAsync(Document document, SyntaxEditor editor, ImmutableArray`1 diagnostics, Boolean addCases, Boolean addDefaultCase, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(Document document, Func`2 editAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 353
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 307
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(Solution originalSolution, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 244
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionResolveHandler.HandleRequestAsync(CodeAction codeAction, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs:line 93
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, IMethodHandler handler, CancellationToken cancellationToken)
System.TypeLoadException: Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
[Error - 1:50:48 PM] Request codeAction/resolve failed.
  Message: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
  Code: -32000 
[object Object]
[Error - 1:51:26 PM] [LanguageServerHost] System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.MefHostExportProvider.Create(String languageName)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices..ctor(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.Create(HostLanguageServices hostLanguageServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.GetRequiredMappedCodeStyleLanguageServices(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.AddMissingBraces(Document document, SyntaxNode& root, TSwitchSyntax& switchNode)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchStatementCodeFixProvider`3.FixOneDiagnostic(Document document, SyntaxEditor editor, SemanticModel semanticModel, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, Boolean hasMissingCases, Boolean hasMissingDefaultCase, TSwitchSyntax switchNode, ISwitchOperation switchOperation)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixOneDiagnosticAsync(Document document, SyntaxEditor editor, Diagnostic diagnostic, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixWithEditorAsync(Document document, SyntaxEditor editor, ImmutableArray`1 diagnostics, Boolean addCases, Boolean addDefaultCase, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(Document document, Func`2 editAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 353
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 307
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(Solution originalSolution, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 244
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionResolveHandler.HandleRequestAsync(CodeAction codeAction, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs:line 93
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, IMethodHandler handler, CancellationToken cancellationToken)
System.TypeLoadException: Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
[Error - 1:51:26 PM] Request codeAction/resolve failed.
  Message: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
  Code: -32000 
[object Object]
[Error - 2:36:51 PM] [LanguageServerHost] System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.MefHostExportProvider.Create(String languageName)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices..ctor(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.Create(HostLanguageServices hostLanguageServices)
   at System.Runtime.CompilerServices.ConditionalWeakTable`2.GetValueLocked(TKey key, CreateValueCallback createValueCallback)
   at Microsoft.CodeAnalysis.Host.CodeStyleHostLanguageServices.GetRequiredMappedCodeStyleLanguageServices(HostLanguageServices hostLanguageServices)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.AddMissingBraces(Document document, SyntaxNode& root, TSwitchSyntax& switchNode)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchStatementCodeFixProvider`3.FixOneDiagnostic(Document document, SyntaxEditor editor, SemanticModel semanticModel, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, Boolean hasMissingCases, Boolean hasMissingDefaultCase, TSwitchSyntax switchNode, ISwitchOperation switchOperation)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixOneDiagnosticAsync(Document document, SyntaxEditor editor, Diagnostic diagnostic, Boolean addCases, Boolean addDefaultCase, Boolean onlyOneDiagnostic, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.PopulateSwitch.AbstractPopulateSwitchCodeFixProvider`4.FixWithEditorAsync(Document document, SyntaxEditor editor, ImmutableArray`1 diagnostics, Boolean addCases, Boolean addDefaultCase, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeFixes.SyntaxEditorBasedCodeFixProvider.FixAllWithEditorAsync(Document document, Func`2 editAsync, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetChangedSolutionAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 353
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.ComputeOperationsAsync(IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 307
   at Microsoft.CodeAnalysis.CodeActions.CodeAction.GetOperationsCoreAsync(Solution originalSolution, IProgress`1 progress, CancellationToken cancellationToken) in /_/src/Workspaces/Core/Portable/CodeActions/CodeAction.cs:line 244
   at Microsoft.CodeAnalysis.LanguageServer.Handler.CodeActionResolveHandler.HandleRequestAsync(CodeAction codeAction, RequestContext context, CancellationToken cancellationToken) in /_/src/LanguageServer/Protocol/Handler/CodeActions/CodeActionResolveHandler.cs:line 93
   at Microsoft.CommonLanguageServerProtocol.Framework.QueueItem`3.StartRequestAsync(TRequestContext context, IMethodHandler handler, CancellationToken cancellationToken)
System.TypeLoadException: Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
System.TypeLoadException: Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
[Error - 2:36:51 PM] Request codeAction/resolve failed.
  Message: Unable to load one or more of the requested types.
Method 'get_PartialDefinitionPart' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationPropertySymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
Method 'get_AllowsRefLikeType' in type 'Microsoft.CodeAnalysis.CodeGeneration.CodeGenerationTypeParameterSymbol' from assembly 'Microsoft.CodeAnalysis.CodeStyle.Fixes, Version=4.10.10.27302, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
  Code: -32000 
```

It might be related to:
https://github.com/dotnet/roslynator/issues/1338
https://github.com/microsoft/vscode-dotnettools/issues/61
https://github.com/dotnet/roslyn/issues/68588

Although those issues are closed.

### Expected Behavior

It should work just like other IDEs:
e.g (VSMac):

https://github.com/user-attachments/assets/0294acbe-0358-4884-8266-30891c35e96f

### Environment Information

dotnet
```
dotnet --info
.NET SDK:
 Version:           8.0.303
 Commit:            29ab8e3268
 Workload version:  8.0.300-manifests.7ccdde63
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  14.5
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/8.0.303/
 ```
VS Code 
```
Version: 1.91.1
Commit: f1e16e1e6214d7c44d078b1f0607b2388f29d729
Date: 2024-07-09T22:07:46.768Z
Electron: 29.4.0
ElectronBuildId: 9728852
Chromium: 122.0.6261.156
Node.js: 20.9.0
V8: 12.2.281.27-electron.0
OS: Darwin arm64 23.5.0
```

VS Code extensions
```
C# Dev Kit
v1.8.14
C#
v2.34.12
```

**Comment by viniciusjarina** [comment] 2024-07-26 17:45
@timheuer any update on this? How can we tell the progress of a task or if it was triaged already?

**Comment by AbhitejJohn** [comment] 2024-07-30 21:50
@viniciusjarina : Apologies for the delay. Tagging @dibarbet and @arkalyanms for thoughts on this.

**Comment by dibarbet** [comment] 2024-08-01 01:46
Duplicate of https://github.com/dotnet/roslyn/issues/72811

Workaround is to turn off `EnforceCodeStyleInBuild` for the project.

**Closed by dibarbet** 2024-08-01 01:46 UTC
Labels: bug, area-roslyn

**Comment by timheuer** [comment] 2024-08-02 17:08
I actually just tried this and it worked fine? (and I have no setting in the project)

VS Code Extensions
  ms-dotnettools.csdevkit: 1.9.53
  ms-dotnettools.csharp: 2.41.26

![Image](https://github.com/user-attachments/assets/a70efe1d-33f6-4453-abc6-3f9dc702404a)

**Comment by viniciusjarina** [comment] 2024-08-02 18:04
@timheuer do you have `Microsoft.CodeAnalysis.CSharp.CodeStyle` NuGet reference in your project ?

**Comment by viniciusjarina** [comment] 2024-08-02 18:07
I know I could add `dotnet format --verify-no-changes` to my CI. I already have that. But the Nuget is added so it could catch those errors in build time before you push changes. All other IDEs work fine with this.

**Comment by timheuer** [comment] 2024-08-02 18:11
> do you have `Microsoft.CodeAnalysis.CSharp.CodeStyle` NuGet reference in your project ?

Yes, I followed your repro steps exactly @viniciusjarina. Note I'm on all pre-release extensions.

**Comment by viniciusjarina** [comment] 2024-08-02 18:12
@timheuer that's great news! thank you for testing it. I will wait them to go stable.

**Comment by scottkuhl** [comment] 2024-08-03 05:18
I just messed with this for the last half an hour because I was confused on what combination of settings broke this.  Here is what I have found:

**You have to turn off `<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>` if you are using any Rosyln analyzers at all.  It does not matter which ones, Roslynator for example will break.**

It does not matter if you are on stable or pre-release of the C# and C# Dev Kit.

This is the still open bug to follow.  No ETA and the team says is hard to fix: https://github.com/dotnet/roslyn/issues/72811

**Comment by viniciusjarina** [comment] 2024-10-08 23:56
Just update to .NET 9 rc2 and latest version of VSCode + C# DevKit and it seem to be working now. 
Congratulations folks.
