### ISSUE TITLE
Sign in is not possible!?

### ISSUE THREAD

**Issue by tomschrot** [microsoft/vscode-dotnettools#943] opened 2024-02-23 08:43 UTC
Type: <b>Bug</b>

VSC keeps demanding a Sign in to my MS account, but Im signed in already?!

I use VSC in Germany, having a German MS account.

The webpage shows:

Anmelden
Eine Anmeldung mit einem persönlichen Konto ist hier nicht möglich. Verwenden Sie stattdessen Ihr Geschäfts-, Schul- oder Unikonto.

I use my personal MS account.

![grafik](https://github.com/microsoft/vscode-dotnettools/assets/1196470/2586bbea-f5d8-433a-a00e-f51d04216890)

Extension version: 1.4.6
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:40:56.878Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 7840HS w/ Radeon 780M Graphics      (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|27.72GB (18.52GB free)|
|Process Argv|--crash-reporter-id e66a5f98-ef34-4476-a532-bd692aad3056|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:30899288
vscaac:30438847
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
pydisww2:30959801
edj9j583:30969295
a89i1917:30961429
7j2b6412:30969109
ccp1r6:30958156

```

</details>

**Comment by glen-84** [comment] 2024-02-23 09:06
Duplicate of #942.

**Comment by timheuer** [comment] 2024-02-23 16:33
FYI we're actually tracking this as #697 /cc @AndreyTretyak

**Closed by timheuer** 2024-02-23 16:33 UTC
