### ISSUE TITLE
Existing project is broken after the new update.

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode-dotnettools#394] opened 2023-08-15 04:07 UTC
### Describe the Issue

Please look at the below image. Program class is not showing in the solution explorer and no language feature is working.

<img width="1507" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/14342773/4a2f3b56-f72a-49b2-8d40-010a69ce3574">

### Environment Information

OS: MacOS
VSCode Version: 1.81.1 (Universal)

**Comment by tmeschter** [comment] 2023-08-15 17:59
@TanvirArjel Can you provide the full text of the "Expected 1 exports(s) with contract name..." message under ConsoleApp1 in the Solution Explorer? That will help us get the bug in front of the right team.

**Comment by TanvirArjel** [comment] 2023-08-16 02:16
@tmeschter Here it is. Cannot copy, so provided a screenshot:

<img width="1152" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/14342773/e990cf5b-6b7e-4669-afdc-b63b3899cd83">

**Comment by timheuer** [comment] 2023-08-16 21:31
Dupe of #318 -- @TanvirArjel can you update to `v0.4.5`  in pre-release and set the new setting to see if you are unblocked?

**Comment by TanvirArjel** [comment] 2023-08-17 02:02
@timheuer It worked. Thank you for the fix.

**Comment by timheuer** [comment] 2023-08-17 04:09
> @timheuer It worked. Thank you for the fix.

Thanks for confirming.  @webreidi should we track #318 as the root issue here and update iteration plan and dupe others?

**Closed** 2023-08-18 15:36 UTC
Labels: bug, needs-more-info, area-project-cps, mac
