### ISSUE TITLE
[BUG] Console.WriteLine() doesn't print anything

### ISSUE THREAD

**Issue by rogersm-uwosh** [microsoft/vscode-dotnettools#775] opened 2023-11-30 23:43 UTC
### Describe the Issue

In .NET MAUI, I have a Console.WriteLine() statement, but it doesn't print anything to the Debug Console. I get a boatload of messages that I don't care about -- assemblies being loaded -- but the few messages that I do care about do not appear, even though with the debugger I can step over them, so they are being hit.

Note that I created a new .NET console application in VSC and it does print.

### Steps To Reproduce

1. Clear the Debug console
2. Execute this line:         Console.WriteLine("hello from here");
3. Look at the Debug console, and observe that it is still empty.

### Expected Behavior

I expect to see "hello from here" in the Debug Console

### Environment Information

macOS Sonoma
VSC 1.84.2
.NET MAUI 0.5.50
C# Dev Kit 1.0.14

> VS bug [#1925507](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1925507)

**Comment by mauroa** [comment] 2024-03-06 20:26
Closing as duplicate of this: https://github.com/microsoft/vscode-dotnettools/issues/685

**Closed by mauroa** 2024-03-06 20:26 UTC
Labels: bug, triaged, area-maui, vs-sync, vs-syncd
