### ISSUE TITLE
[SUGGESTION] Reveal Active File in Solution Explorer

### ISSUE THREAD

**Issue by LeMamin** [microsoft/vscode-dotnettools#288] opened 2023-07-26 07:46 UTC
### Describe the feature you'd like

Hello,

It would be interesting to Reveal Active File in the Solution Explorer as in the Explorer View.

**Comment by smitpatel** [comment] 2023-07-26 14:33
Duplicate of #180

**Closed by smitpatel** 2023-07-26 14:33 UTC
Labels: enhancement, area-solution
