### ISSUE TITLE
C# Dev Kit keeps creating $HOME/Documents/.mono hidden directory with telemetry info in Linux

### ISSUE THREAD

**Issue by RandomBuffer** [microsoft/vscode-dotnettools#930] opened 2024-02-19 14:11 UTC
Type: <b>Bug</b>

**Actual** 
 **C# Dev Kit** keeps creating a hidden **$HOME/Documents/.mono** directory (along with subdirectories and files) which includes telemetry info as tested below.

1. Install **C# Dev Kit**.
2. Click **Create .NET Project**.
3. Create any project from the dropdown.
4. Browse to **$HOME/Documents/.mono** and notice the directory is created with telemetry info.
5. Browse to **$HOME/.mono** and notice a similar directory is also created with telemetry info.
6. Delete the **.mono** directories and repeat the above from Step 2 onwards consistently gives the same result.

**Expected**
**C# Dev Kit** should create the **.mono** directories in another more relevant location according to XDG specs https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html.

Extension version: 1.4.2
VS Code version: Code 1.86.2 (903b1e9d8990623e3d7da1df3d33db3e42d80eda, 2024-02-13T19:41:37.860Z)
OS version: Linux x64 6.6.13-amd64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics (16 x 3881)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|14.46GB (8.91GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6d7321b4-aa58-4739-a430-82330e5093c6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscorecescf:30445987
vscod805:30301674
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
c4g48928:30535728
azure-dev_surveyone:30548225
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
accentitlementst:30887150
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
bf62j303:30959262
3ef8e399:30967273
e3gdj431:30958358
ccp1r3:30958155

```

</details>

**Comment by well-benjamin** [comment] 2024-03-14 04:27
I just today started getting this issue after updating to version, `1.4.29` of the C# Dev Kit. I'm getting a `.mono` dir at the root of my repository. If I delete it, it will just come back (git ignore time hehe).

![image](https://github.com/microsoft/vscode-dotnettools/assets/156377349/33805f8a-e8bb-46c1-9deb-bbd80fb8dc6f)

I'm editing this repo from inside a [dev container](https://code.visualstudio.com/docs/devcontainers/containers) running on the base image [mcr.microsoft.com/vscode/devcontainers/dotnet:dev-8.0-jammy](https://hub.docker.com/_/microsoft-vscode-devcontainers)

`values.xml` contains:
```
<values>
  <value name="StillAlive" type="qword">133548637119787155</value>
</values>
```

Hope this helps 😄

**Comment by samymsa** [comment] 2024-03-14 09:17
Same as @well-benjamin, started getting this issue after updating the C# Dev Kit extension. I'm editing inside WSL2. I'll just use `.gitignore` while this gets fixed.

**Comment by sliekens** [comment] 2024-03-21 09:57
Yep, same here, would rather they put this in a temp folder somewhere. Is there any way to disable telemetry?

**Comment by RandomBuffer** [comment] 2024-03-21 10:47
On that same page there is some info on [extensions-and-telemetry](https://code.visualstudio.com/docs/getstarted/telemetry#_extensions-and-telemetry) and according to  https://github.com/microsoft/vscode-dotnettools/issues/985#issuecomment-2003911324 those settings should work

**Comment by jonathanjyi** [comment] 2024-04-04 22:47
duplicate of #1008

**Closed by jonathanjyi** 2024-04-04 22:47 UTC
Labels: bug, area-telemetry

**Comment by FluentProgrammer** [comment] 2025-08-14 13:41
Confirming this issue has been fixed possibly due to the fix in https://github.com/microsoft/vscode-dotnettools/issues/1008#issuecomment-2152918834.

Tested with C# Dev Kit 1.41.11
