### ISSUE TITLE
[BUG] Unable to install. Taking forever to install.

### ISSUE THREAD

**Issue by dev-aliqasim** [microsoft/vscode-dotnettools#988] opened 2024-03-13 14:24 UTC
### Describe the Issue

At first, I was unable to install C# Dev Kit. It was taking forever to install C# Dev Kit. However, I tried to restart my windows 11 machine several times. But the same problem persisted. Finally, vs code suggested to manually install C# Dev Kit. Following the link to manually install the C# Dev Kit, following error occurred in the browser. Plz fix it. I am having a bad day because of these minor issues. 

{"$id":"1","innerException":null,"message":"Request was blocked due to exceeding usage of resource 'Count' in namespace 'AnonymousId'. For more information on why your request was blocked, see the topic \"Rate limits\" on the Microsoft Web site (https://go.microsoft.com/fwlink/?LinkId=823950).","typeName":"Microsoft.TeamFoundation.Framework.Server.RequestBlockedException, Microsoft.TeamFoundation.Framework.Server","typeKey":"RequestBlockedException","errorCode":0,"eventId":3000}

**Comment by arkalyanms** [comment] 2024-03-18 16:37
Its hitting vscode marketplace throttling. Nothing to do with the extension itself. Needs to move to vscode repo.

**Comment by webreidi** [comment] 2024-03-20 15:33
Duplicate of https://github.com/microsoft/vsmarketplace/issues/869. @dev-aliqasim please go up-vote that issue.

**Closed by webreidi** 2024-03-20 15:33 UTC
Labels: bug, area-vscode
