### ISSUE TITLE
This is a review.  WHY ARE WE MAKING VSCODE INTO VISUAL STUDIO!

### ISSUE THREAD

**Issue by escofield** [microsoft/vscode-dotnettools#659] opened 2023-10-27 15:33 UTC
### Describe the feature you'd like

please do not make vscode more like visual studio.  This is the reason I use vs code.  SPECIFICALLY BECAUSE IT IS NOT VISUAL STUDIO.

I opened up a project directory today,  and magically a solution file was created for me on my behalf.  DON"T F*CKING DO SHIT FOR ME.  K, THANKS!

If I wanted a solution file, I would have created one!

**Comment by timheuer** [comment] 2023-10-27 21:48
Hi @escofield thanks for submitting here. First, while obfuscating the word, I just want to remind contributors here even to issues of our [Code of Conduct](https://github.com/microsoft/vscode-dotnettools/blob/main/CODE_OF_CONDUCT.md).

We're looking to refine the issue you are pointing out (solution file created in-repo) and likely do it in memory so it doesn't affect repo projects.  We leverage this to make use of understanding the workspaces full code and the relations to other aspects of our extension. But understandably, adding assets unexpectedly is not ideal.

That said, if you don't make use of things like the solution view or want to benefit from other areas and just want to focus on code editing only, the C# core extension might be a better option.  The Dev Kit delivers on some new functionality and shares some concepts with other dev tools, but is optional of course. 

Since this is about the SLN file I'm going to close this specifically though as it is a dupe of the discussion in #31

**Closed by timheuer** 2023-10-27 21:48 UTC
Labels: enhancement, area-solution
