### ISSUE TITLE
[BUG] .NET MAUI extension does not respect target device if configuration is different than Debug

### ISSUE THREAD

**Issue by luwed** [microsoft/vscode-dotnettools#732] opened 2023-11-17 10:28 UTC
### Describe the Issue

I noticed that app is not deployed to device/emulator if custom launch configuration is selected and more that one emulator/device is running. There is error in terminal:
  
```
[...]
[73/73] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.so
  [73/73] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.so
  [73/73] System.Private.CoreLib.dll -> System.Private.CoreLib.dll.so
[BT : 1.8.1] error : More than one device connected, please provide --device-id. [/Users/<username>/Projects/TestMaui/TestMaui.csproj::TargetFramework=net7.0-android]

Build FAILED.

[BT : 1.8.1] error : More than one device connected, please provide --device-id. [/Users/<username>/Projects/TestMaui/TestMaui.csproj::TargetFramework=net7.0-android]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:03:00.18

 *  The terminal process "/bin/bash '-l', '-c', 'dotnet build -t:Run -p:Configuration=Release -f net7.0-android -p:AndroidSdkDirectory='/private/var/<username>/Library/Android/sdk' -p:JavaSdkDirectory='/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home' /Users/<username>/Projects/TestMaui/TestMaui.csproj'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

- The issue is similar to https://github.com/microsoft/vscode-dotnettools/issues/250.
- For Debug configuration following command is run in terminal:
` *  Executing task: dotnet build -t:Run -p:Configuration=Debug -f net7.0-android -p:AdbTarget=-s%20__SERIAL__ -p:AndroidAttachDebugger=true -p:AndroidSdbTargetPort=52096 -p:AndroidSdbHostPort=52096 -p:AndroidSdkDirectory='/private/var/<username>/Library/Android/sdk' -p:JavaSdkDirectory='/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home' /Users/<username>/Projects/TestMaui/TestMaui.csproj `
- For Release configuration following command is run in terminal:
`  *  Executing task: dotnet build -t:Run -p:Configuration=Release -f net7.0-android -p:AndroidSdkDirectory='/private/var/<username>/Library/Android/sdk' -p:JavaSdkDirectory='/Library/Java/JavaVirtualMachines/microsoft-11.jdk/Contents/Home' /Users/<username>/Projects/TestMaui/TestMaui.csproj `

### Steps To Reproduce

**Prerequisites**
* Launch two emulators

1. Create folder TestMaui
2. Open folder in Terminal
3. Create new .NET MAUI project running command: 'dotnet new maui'
4. Open project in Visual Studio Code. Below you can see csproj:
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net7.0-tizen</TargetFrameworks> -->
		<OutputType>Exe</OutputType>
		<RootNamespace>TestMaui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		<!-- Display name -->
		<ApplicationTitle>TestMaui</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.testmaui</ApplicationId>
		<ApplicationIdGuid>15294e6f-04e4-41d7-aa21-522ed35a564b</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
	</ItemGroup>

</Project>
```
5. Create launch.json:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "[Debug] Test Maui",
            "type": "maui",
            "request": "launch",
            "preLaunchTask": "maui: Build"
        },
        {
            "name": "[Release] Test Maui",
            "type": "maui",
            "request": "launch",
            "configuration": "Release",
            "preLaunchTask": "maui: Build"
        }        
    ]
}
```
6. Select target device 
7. Open Debug view
8. Select '[Release] Test Maui' from Dropdown

### Expected Behavior

App is deployed to proper device/emulator.

### Environment Information

- OS: macOS Ventura 13.5.1
- VS Code version: 1.84.2
- Extensions: .NET MAUI v0.6.19, C# Dev Kit v1.0.14, C# v2.10.28

> VS bug [#1921025](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1921025)

**Comment by mauroa** [comment] 2023-11-22 18:36
This issue is currently being investigated. Our team will get back to you if either more information is needed, a workaround is available, or the issue is resolved.

**Comment by luwed** [comment] 2023-11-23 09:08
Hi @mauroa, thanks.

**Comment by mauroa** [comment] 2024-03-19 16:54
There's a fix available for this issue that will be published in the next VS Code MAUI pre-release version. We'll proceed to close this issue once that version is available to install.

**Closed** 2024-04-25 16:27 UTC
Labels: bug, triaged, area-maui, area-project-cps, vs-sync, mac, vs-syncd, fixed
