### ISSUE TITLE
[BUG] Find all references shows incorrect count.

### ISSUE THREAD

**Issue by mjrist** [microsoft/vscode-dotnettools#1322] opened 2024-07-29 16:41 UTC
### Describe the Issue

I have a large solution (334 projects). When I look at find all references on a widely used class the reference count is incorrect and changes every time I click refresh:

For example clicking refresh on the same reference:
![image](https://github.com/user-attachments/assets/9fa8dbd5-271f-49ee-9d32-51e53cc60739)
![image](https://github.com/user-attachments/assets/a2c43525-9c44-4172-b329-cd67e72c38eb)
![image](https://github.com/user-attachments/assets/671805b0-a3ae-4208-8cbe-bedf9f75a14c)
![image](https://github.com/user-attachments/assets/8be58bdb-643e-4381-8459-4c74c99b2dba)
![image](https://github.com/user-attachments/assets/e80c726b-730c-4150-9eca-49d8d5566c44)

Also, rename does not update all references. Although it it consistently renames the same number of references if I rename, undo the changes and rename again.

If reload the solution and then rename it will update a different number of references.

### Steps To Reproduce

Load a large solution and view "find all references" on a widely used reference. (I've seen this happen with a class with only 17 references).

### Expected Behavior

Always show the same (and correct) reference count.

### Environment Information

- Ubuntu 23.10 dev container on WSL.
- Vscode 1.91.1 (on windows 11)
- C# extension v2.39.29
- C# dev kit extension v1.8.14

**Comment by dibarbet** [comment] 2024-07-31 18:39
Duplicate of https://github.com/dotnet/vscode-csharp/issues/7391

Fixed in v2.41.26 (pre-release) - just uploaded to the marketplace.

**Closed by dibarbet** 2024-07-31 18:39 UTC
Labels: bug, area-roslyn
