### ISSUE TITLE
Ram getting filled when opening a unity project

### ISSUE THREAD

**Issue by SuperJura** [microsoft/vscode-dotnettools#1353] opened 2024-08-09 09:48 UTC
Type: <b>Bug</b>

I open my unity project, Microsoft.VisualStudio.Code.ServiceHost starts ramping up and taking all of the avaliable ram.

https://github.com/user-attachments/assets/ff2bea88-237e-4ba3-9bbc-96666d10f7f7

Extension version: 1.9.55
VS Code version: Code 1.92.1 (eaa41d57266683296de7d118f574d0c2652e1fc4, 2024-08-07T20:16:39.455Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.77GB (0.92GB free)|
|Process Argv|D:\\Pine\\EscapeSimulator -g D:\\Pine\\EscapeSimulator\\Assets\\_Source\\Runtime\\Menu\\Menu.cs:4251:0 --crash-reporter-id 1aabfa71-c699-4107-b1b0-efcd45508768|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonnoceb:30805159
asynctok:30898717
pythonregdiag2:30936856
pythonmypyd1:30879173
h48ei257:31000450
pythontbext0:30879054
accentitlementsc:30995553
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
dsvsc021:30996838
g316j359:31013175
pythoncenvpt:31062603
a69g1124:31058053
dvdeprecation:31068756
dwnewjupyter:31046869
newcmakeconfigv2:31071590
impr_priority:31102340
nativerepl1:31104043
refactort:31108082
pythonrstrctxt:31112756
wkspc-onlycs-t:31111718
wkspc-ranged-c:31111712

```

</details>

**Comment by jbevain** [comment] 2024-08-09 13:20
Duplicate of #1201.

**Closed by jbevain** 2024-08-09 13:20 UTC

**Comment by MihaPro-CarX** [comment] 2024-08-14 08:55
This topic is about the ServiceHost process. This is most likely a duplicate of this issue: https://github.com/microsoft/vscode-dotnettools/issues/1295
