### ISSUE TITLE
[Suggestion]  docker-compose not supported in solution explorer

### ISSUE THREAD

**Issue by Caitlin-Finn** [microsoft/vscode-dotnettools#1079] opened 2024-04-26 14:30 UTC
### Describe the Issue

I need to be able to run the docker-compose as project like we do in Visual Studio. Currently, the docker-compose isn't supported in the solution view.

![Screenshot 2024-04-26 at 9 27 58 AM](https://github.com/microsoft/vscode-dotnettools/assets/7504073/493d6a68-b9c7-4edf-8101-2f8007fdd510)

### Steps To Reproduce

Load project with solution that contains docker-compose file
View in solution explorer

### Expected Behavior

docker-compose should be supported and you should be able to right click on it and run as project like in visual studio

![image](https://github.com/microsoft/vscode-dotnettools/assets/7504073/2bc19e6e-2c34-42bc-8f4a-d41814b23ef5)

### Environment Information

MacOS

**Comment by phil-allen-msft** [comment] 2024-04-29 18:31
@Caitlin-Finn , is your eventual need to run the composed project, or to run and debug the composed project like you can in Visual Studio?

**Comment by Caitlin-Finn** [comment] 2024-04-29 18:52
Run and debug like in Visual Studio
    On Monday, April 29, 2024 at 01:31:38 PM CDT, Phil Allen ***@***.***> wrote:  
 
 


@Caitlin-Finn , is your eventual need to run the composed project, or to run and debug the composed project like you can in Visual Studio?

**Comment by webreidi** [comment] 2024-05-02 21:15
Closing as duplicate of [Integrated Docker Compose Debugging for .NET Core · Issue #840 · microsoft/vscode-docker (github.com)](https://github.com/microsoft/vscode-docker/issues/840).

**Closed by webreidi** 2024-05-02 21:15 UTC
Labels: enhancement, area-solution
