### ISSUE TITLE
[BUG] Run/Debug - Restart does not honor changes made

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode-dotnettools#615] opened 2023-10-13 19:01 UTC
### Describe the Issue

I am running a console app and when making changes and hitting restart the changes are not reflected. I have to close the app and hit run or debug again. 

*In case it matters, I am using the spectre console nuget package 

### Steps To Reproduce

1. Create a console app 
2. Hit run without debugging OR debug
3. Make changes to console app 
4. Save changes
5. Hit restart in the debugging toolbar at the top 

Changes are not picked up - have to close the app and run or debug again to see changes made. 

### Expected Behavior

For the console app to restart with the saved changes

### Environment Information

- Windows 11
- C# Dev Kit: v0.5.150
- C#: v2.5.30

**Comment by gregg-miskelly** [comment] 2023-10-16 23:58
Duplicate of #496

**Closed by gregg-miskelly** 2023-10-16 23:58 UTC
Labels: bug, duplicate, area-debugging
