### ISSUE TITLE
Skip download of .NET runtime when already installed 

### ISSUE THREAD

**Issue by taisbak** [microsoft/vscode-dotnettools#80] opened 2023-06-08 11:49 UTC
Type: <b>Feature Request</b>

I'm behind a company firewall that blocks download of most archives, e.g. zip.

I have  the latest .NET runtime installed 7.0.5 as the default.

Still C# Dev Kit insists on downloading  and installing the runtime when I open a .NET solution folder.

I think the runtime should be detected and download/installation skipped when the runtime is ok.

Would same some time as well.

Maybe a better title would be: **"Fail to resolve .NET version"**.

Extension version: 0.1.83
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by taisbak** [comment] 2023-06-08 13:04
**Output from "C#":**

[Error - 2:51:19 PM] Microsoft.CodeAnalysis.LanguageServer client: couldn't create connection to server.
Error: Could not resolve the dotnet path!
	at c:\Users\nn\.vscode\extensions\ms-dotnettools.csharp-2.0.206-win32-x64\dist\extension.js:2:961248
	at Generator.next (<anonymous>)
	at s (c:\Users\nn\.vscode\extensions\ms-dotnettools.csharp-2.0.206-win32-x64\dist\extension.js:2:960426)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Output from "C# DEv Kit":**

Starting Open a solution...
Starting Open a solution with environment service...
Starting Clear environment...
Starting Spawn .NET server...
Failed at 'Spawn .NET server' (48370ms) with error: Error: Could not resolve the dotnet path!
Failed at 'Clear environment' (48375ms) with error: Error: Could not resolve the dotnet path!
Failed at 'Open a solution with environment service' (48375ms) with error: Error: Could not resolve the dotnet path!
Failed at 'Open a solution' (48450ms) with error: Error: Exception while opening the solution: Error: Could not resolve the dotnet path!
Failed to open solution Error: Exception while opening the solution: Error: Could not resolve the dotnet path!

**Comment by arkalyanms** [comment] 2023-06-09 17:53
This will need consumption of Noah's SDK acquisition APIs. 

@nagilson note the global install reuse ask.

**Comment by AArnott** [comment] 2023-06-09 21:09
Duplicate of #20

**Closed by AArnott** 2023-06-09 21:09 UTC
Labels: enhancement, triaged, area-sdk

**Comment by taisbak** [comment] 2023-06-14 08:15
Finally I figured out how to solve this using settings - one just have to specify the correct vscode extension IDs:
```
"dotnetAcquisitionExtension.existingDotnetPath": 
    [  
        {  
            "extensionId": "ms-dotnettools.csharp",  
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"  
        },  
        {  
            "extensionId": "ms-dotnettools.csdevkit",  
            "path": "C:\\Program Files\\dotnet\\dotnet.exe"  
        }  
    ]  
}  
```
So - working as designed wasn't so bad after all ;-)
