### ISSUE TITLE
[BUG] Renaming a file causes project system breaks

### ISSUE THREAD

**Issue by 333fred** [microsoft/vscode-dotnettools#439] opened 2023-08-25 23:47 UTC
### Describe the Issue

Renaming a file moves it to the misc files project.

### Steps To Reproduce

1. Create a project with these contents:

Program.cs:
```cs
using test;

Console.WriteLine(Class1.I);
```
Class1.cs:
```cs
namespace test;

public class Class1
{
    public static int I = 1;
}
```

2. Open in VSCode with DevKit.
3. Observe everything loaded correctly.
4. Rename Class1.cs to Class1_1.cs (or any other rename).

/cc @tmeschter

### Expected Behavior

Expected:

The code in Program.cs still works and correctly knows where `Class1` comes from.

Actual:

Program.cs no longer knows where `Class1` is. Performing actions in the renamed file indicates that the project system thinks the file is in the Misc Files project.

### Environment Information

Version: 1.81.1
Commit: 6c3e3dba23e8fadc360aed75ce363ba185c49794
Date: 2023-08-09T22:18:39.991Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.19.0-50-generic snap

DevKit: v0.3.175-ge959c6c2c3

**Comment by tmeschter** [comment] 2023-08-28 17:22
I'm not able to reproduce this on Windows; might be a Linux-specific file watching issue?

**Comment by Michael-Eng** [comment] 2023-08-29 16:00
Did you rename the file in the folder view or the solution explorer?

**Comment by 333fred** [comment] 2023-08-29 16:06
@Michael-Eng folder view.

**Comment by lifengl** [comment] 2023-09-01 00:43
yeah, on Linux the logic to update project when files added/deleted/renamed was broken, and should be addressed in the next pre-release.

**Closed by lifengl** 2023-09-01 00:43 UTC
Labels: bug, area-project-cps, fixed (release pending)
