### ISSUE TITLE
Switching open tabs does not select the file in the SE

### ISSUE THREAD

**Issue by prashantvc** [microsoft/vscode-dotnettools#116] opened 2023-06-12 16:34 UTC
Type: <b>Bug</b>

Switching open tabs does not select the file in the solution explorer.

<img width="1337" alt="image" src="https://github.com/microsoft/vscode-dotnettools/assets/328076/94008ca0-180f-448f-bbcd-08ebdd4d1447">

Extension version: 0.1.83
VS Code version: Code - Insiders 1.80.0-insider (Universal) (ef6abe4cd1573689d070b8715e97019cfadaeb51, 2023-06-12T05:25:17.588Z)
OS version: Darwin arm64 23.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 4|
|Memory (System)|32.00GB (0.49GB free)|
|Process Argv|--crash-reporter-id 0dca3b99-dd0e-424d-97cc-4be51f2678a5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smitpatel** [comment] 2023-06-12 16:54
Duplicate of #51 
If we track active item then switching open tab should be taken as change of active item.

**Closed by smitpatel** 2023-06-12 16:54 UTC
