### ISSUE TITLE
[SUGGESTION] Nuget inspector for Solution Explorer

### ISSUE THREAD

**Issue by SignalMQ** [microsoft/vscode-dotnettools#692] opened 2023-11-07 15:51 UTC
### Nuget inspector for Solution Explorer

**Hello everyone👋👋👋** 
I would like to ask the team of this extension to make a nuget package inspector as it currently works in the integrated environment. This functionality is very lacking in this environment. Thank you in advance.

### Environment Information

Version: 1.84.1
Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
Date: 2023-11-06T12:35:31.181Z
Electron: 25.9.2
ElectronBuildId: 24603566
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.2.0-36-generic

**Comment by timheuer** [comment] 2023-11-07 17:51
Closing as dupe of #62

**Closed by timheuer** 2023-11-07 17:51 UTC
Labels: enhancement, area-solution
