### ISSUE TITLE
[SUGGESTION] Provide support for project configurations for tests

### ISSUE THREAD

**Issue by GeorgeDarakchiev** [microsoft/vscode-dotnettools#639] opened 2023-10-20 10:13 UTC
### Describe the feature you'd like

I would like to be able to build Test project and run the tests in configuration different than Debug.

- Provide a way to build the project in other Configurations (like Android)
- Provide a way to set configuration to the tests.

In the cli it would lould be done like this:
`dotnet test MyProject.csproj -c Android`

Currently tests are discovered only if they are located in the bin/Debug folder, regardless of the project configuration.

For further information check the this repo project: [https://github.com/telerik/ms-samples/tree/main/DevKit/ConfigurationsTestRepo](https://github.com/telerik/ms-samples/tree/main/DevKit/ConfigurationsTestRepo)

- There are two project configurations: Windows and Android
- The one test should be failing in Android configuration and passing for Windows configuration

**Comment by timheuer** [comment] 2023-10-20 15:26
dupe of #67

**Comment by peterwald** [comment] 2023-10-23 17:43
Resolve as duplicate of #67.

**Closed by peterwald** 2023-10-23 17:43 UTC
Labels: enhancement, area-test, area-maui
